palantir/blueprint

packages/landing/src/landing.scss

Landing: put description and buttons on top of components image

---

packages/docs/src/index.html

This makes the docs work better on mobile. It's not a full solution, but it's an improvement over the way it is now

Remove meta viewport tag from docs

---

.stylelintignore
gulp/sass.js
gulp/watch.js

- remove `sass-watch-*` tasks
- determine tasks to run when calling `gulp.watch` instead of inside
the `sass-watch-*` task
- this fixes an issue where changing docs scss files would recompile
almost everything else (due to docs project deps in gulp file)

smarter sass watcher

---

packages/core/src/components/popover/popover.tsx
packages/core/test/popover/popoverTests.tsx

When Overlay calls its onClose callback within `handleKeyDown`, an inline Popover's targetElement is contained within the eventTarget. Popover's `handleOverlayClose` should only disable closing for click events, so I added a case to allow the KeyboardEvent to trigger the close.

Fix inline Popover closing via Escape keypress

---

packages/core/examples/common/intentSelect.tsx
packages/core/src/common/classes.ts
packages/core/src/common/intent.ts

`IntentSelect` uses the `Intent` as its `value` so it'll update as the value is changed.
Also added `Intent.NONE` which can be used instead of null values when you don't want an intent.

IntentSelect uses Intent as value.

---

gulp/docs.js
packages/docs/src/components/navbar.tsx
packages/docs/src/index.tsx

- `docs-versions` gulp task outputs latest release of each major version (instead of all tags) in reverse order (latest first)
- hide versions menu if there's only one version
- as there's only one major version here, this PR ends up hiding the version selector which fixes #129 (as you can't get to those broken links)

remove docs versions selector

---

packages/landing/src/index.html
packages/landing/src/landing.scss

Removed flexbox usage on the landing page and switched to floats for the column features.
I'm not super experienced in responsive design, so any comments greatly appreciated. 
Please test in browser at full screen, 768 vs 769 width as well as 425 vs 426 width, as well as with the iPhone simulator. My original repro is from iPhone 6, iOS 9.2:
Screen recording of new behavior, specifically chose to center when viewing at the tablet width:
P.S. May need @llorca or @cmslewis to assist getting this past the review process, as I'm about to lose internet over the next day while in the air so I won't be able to follow up until later. If not, I'll take care of it as soon as possible.

Remove flexbox usage in landing to fix mobile layout

---

packages/core/src/_typography.scss
packages/core/src/components/callout/_callout.scss
packages/docs/src/styles/_content.scss

Take 10px off the top and the bottom of heading margin so they flow better. 
These new values are already used in the docs, so we can remove a selector override.

decrease running text heading margin

---

packages/docs/src/components/section.tsx
packages/docs/src/components/styleguide.tsx
packages/docs/src/index.tsx
packages/docs/src/styles/_content.scss

- revert anchor padding trick for section positioning (see 06d41ab)
- invisible `<a name="" />` with negative margin solves all our anchor woes!
- can even use only margins on the headings! adjust margins a bit to account for collapsing and descenders.
- adjust some params for the scroll spy algorithm to account for new styles.
this one little change cleans up every hack in these headings!
(discovered by inspecting styles of React docs site)

brilliant docs anchors!

---

gulp/typescript.js
gulp/util/webpack-config.js
packages/core/.npmignore
packages/core/examples/tsconfig.json
packages/core/tsconfig.json
packages/datetime/.npmignore
packages/datetime/examples/tsconfig.json
packages/datetime/tsconfig.json
packages/landing/tsconfig.json
packages/table/.npmignore

- include tsconfig.json in npm packages because it's useful for development (particularly in the internal repo where we actually want to build _these_ projects)
- i had originally excluded it cuz i thought it wouldn't be useful and the `typeRoots` relative path was too brittle for public distribution
- so here I remove `typeRoots` from tsconfig.json files and instead set it much more reliably in `gulp-typescript` and `ts-loader` config where the relative paths are perfectly at home

tsconfig updates for NPM consumption

---

Gulpfile.js
gulp/sass.js
package.json
packages/core/.npmignore
packages/datetime/.npmignore
packages/table/.npmignore

1. remove `resources` from `.npmignore` so those files can at least be installed.
2. add a new option "bundle" for `sass-compile` task that enables the import inlining and asset copying functionality
- published packages use the default "compile" behavior
- only the `docs` and `landing` packages need to "bundle" because they need to produce deployable `dist/` directories.

sass "bundle" option to copy assets

---

gulp/icons.js
gulp/karma.js

use `path.resolve` instead of `path.join` for icons.json because the path gets passed to `require()`.
also fix karma `typeRoots` to resolve all those missing typings. see output from `gulp test` on this circle build: https://circleci.com/gh/palantir/blueprint/499 for repro.

fix require path to icons.json

---

packages/core/src/components/hotkeys/hotkeysEvents.ts
packages/core/test/hotkeys/hotkeysTests.tsx

Hotkey behavior is now properly triggered when the user is focused within a checkbox or radio button. (Previously, the hotkey behavior was prevented unnecessarily.) Also added new unit tests to verify this behavior.
Nothing in particular.

Permit hotkey behavior within checkboxes and radio buttons

---

packages/core/src/components/navbar/_navbar.scss

To avoid blurriness, the dark nav shadow should only be inset when the app is light themed. When the app is dark themed, it's always outset.
Before (blurry edge):
After (sharp):

Make dark nav shadow inset inside light themed app

---

packages/core/src/components/tabs/tabPanel.tsx

Corrected a misspelling that causes an error in the console
aria-labeledby
should be
aria-labelledby

Fixing 'Warning: Invalid aria prop `aria-labeledby` ...' message

---

Gulpfile.js
circle.yml
gulp/sass.js
package.json
packages/core/src/common/_font-imports.scss
packages/core/src/components/breadcrumbs/_breadcrumbs.scss
packages/core/src/components/button/_button-group.scss
packages/core/src/components/button/_button.scss
packages/core/src/components/callout/_callout.scss
packages/core/src/components/dialog/_dialog.scss
packages/core/src/components/editable-text/_editable-text.scss
packages/core/src/components/forms/_common.scss
packages/core/src/components/navbar/_navbar.scss
packages/core/src/components/popover/_common.scss
packages/core/src/components/progress/_progress-bar.scss
packages/core/src/components/spinner/_spinner.scss
packages/core/src/components/toast/_toast.scss
packages/core/src/components/tooltip/_tooltip.scss
packages/datetime/src/_datepicker.scss
packages/docs/src/docs.scss
packages/docs/src/styles/_colors.scss
packages/landing/src/_overrides.scss
packages/landing/src/landing.scss
packages/table/src/common/_variables.scss

use [`node-sass-package-importer`](https://github.com/maoberlehner/node-sass-package-importer) to support package names in sass imports instead of relative paths, which break when trying to compile sass APIs outside the monorepo. package paths must begin with the `~` character, like webpack sass-loader: `@import "~@blueprintjs/core/dist/blueprint.css"`.
update relevant `@import` paths.

node_modules support for sass imports

---

packages/core/src/components/context-menu/_context-menu.scss
packages/core/src/components/portal/_portal.scss
packages/docs/src/styles/_layout.scss

- set `min-height` on docs page so the white background never shows through. resolves issue in https://github.com/palantir/blueprint/issues/183#issuecomment-261070996
- use `display: block` for portals and context menus so their appended elements don't take up space at the end of the page.
test the Overlay family and ensure that when opened they do not add ~20px of white space at bottom of page.

fix portal display issues

---

packages/table/src/tableBody.tsx

In addition to calculating absolute position for cells,
we must also merge in style properties that are attached
to the Cell component itself.

Merge cell style

---

packages/table/src/index.ts

Adds exports for Draggable and DragSelectable (and
supporting interfaces) to public API.

Export Draggable components from Table

---

packages/table/preview/index.html
packages/table/preview/index.tsx
packages/table/src/headers/columnHeader.tsx
packages/table/src/headers/rowHeader.tsx
packages/table/src/index.ts
packages/table/src/interactions/selectable.tsx
packages/table/src/table.tsx
packages/table/src/tableBody.tsx
packages/table/test/selectionTests.tsx

Related: #191
Adds "selectedRegions" prop to Table to allow to user to take over
control of selection. If defined, the user will be responsible for
updating the selection and should probable add a "onSelection"
callback.
Adds "selectedRegionTransform" prop to table to allow users to
transform the selection region. This allows users to, for example,
select a whole row when the user clicks on a single cell. Using
a transform is advantageous because we can still handle interaction
semantics like multiselect, meta-click, and click-to-deselect.

Controllable selection

---

packages/docs/src/styles/_sections.scss
packages/table/src/_docs.scss
packages/table/src/table.scss

Fixes #203
Give all table examples a fixed height of 300px

Fix table height in docs

---

packages/core/src/components/slider/_common.scss

Add a `min-width` of `150px` to sliders. This fixes the documentation popover bug mentioned in the issue (the popover wasn't specifying an explicit `width`, so it was rendering with zero width before):
(optional)

Add a min-width to sliders

---

packages/table/src/cell/formats/jsonFormat.tsx
packages/table/src/cell/formats/truncatedFormat.tsx
packages/table/src/index.ts
packages/table/test/formatsTests.tsx

Previously, the `TruncatedFormat` cell would display
a popover target with the "..." icon when its text
content was longer than the `truncationLength` prop.
Cells that weren't truncated this way used a CSS
"text-overflow: ellipsis" rule, which lead to
the odd sight of a mixture of "..." in the cells.
This change alters the default behavior to always
show the large "..." icon even if the cell's text
content isn't truncated. Therefore the look of the
cells will be much more consistent.
Also, the `JSONFormat` cell will turn off the
"..." popover target for nully values.

[table] Adjust Truncated Popover Behavior

---

packages/docs/src/components/icon.tsx

- Changed the download link to reference icon files in the `master` branch instead of `develop`, which doesn't exist.
- The context menu already dismisses as expected when I click on the document. Not sure when that got fixed, but this PR does nothing in particular to address it.

Fix icon menu bugs

---

packages/datetime/src/common/dateUtils.ts

Made typings reflect reality.
Since onChange can contain nulls, it should be declared as such.

Declare values in DateRange as optional

---

packages/core/src/components/forms/_control-group.scss

Super subtle bug here. In the docs, we currently have the following example for `.pt-control-group`:
```
<div class="pt-control-group">
<button class="pt-button pt-intent-primary">Add</button><div class="pt-input-group">
<span class="pt-icon pt-icon-people"></span>
<input type="text" class="pt-input" placeholder="Find collaborators..." style="padding-right:94px">
<button class="pt-button pt-minimal pt-intent-primary">
can view<span class="pt-icon-standard pt-icon-caret-down pt-align-right"></span>
</button>
</div>
</div>
```
This presumably shows a control group being composed with a button and an `<InputGroup>`. But this isn't the HTML emitted by such a composition. The real HTML looks like this:
```
<div class="pt-control-group">
<button class="pt-button …
```

Fix CSS for button inside .pt-control-group > .pt-input-group

---

packages/table/src/cell/editableCell.tsx
packages/table/src/headers/editableName.tsx

`<EditableText>` has a default min-width of 80px,
which overflows the table cell.
Settings the minWidth prop to null will fix this.

[table] Remove min width from editable components

---

README.md

Got some feedback that it'd be great to have a direct link to the docs when viewing https://github.com/palantir/blueprint

Add obvious docs link to README

---

packages/core/src/components/tabs/_tabs.scss

Restrict `.pt-vertical` style modifications to immediate children only when applied to a `<Tabs>` component.
**Before:**
Nested tabs unexpectedly inherit the `pt-vertical` styles and generally behave weirdly.
**After:**
Nested tabs do not inherit `.pt-vertical` styles applied to a parent tab container. Everything works as expected.
A fix for this issue necessarily involves increasing the specificity of `.pt-vertical` styles on certain CSS selectors (in particular, on `.pt-tab` and `.pt-tab-indicator`). This might break consumers' styles. Should we wait for a major-version bump, or are we okay with the slightly broken API?

Tweak tab styles so we don't forcefully style deeply nested tabs

---

packages/core/src/common/classes.ts
packages/core/src/components/forms/_control-group.scss
packages/core/src/components/overlay/_overlay.scss
packages/core/src/components/overlay/overlay.tsx
packages/core/test/overlay/overlayTests.tsx
packages/core/test/portal/portalTests.tsx
packages/core/test/tooltip/tooltipTests.tsx
packages/docs/src/styles/_sections.scss

- Introduce a `pt-overlay` class to serve as the top-level wrapper descriptor for the overlay component.
_As a consumer of Blueprint in the past, I was always much happier when everything had a clear CSS class attached to it. CSS rules downstream are much easier to grok and maintain when applied to meaningfully named elements, rather than opaque HTML tag names._
- Introduce a `.pt-overlay-inline` class and apply it to the `.pt-overlay` element iff the overlay is being rendered inline.
_This allows us to set `.pt-overlay-backdrop` and/or overlay content to `position: absolute` when the overlay is rendered inline, so that the overlay intuitively positions itself relative to its parent in that case._  
- Introduce a `.pt-overlay-content` class that we apply under-the-hood to overlay content …

Fix overlay issues

---

packages/datetime/src/dateInput.tsx

- Properly handle moment-timezone's setDefault
- DateInput accepts dates in the local timezone
- DateInput onChange returns dates in the local timezone
- DateInput.handleDateChange method 
- Making sure this works in multiple timezones
- Making sure this works with and without moment-timezone

moment-timezone compatability for DateInput

---

packages/core/src/components/slider/coreSlider.tsx
packages/core/src/components/slider/handle.tsx
packages/core/src/components/slider/rangeSlider.tsx
packages/core/src/components/slider/slider.tsx
packages/core/test/common/utils.ts
packages/core/test/slider/rangeSliderTests.tsx
packages/core/test/slider/sliderTests.tsx
packages/table/src/index.ts

I've added touch events handling to slider component, so it can be used for mobile browsers.
Touch events are fired instead of mouse events in mobile browsers,
to simulate this behavior on desktop you can use device mode in Chrome
https://developers.google.com/web/tools/chrome-devtools/device-mode/

add touch events handling to slider

---

packages/core/src/accessibility/focusStyleManager.ts
packages/core/src/accessibility/index.ts

- Create a `core/src/accessibility/` folder
- Move the focus style manager into this folder
This is mostly just for good hygiene. Feels weird to have the focus stuff in index.ts.

Move focus style manager to its own file

---

packages/datetime/src/dateRangePicker.tsx
packages/datetime/test/dateRangePickerTests.tsx

- Set the `displayMonth` to `initialMonth - 1` if the initial month is at the end of the allowable range. This keeps the max month on the _right_ side of the date-range picker, which you aren't able to proceed past anyway.
- Edge case: if the initial month is the same as the min _and_ max month, don't change it. 
- Pretty simple change. Does it look sane?

Fix date-range picker wraparound behavior

---

packages/core/src/components/button/buttons.tsx

- allow changing `type`/`role` of buttons by moving the spread after those props
- also support changing `tabIndex` on `AnchorButton`

Allow changing type/role of buttons

---

packages/datetime/src/common/utils.ts
packages/datetime/src/datePickerCaption.tsx

- Add an optional third `containerElement` parameter to `Utils.measureTextWidth` (defaults to `document.body`)
- Leverage this in `DatePicker` to ensure we're measuring text as sized within that component 
- FYI: I added `*Element` suffixes to each of the elements for clarity and consistency. The type handles that, but this makes things easier to read quickly at a glance.
- FYI: Verified that this works by changing body text size to `100px` and observing that the `<DatePicker>` dropdown arrows still appeared in the expected place.

Fix possibly mis-measured text width in DatePicker

---

gulp/sass.js
gulp/watch.js

docs.scss imports all the compiled CSS files, which then gets compiled into docs.css. Changing a downstream package SCSS file (like `_buttons.scss`) updates blueprint.css but docs.scss does not pick up those changes.
this PR adds a watcher that recompiles docs.scss when any dist/*.css file changes. it also refactors sass and typescript watching to actually ignore generated files (which prevents a few unnecessary recompiles).

refactor sass watching so page reloads

---

packages/core/src/components/popover/popover.tsx

- only invoke `onClose` when `Popover` `isDisabled` changes from false to true (not every update when it is true)

Popover onClose only when disabled changes to true

---

packages/core/src/common/abstractComponent.ts
packages/core/src/components/collapse/collapse.tsx
packages/core/src/components/context-menu/contextMenu.tsx
packages/core/src/components/editable-text/editableText.tsx
packages/core/src/components/popover/popover.tsx
packages/core/src/components/tabs/tabList.tsx
packages/core/src/components/tabs/tabs.tsx
packages/core/src/components/toast/toast.tsx

- add timeout management to `AbstractComponent`
- a simple list of timeouts started by this instance
- a way to set a timeout
- a way to clear them all
- and auto-clear when unmounting
- refactor components that used `setTimeout`
- the only remaining instance of `window.setTimeout` is `HotkeyDialog` which is not a React Component and therefore can't use this feature.
They should all behave exactly the same as before.

Add timeout management to AbstractComponent

---

gulp/aliases.js
gulp/webpack.js
packages/core/examples/tsconfig.json
packages/docs/tsconfig.json

- added `baseUrl` and `paths` to docs `tsconfig.json` so it always looks in `docs/node_modules` for `@blueprintjs` packages. (thanks @ericanderson!)
- `webpack-compile-docs` depends on `docs` alias to generate necessary data (allows standalone usage).

resolve examples "cannot find module" errors

---

packages/core/src/common/_color-aliases.scss
packages/core/src/common/_colors.scss
packages/core/src/common/_font-imports.scss
packages/core/src/common/_icons.scss
packages/core/src/common/_mixins.scss
packages/core/src/common/_variables.scss
packages/core/src/components/button/_common.scss
packages/core/src/components/card/_card.scss
packages/core/src/components/collapse/_collapse.scss
packages/core/src/components/dialog/_dialog.scss
packages/core/src/components/forms/_common.scss
packages/core/src/components/forms/_controls.scss
packages/core/src/components/hotkeys/_hotkeys.scss
packages/core/src/components/menu/_common.scss
packages/core/src/components/navbar/_navbar.scss
packages/core/src/components/overlay/_overlay.scss
packages/core/src/components/popover/_common.scss
packages/core/src/components/progress/_progress-bar.scss
packages/core/src/components/slider/_slider.scss
packages/core/src/components/table/_table.scss
packages/core/src/components/tabs/_tabs.scss
packages/core/src/components/tag/_common.scss
packages/core/src/components/tooltip/_common.scss
packages/datetime/src/_datepicker.scss
packages/datetime/src/_timepicker.scss
packages/table/src/cell/_common.scss
packages/table/src/common/_variables.scss
packages/table/src/headers/_common.scss
packages/table/src/interactions/_interactions.scss
packages/table/src/layers/_layers.scss

- ~~Include tests~~ N/A
- ~~Update documentation~~ N/A
- Allow all of the variables defined to be overridden . 
- Completeness

add !default to all SCSS variable declarations

---

packages/core/src/components/_index.scss
packages/docs/src/styleguide.md

- list typings that must be installed for each package on Overview page
- is this the best place for this section?
- is there a way to simply depend on these `@types` packages? maybe as `devDependencies`?

add TypeScript section to docs Overview page

---

packages/core/package.json
packages/core/src/common/_resets.scss
packages/core/src/common/tetherUtils.ts
packages/core/src/components/overlay/overlay.tsx
packages/core/src/components/portal/_portal.scss
packages/core/test/overlay/overlayTests.tsx

- Change `.pt-portal` to `position:absolute` to take it out of document flow.
_This prevents browsers from autoscrolling to the bottom of the document (where portals are appended) when programmatically .focus()'ing within a portal child element._
- Stick `.pt-portal` to the top, left, and right of the `body`.
_This ensures that content still calculates offsets from the top of the document and that content won't be horizontally scrunched._
- Move `tabindex` from the `.pt-overlay` wrapper down to the overlay's immediate **children**.
_Despite the CSS changes above, programmatically `.focus()`'ing on the overlay can still cause autoscrolling to the bottom of the page in some cases. Moving the `tabindex` to the overlay content ensures that the browser will scroll to the content itself if need …

Fix portal/popover position and scrolling issues

---

packages/core/package.json
packages/core/src/accessibility/focusStyleManager.ts
packages/core/src/components/hotkeys/hotkeyParser.ts
packages/core/src/components/hotkeys/hotkeysEvents.ts
packages/core/src/components/hotkeys/hotkeysTarget.tsx
packages/core/src/components/index.ts
packages/core/src/components/menu/menuItem.tsx

- Resolves a few minor issues which prevent Blueprint from rendering on the server.

Enable server-side/isomorphic rendering

---

packages/core/src/components/hotkeys/hotkeysDialog.tsx
packages/core/test/hotkeys/hotkeysTests.tsx

- Make `HotkeysDialog` **not** inline
- Add a unit test to verify that the `HotkeysDialog` doesn't render inline 
_BEFORE:_
_AFTER:_
I've verified that the dialog closes when you click the background and/or when you press <kbd>Esc</kbd>.

Make HotkeysDialog not inline

---

packages/core/examples/menuExample.tsx
packages/core/src/components/menu/menuItem.tsx
packages/core/test/menu/menuTests.tsx

- `<MenuItem disabled />` disables its submenu Popover and removes `href`

MenuItem disabled=true now prevents submenu and click interaction

---

packages/core/src/components/forms/controls.tsx

This is purely a documentation/usability improvement. `disabled` was already supported from `HTMLProps` but now the prop will be documented in the props table to avoid any potential confusion.

add `disabled` to IControlProps so it appears in props table

---

packages/core/src/components/breadcrumbs/_breadcrumbs.scss
packages/core/src/components/button/_common.scss
packages/core/src/components/forms/_controls.scss
packages/core/src/components/forms/_input-group.scss
packages/core/src/components/popover/_popover.scss
packages/core/src/components/spinner/_spinner.scss
packages/core/src/components/toast/_toast.scss
packages/core/src/components/tree/_tree.scss
packages/table/src/cell/_common.scss
packages/table/src/table.scss

found a host of Sass variables that were missing `!default` declarations, now they aren't!
this should support easier checkbox styling (#396).
addresses #194 and #377

more !default Sass variables

---

packages/table/examples/tsconfig.json

Without a tsconfig in the `packages/table/examples` folder, VSCode isn't able to include 'react' in the example files.

Add tsconfig to table/examples folder

---

gulp/karma.js

The default mime type of these files is a QuickTime video format. This
change allows us to serve `*.ts` files to a Karma server and allow
them to be executed in a Chrome browser. PhantomJS doesn't seem have
strict mime-type checking, so this doesn't affect tests on CircleCI.

Force Karma to serve ts/tsx files as typescript

---

packages/core/src/components/_index.scss
packages/docs/src/styleguide.md

- a significant refactor of the two Usage sections
- Overview Usage is now mostly a link to Components Usage that scratches the peer dep itch
- Components Usage steps through setting up BP with peer deps and CSS imports
- new section about DOM4 so we can point folks to it
- copy editing! the DOM4 section feels pretty awkward

more explicit usage docs

---

packages/core/src/common/_variables.scss
packages/datetime/src/_datepicker.scss
packages/docs/src/docs.scss
packages/docs/src/styles/_content.scss
packages/docs/src/styles/_syntax.scss

- dark and light syntax themes!
- we've been highlighting this whole time, just not coloring.
- fix a few language hints on code blocks.

Add code syntax theme to docs

---

gulp/watch.js

- the glob did not include files in `src/` itself; there had to be at least one subdirectory not named "generated"
- the new glob pattern also includes files with no subdirectory at all
- this fixes watching for a whole bunch of files, affecting all the packages 😱

fix watching files in src/ itself

---

packages/core/src/components/collapse/collapse.tsx

Clear previous timeouts when `isOpen` prop changes
Previous timeouts are not still triggered when `isOpen` is changed faster than the transition duration.

Clear previous delayed timeouts when opening or closing collapse

---

packages/core/src/common/errors.ts
packages/core/src/components/toast/_toast.scss
packages/core/src/components/toast/toaster.tsx
packages/core/test/toast/toasterTests.ts

- clone Toast props before mutating. this avoids leaking the mutation and allows more than one of each Toast to appear in the example.
- ensure Toasts are always `position: relative` so they also stack when `inline`.
- warn when passing inline prop to Toaster.create()
- are you into this new warning or is it overkill? i updated the props docs with the same content.

fix Toast stacking

---

packages/core/src/common/_colors.scss

Small PR that adds !default to the core blueprint colors. I know this was discussed already internally by you folks but following discussion in #123 I thought Id create this PR incase you agreed with the line of reasoning there. If not, then please close/delete this PR :)
Sass lint is passing.

Added !default to core colors

---

packages/core/src/components/menu/_common.scss

Increase the line height to see the typographic descenders

Fixes menu divider title typographic descender being cut off

---

packages/core/src/components/skeleton/_skeleton.scss
packages/docs/src/styles/_sections.scss

- make skeleton cards fit on the same line
- this revealed a bug where the two cards were not the same height, so...
- remove .pt-skeleton line-height to preserve original dimensions

remove skeleton line-height

---

packages/datetime/src/datePickerCaption.tsx
packages/datetime/test/datePickerCaptionTests.tsx

- DatePickerCaption allows out-of-bounds year but disables the option, so it's for display only. 
- this handles the last-month-of-max-year case.

DatePickerCaption shows out-of-bounds year

---

packages/core/src/components/dialog/_dialog.scss

- set `min-height` on Dialog header so it always occupies the expected space regardless of contents.
- simplify margins of header children
- add margin-right to `h5` when it's last-child so text won't run to the edge

fix Dialog header height w/o icon or close button

---

packages/datetime/src/dateRangePicker.tsx
packages/datetime/test/dateRangePickerTests.tsx

make a copy of the `value[0]` so that it doesn't get mutated in line 140.
`props.initialMonth` can also be mutated from the first part of the if block, but I don't think that matters.

Fix daterangepicker initial value month

---

packages/core/src/components/progress/_common.scss
packages/core/src/components/progress/_progress-bar.scss
packages/core/src/components/spinner/_spinner.scss

- Add a Sass file for common progress bars and spinners variables
- Use the same colors for progress bars and spinners
- Make sure it looks good on both themes.
- A bit out of scope: should we move `spinner/` and `skeleton/` folders into `progress/`? It would also reflect the hierarchy of the docs

Use same colors for progress bars and spinners

---

packages/datetime/examples/timePickerExample.tsx
packages/datetime/src/timePicker.tsx
packages/datetime/test/timePickerTests.tsx

Added `selectOnFocus` prop to `TimePicker` component - auto highlights text if enabled, defaults to false.

Select timepicker text on focus

---

packages/datetime/src/common/months.ts
packages/datetime/src/datePickerCore.tsx
packages/datetime/src/dateRangePicker.tsx
packages/datetime/src/index.ts
packages/datetime/test/datePickerTests.tsx
packages/datetime/test/dateRangePickerTests.tsx

- Expose months mapping in datetime for more verbose code
- Fixes changing displayMonth when selecting dates across years
- should`Months` be an enum (could be inconsistent if we make a 1-indexed variant as @cmslewis mentions in the issue)?
- the problem from the issue can be reproduced by selecting December on the left hand calendar, then select a start date in December and an end date in January (the displayed months will change unnecessarily)

Expose months value mapping in datetime package

---

packages/core/src/components/editable-text/_editable-text.scss
packages/core/src/components/forms/_common.scss
packages/datetime/examples/timePickerExample.tsx
packages/datetime/src/_dateinput.scss
packages/datetime/src/_datepicker.scss
packages/datetime/src/_daterangepicker.scss
packages/datetime/src/_datetimepicker.scss
packages/datetime/src/_timepicker.scss
packages/datetime/src/dateRangePicker.tsx

Noticed that time picker still had custom shadows. Making it consistent with already available APIs.
Before:
After:

Improve time picker focus box-shadow

---

circle.yml

- run NPM `build:gulp` task instead of `gulp build` because the npm task sets NODE_ENV directly
- so external contributors don't have to set the environment variable manually on circle.
- verified in #349 but pulled out here as separate PR

run NPM gulp build task which sets NODE_ENV

---

packages/docs/src/styles/_sections.scss

Dialog in the CSS API section of the docs doesn't go above the top nav bar anymore when scrolling.

Overwrite dialog z-index in docs css api section

---

packages/datetime/src/common/utils.ts

- Changing `innerHTML` to `textContent` provides stronger protections against XSS as what's being inserted here is supposed to be text and not html.
- The intention of the span's content being text vs html.

eliminate innerHTML

---

packages/table/src/cell/formats/jsonFormat.tsx
packages/table/test/formatsTests.tsx

Previously, JSONFormat cells would not allow you to change the
showPopover prop because it wanted to detect nulls and override
the value.
Now, if the user actually sets the prop on JSONFormat, we will
still hide the popover for nully values, but will use their
prop as the default.

Handle popover prop on JSONFormat

---

packages/core/src/common/classes.ts
packages/core/src/components/forms/_common.scss
packages/core/src/components/forms/_controls.scss
packages/core/src/components/forms/_input-group.scss
packages/core/src/components/forms/_input.scss
packages/core/src/components/forms/_label.scss
packages/core/src/components/forms/_select.scss
packages/core/src/components/forms/controls.tsx

- Allow disabled label color with `.pt-disabled`.
- Allow input-group icon color with `.pt-disabled`.
- Allow select arrow color with `.pt-disabled`.
- Update CSS API documentation for `:disabled` to include `.pt-disabled` usage.

Allow pt-disabled colors in label, select and input-group, and update documentation

---

packages/core/examples/buttonsExample.tsx
packages/core/src/components/button/abstractButton.tsx
packages/core/src/components/button/buttons.tsx
packages/core/test/buttons/buttonTests.tsx

- Provide consistency in `SPACE` and `ENTER` keyboard Interactions between `<Button />` and `<AnchorButton />` with a base `AbstractButton`
- Manually tested across Chrome v55.0, Firefox v50.1, Safari 10.0, IE11, Edge
- NB. Interactions were already standardized across all browsers for `<button/>`
- Any edge cases I'm missing here?
- Leaving out splitting `buttons.tsx` into two files and moving helper functions into `AbstractButton` for another PR

Consistent space and enter keystrokes between buttons and anchor buttons

---

packages/datetime/src/common/dateUtils.ts
packages/datetime/src/dateTimePicker.tsx
packages/datetime/test/dateTimePickerTests.tsx

Split up the internal state in `DateTimePicker` to let the date and time be manipulated separately.
I considered keeping `value` in the state in addition to `dateValue` and `timeValue` to quickly access the combination of the two. Would this be more confusing than it is useful?

Fix datetimepicker clear date selection

---

packages/datetime/package.json

- We don't use anything in the breaking changes in the change log.
- NB. The typings we pull in are based on v1.2.0

Upgrade react day picker

---

packages/table/examples/cellLoadingExample.tsx
packages/table/src/tableBody.tsx

The docs build is reporting unused variable errors. This PR addresses those issue. A followup PR (https://github.com/palantir/blueprint/pull/471) will update the tsconfig settings across the packages to make these errors visible when compiling the packages.

Fix docs compilation unused var errors

---

packages/docs/src/styleguide.md
packages/docs/src/styles/_syntax.scss

to explain type annotations, hopefully easing burden on non-TS consumers.
addresses #464

add TypeScript section to Overview

---

packages/core/src/components/editable-text/_editable-text.scss
packages/core/src/components/editable-text/editableText.tsx
packages/core/test/editable-text/editableTextTests.tsx

- Do not call `onChange` nor `onConfirm` on blur / enter if value not changed
- Do not call `onChange` nor `onCancel` on escape if value not changed

Don't fire EditableText events if value has not changed

---

packages/table/examples/index.ts
packages/table/examples/tableFormatsExample.tsx
packages/table/src/_docs.scss

Adds TableFormatsExample to docs.
Adds ITruncatedFormatProps and IJSONFormatProps interfaces to docs.

Add docs and example for formatted cell components

---

packages/core/src/components/overlay/overlay.tsx
packages/core/src/components/toast/toast.tsx
packages/core/test/toast/toasterTests.ts

- Add `tabIndex` to toast wrappers - necessary from the changes in #276, which is looking for an explicit `tabIndex`.
- Another solution is that we could set the `tabIndex` on the first toast if `autoFocus` is set to true, but I don't want to expose that in the Toast props...

Fix toast autofocus

---

packages/table/src/common/grid.ts
packages/table/test/gridTests.ts

Add checks to prevent index out of bounds exception when calculating
number of ghost rows and cols to add.

Show ghost cells when 0 rows or cols

---

packages/core/src/components/tabs/tabs.tsx
packages/core/test/tabs/tabsTests.tsx

- Remove the `if` block in componentWillReceiveProps which leads to `setState` being called twice.
- Although specific, adding a test because of the complexity in the component.
Tried looking at #48 to see why that bit of code was introduced but can't quite figure it out, @cyu06 does anything ring a bell? Unless I'm missing something, the interactions look fine.

Fix Tabs onChange handler called twice when controlled

---

packages/core/src/components/button/abstractButton.tsx

- Two toasts appear when pressing `ENTER` on the button in an alert
note: Holding down on `ENTER` will show multiple alerts. This was also an issue < v1.6. I'm not sure if we want to throttle the call (the default browser behaviour that we're mimicking doesn't).

Fix click callback called twice when pressing ENTER key on Button

---

packages/datetime/src/dateInput.tsx
packages/datetime/test/dateInputTests.tsx

- Return `null` as the date argument in DateInput's `onChange` handler

Emit onChange with null when DateInput is empty

---

gulp/sass.js

- if `@pt-grid-size` is not a simple `#px` value then the Less compiler will error with "invalid type"
- can anyone think of more good simple tests? the regression we encountered was `!default` statements causing variables to be interpreted as strings instead of units or colors, which this test handles simply. not sure what else we can do?

improved Less variables test checks type

---

packages/core/src/common/_variables.scss
packages/core/src/components/button/_button-group.scss
packages/core/src/components/button/_button.scss
packages/core/src/components/button/_common.scss
packages/core/src/components/forms/_control-group.scss
packages/core/src/components/forms/_controls.scss
packages/core/src/components/forms/_file-upload.scss
packages/core/src/components/slider/_common.scss
packages/core/src/components/slider/_slider.scss

- Refactor buttons to use box shadows instead of borders
- Add new variable to deal with buttons on top of non-plain content: `$button-box-shadow-overlay`
- Update shadow values for buttons (done with @piotrk)
- Play with button groups and control groups in both themes, including with `disabled` buttons/inputs, `readonly` inputs, and all kinds of weird combinations that you can think of.
- Make sure everything is aligned and that there's no blurry edge or pixels.
Example from #233.
Before:
After:

Refactor buttons borders

---

packages/core/src/components/tag/tag.tsx

Add `type` attribute to remove buttons on Tag components, since not having type="button" submits forms that contain the element on some browsers.

Add type attribute to tag remove button

---

packages/core/src/components/forms/inputGroup.tsx

(doesn't have an issue - have just noticed it for months and finally bit the bullet to fix it)
**Before**
Dense line of code and broken syntax-highlighting in VS Code.
**After**
Icon-rendering code is more readable, and syntax highlighting is fixed.
Left icons still render properly

Fix syntax highlighting in inputGroup.tsx

---

packages/table/src/tableBody.tsx

Fixes an issue where the className on `Cell` is not being passed correctly via the `renderCell`
Use `baseCell.props.className` instead of `this.props.className`

Use Cell's className instead of TableBody

---

gulp/aliases.js
gulp/dist.js
packages/table/preview/tsconfig.json
packages/table/tsconfig.json

- new gulp `test-dist` task asserts that main files exist for each package.json
- revert table tsconfig change
- add tsconfig.json to table/preview that extends its parent so those files can be compiled (hooray TS 2.1)

test existence of dist files

---

packages/docs/package.json
packages/table/package.json

- __Fixed__ misplaced main files so the package can be imported correctly #566

Prepare Release Table 1.4.1

---

packages/core/examples/collapsibleListExample.tsx
packages/core/examples/overlayExample.tsx
packages/core/src/common/_variables.scss
packages/core/src/components/_index.scss
packages/core/src/components/context-menu/_context-menu.scss
packages/core/src/components/hotkeys/_hotkeys.scss
packages/core/src/components/menu/_menu.scss
packages/datetime/src/_datepicker.scss
packages/docs/src/styleguide.md
packages/docs/src/styles/_icons.scss
packages/table/src/_docs.scss

- Icons page icons are now using `$pt-icon-color` following #497 
- Various sentence casing type of things

Proper docs icon colors and sentence casing

---

packages/core/src/components/button/abstractButton.tsx
packages/core/test/buttons/buttonTests.tsx

- add docs for `Button` `type` prop
- wrap string children in span so `loading` can hide them
cc @greglo

Fix loading Button children

---

packages/core/examples/editableTextExample.tsx
packages/core/src/components/editable-text/editableText.tsx

Allow `maxLength` prop to input and textarea element in `<EditableText />`

Add maxLength props to EditableText

---

packages/table/src/common/grid.ts
packages/table/test/gridTests.ts

Fixes a bug in `grid#getWidth` and `grid#getHeight` when there are 0 columns and rows. This would prevent styles from being properly set on the table body, leading to ghost cells rendering on top of each other.
Before:
After:

Render ghost cells properly when there is no content

---

packages/core/src/compatibility/browser.ts
packages/core/src/compatibility/index.ts
packages/core/src/components/editable-text/editableText.tsx

Only add buffer widths in EditableText for IE and Edge

---

packages/core/src/compatibility/browser.ts

The build is currently failing because the tests throw this error:
```
ReferenceError: navigator is not defined
```
when running `EditableText` code that imports the `browser.ts` file.

Handle for cases when navigator is undefined

---

gulp/aliases.js
gulp/dist.js
gulp/typescript.js
gulp/util/webpack-config.js

new `typescript-bundle` task group webpacks each package's compiled js files and spits out `dist/[name].bundle.js`.
- is there a convention for specifying a bundled file in package.json? a la main/typings/style? i couldn't find anything relevant after much googling.

Add bundle tasks for distribution

---

packages/datetime/src/_daterangepicker.scss
packages/datetime/src/common/classes.ts
packages/datetime/src/datePickerCore.tsx
packages/datetime/src/dateRangePicker.tsx
packages/datetime/test/dateRangePickerTests.tsx

On hover in the `DateRangePicker`, show a visual preview of the range you're about to select. Additionally, hide "outside" dates, because they introduce too much weirdness in hover interactions.
The upcoming `DateRangeInput` implementation will need to display the hovered range in its input fields so that the user remains fully aware what the effect of the next mouse click will be (e.g. the component will need to show the hovered dates in the input fields and move focus between the fields based on the hovered date vs. the selected date/range). This PR just gets the visual hover preview working.
- Are the CSS styles sane and minimal?
- Are there any weird bugs with hovered ranges vis-a-vis selected dates/ranges?
- Are there any bugs with `allowSingleDayRange`?
- Is it reasonable to call …

[Date Range Input] - Part 1: Show a selection preview on hover

---

packages/core/examples/toastExample.tsx
packages/core/src/components/toast/toast.tsx
packages/core/test/toast/toastTests.tsx
tslint.json

- toast `action` accepts `ILinkProps` (href and target), uses `AnchorButton`
- refactor toast tests to use a little wrapper function that find the action and dismiss buttons. this puts the queries in one place, if we need to change them in the future.
- ban `describe.only` and `it.only` in TSLint for the same reason as console.log: useful in local development but problematic in real environments.

Toast action can be a link

---

packages/core/examples/contextMenuExample.tsx
packages/core/src/components/context-menu/_context-menu.scss
packages/core/src/components/context-menu/contextMenuTarget.tsx

ContextMenuTarget class decorator has no onClose callback

onCloseContextMenu implemention added in contextMenuTarget

---

packages/core/src/components/menu/_common.scss
packages/core/src/components/menu/_menu.scss
packages/docs/src/components/navMenu.tsx
packages/docs/src/components/navigator.tsx
packages/docs/src/styles/_layout.scss
packages/docs/src/styles/_navigator.scss

As per the previous discussion thread on #513.
- Default hover and active states are grey
- `.pt-active` === `:active` (background is dependent on `.pt-intent-*`)
- `.pt-disabled` > `.pt-active` / `pt-intent-*`

Menu item hover / active states (including with pt-intent-*)

---

packages/core/src/compatibility/browser.ts
packages/table/preview/index.tsx
packages/table/src/table.tsx
packages/table/test/harness.ts
packages/table/test/selectionTests.tsx

Part of #298 
You can specify a getCellData in the props and then
cmd+c will copy selected cells.
What I'm doing here is sane, the shortcut only works when it's supposed to, etc.

Add support for copying table cells with cmd+c hotkey

---

packages/core/src/components/button/_button-group.scss
packages/core/src/components/button/_common.scss
packages/core/src/components/forms/_common.scss
packages/core/src/components/forms/_control-group.scss
packages/docs/src/styles/_sections.scss

- Clearly specify the z-index stack of all possible `.pt-button-group` elements to ensure sharp edges in all cases and states:
```
(lowest z-index)
default buttons
:disabled, .pt-disabled
normal
:focus
:hover
:active, .pt-active
intent buttons
:disabled, .pt-disabled
normal
:focus
:hover
:active, .pt-active
(highest z-index)
```
- Clearly specify the z-index stack of all possible `.pt-control-group` elements to ensure sharp edges in all cases and states:
```
(lowest z-index)
input fields
:disabled, .pt-disabled
normal
regular buttons / pt-select > select
:disabled, .pt-disabled
normal
:focus
:hover
:active, .pt-active
pt-input intent
intent buttons (selects can't be intented yet, but if they could be, they'd be here too)
:disabled, .pt-disabled
normal
:focus
:hover
:active, .pt-active …
```

Fix z-index stack for .pt-button-group and .pt-control-group elements

---

docs/blueprint-landing.css
docs/blueprint-landing.js
docs/docs/docs.css
docs/index.html
package.json
packages/core/package.json
packages/datetime/package.json
packages/docs/package.json
packages/landing/package.json
packages/table/package.json

:fireworks: **Highlights**: browser-ready bundles in NPM distribution (+[unpkg](https://unpkg.com/)), new `NumericInput` component, `Menu` is gray + "active" support, <kbd>cmd+c</kbd> copy table cells!
- 🌟  **NEW** each package now includes a `dist/<name>.bundle.js` file which is a UMD bundle of all the javascript #588 
- this will allow us to support consumption from [Unpkg CDN](https://unpkg.com/), which is useful for environments like JSFiddle
- **NEW** test suite for NPM main files, ensures #566 won't happen again
- **NEW** isomorphic test suite ensures basic component support for server-side rendering (:tophat: @ codebling) #370, #595 
- **Changed** sweet refactors to the gulp build code make it friendlier …

Prepare Release v1.8.0

---

packages/datetime/examples/dateRangeInputExample.tsx
packages/datetime/examples/index.ts
packages/datetime/src/_daterangeinput.scss
packages/datetime/src/blueprint-datetime.scss
packages/datetime/src/common/classes.ts
packages/datetime/src/dateRangeInput.tsx
packages/datetime/src/index.ts
packages/datetime/test/dateRangeInputTests.tsx
packages/datetime/test/index.ts
packages/docs/src/styles/_examples.scss

> Second attempt at PR #609, which got in a bad state
Implemented the basic HTML and CSS for the `DateRangeInput` (without the popover), plus an example and a unit test.
- The unit test here is just a placeholder; it's present to ensure this PR meets the minimum coverage threshold.
- @llorca and I decided to nix (read: not implement) the calendar icon for now in preparation for nixing the `openOnFocus` prop eventually. That prop doesn't really make sense on this component, since this input wouldn't be particularly usable sans popover.

[Date Range Input] - Part 2: Basic HTML/CSS, example, and unit test

---

gulp/docs.js
package.json
packages/docs/src/common/propsStore.tsx
packages/docs/src/components/propsTable.tsx
packages/docs/src/components/section.tsx
packages/docs/src/components/styleguide.tsx
packages/docs/src/index.tsx
packages/docs/src/styles/_props.scss

- update to [ts-quick-docs@0.5.1](https://github.com/giladgray/ts-quick-docs/releases) to bring back default values
- refactor props table Tags: bold title, inline-block, reorder
we now have support for arbitrary `@tags` in doc comments, but we only know how to render the three shown in the screenshot (required, deprecated, inherited). a cool future task would be adding some new tags like `@since <version>` and `@warning <usage note/caveat>` (this could render a small callout!).
contrived example to demonstrate some of the new features:

restore props defaults

---

gulp/aliases.js
gulp/index.js
gulp/typescript.js

- add `withTasks` option to `defineTaskGroup` to include tasks that can't be defined in the group, such as `tslint-gulp`.
- always use `run-sequence` so parent task timing includes children:
```
[13:46:39] Using gulpfile ~/palantir/blueprint-public/Gulpfile.js
[13:46:39] Starting 'tsc'...                    <-- parent task starts first
[13:46:39] Starting 'icons'...
[13:46:39] Finished 'icons' after 102 ms
[13:46:39] Starting 'tsc-core'...
[13:46:39] core: compiling 68 typescript files
[13:46:44] Finished 'tsc-core' after 5.02 s
[13:46:44] Starting 'tsc-datetime'...
[13:46:44] Starting 'tsc-table'...
[13:46:44] datetime: compiling 13 typescript files
[13:46:46] table: compiling 35 typescript files
[13:46:49] Finished 'tsc-datetime' after 5.26 s
[13:46:49] Finished 'tsc-table' after 5.3 s …
```

gulp defineTaskGroup withTasks

---

packages/datetime/test/dateRangeInputTests.tsx

Add unit tests for `inputRef` handling (should have done this in the previous part, so making it a separate followup PR).
Nothing in particular. Should be quick.

[Date Range Input] - Part 3: inputRef unit tests

---

packages/core/src/components/tree/tree.tsx
packages/core/src/components/tree/treeNode.tsx
packages/core/test/tree/treeTests.tsx

Fixes #637
Added an `onNodeContextMenu` callback prop to `Tree`
* Can we get the tests working?
* Do we need the example in the docs changed at all?

Add onNodeContextMenu prop to Tree

---

packages/core/src/components/button/_button-group.scss
packages/core/src/components/forms/_control-group.scss

Add support for the generic `pt-fill` class modifier to control groups.
The CSS that enables that. It's very similar to button groups.

Support pt-fill in control groups

---

packages/core/src/components/popover/popover.tsx
packages/core/test/popover/popoverTests.tsx

- N/A Update documentation
Read `targetElement.clientWidth/Height` only when `useSmartArrowPositioning` is true.

Read target client width/height when useSmartArrowPositioning=true

---

packages/core/examples/numericInputExample.tsx
packages/core/src/components/forms/numericInput.tsx
packages/core/test/controls/numericInputTests.tsx

- _Bugfix:_ Stop auto-selecting the entire contents of the in the input field whenever props change
- _Nit:_ Deleted an errant unused variable in `numericInputTests.tsx`
- Updated `NumericInput` example to be fully controlled, so we can verify the error doesn't pop up again.

[Bugfix] Fix NumericInput auto-selection in controlled mode

---

packages/core/src/components/forms/_numeric-input.scss

- Use the more proper `onValueChange` callback instead of `onKeyDown` in `NumericInput` docs sample code

[Numeric Input] Use onValueChange in docs example code

---

packages/core/src/components/tooltip/_tooltip.scss
packages/core/src/components/tooltip/tooltip.tsx

- Sets `hoverOpenDelay` to `0`
- Keep transition duration at 100ms
Thoughts? cc @adidahiya @pkwi @thisisalessandro

Speed up tooltips by default

---

packages/core/src/common/props.ts

The `text` prop isn't required so the docs should reflect that

Tweak IActionProps docs

---

packages/core/src/components/forms/numericInput.tsx
packages/core/test/controls/numericInputTests.tsx

- _Bugfix:_ When `props.min` or `props.max` are updated such that the current value is now out of bounds, fire `onValueChange` with the clamped value to prevent the parent component from "remembering" the unclamped value.
_Before:_
Original value is shown if a bound changes to something else and back.
_After:_
Original value is replaced with the clamped value, such that the clamped value stays as is when the bounds change.

[Numeric Input] Fire onValueChange when min/max updated

---

packages/docs/src/styles/_content.scss

Adding `max-width: 100%;` on `.kss-example` fixes overflow problem on Firefox. 
I've tested on `Ubuntu, FF47`, but I think it should work on `OSX, FF51`.

Fix .kss-example overflow on Firefox

---

packages/datetime/src/common/dateUtils.ts
packages/datetime/src/common/displayMonth.ts
packages/datetime/src/common/monthAndYear.ts
packages/datetime/src/dateRangePicker.tsx
packages/datetime/test/dateRangePickerTests.tsx

The current way that we handle the `displayMonth` and in the state in `DateRangePicker` makes the code pretty unreadable if you do the obvious extension to the state as in #575.
Want to see how folks feel about creating a new class with all the comparison and helper methods. Caveat is that in the edge cases, you can end up cloning and recreating a lot of classes, but they're just functions anyway so shouldn't hit any perf problems.
This change along with the comments in the blocks from #575 should make things a lot easier to parse.
NB. Want some feedback if this is an awful idea before I clean up the duplication and un-disable the tests

Create new class for DateRangePicker state internals

---

packages/datetime/src/common/dateUtils.ts
packages/datetime/src/common/errors.ts
packages/datetime/src/dateInput.tsx
packages/datetime/src/dateRangeInput.tsx
packages/datetime/src/dateRangePicker.tsx
packages/datetime/test/dateRangeInputTests.tsx
packages/datetime/test/dateRangePickerTests.tsx
packages/docs/src/styles/_examples.scss

> Follow the commits to see the bite-sized progression of this work.
- *New Feature:* Show a basic `DateRangePicker` popover on focus in either input field.
- *New Feature:* Save the selected date range in the `DateRangeInput`'s state.
- *New Feature:* Trigger `onChange` when the selected date range changes.
- *Refactor:* Pull utility functions shared between `DateRangeInput` and `DateInput`, into `dateUtils`. 
- *Bugfix:* Tweak the docs style for immediate-sibling `pt-input-group`s to fix a style bug.

[Date Range Input] - Part 4: Basic DateRangePicker popover

---

packages/datetime/src/common/dateUtils.ts
packages/datetime/src/dateInput.tsx
packages/datetime/src/dateRangeInput.tsx
packages/datetime/test/dateRangeInputTests.tsx

> Second attempt at #680, which got in a bad state.
- _New feature_: Show the selected date range in the input fields
- _Refactor_: Add `isMomentNull(momentDate: moment.Moment): boolean` utility function, and use it in `dateInput.tsx` instead of `this.isNull`.
- This does _not_ support typing into the input fields yet; you can modify the date range only by clicking in the date picker.
- This does _not_ care about which input field was focused before the click; that'll come later.

[Date Range Input] - Part 5: Show selected values in input fields

---

packages/datetime/examples/dateRangePickerExample.tsx
packages/datetime/src/_daterangepicker.scss
packages/datetime/src/common/classes.ts
packages/datetime/src/dateRangePicker.tsx
packages/datetime/test/dateRangePickerTests.tsx

- Enable independent months feature though props
- Add independent DateRangePicker months tests
- Update docs
`isSequential` naming?

Set independent months in DateRangePicker through props, and add tests

---

packages/core/src/components/tree/_tree.scss
packages/core/src/components/tree/tree.tsx
packages/core/src/components/tree/treeNode.tsx
packages/core/test/tree/treeTests.tsx

Fixes #644
Add a `Tree#getNodeContentElement` method in order to get the underlying HTMLElement of tree nodes.
* We probably should add docs. Do we have any examples of other components with public methods?
* Naming for the new method
* Make sure implementation logic looks right

Add Tree#getNodeContentElement

---

packages/core/src/components/button/_common.scss

Hide background color on dark minimal disabled intent button hover

---

packages/core/src/common/classes.ts

Add `pt-icon` and `pt-text-overflow-ellipsis` to `Classes` 
Not sure if `pt-text-overflow-ellipsis` should be considered a "modifier" or in a new category 
@giladgray for review

Expose more CSS classes in JS

---

packages/core/src/components/forms/_common.scss

It's already declared at a higher level

Remove unnecessary font-family declaration on inputs

---

packages/core/src/components/forms/_input-group.scss

Before (lighter than placeholder, bad):
After:

Fix input group action static color

---

packages/core/src/components/button/_common.scss

Before (colored text only):
After (adds background shape):

Same styles for minimal button hover & focus

---

packages/core/examples/numericInputBasicExample.tsx
packages/core/src/components/forms/numericInput.tsx
packages/core/test/controls/numericInputTests.tsx

- New props are automatically added to `NumericInput`'s props tables
- Added toggles in the basic example for "Select all on focus" and "Select all on increment"
- _New feature:_ Add `selectAllOnFocus` prop.
- _New feature:_ Add `selectAllOnIncrement` prop.
- _Bugfix:_ Fix an unrelated unit-test lint error that wasn't causing builds to fail.
- _Bugfix:_ Fix #703 (failing `karma-unit-core` test in FF)
- _Bugfix:_ Fix #704 (focus hoarding on IE11)

[Numeric Input] Add "selectAllOnFocus" and "selectAllOnIncrement" props

---

packages/datetime/src/common/dateUtils.ts
packages/datetime/src/dateRangeInput.tsx
packages/datetime/test/common/dateTestUtils.ts
packages/datetime/test/dateInputTests.tsx
packages/datetime/test/dateRangeInputTests.tsx

> Second attempt at #683. The squashing is getting in the way of my rebasing behavior as I proceed to successive Parts. I'll stop opening multiple PRs at once.
Implemented controlled mode.
- _New feature_: Introduce a `value` prop.
- _New feature_: Introduce a `defaultValue` prop.
- Add prop descriptions for all existing props. 
- Add unit tests (and some reorganize existing ones into `when controlled` and `when uncontrolled` blocks).
- Harden existing unit tests (now that we can control the initial display month via `defaultValue` or `value`).

[Date Range Input] - Part 6: Controlled Mode

---

packages/core/src/components/forms/_input.scss

Per Andrew Colombi's feedback:
I noticed this line in the docs, "Text areas are similar to text inputs, but they are resizable" in the Text areas section of the "Form controls" page. My understanding is that the big difference between Text area and Text input is that Text area can be used for multiline editing. So that's what I would put there instead.

Update text area docs

---

packages/core/src/components/callout/_callout.scss
packages/core/src/components/forms/_input-group.scss
packages/core/src/components/menu/_common.scss

With this PR, colored icons get the same color value than the text next to it, in menus, callouts... Somehow, this was already the case for minimal buttons, so nothing to change there.
Before:
After:
cc @pkwi

Use same color for colored icon and text in menus, callouts

---

packages/core/src/components/button/abstractButton.tsx

Fixes #710
This is my first PR so please let me know if I need to update docs or do anything else.

Add 'active' prop to Button to avoid having to use 'pt-active' in className

---

packages/core/src/components/button/_common.scss
packages/core/src/components/forms/_common.scss
packages/core/src/components/forms/_file-upload.scss

- _New feature:_ Add support for `:disabled` on `pt-file-upload`
- _Refactor:_ Pull common `pt-button`/`pt-input` disabled styles into reusable mixins
- _Documentation:_ Add Modifier example in docs to showcase the new `:disabled` state.
- See #689 for the full discussion. Does this approach make sense? And does my execution look good on each of the three points above?
- I can add a unit test if we want.
Also, buttons are visually unchanged:
And inputs are visually unchanged:

Add :disabled support for pt-file-upload

---

packages/datetime/src/common/dateUtils.ts
packages/datetime/src/dateRangeInput.tsx
packages/datetime/test/dateRangeInputTests.tsx

- _New feature:_ Can now type dates into the input fields, and the picker selection will update (if uncontrolled).
- _Bugfix:_ Fix parallel issue I noticed in `DateInput` where editing the input field in controlled mode overwrote a controlled value. Now, if the user changes the text in an input field in controlled mode, (1) the calendar selection will not change, and (2) the controlled value will be repopulated in the field on blur. (And to be clear, I fixed this just for `DateRangeInput`, not for `DateInput` too).
_Changes NOT included:_
- **I didn't implement input validation yet**. It's perfectly possible to input backward or otherwise invalid date ranges. The next PR will deal with input validation.
- **I didn't implement focus-handling yet.** The focused field has no bearing on which …

[Date Range Input] - Part 7: Typing dates into input fields

---

packages/core/package.json
packages/core/src/blueprint.scss
packages/core/src/common/_mixins.scss
packages/core/src/components/forms/_common.scss
packages/core/src/components/progress/_progress-bar.scss

- bump bourbon to latest 4.x
- stop using bourbon prefixer mixins. Bourbon has deprecated _all_ of them in favor of a tool like Autoprefixer. we already use Autoprefixer so this was easy.
- manually disable logging of bourbon deprecations warnings via handy Sass variable!
- the only remaining warning is about `strip-units` being renamed, but nothing we can do as we're not on 5.0 yet.
cc @bsr203

fix bourbon deprecations warnings

---

packages/core/src/components/non-ideal-state/_non-ideal-state.scss

add `height: 100%` to NonIdealState so it fills its container and centers its contents. we already set `width: 100%` so this is just consistent.
try setting an explicit height on the parent `div` of the example and you'll see how the `.pt-non-ideal-state` grows to fill the space and keeps its content centered.

center NonIdealState contents vertically

---

packages/core/src/components/button/_common.scss

Fix appearance of custom minimal buttons in focus states

---

docs/blueprint-landing.css
docs/blueprint-landing.js
docs/docs/docs.css
docs/docs/docs.js
package.json
packages/core/package.json
packages/datetime/package.json
packages/docs/package.json
packages/table/package.json

:fireworks: **Highlights**: new `NumericInput` props, `.pt-tag` mixins support custom colors, non-contiguous `DateRangePicker` months.
- 🖌  Updated Sketch Kit: removed missing font references, added Callouts. #728
- 🌟  __NEW__ `NumericInput` props:
- `allowNumericCharactersOnly` (default `true`) restricts the allowed characters. #618, #676 
- `selectAllOnFocus` selects all text when the input is focused #705 
- `selectAllOnIncrement` selects all text when the input is incremented #705 
- __NEW__ `Tree` `getNodeContentElement` instance method to access the underlying `HTMLElement` of tree nodes. Useful for implementing scrolling (#644). #679 
- __NEW__ `Button` `active` prop sets `.pt-active` class (:tophat: …

Prepare Release v1.10.0

---

packages/core/src/components/forms/numericInput.tsx

- Add `selectAllOnIncrement` to `removeNonHTMLProps` to get rid of the React warning.

Add 'selectAllOnIncrement' to removeNonHTMLProps

---

packages/table/src/table.tsx

Fix behavior so that className (and everything else) from the parent column, as it worked before.

Pass along column props to cell renderer

---

packages/core/examples/buttonsExample.tsx

Hey Blueprint team,
I was excited my new `Button active` prop made it in 1.10 and it cleaned up my code significantly! 😄 
I noticed the docs were missing a `Switch` showing off the new prop in the docs. Here's a PR. Lmk if anything is missing.
Drew

Update Button docs to add a switch demonstrating the new active prop

---

packages/datetime/src/dateRangeInput.tsx
packages/datetime/src/index.ts
packages/datetime/test/dateRangeInputTests.tsx

Input validation when typing dates.
- _New feature_: Show an error message when the inputted date has an invalid date format (configurable via a new prop: `invalidDateMessage`).
- _New feature_: Show an error message when the inputted date is out of range of `[minDate, maxDate]` (configurable via a new prop: `outOfRangeMessage`).
- _New feature_: Show an error message when the inputted dates overlap (configurable via a new prop: `overlappingDatesMessage`).
- _New feature_: Trigger `this.props.{start,end}InputProps.onChange` for controlled usage.
- Add a bunch of rigorous unit tests for each of these cases, verifying behavior for all permutations of scenarios (inputting in start field or end field, inputting out-of-range dates that precede min or exceed max, etc.).
- Various other handling …

[Date Range Input] - Part 8: Input Validation

---

packages/table/examples/tableFormatsExample.tsx
packages/table/src/cell/formats/jsonFormat.tsx
packages/table/test/formatsTests.tsx

Remove `PureRender` and change the default props to detect truncation.
I left JSONFormat alone when first implementing the detect truncation feature because I thought people might prefer to just always show the popover to view JSON and manually truncate. Are the default props changes okay?
JSONFormat now properly detects truncation

Remove PureRender and default to detect truncation

---

packages/core/src/components/overlay/overlay.tsx

literally a single character fixes the Overlay `openStack` so it removes overlays when they're at index `0`.

fix bad index comparison in Overlay stack

---

packages/core/src/common/errors.ts
packages/core/src/common/utils.ts
packages/core/src/components/tabs/_tabs.scss
packages/core/src/components/tabs/tabs.tsx

- `Utils.isNodeEnv` helper function checks value of `process.env.NODE_ENV`.

add deprecation warning to Tabs constructor

---

packages/core/src/common/keys.ts
packages/datetime/src/common/dateUtils.ts
packages/datetime/src/common/errors.ts
packages/datetime/src/dateRangeInput.tsx
packages/datetime/src/dateRangePicker.tsx
packages/datetime/src/index.ts
packages/datetime/test/dateRangeInputTests.tsx

I tried to find some lower bar of completeness so that we can release this thing ASAP, but I really couldn't find a tradeoff that made sense. **A usable `DateRangeInput` that supports both typing and click-selection really needs to obey—and control—the focused input field.** This PR makes that happen to (I think) glorious effect, and I've tested the heck out of it to make sure every little edge case works as expected.
(See preview for now, will add a GIF tomorrow)

[Date Range Input] - Part 9: Obey and control the focused field

---

packages/table/src/cell/formats/_formats.scss

Change overflow: scroll to auto
Looks so much better now:

Use overflow: auto for table popovers rather than scroll

---

packages/datetime/examples/common/formatSelect.tsx
packages/datetime/examples/dateInputExample.tsx
packages/datetime/examples/dateRangeInputExample.tsx
packages/datetime/src/_daterangeinput.scss
packages/datetime/src/dateRangeInput.tsx
packages/datetime/test/dateRangeInputTests.tsx

- Change popover position back to `BOTTOM_LEFT`
- Add documentation for `DateRangeInput` (pretty closely mimicking documentation for `DateInput`).
- Add `disabled` prop, add a control for it to the example, and add tests
- Add `closeOnSelection` prop, add a control for it to the example, and add tests
- Add a `format` control to the example (and create a new, reusable `FormatSelect` component)
This is the full—and final!—set of changes I'd like to merge into `feature/date-range-input`. Next step after this merges: merge `feature/date-range-input` into `master`.

[Date Range Input] - Part 10: Docs, final little props, etc.

---

packages/core/src/common/tetherUtils.ts
packages/core/src/components/context-menu/contextMenu.tsx
packages/core/src/components/popover/popover.tsx
packages/table/src/cell/formats/truncatedFormat.tsx
packages/table/src/headers/columnHeaderCell.tsx

- Set the constraints prop on Popover to deprecated
- Introduced the tetherOptions prop on Popover, where it is possible to overwrite the settings of Tether

Add tetherOptions prop to Popover

---

packages/datetime/src/dateRangeInput.tsx

**Before:** If you moved your mouse within the calendar while the `DateRangeInput` popover was closing, then `handleDateRangePickerHoverChange` was invoked, which had the unfortunate side effect of refocusing an input and consequently reopening the popover on focus.
**After:** If `isOpen` is false, then we know the popover is either closed or animating closed. Adding a check for that case in `handleDateRangePickerChange` and `handleDateRangePickerHoverChange` fixes the re-opening popover issue.
Do we want to add unit tests for this? Would require a hard assumption on a transition duration specified in a SCSS file, which feels...meh.

Ignore mouse events in DateRangeInput popover when animating closed

---

packages/table/preview/index.tsx
packages/table/src/regions.ts
packages/table/src/table.tsx
packages/table/test/tableTests.tsx

Add the ability to resize multiple columns or rows together -- all selected columns/rows will resize when you resize a single one. 
Right now I'm just calling the callback for the one row/col that was changed by user interaction -- I'm not sure if we should call it a bunch of times, or change the interface and make it a breaking change, or what. What are your thoughts here?

Add linked column and linked row resizing -- resizing one does all

---

packages/core/src/components/non-ideal-state/nonIdealState.tsx

It would appear that the docs for this component were
....
....
"non-ideal"

Non ideal docs

---

packages/core/examples/numericInputBasicExample.tsx
packages/core/src/components/forms/_numeric-input.scss
packages/core/src/components/forms/numericInput.tsx
packages/docs/src/styles/_sections.scss

Add `pt-fixed` to the `pt-button-group` within `NumericInput`. This ensures only the `pt-input-group` will stretch when the `NumericInput` is styled as full-width via a `pt-fill` class.
- Is there a good way to test this?
- **DONE** ~Do we want to add a note mentioning you can style `NumericInput` with `pt-fill`?~

Add styling to support full-width NumericInput

---

packages/table/src/locator.ts

Fix bug I accidentally introduced in #685 ( https://github.com/palantir/blueprint/pull/685/files#diff-85bb3412e972df58b0e3115a878bf248L63 )
Make class should be what it should be so it actually selects the cells in the table.

Fix column auto resize

---

packages/core/examples/sliderExample.tsx
packages/core/src/common/utils.ts
packages/core/src/components/slider/coreSlider.tsx
packages/core/test/slider/sliderTests.tsx

- `Slider` `labelPrecision` prop for default label formatting
- default value is inferred from `stepSize` prop
- store actual value in state to avoid recomputing it for every label render
- new util `countDecimalPlaces(num)`

Slider labelPrecision

---

packages/core/src/common/props.ts
packages/core/src/components/forms/controls.tsx
packages/core/test/common/propsTests.ts

"indeterminate" is not a valid HTML attribute for inputs, so we should filter it out automatically
**Edit:** My original change wasn't necessary on it's own, this PR has been slightly changed in purpose

Filter out "indeterminate" prop by default

---

packages/core/src/components/forms/_file-upload.scss

Add pt-fill support to file upload

---

packages/table/src/common/_variables.scss
packages/table/src/interactions/_interactions.scss
packages/table/src/regions.ts
packages/table/src/table.scss
packages/table/src/table.tsx
packages/table/test/tableTests.tsx

Add styles for select-all for table
Added select-all interactions -- clicking on the upper left hand corner, or pressing mod+a 
The "display: table" style change is weird because I have no idea why it works -- does anyone know a better way to make it have the height of its child? 
The "table" method in regions.ts is one of the most hillarious functions I've ever written. 
I added "full table" selection to all -- should we add a ROWS_COLUMNS_AND_CELLS selection mode to the thing? Or leave as-is?

Add select all styles and interactions to table

---

packages/datetime/src/dateRangePicker.tsx
packages/datetime/test/dateRangePickerTests.tsx

1. During getStateChange, when setting a date range that spans months, left view and right view are kept only 1 month apart. Previous to this fix, the right view would get set to the end month of the range even though the start month and the following month are what gets displayed in the component. This then causes a no-op the following round trip through when selecting a single date range that lies within the previous range's end month.
Behavior with other settings like `contiguousCalendarMonths`, but that is not taken into account throughout the existing code.
Selected "Past 3 months"
Selected "Past week"

[DRP] Assign right and left together, keep them 1 month apart

---

docs/blueprint-landing.css
docs/blueprint-landing.js
docs/docs/docs.css
docs/docs/docs.js
package.json
packages/core/package.json
packages/core/src/components/slider/coreSlider.tsx
packages/core/test/text/textTests.tsx
packages/datetime/package.json
packages/docs/package.json
packages/table/examples/tableFormatsExample.tsx
packages/table/package.json

:fireworks: **Highlights**: new `Text` component, tooltips can open on focus, `Table` select all, `Table` resize all selected rows/columns, `Cell` text wrapping!
- 🌟  __NEW__ `Text` component conditionally adds the `title` attribute and truncates with an ellipsis when content overflows its container (:tophat: @ryanmcnamara) #765 
- 🌟  __NEW__ `Popover`/`Tooltip` `openOnTargetFocus` prop (default `true`) triggers the popover when its target is focused #734 
- this prop is only available when `interactionKind` is `HOVER` or `HOVER_TARGET_ONLY`
- __NEW__ `Popover`/`Tooltip` `tetherOptions` prop exposes the remaining [Tether options](http://tether.io/#options) (:tophat: @Binck360) #750 #789 
- this may allow you to …

Prepare Release 1.12.0

---

packages/docs/src/components/styleguide.tsx

- this solves the overscroll issue we had previously (cuz page doesn't change) while also ensuring that the active section is always visible when the page loads.
- sidebar scrolls the active _page_ into view so you can see the entire layout, rather than just the active section!
overscroll issue fixed! notice how the scrollspy still updates the active section when it's offscreen:
scroll the active _page_ into view so you can see the entire layout:

[DM] only update scroll position when page changes

---

gulp/util/text.js
package.json

[documentalist@0.0.4](https://github.com/palantir/documentalist/releases/tag/release-0.0.4) enables markdown rendering in the KSS plugin for documentation and markup code.

[DM] update documentalist for syntax highlighting

---

packages/core/examples/common/baseExample.tsx
packages/core/examples/contextMenuExample.tsx
packages/core/examples/index.ts
packages/core/examples/inputGroupExample.tsx
packages/docs/src/common/resolveExample.tsx
packages/docs/src/components/page.tsx
packages/docs/src/styles/_examples.scss
packages/docs/src/styles/_sections.scss

Definitely read the individual commits to follow the individual threads here.
- `BaseExample` exports its props interface so docs example renderer can reuse it.
- add more `data-` attributes and corresponding sass helper functions so we can target specific pages (`[data-page-id="table-js"]`) and react examples (`[data-example-id="ButtonsExample"]`).
- refactor some of the more involved examples so their custom styles are hopefully simpler. see `ContextMenuExample` and `InputGroupExample` commits.
@themadcreator this PR should fix the table examples.

[DM] React examples styles

---

packages/table/src/headers/columnHeaderCell.tsx
packages/table/src/table.tsx
packages/table/test/columnHeaderCellTests.tsx
packages/table/test/columnTests.tsx
packages/table/test/harness.ts
packages/table/test/tableTests.tsx

- Pass through custom `className` for `Table`, `Column`, and `ColumnHeaderCell`
- Add unit tests for each
- Does this scheme make sense?

[Table] Pass custom className to Table, Column, ColumnHeaderCell elements

---

packages/datetime/src/common/dateUtils.ts
packages/datetime/src/dateRangePicker.tsx
packages/datetime/test/common/dateUtilsTests.tsx
packages/datetime/test/dateRangePickerTests.tsx
packages/datetime/test/index.ts

- Add `areRangesEqual` in `dateUtils.tsx` plus unit tests
- Fix the bug and guarantee it with a unit test.
- We should unit-test our utility functions.
- After these changes, the `DateRangePicker` will still shift if you finish selecting a range with a click in the RIGHT month (it shifts the right month to be the new LEFT month).

[DateRangeInput] Bugfix: don't shift month view on day hover

---

packages/datetime/src/dateRangeInput.tsx
packages/datetime/src/dateRangePicker.tsx
packages/datetime/test/dateRangeInputTests.tsx

Before, we let the focused field dictate which end of the boundary the next click would specify.
Now, we simply mirror the behavior of the default `DateRangePicker`, moving focus as necessary to indicate which boundary the next click will modify.
In particular:
- If selection is `[<startDate>, null]` with `END` field focused:
- _Before:_ Clicking on `<startDate>` sets selection to `[null, <startDate>]`
- _After:_ Clicking on `<startDate>` sets selection to `[null, null]`
- If selection is `[null, <endDate>]` with `START` field focused:
- _Before:_ Clicking on `<endDate>` sets selection to `[<endDate>, null]`
- _After:_ Clicking on `<endDate>` sets selection to `[null, null]`
- If selection is `[<startDate>, <endDate>]` with `START` field focused:
- _Before:_ Clicking on `<endDate>` sets …

[DateRangeInput] Make on-click behavior more intuitive

---

packages/datetime/examples/dateRangeInputExample.tsx
packages/datetime/src/dateRangeInput.tsx
packages/datetime/test/dateRangeInputTests.tsx

Add `selectAllOnFocus` prop that, when `true`, selects the text in the field:
- On manual focus
- On day hover in the calendar
Also added a "Select all on focus" toggle to the `DateRangeInput` example. 
Can't unit test this in Phantom, hence the lack of tests. :(

[DateRangeInput] Add selectAllOnFocus prop

---

packages/core/src/components/tabs2/tabs2.tsx
packages/core/test/tabs/tabs2Tests.tsx

basically, `isTab` first checks `!= null`.
new rule: type guards must first check existence.

[Tabs2] fix NPEs with null children

---

packages/core/src/common/_mixins.scss
packages/table/src/table.scss

`Table`'s `will-change` rules are not playing nicely with `Popover`'s `transition` rules. Consequently, tables appear blurry in dialogs (see the YouTube video linked from #742 for a good illustration of the Chrome bug that's causing all of this).
This PR deletes these `will-change` rules in favor of old-fashioned `tranform: translateZ(0)` rules to remove the blurriness while keeping the hardware-accelerated benefits intact.
I made a `TableDialogExample` locally to verify the changes (but didn't push it to the branch). See the screenshots below for the Before/After.
_Before:_
_After:_

[Table] Fix blurry table in dialog

---

packages/core/examples/tabs2Example.tsx
packages/core/src/components/tabs/_tabs.scss

- minor change to Tabs CSS API: `.pt-large` modifier can be applied to _any ancestor_ of `.pt-tab`, not just the `.pt-tab-list`: `.pt-large .pt-tab`
- so `<Tabs className={Classes.LARGE}>` will give you nice large tabs
- an alternative approach to this fix is to add `tabListClassName` prop. is that preferable? might that be desirable anyway, even with this change?

[Tabs] .pt-large .pt-tab uses simple nesting

---

packages/datetime/examples/dateRangeInputExample.tsx
packages/datetime/src/common/dateUtils.ts
packages/datetime/src/dateRangeInput.tsx
packages/datetime/src/dateRangePicker.tsx
packages/datetime/test/dateRangeInputTests.tsx
packages/docs/src/styles/_sections.scss

- Add `allowSingleDayRange` prop to `DateRangeInput`
- Add unit tests
- Add toggle to example
- Tricky date comparison logic that needs to ignore hours/minutes/seconds/millis.
- Modified overlapping-dates logic.

[DateRangeInput] Add allowSingleDayRange prop

---

packages/datetime/src/dateRangeInput.tsx
packages/datetime/test/dateRangeInputTests.tsx

- Show formatted min/max dates on focus in an empty start/end input
- Things break if `min/max === null`, but that's already not really a supported case. Can address that more generally in a future PR if we want.
- See comments about caching the formatted min/max date strings. If we don't cache the formatted min/max date strings in `this.state`, then we'll have to cast those vanilla JS dates to `moment`s on every render just to achieve properly formatted placeholder dates, which is exceedingly wasteful.

[DateRangeInput] Show formatted min/max dates on focus when inputs empty

---

packages/datetime/examples/dateInputExample.tsx
packages/datetime/src/dateInput.tsx
packages/datetime/test/dateInputTests.tsx

Got a request in person to add support for hiding the calendar icon in `DateInput`. Seemed reasonable and easy, hence this PR. After initially adding a `showIcon` prop to accomplish this, @llorca and I agreed that deleting the calendar icon altogether would be preferable (this is what we did with `DateRangeInput`).
Related: see #867, which I've assigned to Milestone 2.X due to its API-breaking nature (goal is to remove `openOnFocus` if we go through with deleting the icon element now).
- Add `rightElement` prop to `DateInput` to allow customizable right element (particularly: nothing, static icon, interactive icon)
- Does this sound reasonable?
- Is this considered a breaking change or not?
- Is the prop description text okay?
_Before_
_After_

[DateInput] Delete calendar icon, add optional rightElement prop

---

packages/core/src/components/forms/_common.scss

Restores input borders in Mobile Safari on iOS

Shows input borders in Mobile Safari on iOS

---

gulp/docs.js
package.json
packages/docs/src/common/resolveDocs.ts
packages/docs/src/common/resolveExample.tsx
packages/docs/src/components/navMenu.tsx
packages/docs/src/components/navigator.tsx
packages/docs/src/components/page.tsx
packages/docs/src/components/propsTable.tsx
packages/docs/src/components/styleguide.tsx
packages/docs/src/index.tsx

- update to documentalist@0.0.5. let the [release notes](https://github.com/palantir/documentalist/releases/tag/release-0.0.5) serve as a preview of the changes in this PR.
- 🔥 sweet url-like routes of the form `core/components/button.javascript-api`
- the `nav` tree logic is now built into DM so the gulp task is dead simple config, as it should be

[DM] core/components/button.javascript-api

---

gulp/docs.js
package.json
packages/docs/src/components/navMenu.tsx
packages/docs/src/index.tsx
packages/docs/src/styles/_layout.scss

- documentalist@0.0.6: now with options. 
- use .d.ts files for typescript info, like we used to (shaves about 2s off runtime)
- nav only expands active route, not all pages

[DM] nav nesting

---

packages/datetime/examples/dateRangeInputExample.tsx
packages/datetime/src/dateRangeInput.tsx
packages/datetime/src/dateRangePicker.tsx
packages/datetime/test/dateRangeInputTests.tsx
packages/docs/src/styles/_sections.scss

Quick PR to ensure users can configure all `DateRangePicker` props from `DateRangeInput`. In particular:
- Add `contiguousCalendarMonths` prop to `DRI`
- Add `shortcuts` prop to `DRI`
- Add unit tests
- Add `contiguousCalendarMonths` toggle to `DRI` example
- This PR was motivated by internal requests.
- Possible to get in for today's release?

[DateRangeInput] [DateRangePicker] Support the same props in DRI as in DRP

---

packages/table/src/headers/_headers.scss
packages/table/src/headers/columnHeaderCell.tsx

Quick little thing. In the spirit of aggressively opening PRs and then asking for feedback, I propose that we change the default header-menu icon from `pt-icon-more` (···) to `pt-icon-chevron-down` (⌄), which looks and feels much more intuitive to me.
Also, I found it annoying that the icon looked the same whether you were hovering inside or outside of it within the header cell. This PR shows the icon with `$pt-icon-color` when you hover in the header cell but NOT within the icon, showing `$pt-icon-color-hover` only when you mouse over the clickable icon area.
_Before:_
_After (Light theme):_
_After (Dark theme):_
For what it's worth, these changes seem consistent with the original mocks for the Table from way back when (although the chevron in the mocks feels too big):
- I think the …

[Table] Change header menu icon to chevron and add a bounding box for better affordance

---

packages/table/preview/index.html
packages/table/preview/index.tsx

The dashes made it harder to grok and were less realistic. The fixed size was unnecessary for this example and cut off the last column awkwardly
@cmslewis

Update table example for ease of use

---

packages/datetime/test/dateInputTests.tsx

Delete unused Button import in `dateInputTests.tsx`. Been meaning to do this ever since I noticed it a few weeks ago; just kept forgetting.

Fix broken DateInput test

---

packages/table/preview/index.html

Interestingly I never tried to view the examples below the custom header example when I first made this change. Now I did and I don't like the unbounded table, but I do want it to be wider
@cmslewis - sorry for the churn

[Table] Add back fixed size to table example but increase width

---

packages/core/src/components/button/_button-group.scss
packages/core/src/components/button/_common.scss

Now works well with `pt-minimal`, `pt-large`, `pt-vertical` or any combination of these.
The general approach to the solution
Before:
After:

Make minimal button group divider modifier-independent

---

packages/datetime/src/dateRangeInput.tsx
packages/datetime/src/dateRangePicker.tsx
packages/datetime/src/dateRangeSelectionStrategy.ts

Found some time tonight to refactor related logic around date-range selection and hovered-boundary refocusing into a separate `DateRangeSelectionStrategy` class. We can make the strategy a prop in `IDateRangePickerProps` eventually (perhaps making it a Plain Old JS Object in the process), but for now, this particular strategy is hardcoded into `DateRangePicker`.
- Tons of code deleted!
- All unit tests still pass!
- Added `hoveredBoundary` as a third parameter to `onHoverChange`; now, the `DateRangeInput` doesn't have to duplicate any work.
- The unit tests we had in place were sufficiently exhaustive to make the correctness of this refactor quite easy to guarantee!

[DateRangePicker] [DateRangeInput] Refactor related logic into DateRangeSelectionStrategy class

---

packages/table/src/table.tsx

In a world with strict-null-checks, the typing is wrong -- make it so the typing actually supports sparse arrays in a strict null check world.

[Table] Make row and column heights/widths sparse arrays types correct

---

packages/table/src/regions.ts
packages/table/src/table.tsx

When receiving new props, if regions are in uncontrolled mode, check all regions to make sure they still fit. Remove the ones that don't. 
I'm doing this in uncontrolled mode only. Should I do it in controlled mode too?

[Table] Remove invalid selection regions when getting new props

---

packages/core/src/components/collapse/collapse.tsx

... not overflow style because it only controls vertical height / animation of its contents.
Bugfix to limit the scope of the `Collapse` component's inline styles because this was messing up layout in my app.

Collapse container should only set overflow-y

---

packages/datetime/src/dateRangeInput.tsx
packages/datetime/src/daterangeinput.md
packages/datetime/test/dateRangeInputTests.tsx

- Add a `popoverProps` prop to `DateRangeInput` to support custom callbacks for `popoverWillOpen`, `onClose`, etc.
- *DO NOT* allow users to override `autoFocus`, `content`, or `enforceFocus`, because that would lead to sad times w/r/t UX.
- *DO* allow for overriding of `isOpen` and other popover props.
- Does it make sense to allow overriding of `isOpen`?
- Should we throw an error or print a warning or otherwise notify the user when certain props they included are being ignored?

[DateRangeInput] Add popoverProps prop

---

packages/core/src/common/errors.ts
packages/core/src/components/popover/popover.tsx
packages/core/src/components/tooltip/tooltip.tsx
packages/core/test/popover/popoverTests.tsx
packages/core/test/tooltip/tooltipTests.tsx

- disable empty tooltips
- empty = null/undefined, empty string, whitespace strings.

[Tooltip] disable empty tooltips

---

packages/core/src/components/menu/_common.scss

this is causing internal builds to fail (https://pl.ntr/eH). public builds are fine because the default values never get used in blueprint.css

fix sass argument typo

---

packages/core/src/common/tetherUtils.ts
packages/core/src/components/popover/popover.tsx
packages/core/test/popover/popoverTests.tsx

- fixes a super subtle bug whereby the implementation for `useSmartPositioning` modified the `tetherOptions` argument. in the default state, `tetherOptions` refers to the static `Popover.defaultProps.tetherOptions` object so all popovers would inherit the smart positioning constraints. mutation removed!
- :x: deprecate `useSmartPositioning`

Popover useSmartPositioning should not mutate defaultProps

---

packages/core/src/components/collapse/_collapse.scss

#938 broke collapse styles by changing the TS overflow to `overflow-y`, but leaving scss overflow as `overflow` (which is not overridden by the latter). That means that shadows and other overflowing elements are cut off.
This PR fixes the issue by also switching scss overflow to `overflow-y`.
@adidahiya for SA

Fix collapse overflow

---

packages/core/examples/popoverExample.tsx
packages/core/src/common/abstractComponent.ts
packages/core/src/common/errors.ts
packages/core/src/components/dialog/dialog.tsx
packages/core/src/components/forms/radioGroup.tsx
packages/core/src/components/popover/popover.tsx
packages/core/src/components/tabs/tabs.tsx
packages/core/src/components/toast/toaster.tsx
packages/core/src/components/tooltip/tooltip.tsx
packages/core/test/controls/radioGroupTests.tsx
packages/core/test/popover/popoverTests.tsx

- Refactor most Popover errors to warnings
- Refactor PopoverExample to avoid warnings
- Refactor most errors into warnings
- Refactor RadioGroup errors to support non-Radio children
- Remove non-error tests, fix others

refactor most validateProps errors to warnings

---

packages/datetime/src/common/errors.ts
packages/datetime/src/dateInput.tsx
packages/datetime/test/dateInputTests.tsx

- new `popoverProps` prop proxied to `Popover`
- :x: deprecate `popoverPosition`

DateInput popoverProps

---

packages/core/src/common/errors.ts
packages/core/src/common/utils.ts
packages/core/src/components/alert/alert.tsx
packages/core/src/components/context-menu/contextMenuTarget.tsx
packages/core/src/components/hotkeys/hotkey.tsx
packages/core/src/components/hotkeys/hotkeys.tsx
packages/core/src/components/menu/menuItem.tsx
packages/core/src/components/slider/handle.tsx
packages/core/src/components/toast/toaster.tsx
packages/core/test/context-menu/contextMenuTests.tsx
packages/core/test/hotkeys/hotkeysTests.tsx
packages/core/test/menu/menuTests.tsx

- check the commits for exact changes.
- remaining constants in `errors.ts` that do not include the word `WARN` are actual show-stopping errors so it's ok to throw them. (currently; we may want to refactor some components so these aren't show-stopping.)

Convert more errors to warnings

---

packages/datetime/src/dateRangeInput.tsx
packages/datetime/test/dateRangeInputTests.tsx

Literal changes:
- Change `IInputGroupProps` to `HTMLInputProps & IInputGroupProps` for each input
- Can now add custom callbacks for `onFocus`, `onBlur`, `onClick`, and so on.
- Can now add custom placeholder text.
- Add tests
- Update descriptions for `startInputProps` and `endInputProps` to mention the props you can't customize.
- Ended up casting the input-group props as `any` when spreading. Is there a better way? See #943 as well.
- The `handleXInputY` callbacks are a little repetitive. There's probably a cute way to make all of those wrappers more concise.

[DateRangeInput] Support full HTMLInputProps on each input

---

packages/datetime/examples/dateInputExample.tsx
packages/datetime/src/dateInput.tsx
packages/datetime/test/dateInputTests.tsx

- must set `datePickerProps` rather than spreading all props. (cc @mfedderly)

fix DateInput composition of DateTimePicker

---

packages/datetime/src/dateRangeInput.tsx
packages/datetime/test/dateRangeInputTests.tsx

- `IDateRangeInputProps extends IDatePickerBaseProps` but it didn't pass all of them along to `DateRangePicker`
- I changed the props to use a spread so all supported props will be passed along automatically (including `locale`).

DateRangeInput spreads all props to DateRangePicker

---

packages/datetime/src/common/errors.ts
packages/datetime/src/dateInput.tsx
packages/datetime/src/dateinput.md

- Deprecate `openOnFocus` (on the road to #867)
- Remove mention of calendar button in `DateInput` docs (we deleted it in `datetime` `v1.11.0`)

[DateInput] Remove mentions of calendar button

---

packages/table/src/cell/formats/jsonFormat.tsx
packages/table/src/cell/formats/truncatedFormat.tsx
packages/table/src/column.tsx
packages/table/src/common/contextMenuTargetWrapper.tsx
packages/table/src/common/loadableContent.tsx
packages/table/src/common/utils.ts
packages/table/src/headers/editableName.tsx
packages/table/src/headers/rowHeaderCell.tsx
packages/table/src/interactions/menus/copyCellsMenuItem.tsx
packages/table/src/interactions/resizeHandle.tsx
packages/table/src/layers/guides.tsx
packages/table/src/layers/regions.tsx
packages/table/src/regions.ts
packages/table/src/table.tsx
packages/table/test/utilsTests.ts

Redux of #988 that fixes some of the nefarious bugs that popped up.
Goal: Improve table perf by eliminating unnecessary re-renders, particularly when clicking+dragging.
- Add `@PureRender` decorator throughout `packages/table`.
- Add custom `shouldComponentUpdate` to `GuideLayer` to avoid unnecessary re-renders.
- Add custom `shouldComponentUpdate` to `RegionLayer` to avoid unnecessary re-renders.
- 🔥 Also, change `RegionLayer` props to accept pre-computed `regionStyles` instead of `getRegionStyle` function. Before, we were creating this styling function inline in `table.tsx` on each render, causing shallow comparison between `this.props.getRegionStyle === nextProps.regionStyle` to always return `false` in `RegionLayer.shouldComponentUpdate`. Ultimately, this led to tons of unnecessary …

[Table] Eliminate unnecessary re-renders everywhere

---

packages/core/src/components/tooltip/tooltip.tsx

- add `inheritDarkTheme` prop
- only warn about empty content when it _would_ be shown

[Tooltip] add inheritDarkTheme and fix empty warning

---

packages/core/examples/alertExample.tsx
packages/core/examples/dialogExample.tsx
packages/core/examples/overlayExample.tsx
packages/core/examples/toastExample.tsx
packages/core/examples/tooltipExample.tsx
packages/core/src/components/popover/popover.tsx
packages/site-docs/src/components/blueprintDocs.tsx
packages/site-docs/src/tags/reactExamples.ts

- the actual fix for the issue was ensuring that we call `this.setState()` _after_ updating local storage with new theme state so that the examples are seeing the latest state when they re-render.
- refactor BaseExample `getTheme` callback prop to string `themeName`, for simplicity.
- Popover and Tooltip examples should respond to theme switching every time.
Here's a cool thing:

[site-docs] fix theme switcher inheritance

---

docs/blueprint-landing.css
docs/blueprint-landing.js
docs/docs/site-docs.css
package.json
packages/core/package.json
packages/datetime/package.json
packages/docs/src/components/baseExample.tsx
packages/site-docs/package.json
packages/table/package.json

:fireworks: **Highlights**: top quality bug fixes and some very impressive new `Table` features.
- __Fixed__ `Popover` `useSmartPositioning` does not mutate `defaultProps` for all other popovers on the page #973 
- __Fixed__ `Collapse` overflow styles (follow-up from #938) #976 
- __Fixed__ `Tooltip` `inheritDarkTheme` prop now appears in interface #993 
- __Fixed__ `Tooltip` warns about disabling empty popover only when popover _would_ be shown #1000 
- __Fixed__ set `displayName` correctly on all components (must be `public static`) #982
- __Fixed__ `dark-menu-item` sass mixin argument typo #961 
- __Changed__ most props validation thrown errors to console warnings because they are not error-worthy, merely …

Prepare Release 1.15.0

---

packages/core/src/components/popover/popover.md
packages/table/src/cell/formats/truncatedFormat.tsx

- we were already setting `tetherOptions`, and then overriding it with `useSmartPositioning` 😱 
- had to update constraints to preserve prior behavior.

fix Popover deprecation warning in Table

---

packages/datetime/src/dateInput.tsx
packages/datetime/src/dateRangeInput.tsx
packages/datetime/test/dateInputTests.tsx

- add `DateInput` `inputProps` exactly like we did for `DateRangeInput` in #945 
- turns out this wasn't the least bit breaking, nor did it require any deprecations!

[DateInput] add inputProps just like DRI

---

packages/docs/src/components/documentation.tsx
packages/docs/src/styles/_layout.scss

- add `?examples` query string to URL to hide all that crufty text so you can focus on the _examples_

add ?examples to hide all that crufty text

---

packages/table/src/headers/columnHeader.tsx
packages/table/src/headers/rowHeader.tsx
packages/table/src/locator.ts
packages/table/test/columnTests.tsx

Added the relevant classes to the column and row headers, so they'll be included if you try to select all the cells in a given column/row. 
Modified the resize logic to only grab cells with that one class, instead of also grabbing all the headers in the entire table.

Add cell class to row/column headers so auto-resize works properly

---

packages/table/src/cell/formats/jsonFormat.tsx
packages/table/src/cell/formats/truncatedFormat.tsx

Delete @PureRender on `TruncatedFormat` and `JSONFormat` so that cell content updates properly when cells are resized.
This is a quick fix that may increase the number of unnecessary re-renders. Would be better to think of a not-weird way to inform cell content that a cell parent's width has updated.
Some weird ways that come to mind:
- Passing a callback that a parent fires for a child to respond to is backward and weird.
- Passing a prop value like `shouldUpdate`/`didCellSizeChange` is goofy and weird.
- `context`? Have never done much with that, but from what I've read, even this use case seems ill-fitted for that.
- Or, keeping the API more straightforward (but bloated): `cellWidth`/`cellHeight` props.

[Table] Delete @PureRenders on TruncatedFormat and JSONFormat

---

packages/datetime/examples/common/formatSelect.tsx

Got a comment that the `DateInput`/`DateRangeInput` examples are missing a pretty common date format for the US: `MM/DD/YYYY`. This PR adds that format and makes it the default for each example.

[DateInput] [DateRangeInput] Add MM/DD/YYYY example and make it the default

---

packages/core/examples/numericInputBasicExample.tsx
packages/docs/src/styles/_examples.scss
packages/site-docs/src/styles/_sections.scss

Style the `NumericInput` basic example container to `width: 100%` to fix the `Full width` switch.

[NumericInput] Fix pt-fill example in docs

---

packages/datetime/examples/dateRangeInputExample.tsx
packages/datetime/src/common/errors.ts
packages/datetime/src/dateRangeInput.tsx
packages/datetime/test/dateRangeInputTests.tsx

- Controlled mode now has the same UX as uncontrolled mode.
- In particular, clicking a start date in controlled mode moves the focus to the end-date field and vice versa.
- If you hover over a date and then use the keyboard to edit it, the keyboard-edited date will be displayed (before, we were simply displaying the hovered date, which didn't show the effects of your keystrokes.)
- In general, any time the value changes, we now clear the `{start,end}HoverString` value in state, showing the `{start,end}InputString` instead.
- After typing an invalid date into a field, hovering over a valid date will hide the error state for the duration of the hover. The error state will return if you mouse out of the calendar without clicking a date.
- Throw a descriptive error if `value === null` …

[DateRangeInput] Fix various bugs

---

packages/datetime/src/dateRangePicker.tsx
packages/datetime/test/dateRangePickerTests.tsx

Herp derp. Wasn't include the `mouseenter` and `mouseleave` listeners in the split `DayPicker`s before. Fixed here. Also pulled out the common base props into a shared object and added a unit test to prevent this from happening again.
Worth mentioning the issue in a comment above the new unit test?

[DateRangePicker] Ensure hovered range displays when contiguousCalendarMonths=false

---

packages/core/src/components/tabs2/tabs2.tsx
packages/core/test/tabs/tabs2Tests.tsx

cc @JKillian 
As easy as removing an `if` statement!

[Tabs2] clicking selected tab again fires onChange

---

packages/docs/src/components/navigator.tsx
packages/docs/src/styles/_navigator.scss

- adjust scroll position of menu when using keyboard to select items
- leaves previously selected item visible above/below new selection. nice!
- track matches in state for a few good reasons:
- only compute it once when query changes instead of in every render
- can reliably clamp arrow key movement to ensure user can't slide off the end

[Docs] Navigator scrolls selected item into viewport

---

packages/core/examples/editableTextExample.tsx
packages/core/src/components/editable-text/editableText.tsx
packages/core/test/editable-text/editableTextTests.tsx

- turns out uncontrolled usage _never worked in a big way_
- so i refactored the example such that Title is uncontrolled. now we have an example to test differences between the two modes.
- note that `maxLength` affects the two inputs differently because there's some logic that trims the controlled state. try setting max length to something less than the length of both fields.
cc @dskiff

[EditableText] only sets defaultValue on initial render

---

packages/core/src/common/errors.ts
packages/core/src/components/forms/numericInput.tsx
packages/core/test/controls/numericInputTests.tsx

- Add `clampValueOnBlur: boolean` prop that defaults to `false` so as to not affect current `NumericInput` users.
- Invoke `onValueChange` with the clamped value if the value was clamped on blur.
- Throw error if `clampValueOnBlur={true}` but `min` and `max` are `null/undefined`.
- Add unit tests.
- Fix a few other suboptimalities in the `NumericInput` code.
- The prop description. How does it look?
- Should this just be default behavior out of the box? Would prefer not, so that the basic `NumericInput` mimics `input[type="number"]` as closely as possible.
- Should we add a switch for `clampValueOnBlur` in the Basic Example in the docs?
Here's an example of clamping on blur when `min=0` and `max=10`:
_(Ignore the weird colors; they're an artifact of Gifox)_

[NumericInput] Add clampValueOnBlur prop

---

packages/core/src/components/popover/popover.tsx

Because of depreciation of smart positioning option, looking at the doc and just copypaste the example could throw an error.
Add missing parenthesis in the tethering conf example

Missing parenthesis in popover doc

---

packages/table/preview/index.html
packages/table/preview/index.tsx
packages/table/src/table.tsx
packages/table/test/tableTests.tsx

Add a method called `resizeRowsByTallestCell` that takes in an array of column indices (or a single column index) to resize by one or more columns. If no array is provided, the method uses the columns in the viewport.

[Table] Add resizeRowsByTallestCell to handle multi-column resize

---

docs/blueprint-landing.css
docs/blueprint-landing.js
docs/docs/site-docs.css
package.json
packages/core/package.json
packages/datetime/package.json
packages/docs/package.json
packages/site-docs/package.json
packages/table/package.json

:fireworks: **Highlights**: _TODO_
- __NEW__ `NumericInput` `clampValueOnBlur` prop will restrict the value to between `min` and `max` when the input is blurred (default `false` for compatibility) #1044 
- __NEW__ `NumericInput` `large` prop applies `.pt-large` modifier to use larger inputs and buttons #907
- this was not as simple as adding `.pt-large` once to the container element, so we opted for a prop to ensure the correct classes are added correctly, see #1038  
- __Fixed__ `EditableText` only sets `defaultValue` on initial render #987 
- __Fixed__ `Tabs2` clicking selected tab again fires `onChange` #1067 
- 📦  __Replaced__ deprecated package `react-addons-css-transition-group` with `react-transition-group` …

Prepare Release v1.17.0

---

gulp/util/karma-config.js
packages/table/src/interactions/selectable.tsx
packages/table/test/harness.ts
packages/table/test/selectableTests.tsx

~Quick work-in-progress PR to get feedback on the interaction of Shift+Clicking to expand a selection.~
- Can now shift+click or shift+drag to expand a selection.
- Add unit test
Caveats:
- This PR does not yet leverage the focus cell; a polished version would need to consider that.
- The focus cell moves to the appended region when you expand the selection (erroneous, but not a big deal for now).
Ignoring the code and the lack of focus-cell consideration at the moment, how does the basic interaction feel?
~Should I extend the `DragSelectable` API to include knowledge of the focus cell for this PR? Or should I wait.~ **Decision:** we need to support shift+click when `enableFocus={false}` anyway, so might as well merge this PR as is.

[Table] Prototype: Shift+click or shift+click/drag to expand selection

---

packages/table/src/headers/columnHeader.tsx
packages/table/src/headers/rowHeader.tsx
packages/table/src/locator.ts
packages/table/src/tableBody.tsx
packages/table/test/tableTests.tsx

This PR contains only the changes from #1066 that directly fix #950. It does not anything related to _auto-scrolling_ while drag-selecting, because that behavior still needs more attention from me.
Fix issues with manual scrolling while a drag-selection is in progress:
- Mousing down on a **row** header and scrolling anchors the selection to that original row.
- Mousing down on a **column** header and scrolling anchors the selection to that original column.
- Mousing down on a **cell** and scrolling anchors the selection that original cell.
_NOTE:_ This PR still suffers from an existing issue where after a while, the drag selection on column/row headers stops growing all of a sudden. That's not a new issue; still, we should investigate further. Tracking in #1113.
Does it work as expected? …

[Table] Anchor drag-selections to their original activation cell

---

packages/table/preview/index.html
packages/table/preview/index.tsx
packages/table/src/cell/formats/_formats.scss

The truncated non-word-wrapped cells were taking up the
whole cell and so the size calculation wasn't working properly.
Now it should work properly.
This is pretty straightforward :)

[Table] Fixed the row resize for truncated non-word-wrapped

---

packages/table/preview/index.html
packages/table/src/cell/cell.tsx
packages/table/src/common/utils.ts
packages/table/src/headers/columnHeaderCell.tsx
packages/table/src/headers/rowHeaderCell.tsx
packages/table/src/interactions/resizable.tsx
packages/table/test/columnTests.tsx

@dcervelli This fixes the cell re-renders when only the style object has changed. 
Here's an after/before on this change in the profiler.
I have a commit locally that applies the same treatment to RowHeaderCell and ColumnHeaderCell, however it doesn't quite do the right thing. Both take a prop `resizeHandle` which is a React Component. This component, as with all components, is recreated each time, and as such it fails at a shallow equality check. I wonder if there's a react utility for checking ahead of time wether two elements will work out to be equal?

[Table] Correct pureRender logic on Cell as style object is reconstructed each render

---

packages/table/src/common/utils.ts
packages/table/test/tableTests.tsx
packages/table/test/utilsTests.ts

- Fix build (by fixing lint errors).
- Tweak logic around checking for `null | undefined` equality.
- Write tests for `deepCompareKeys`.
- Fix existing lint errors.

❗ FIX BUILD

---

packages/core/src/components/non-ideal-state/_non-ideal-state.scss

Is the new `.pt-non-ideal-state > :not(:last-child)` selector acceptable?

[Non-ideal State] Consistent margin between items

---

packages/datetime/src/common/errors.ts

The deprecation notice says `popoverProps` is deprecated, this is not true. Especially confusing since we then tell you to use `popoverProps.position`.

[DateInput] Fixes confusing typo in prop deprecation notice

---

packages/table/src/table.tsx

Allows Typescript 2.3 to be used which changed some of the behaviour of children with React: https://github.com/Microsoft/TypeScript/issues/13618
Whether this breaks anything in Typescript 2.2

Convert Table children to union type for ts 2.3 support

---

packages/core/src/components/forms/numericInput.tsx
packages/datetime/src/dateInput.tsx
packages/datetime/src/dateRangeInput.tsx
packages/docs/src/components/navigator.tsx

- Add `autoComplete="off"` to:
- `DateInput`
- `DateRangeInput`
- `NumericInput`
- `Navigator` (docs-only component)
- Do we need to include this on `Navigator`?
- Should `autoComplete="off"` go before the `html(Input)Props` spreads?
- Not really sure how to test this; the original autocomplete behavior isn't happening for me on IE.

Set autoComplete='off' in all InputGroups

---

packages/table/src/common/grid.ts
packages/table/test/gridTests.ts

Check whether or not a region is fully contained in the table before styling it; if it turns out it isn't, style it with `display: none`

[Table] Don't show regions that aren't in the table

---

packages/datetime/src/dateInput.tsx
packages/datetime/test/dateInputTests.tsx

**Before:** incrementing or otherwise changing the time would immediately close the popover if `closeOnSelection=true`.
**After:** Stop doing that. Popover now closes only after clicking a date in the calendar, not after changing the time (or the month, but that was already implemented).

[DateInput] Don't closeOnSelection when the time changes 

---

packages/core/examples/popoverExample.tsx
packages/core/src/common/errors.ts
packages/core/src/common/utils.ts
packages/core/src/components/popover/popover.tsx
packages/core/src/components/tooltip/tooltip.tsx
packages/core/test/popover/popoverTests.tsx
packages/core/test/tooltip/tooltipTests.tsx

- move empty content check from Tooltip to Popover
- remove now-unused `Utils.isReactText`
- add empty content option to Popover example so you can see warning in console (though not in prod mode)

disable empty Popover

---

packages/core/src/common/_variables.scss

- move `"Icons16"` font before keyword in `$pt-font-family`

move icons font before keyword in $pt-font-family

---

packages/table/src/cell/formats/_formats.scss
packages/table/src/cell/formats/truncatedFormat.tsx

Take the width into account when measuring if we should show or hide the popover handle
This is... pretty straightforward. I had a much more complicated way of doing this, but realized we might as well just do it the easy way first.

[Table] Use width of popover dots when calculating whether to show it

---

packages/core/src/components/dialog/dialog.md

- Put dialog example first (_finally_...)
- Document the default behavior correctly (`inline={false}` by default)

Fixup dialog component docs

---

packages/table/preview/nav.tsx
packages/table/preview/perf.html
packages/table/preview/perf.tsx

- Out with the old `perf.html` spreadsheet example.
- In with the new `Table` Playground. (The term "playground" is a little overloaded now; feel free to suggest something else, though note that string doesn't appear in this PR.)
- I've discovered so many `Table` bugs and/or weirdnesses from this already!
- I want to merge this quickly and add to it iteratively in future PRs (TODO: text truncation, `resizeByTallest...`, reorganize the table preview pages).
- Play with it at `[table docs url]/perf.html`.
- Happy to polish styles in future PRs if we need to.

[Table] Create a playground where you can toggle all features in one place

---

package.json
packages/core/src/components/tabs2/tabTitle.tsx
packages/core/src/components/tabs2/tabs2.tsx
packages/core/test/buttons/buttonTests.tsx
packages/core/test/controls/controlsTests.tsx
packages/core/test/controls/inputGroupTests.tsx
packages/core/test/tabs/tabs2Tests.tsx
packages/datetime/test/dateRangeInputTests.tsx

- Expose click event in Tabs2 onChange handler
- Upgrade to Chai 4.0, remove tests that were mostly tautological and relied on old lenient APIs

Expose click event in Tabs2 onChange handler

---

packages/table/src/interactions/selectable.tsx
packages/table/test/selectableTests.tsx

If `allowMultipleSelection={false}`, then drag-selecting will simply move a single-cell/single-row/single-column selection around to follow your cursor. Now assume `enableFocus={true}` when you do that.
_Before:_
The focus cell stays put on drag in spite of your moving selection.
_After:_
The focus cell moves with the selection on drag (except when you select the `FULL_TABLE` on click, in which case the existing code does not move the focus cell - which is a separate bug!).
- Does this behavior feel more correct that the previous behavior?

[Table] Have focused cell follow selection if allowMultipleSelection=false

---

packages/table/src/interactions/selectable.tsx
packages/table/src/regions.ts
packages/table/src/table.tsx
packages/table/test/tableTests.tsx

Move the focus cell to (0, 0) on `FULL_TABLE` selection (i.e. on click in the top-left corner). 
_Before:_
_After:_

[Table] Move focus cell to (0,0) on FULL_TABLE selection

---

packages/table/src/interactions/selectable.tsx

Two PRs recently merged (#1171, #1172), one that moved a function to a different file, one that referenced the function in its old position. Neither failed the build by itself, but together, they've broken the build on `master`.
This fixes that.

Fix build!

---

packages/table/src/common/utils.ts
packages/table/src/table.tsx

- Fix bugs with boolean-checking and array deep-comparison in `Utils.deepCompareKeys`
- Add a custom `shouldComponentUpdate` to `Table` to deeply compare `state.selectedRegions`
- Eliminates unnecessary re-renders when selection is disabled (before: every `mouseup` and `mousedown` with selection disabled would trigger a re-render of every cell in view, because `selectedRegions` was being continually overwritten with a new empty-array instance). 
- Eliminates re-render on `mouseup` if one just happened on `mousedown`.
- Continues to shallowly compare every other key in `props` and `state`

[Table] Eliminate excessive selection re-renders

---

packages/core/src/components/forms/numericInput.tsx
packages/core/test/controls/numericInputTests.tsx

- Add `onButtonClick` prop that fires when either button is "clicked" (via mouse, focus + `Space`, focus + `Enter`, etc.)
- Is this a good name/API for the callback?

[NumericInput] Add onButtonClick prop

---

packages/table/src/cell/cell.tsx
packages/table/src/common/utils.ts
packages/table/src/headers/columnHeaderCell.tsx
packages/table/src/headers/headerCell.tsx
packages/table/src/headers/rowHeaderCell.tsx
packages/table/src/interactions/draggable.tsx
packages/table/src/layers/regions.tsx
packages/table/src/table.tsx
packages/table/src/tableBody.tsx
packages/table/test/utilsTests.ts

- Refactor `shallowCompareKeys` to accept a type-checked blacklist or whitelist.
- Fix resultant breakages all over the `Table` codebase.
- Does the typing stuff look sane?
- Any keys I didn't convert properly into the new scheme?

[Table] Refactor Utils.shallowCompareKeys to accept whitelist OR blacklist

---

packages/table/src/locator.ts
packages/table/test/tableTests.tsx

Modify the selector to only include table cells

Only use table cells for resizeByTallest, not header cells

---

packages/core/src/common/_variables.scss

Similarly to input focus shadows, `box-shadow` transitions require the same number of shadows for best visual results.
Before:
After:

[Cards] Fix hover transition flicker

---

packages/table/src/table.tsx

Fix a lint error caused by invalid props being passed to `ColumnHeaderCell` in `table.tsx`.

[Table] Fix lint error in Table#columnHeaderCellRenderer

---

gulp/typescript.js
packages/docs/src/components/interfaceTable.tsx
packages/docs/src/tags/interface.tsx

- ignore code coverage in linters (per @cmslewis)
- handle unknown `@interface` tags in renderer
these issues came up while working on #1159 but didn't make sense in that PR so here they are.

fix wee dev bugs

---

packages/table/preview/index.tsx
packages/table/src/interactions/selectable.tsx
packages/table/test/selectableTests.tsx
packages/table/test/tableTests.tsx

- Log to the console whenever callbacks are fired in Table Playground
- Currently, we fire `onSelection` every time a drag event is triggered (`onActivation`, `onDragMove`, `onDragEnd`). This fires `onSelection` SO many times. Now, we fire `onSelection` only when the selection changes. See GIFs below for a demo.
- This requires a deep comparison between the old selected-regions array and the new one, but that's a relatively inexpensive check, since most of the time we'll only have one selected region in play.
_Before:_
_After:_

[Table] Fire onSelection only when the selection actually changes

---

packages/table/src/cell/editableCell.tsx
packages/table/src/headers/columnHeaderCell.tsx
packages/table/src/headers/header.tsx
packages/table/src/headers/headerCell.tsx
packages/table/src/headers/rowHeader.tsx
packages/table/src/headers/rowHeaderCell.tsx

- Add more specific `shouldComponentUpdate`s in `*Header`s and `*HeaderCell`s.
- Delete `HeaderCell`'s wonky internal `shallowlyComparablePropKeys` prop
This is part of constellation of upcoming perf-related PRs; it doesn't have much effect on its own, but it will in concert with other changes (which are all implemented on `cl/table-perf` if you want to peek at that).

[Table] Add custom shouldComponentUpdates in Header and HeaderCell

---

packages/table/src/locator.ts

Modify resize-by-tallest so it won't error out -- if we don't recognize anything inside the cell, use the current cell height. 
It doesn't make sense to special-case loading cells here, and covering cases where users have defined their own cell renderers to have sane defaults is good.

Add a default fallback for tallest cell calculations

---

packages/table/src/headers/columnHeader.tsx
packages/table/src/headers/header.tsx
packages/table/src/headers/rowHeader.tsx

In #1206, I added a custom `shouldComponentUpdate` to the `Header` component, but I accidentally left a `@PureRender` decorator on it as well, which leads to a runtime warning that we didn't catch before merging that PR. Unfortunately, while `pure-render-decorator` warns you that it can't add its default `shouldComponentUpdate` because a `shouldComponentUpdate` is already defined, _it overwrites yours anyway_. Removing the decorator to get rid of this warning caused tests to fail.
This PR fixes those tests by moving the `Header`'s custom `shouldComponentUpdate` code a level up into `ColumnHeader` and `RowHeader`. I'm still not clear why that fixes things, but I opened an issue (#1214) to track.
Exporting a custom function like this is awkward, but is it reasonable for now? I want to …

[Table] Fix shouldComponentUpdate issues in *Header's

---

packages/table/preview/index.tsx
packages/table/src/cell/cell.tsx
packages/table/src/cell/editableCell.tsx
packages/table/src/headers/columnHeader.tsx
packages/table/src/headers/columnHeaderCell.tsx
packages/table/src/headers/header.tsx
packages/table/src/headers/headerCell.tsx
packages/table/src/headers/rowHeader.tsx
packages/table/test/columnHeaderCellTests.tsx
packages/table/test/editableCellTests.tsx

- Add optional new `index` prop to `HeaderCell` (can be passed to callbacks to avoid having to re-instantiate anonymous functions in parent components on each re-render).
- Add optional new `rowIndex` and `columnIndex` props to `Cell` (same reasoning).
- Pass `index` callback to `ColumnHeaderCell`'s `renderName` callback.
- Pass `rowIndex` and `columnIndex` to `EditableCell` callbacks.
- Refactor `preview/index.tsx` to take advantage of these new `*index` props
Perf gains! This approach lets you provide a persistent function instance as a callback to the various `*Cell` components, causing shallow equality checks on that function instance to pass now. This avoids lots of unnecessary re-renders.

[Table] Introduce Cell/HeaderCell index props and pass them to callbacks

---

packages/datetime/examples/timePickerExample.tsx
packages/datetime/src/_timepicker.scss
packages/datetime/src/timePicker.tsx
packages/datetime/test/timePickerTests.tsx

- "Disabled" optional property added to TimePiker component. False for default
- Styling was reused from `core/src/components/forms/common`, as for InputGroup component
- Changes pass linter checks
- Covered with tests

[DateTime] Add disabled prop to TimePicker

---

packages/table/src/table.tsx
packages/table/test/tableTests.tsx

Added a few checks to `componentWillReceiveProps` to leave the table in a good state post-update: 
- If `enableFocus` toggles from `true` to `false`, clear the focused cell.
- If `selectionModes` changes, clear selected regions having cardinalities that are no longer selectable.
- If the number of rows or columns decreases, auto-scroll to the last row/column to keep it visible.
- If the number of row widths or column heights decrease, auto-scroll to the last row/column to keep it visible.
- I can add more checks later.

[Table] Add more checks to componentWillReceiveProps

---

packages/table/src/headers/columnHeader.tsx
packages/table/src/headers/rowHeader.tsx
packages/table/test/tableTests.tsx

- Have `ColumnHeader`s and `RowHeader`s respond to `FULL_TABLE` updates too.
_After:_

[Table] Bugfix: Have column headers and row headers respond to FULL_TABLE selections too

---

packages/table/preview/index.tsx
packages/table/src/common/errors.ts
packages/table/src/common/index.ts
packages/table/src/headers/columnHeaderCell.tsx
packages/table/src/headers/headerCell.tsx
packages/table/src/headers/rowHeaderCell.tsx
packages/table/test/columnHeaderCellTests.tsx

The `HeaderCell#menu` prop we have now is bad, because `<MenuItem>`s typically require callbacks that are instantiated as inline anonymous functions so that they can have access to a row/column index.
This PR deprecates `HeaderCell#menu` and introduces `HeaderCell#renderMenu` instead, a callback that receives a row/column index parameter and expects a JSX element in return. This works in concert with the `HeaderCell#index` props introduced in #1210.
The major benefit here is that `shouldComponentUpdate` checks pass, because `renderMenu` can be a single, persistent function instance; whereas `menu` was typically reinstantiated on each re-render.
Does this API change sound good?

[Table] Introduce HeaderCell#renderMenu prop, deprecate HeaderCell#menu prop

---

packages/table/src/common/utils.ts
packages/table/test/utilsTests.ts

Proposing to add `getShallowUnequalKeyValues` and `getDeepUnequalKeyValues` to our `Table` utils. These functions are useful primarily for debugging `shouldComponentUpdate`; I kept reimplementing the same helpers to do just this, so I figured I'd open a PR to add them to the codebase permanently.
- Is it worth having these around permanently? I think so.
- If you agree, then I'll add tests. Not before. :)

[Table] Add new utils: getShallowUnequalKeyValues and getDeepUnequalKeyValues

---

packages/table/preview/index.tsx
packages/table/src/headers/columnHeaderCell.tsx

Some final, tiny cleanups from last week's `Table` perf work:
- Move from anonymous functions to private functions in `ColumnHeaderCell`.
- Use fat arrow instead of `.bind(this)` in `index.tsx`
- Provide indices to cells when editing is disabled on Table preview.

[Table] Final cleanups from perf work

---

packages/table/preview/index.tsx

One final cleanup: provide `index` prop to `RowHeaderCell` in `index.tsx` (for use in the `renderMenu` callback). Only affects the table preview page.

[Table] Provide index to RowHeaderCell in index.tsx

---

packages/table/preview/index.tsx

- Add `<select>` menu to change cell content in the entire table in one fell swoop.
- Empty
- Cell names (A1, J17, etc.)
- Long text (random alphanumeric strings between 5 and 40 chars long) 
- Delete the old "Fill with random text" menu items in column headers.
- This only affects the table preview page. 
- We really need some way to force update all cells in the `Table`, without requiring scrolling (this goes for any `Table`, not just our preview). This constraint is why you have to scroll before seeing the cell content change.

[Table] Add menu to change cell content in Table playground

---

packages/table/src/table.tsx
packages/table/test/tableTests.tsx

Add a locator to the table component as a private attribute, and use _that_ in resizeByTallest.
This is just adding the variable, no refactor. I'm not sure this is the best way, but I'm also not sure what a good refactor here would be, given the way we use the locator. Does anyone have a better idea? I'd almost like to pass the children a _reference_ to the locator (an object that just contains one thing, which is the locator) and do this with an added level of indirection -- but that just seems silly.

[Table] Add locator to table component for use in functions

---

packages/labs/README.md
packages/labs/src/blueprint-labs.scss
packages/labs/src/index.ts
packages/labs/src/labs.md
packages/labs/src/query-list/queryList.tsx
packages/labs/src/select/_select.scss
packages/labs/src/select/select.tsx
packages/labs/test/index.ts
packages/labs/test/queryListTests.tsx

- 🔥  rename `InputList` &rArr; `QueryList` because it's all about the `query`, but input nature is up to you in the `renderer`
- mimic `core` directory structure, with folder for each component

[Labs] InputList ⇒ QueryList

---

packages/core/src/components/portal/portal.md
packages/core/src/components/portal/portal.tsx
packages/core/test/portal/portalTests.tsx

Add a context property called `blueprintPortalClass` that all Blueprint Portals respect.  This is very beneficial if you are displaying dialogs within a shared component/larger plugin and want to scope your styles.  You _could_ go through to every instance of Popover/Dialog/Tooltip and add the class yourself, but you're likely to forget to do it the next time you add something.
Not sure how to update documentation on this one.  Also open to suggestions on the context prop name.
Side note: writing the tests for this was confusing/tricky because the tests started with 3 Portals in wherever enzyme puts them.  I would have expected to start with an empty space to test.  Is there a chance something isn't cleaning up properly?

Portal context class

---

packages/core/src/common/errors.ts
packages/core/src/components/portal/portal.tsx

Move the new error message from #1245 into `errors.ts` with the rest of its friends.

[Portal] Move new Portal error message to errors.ts

---

packages/table/src/cell/editableCell.tsx
packages/table/test/editableCellTests.tsx

Have `EditableCell` fully control the value that it passes to its child `EditableText` component. (At preset, it's simply passing down the value as a `defaultValue`, so only the initial render is "controlled," as it were.) 
This approach fixes the issue as far as I can tell. Does everything feel right? @seansfkelley, would especially appreciate a pass from you.

[Table] Have EditableCell fully control value in child EditableText

---

packages/labs/src/query-list/queryList.tsx
packages/labs/test/queryListTests.tsx

Right now if you have a class that instantiates a raw queryList and passes in an empty filtered list and undefined as the active state, then on `componentDidUpdate` it will call update and pass an active item of undefined. If you have a parent class that listens to `onActiveItemChange` and then sets its state, the parent class will be re-rendered. Then the queryList will will be re-rendered, and so on and so forth. This will cause an infinite re-rendering loop and a stackover-flow error. You can emulate this behavior if you remove @pure-render from select.tsx and remove:
```
if (filteredItems.length === 0) {
return noResults;
}
```
so the query list is always rendered.
Then if you filter to an empty list in select.tsx, you will get a stack-overflow error
@giladgray This fixes an edge case …

[Labs] Propagate event correctly when handling empty list

---

packages/core/src/components/table/_table.scss

`<thead>` elements can only have `<tr>` elements as children: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead

Fix example in pt-table documentation

---

packages/table/src/common/cell.ts
packages/table/src/interactions/selectable.tsx
packages/table/src/regions.ts
packages/table/src/table.tsx
packages/table/test/selectableTests.tsx
packages/table/test/selectionTests.tsx
packages/table/test/tableTests.tsx

Focus cells now track what region they belong to.
Pressing enter/tab and their shift-ed counterparts move the cell inside the selected region
There's a... large block of code in this code that's duplicated a bunch, with minor changes. There really should be a way to simplify it. I'm not sure what that is. Help, please?
Also, all of my names for functions are pretty mediocre here.

[Table] Adds focus cell tab and enter microinteraction behavior

---

packages/core/src/components/tag/tag.tsx

Use more succinct `safeInvoke` instead of separate deconstruction + `isFunction` + invoke statements.

[Tag] Use safeInvoke for onRemove

---

docs/blueprint-landing.css
docs/blueprint-landing.js
docs/docs/site-docs.css
package.json
packages/core/package.json
packages/labs/package.json
packages/site-docs/package.json
packages/table/examples/index.ts
packages/table/examples/tableReorderableExample.tsx
packages/table/package.json
packages/table/src/docs.md

:fireworks: **Highlights**: `TagInput` component, `Table` column reorder handles, Tab/Enter to navigate `Table` focus cell
- __NEW__ `Tag` `onRemove` callback now receives full tag props as second argument (#1267)
- __NEW__ `Portal` now receives `blueprintPortalClassName` context property (#1244, #1245) (🎩 @jrafidi)
- This is beneficial if you are displaying dialogs within a shared component/larger plugin and want to scope your styles.
- 🌟 __NEW__ `TagInput` component (#1232)
- Renders `Tag`s inside an input, followed by an actual (ghosted) text input.
- On `Enter`, the inputted text is displayed in a new tag.
- This component is fully controlled, and all tags are individually customizable via `tagProps`.
- …

Prepare Release 1.21.0

---

packages/table/src/common/utils.ts
packages/table/test/utilsTests.ts

Use a basic for loop in `Utils.times(...)` instead of a `.map(...)`. This lets the function handle much bigger numbers without filling up the call stack.
Poke around the table example to make sure everything still works.

[Table] Improve Utils.times(...) to work with huge numbers 

---

packages/table/src/headers/headerCell.tsx

Matching table package version number instead of core

[Table] Update deprecation package version for `menu`

---

packages/datetime/src/_timepicker.scss

Show `cursor: not-allowed` when you hover over disabled `TimePicker` inputs.
Before:
After:

[TimePicker] Show "not-allowed" cursor on input hover

---

packages/table/preview/index.tsx

Fixes a syntax issue with the log statement introduced in #1268

[Table] Add missing + sign to multiline log statement

---

packages/core/src/components/collapse/collapse.tsx

React.HTMLAttributes requires `overflowY` to be a member of a string union: `"initial" | "inherit" | "unset" | "auto" | "hidden" | "scroll" | "visible" | undefined`. In Collapse.render, the `overflowY` needs to be given the explicit type `"visible" | undefined` in order to be assignable to HTMLAttributes. Otherwise, it gets the type `string`, which is too general.
See also DefinitelyTyped/DefinitelyTyped#17581, which this change depends on.
See also discussion at Microsoft/TypeScript#16047.

Fix collapse.tsx for TS 2.4

---

packages/datetime/src/dateTimePicker.tsx
packages/datetime/test/dateTimePickerTests.tsx

On deselect in `DateInput` with time precision specified, this PR now properly clears the selected date in the calendar. The bug was specifically with controlled usage of the `DateTimePicker`: when `nextProps.value == null`, we weren't setting `this.state.dateValue` to `null` for some reason.
Give it a try in the dev preview.

[DateInput] Clear selected date on deselect when time precision specified

---

packages/datetime/src/common/dateUtils.ts
packages/datetime/test/dateRangeInputTests.tsx

This PR fixes bug in `fromDateToMoment` with `undefined` values. Before, if the provided `date` shallowly equaled `null` (i.e. if `date === undefined || date === null`), then we returned `moment(date)`. This effectively returned `moment()` when `date` was `undefined`, which returns the current date and time.
Now, we explicitly return `moment(null)` in either case, which creates an invalid or "empty" moment object as expected.

[DateRangeInput] Fix display value when controlled value is [undefined, undefined]

---

packages/core/src/common/keys.ts

See https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode for browser compatibility, 46 is used on all browsers.

Add delete key code

---

packages/labs/src/components/select/select.tsx

Not technically broken, but it's better to be accurate (both `Classes` and `CoreClasses` are used in this file)

[Select] Proper classes import

---

packages/core/test/editable-text/editableTextTests.tsx

- Improved test for `onConfirm` behavior.
- Verify that `onCancel` was not called.
- Verify that new value was saved in input.
- Improved test for `onCancel` behavior.
- Verify that `onConfirm` was not called.
- Verify that new value was saved in input.
- Add test to verify that `onConfirm` was called when <kbd>Enter</kbd> pressed with unchanged value.

[EditableText] Improve tests for onConfirm and onCancel behavior

---

packages/core/src/components/hotkeys/hotkey.tsx
packages/core/src/components/hotkeys/hotkeysEvents.ts
packages/core/src/components/hotkeys/keyCombo.tsx
packages/core/test/hotkeys/hotkeysTests.tsx

- Add `allowInInput?: boolean` prop to `Hotkey`, which defaults to `false`.
- With `allowInInput={true}`, a hotkey can be triggered when a `"text"`, `"password"`, or `[contenteditable=true]` input is focused. This is currently not possible.
- Add `disabled?: boolean` prop to `Hotkey`, which defaults to `false`.
- With `disabled={true}`, a hotkey will not be triggered.
- Add `preventDefault?: boolean` prop to `Hotkey`, which defaults to `false`.
- With `preventDefault={true}`, `event.preventDefault()` will be invoked in response to `keydown` and `keyup` events before the respective `onKeyDown` and `onKeyUp` callbacks are invoked.
- Add `stopPropagation?: boolean` prop to `Hotkey`, which defaults to `false`.
- With `stopPropagation={true}`, `event.stopPropagation()` will be invoked in …

[Hotkeys] Add allowInInput, disabled, preventDefault, stopPropagation props

---

packages/datetime/examples/dateRangePickerExample.tsx
packages/datetime/src/dateRangePicker.tsx
packages/datetime/test/dateRangePickerTests.tsx
packages/site-docs/src/styles/_sections.scss

- __Fixed__ `DateRangePicker` now disables shortcuts that aren't fully contained in `[minDate, maxDate]`, inclusive.
- Add "Minimum date" and "Maximum date" dropdowns to the `DateRangePicker` example to verify.

[DateRangePicker] Disable out-of-range shortcuts

---

packages/core/src/components/non-ideal-state/_non-ideal-state.scss

Useful for multiline cases.
Before:
After:

[Non-ideal state] Fix title centering

---

packages/table/src/headers/rowHeader.tsx

Previously, a bug in chrome broke scrolling in the table.
As demonstrated in this fiddle, the bug has been fixed.
https://jsfiddle.net/2rmz7p1d/5/
The RoundSize workaround has non-zero performance impact,
so we should disable it now that chrome is fixed.

Disable the `<RoundSize>` component wrapper

---

packages/core/src/components/dialog/_dialog.scss

- Going from 25% to 10%
- Doesn't impact short dialogs, but makes tall dialogs better
- Decent compromise until we fix `Overlay` and backdrop woes (centering, scrolling, etc...)

[Dialog] Reduce top position

---

packages/labs/src/common/classes.ts
packages/labs/src/components/omnibox/omnibox.tsx
packages/labs/src/components/select/multiSelect.tsx
packages/labs/src/components/select/select.tsx
packages/labs/src/components/tag-input/tagInput.tsx

Following up on @cmslewis comments from https://github.com/palantir/blueprint/pull/1325
The only piece I didn't do is `noResults` -> `noResultsElement` because it's technically a breaking change. Just want to make sure that it's fine to break `@blueprintjs/labs` whenever needed.

[Labs] Cleanups and followups

---

packages/datetime/src/dateTimePicker.tsx
packages/datetime/test/dateTimePickerTests.tsx

- __Fixed__ `DateInput` with time precision enabled no longer defaults to Today when popover re-opens with controlled `value === null` 
- Note: If you deselect a date and then close the popover, the time fields will be cleared as well on re-open.
Fixing the time fields (to not clear on popover re-open) would require more plumbing work, and I wasn't sure what the best UX was. @llorca? I also wanted to bias toward getting this quick fix submitted.

[DateInput] No longer defaults to Today with time precision enabled

---

packages/table/src/cell/formats/truncatedFormat.tsx

Add a bit of buffer space to the calculation -- if there's a fractional amount of pixels off, we err on the side of not showing the popover, to deal with inconsistencies when at different zoom levels. 
Also only change the popover visibility when set to WHEN_TRUNCATED.

[TruncatedFormat] Fix popover size issues leading to infinite loops

---

packages/core/src/components/forms/_controls.scss
packages/core/src/components/forms/_form-group.scss

- Proper `min-height` for `.pt-control` (16px normal, 20px large)
- Align `.pt-form-group` items to their baseline
- Tweak `.pt-control` vertical margin within `.pt-form-group`
Before:
After:

[Form group] Better pt-control support

---

packages/table/preview/index.tsx
packages/table/src/common/classes.ts
packages/table/src/headers/columnHeader.tsx
packages/table/src/headers/rowHeader.tsx
packages/table/src/quadrants/_quadrants.scss
packages/table/src/quadrants/tableQuadrant.tsx
packages/table/src/table.tsx
packages/table/test/tableTests.tsx

- Can now configure the number of frozen rows and columns from the example page.
- Num. frozen rows: `[0, 1, 2, 5, 20, 100, 1000]`
- Num. frozen columns: `[0, 1, 2, 5, 20, 100, 1000]`
- Headers are now fixed AND __scrollable__:
- Row headers are now contained in the `LEFT` quadrant, leaving them fixed during scrolling.
- Column headers are now contained in the `TOP` quadrant, leaving them fixed during scrolling.
- The top-left "menu" element is now contained in the `TOP_LEFT` quadrant, leaving it fixed and above everything else.
- Toggling `isRowHeaderShown` properly resizes and repositions quadrants.
- Make sure the quadrants resize properly when:
- Changing `Num. frozen columns`
- Changing `Num. frozen rows`
- Changing `Num. columns`
- Changing `Num. rows`
- Toggling row headers
- Known …

[Table] Frozen Rows/Cols - Part 2: Style Fixes & Example Controls

---

packages/core/src/common/utils.ts
packages/core/test/common/utilsTests.ts
packages/table/src/common/errors.ts
packages/table/src/table.tsx
packages/table/test/tableTests.tsx

- Add validation for `numFrozenRows` bounds and `numFrozenColumns` bounds.
- Move an existing `Table` warning message into `errors.ts`.
- Fix bug in `Table#syncRowHeaderSize` when `rowHeaderElement == null`.
- Add tests for all the new quadrant sync'ing code.
- Size sync'ing (e.g. when toggling `isRowHeaderShown` and `useInteractionBar`)
- Scroll sync'ing
- Do these tests look okay?
- Is the validation logic for `numFrozenColumns` and `numFrozenRows` okay? Feels slightly excessive but still helpful.
- I couldn't figure out how to write a few of the tests, so I left them as placeholders. LMK if you have ideas. (See: https://github.com/palantir/blueprint/pull/1361/files#diff-eea83e2366941709af74b6efcc2454bfR287)

[Table] Frozen Rows/Cols - Part 3: Tests for new code

---

packages/table/preview/index.tsx
packages/table/src/layers/_layers.scss
packages/table/src/layers/regions.tsx
packages/table/src/locator.ts
packages/table/src/quadrants/_quadrants.scss
packages/table/src/quadrants/tableQuadrant.tsx
packages/table/src/table.scss
packages/table/src/table.tsx
packages/table/test/locatorTests.tsx

- __Fixed__ `Table` selection interactions now work properly in the multi-quadrant architecture.
- Intermediate borders are no longer shown within the bounds of a selection (e.g. at quadrant boundaries) ([Link #1](https://github.com/palantir/blueprint/pull/1370/files#diff-6bc89efba539cc29af0dae9b17c57f75R1482), [Link #2](https://github.com/palantir/blueprint/pull/1370/files#diff-6bc89efba539cc29af0dae9b17c57f75R1483))
- `FULL_TABLE`, `FULL_COLUMN`, and `FULL_ROW` selections no longer extend outside of smaller tables. ([Link #1](https://github.com/palantir/blueprint/pull/1370/files#diff-e78bd13417417b00c597bf8ad2ca9e1eR16), [Link #2]())
- Mouse events now map to the proper cell coordinates in the grid. ([Link](https://github.com/palantir/blueprint/pull/1370/files#diff-85bb3412e972df58b0e311 …

[Table] Frozen Rows/Cols - Part 4: Selection

---

packages/table/src/headers/header.tsx

- __Fixed__ `Table` reordering handle now includes missing `pt-icon-standard` class
- This fixes missing-icon issues on some browsers

[Table] Add pt-icon-standard to reordering drag handle

---

packages/core/src/components/forms/_common.scss
packages/labs/examples/selectExample.tsx

Native `<select>` should be the double caret similarly to the native one:
Our custom `<Select>` is more like a dropdown, can get caret down as used elsewhere:

More accurate icons for selects

---

packages/table/src/cell/_borders.scss
packages/table/src/quadrants/_quadrants.scss
packages/table/src/table.tsx
packages/table/test/formatsTests.tsx
packages/table/test/tableTests.tsx

- Fix some style bugs with borders on quadrant boundaries (when # frozen == 0 and when # frozen > 0)
- Remove placeholder Red, Green, Blue quadrant colors.
- Small perf fix: guard against cyclic dependency between scroll listeners. 
- Next steps:
1. Introduce `TableQuadrantStack` to encapsulate quadrant sync'ing behavior. (already done locally)
1. Work on performance to reduce scroll lagging between quadrants.

[Table] Frozen Rows/Cols - Part 5: Polishes

---

packages/core/src/components/button/_common.scss

> I traced back some old PRs internally, and it looks like we matched focus styles to hover styles before we ever had the `FocusStyleManager`, which made a lot of sense with regards to accessibility and keyboard navigation. Might be safe to remove now!
This PR removes these custom focus styles. Feels much better IMO.

[Button] Remove custom focus style in minimal state

---

packages/table/src/interactions/_interactions.scss
packages/table/src/quadrants/tableQuadrant.tsx
packages/table/src/table.tsx

- Modify styling so that the row and column resize guides only show up in the right places
- Use math and logic to figure out the exact position where the guides need to be drawn based on which quadrant they came from.

[Table] Frozen Rows/Cols - Part 4.5: resize guides

---

packages/core/src/components/button/_button.scss

Getting too many requests about this. Two solutions:
1. we lift the restriction
1. we create a whitelist of icons that are okay inside small buttons
This PR does the former. I really dislike the latter, and it seems to make sense to push this responsibility to consumers anyway.

[Button] Remove small button icon restriction

---

packages/core/src/components/overlay/overlay.tsx
packages/core/test/overlay/overlayTests.tsx

[Overlay] Enforce focus after backdrop mouse down

---

packages/labs/src/components/omnibox/omnibox.tsx
packages/labs/src/components/select/multiSelect.tsx
packages/labs/src/components/select/select.tsx

- Consumers can use `inputProps.onChange` to listen to the query

[Labs] Listen to query on select components

---

packages/core/src/common/_mixins.scss
packages/core/src/components/button/_common.scss
packages/core/src/components/forms/_controls.scss

- Remove `linear-gradient-with-fallback` mixin and rely on straight CSS
- Good browser support: http://caniuse.com/#search=linear-gradient)
- Gradients on buttons are `!default` variables that can be customized like all the other ones

[Button] Refactor button gradients

---

packages/labs/examples/selectExample.tsx
packages/labs/src/components/select/select.tsx

- Add a `resetOnClose` prop that when set to `true` resets the query every time the popover is about to open

[Labs] Add resetOnClose prop to Select

---

packages/labs/examples/tagInputExample.tsx
packages/labs/src/components/tag-input/tagInput.tsx
packages/labs/src/labs.md
packages/labs/test/tagInputTests.tsx

- `separator` prop allows adding multiple entries at once 
- `onChange` prop combines `onAdd` and `onRemove` for easy controlling (and implements basic array manipulation logic)
- `placeholder` prop appears only when `values` is empty
- use `inputProps.placeholder` if you want it to appear all the time
- 🔥 __API BREAK__: `onAdd` now receives `string[]` instead of single `string`
```diff
- private handleAdd = (value: string) => this.setState([...this.state.values, value])
+ private handleAdd = (values: string[]) => this.setState([...this.state.values, ...values])
```
- definitely review the individual commits here: one per added prop (tests included!)
- how awesome are these props?

[TagInput] add separator, onChange, placeholder props

---

packages/core/src/components/button/_common.scss

- this small change fixes icon centering in small buttons
- there is also precedent for this in `InputGroup` which defines its own [small button styles](https://github.com/palantir/blueprint/blob/master/packages/core/src/components/forms/_input-group.scss#L76-L81) (before the button modifier existed) and does _not set_ `font-size` and no one complained.

remove small font-size from small buttons

---

packages/labs/examples/tagInputExample.tsx
packages/labs/src/components/tag-input/tagInput.tsx
packages/labs/test/tagInputTests.tsx

`values` array now accepts `React.ReactNode[]`, which is actually the same type as `children`! not using `children` for this makes the array nature explicit. One cool thing is you can now pass an array to do inline styling: `values: ["Barney", ["Bar", <em>thol</em>, "emew"], "Bertha"]`
had to widen the types of a few props to support this (but actually added only one line of actual code), so I added some notes to props docs about how you can declare your own simpler types on your handlers.
- do we actually want this? the fact that i had to change no code and everything just works suggests, "why not!"
- `ReactNode` is basically the most permissive type out there.  Do we want to be a little more strict like `string | JSX.Element`?

[TagInput] values accepts any valid JSX

---

packages/datetime/src/dateRangeInput.tsx
packages/datetime/test/dateRangeInputTests.tsx

Use a single component instance for all DRI hover tests. This ultimately shaves `20 seconds` off the time for the DRI tests, a nearly `30%` reduction.
_Before:_
`1 min 9.075 secs`
_After_:
`49.435 secs`
Is the new, public `DRI.reset()` method okay to have?

[DateRangeInput] Speed up the DRI tests

---

packages/labs/examples/tagInputExample.tsx
packages/labs/src/common/classes.ts
packages/labs/src/components/tag-input/_tag-input.scss
packages/labs/src/components/tag-input/tagInput.tsx
packages/labs/test/tagInputTests.tsx

- `leftIconName` renders an icon as first child
- `rightElement` appears as last child
- just like `InputGroup`

[TagInput] leftIconName + rightElement

---

packages/table/src/table.tsx
packages/table/test/columnTests.tsx
packages/table/test/formatsTests.tsx
packages/table/test/loadingOptionsTests.tsx
packages/table/test/selectionTests.tsx
packages/table/test/tableTests.tsx

- Fix tests that I broke and `skip`'d in past PRs.
- In particular, be sure to `delayToNextFrame` when testing anything to do with scrolling, which is now throttled via `requestAnimationFrame`.
- Also, test the `MAIN` quadrant's scroll container by default.
- ~HOW DO I FIX THE BROKEN `TruncatedFormat` test? Can't figure it out.~ Fixed with `position: relative;`. :(
- https://github.com/palantir/blueprint/blob/cl/table-frozen-rows-cols-8-fix-tests/packages/table/test/formatsTests.tsx#L55

[Table] Frozen Rows/Cols - Part 8: Fix tests

---

packages/core/src/components/tooltip/tooltip.tsx
packages/labs/examples/index.ts
packages/labs/examples/popover2Example.tsx
packages/labs/examples/tooltip2Example.tsx
packages/labs/src/components/index.ts
packages/labs/src/components/popover/popover2.tsx
packages/labs/src/components/tooltip/tooltip2.tsx
packages/labs/src/labs.md
packages/labs/test/popover2Tests.tsx
packages/site-docs/src/styles/_examples.scss

`Tooltip` 2.0 based on `Popover` 2.0.

[Labs] Tooltip 2

---

packages/labs/examples/tagInputExample.tsx
packages/labs/src/components/tag-input/tagInput.tsx
packages/labs/test/tagInputTests.tsx
packages/table/src/table.tsx

- previously, falsy `values` would render as empty tags. it was weird, it was bad.
- now, they don't appear at all, and are excluded from keyboard nav.
- falsy values are preserved in the `onChange` array, they're just ignored by interactions.
- i toyed with filtering them out on change, but it felt too intrusive.

[TagInput] ignore falsy values

---

packages/core/src/components/popover/popover.md
packages/core/src/components/tabs2/tabs2.md
packages/core/src/components/tooltip/tooltip.md
packages/labs/src/labs.md

- tone down Popover2 announcement notes
- fix some naming
- clearer Tooltip2 notes
- add callouts in original Popover and Tooltip docs linking to 2.0 in labs

Popover2 docs cleanup

---

packages/core/resources/icons/icons.json

(Technically a breaking change, but we think it'd be silly to wait for 2.0 for such a small correction)

[Icon] Fix pt-icon-bank-account className

---

packages/core/src/components/icon/_icons.scss

Without this I get Sass error `File to import not found or unreadable: common/icons.`
You may want to push a patch release for this, this is a regression from previous behaviour.

[Core] v1.25.0 regression fix for user-land sass compilation

---

docs/docs/site-docs.css
packages/site-docs/package.json
packages/site-docs/yarn.lock

- fix normalize.css devDependency version in docs site so it matches __core__. due to #1276: https://github.com/palantir/blueprint/pull/1276/files#diff-7c55e4e59594216d1a073cc53cef843aR17
- rebuild docs site to silently fix buttons

fix normalize.css version on docs site

---

packages/table/src/quadrants/_quadrants.scss

Similar issue to #1456, but when importing the table's scss.
Without this I get `File to import not found or unreadable: ../../core/src/common/mixins.` and `File to import not found or unreadable: ./common/variables.`

[Table] Fix for user-land sass compilation

---

packages/core/src/components/tabs/_tabs.scss

- Allows for nested tabs of different sizes
- `.pt-tab-list` still takes `.pt-large`, but only changes its direct `.pt-tab` children

[Tabs] Allow nested tabs of different sizes

---

packages/core/src/common/props.ts
packages/core/src/components/forms/controls.tsx
packages/core/src/components/forms/radioGroup.tsx

Add `inline` as a prop to RadioGroup to enable inline radio buttons. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/blueprint/1475)

[RadioGroup] Add inline prop for radio button group

---

packages/table/src/common/classes.ts
packages/table/src/quadrants/_quadrants.scss
packages/table/src/quadrants/tableQuadrantStack.tsx
packages/table/test/tableTests.tsx

- BEFORE: All quadrants were `position: absolute`, meaning the surrounding table container had no idea how big to make itself, so it collapsed down to its `min-height` of `60px` in containers that didn't have a fixed size.  
- AFTER: Keep the `MAIN`-quadrant content in the document flow to ensure the table sizes itself appropriately.
- CSS nuances. Am I using `flex` appropriately?
- I've found the _Features (Legacy)_ page in the table preview helpful for testing this!
- Please test the dev preview thoroughly to ensure nothing looks broken! (e.g. scrollbars should still not be visible in non`MAIN` quadrants)

[Table] Fix Table sizing when shown in flex parent

---

packages/datetime/src/common/dateUtils.ts
packages/datetime/src/dateInput.tsx
packages/datetime/src/dateRangeInput.tsx
packages/datetime/test/dateInputTests.tsx
packages/datetime/test/dateRangeInputTests.tsx

This PR is closely related to #1429. We didn't notice that the date range input was a separate component from the date input. This applies the same two fixes (applying the locale at parsing time and at formatting time) to the date range input.
(Note: To get the screenshot of the change, I had to add "L" to the list of formats and set the locale of the DateRangeInput. Neither of these changes are currently in the PR.)

[DateRangeInput] Pass locale to moment for formatting, part 2

---

packages/core/src/components/non-ideal-state/_non-ideal-state.scss

Before:
After:
I checked that Chrome and Firefox were unaffected by the change.

Prevent non-ideal state text from bleeding horizontally in IE.

---

packages/core/src/components/forms/_common.scss
packages/labs/src/components/tag-input/_tag-input.scss

~~- [ ] Include tests~~
~~- [ ] Update documentation~~
Making the color of the placeholder for `MultiSelect` and `TagInput` consistent with normal `.pt-input` as well as the padding.
Whether this disrupts other configurations
before:
after:

[MultiSelect/TagInput] Visual consistency of placeholder with normal inputs

---

packages/table/preview/index.tsx
packages/table/src/common/renderMode.ts
packages/table/src/common/renderOptimizationMode.ts
packages/table/src/table.tsx
packages/table/src/tableBody.tsx
packages/table/test/tableBodyTests.tsx

- 💎 __NEW__ `Table` now supports a `renderMode?: RenderMode` prop:
- `RenderMode.BATCH` _(default)_: renders cells in batches to improve performance
- `RenderMode.NONE`: renders cells synchronously all at once
- Added a new "Batch rendering" switch to the `Table` example:
I designed the prop as a `RenderMode` enum instead of a `useBatchRendering` boolean to allow us to support additional rendering modes in the future. See: https://github.com/palantir/blueprint/issues/1374#issuecomment-318497948, pasted here for your convenience:
> Another idea is, instead of a prop `useBatchRendering?: boolean;`, to add a `renderOptimizationMode?: RenderOptimizationMode;` prop (working title) that accepts values like:
> - `RenderOptimizationMode.BATCH`: render as many new cells as possible per frame, and …

[Table] Add renderMode prop

---

packages/table/src/quadrants/tableQuadrantStack.tsx
packages/table/test/tableTests.tsx

- 🐛 __FIXED__ `Table` resizing columns no longer throws an error when `isRowHeaderShown={false}`
I know the `getRowHeaderWidth` function is used in only one place, but it felt cleaner and clearer to me to pull that consideration out into a separate helper.

[Table] Resizing columns no longer throws error when row header is hidden

---

packages/table/src/table.tsx
packages/table/test/tableTests.tsx

- 🐛 __FIXED__ `Table` `FULL_ROWS`, `FULL_COLUMNS`, and `FULL_TABLE` selection overlays now align properly to cells on their bottom/right sides.
- Are the `alignmentCorrection` and `alignmentCorrectionString` variables overkill?
**_Before:_**
`FULL_ROWS` selection is 1px too narrow.
`FULL_COLUMNS` selection is 1px too short.
`FULL_TABLE` selection is 1px too short and 1px too narrow.
**_After:_**
All overlays align perfectly with the cell borders below.

[Table] Fix selection off-by-1px alignment issues

---

packages/labs/examples/index.ts
packages/labs/examples/suggestExample.tsx
packages/labs/src/components/index.ts
packages/labs/src/components/select/suggest.tsx
packages/labs/src/labs.md
packages/labs/test/index.ts
packages/labs/test/selectTests.tsx
packages/labs/test/suggestTests.tsx

`Suggest` component composes `Popover`, `InputGroup` and `QueryList`

[Labs] Suggest component

---

packages/core/src/components/tabs2/tabs2.tsx
packages/core/test/tabs/tabs2Tests.tsx

- 💎 __NEW__ `Tabs2` now offers the `large?: boolean` prop to set `pt-large` styling via the JavaScript API.
- ⚠️ This PR fixes a regression introduced in 1.26.0 (#1476 via #1494).
- The deprecated `Tabs` component is not prohibitively affected by the regression, because consumers must supply their own `<TabList>` child that they can style with `pt-large` (small changes like this were a known risk of merging #1476).
- Prop description language. I took inspiration from `NumericInput`'s `large`-prop description.
- **Should we cut a patch release (1.26.1)?**

[Tabs2] Add 'large' prop

---

packages/datetime/src/dateTimePicker.tsx
packages/datetime/test/dateTimePickerTests.tsx

In dateTimePicker component, we should only reset the state based on props if the props have actually changed. Otherwise, we will needless clear or reset DateTimePicker state based on props that have not changed. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/blueprint/1474)

[DateTimePicker] Fix where changing TimePicker clears date

---

docs/blueprint-landing.css
docs/blueprint-landing.js
docs/docs/site-docs.css
package.json
packages/core/package.json
packages/datetime/package.json
packages/datetime/src/dateTimePicker.tsx
packages/datetime/test/dateTimePickerTests.tsx
packages/docs/package.json
packages/labs/package.json
packages/site-docs/package.json
packages/site-landing/package.json
packages/table/package.json

:fireworks: **Highlights**: `Table` __`scrollToRegion(region: IRegion)`__ instance method, `Table` __`renderMode`__ to toggle batched cell rendering, `Table` __`onCompleteRender`__ prop, new `Suggest` component
- #1498 `pt-file-upload` now adds `ellipsis` styling to long, overflowing file names.
- #1510 `Tabs2` now offers a `large` prop to enable `pt-large` styling.
- ⚠️ This new prop addresses a reported `pt-large` regression from our last release (see: #1506).
- #1474 `DateTimePicker` no longer clears selected date when changing time values. (🎩 @cathyxz)
- #1496 🌟 `Table` now offers a __`scrollToRegion(region: IRegion)`__ instance method to programmatically scroll a desired row, column, or cell into view!
- The …

Prepare Release 1.27.0

---

packages/core/test/overlay/overlayTests.tsx

This test fails quite often now, but not always:
```
<Overlay>
Focus management
✖ brings focus to overlay if autoFocus=true
```
Since this has been causing tons of build failures on branches that don't even touch `Overlay` code, I'm opening this PR to `.skip` this test for now.

[Overlay] Skip flaky unit test

---

packages/site-docs/package.json
packages/table/package.json

- `@blueprintjs/table` now exports `RenderMode` enum (for use in `Table`'s `renderMode?: RenderMode` prop).

Prepare release table-1.24.1

---

packages/table/src/cell/_borders.scss

- 🐛 __FIXED__ `Table` column-header ghost cells are no longer missing borders.
- Does the column-header border still look good in every case?
- I noticed some existing style weirdness with header borders when there are `0 rows` and/or `0 columns`. Can address that later.
_BEFORE_
_AFTER:_

Fix Table column-header borders on ghost cells

---

.vscode/settings.json

This helps guard against noisy project-wide searches.
Left off node_modules, since that is baked into vscode as an exclude.
https://github.com/palantir/blueprint/blob/master/.gitignore
https://github.com/palantir/blueprint/blob/master/.stylelintignore
How do we feel about having the vscode settings checked into the repo? Thought this sort of thing was generally discouraged.

Make vscode exclusions consistent with gitignore / stylelintignore

---

packages/labs/examples/selectExample.tsx
packages/labs/src/components/select/select.tsx
packages/labs/src/labs.md
packages/labs/test/selectTests.tsx

- Add a `disabled` prop that disables the internal popover if set

[Labs] Add disabled prop to Select

---

packages/table/src/tableBody.tsx
packages/table/test/tableBodyTests.tsx

- 🐛 __Fixed__ `Table` now selects the target cell on right-click if the cell is not already contained in a selection.

[Table] Select the target cell on right-click

---

packages/table/src/headers/header.tsx
packages/table/src/interactions/reorderable.tsx
packages/table/test/reorderableTests.tsx
packages/table/test/tableTests.tsx

Add the focus cell logic to the selection logic for the drag handles.

[Table] Move focused cell when columns/rows are reordered

---

packages/table/src/common/errors.ts
packages/table/src/common/internal/focusedCellUtils.ts
packages/table/src/headers/columnHeader.tsx
packages/table/src/headers/header.tsx
packages/table/src/headers/rowHeader.tsx
packages/table/src/interactions/reorderable.tsx
packages/table/src/interactions/selectable.tsx
packages/table/src/regions.ts
packages/table/src/table.tsx
packages/table/src/tableBody.tsx
packages/table/test/common/internal/focusedCellUtilsTests.ts
packages/table/test/common/internal/index.ts
packages/table/test/harness.ts
packages/table/test/regionsTests.ts
packages/table/test/selectableTests.tsx
packages/table/test/tableTests.tsx

Improve shift-selection behavior.
- 🐛 __FIXED__ `Table` expand-selection behavior now expands from the focused cell. #823 #298 #1285 #1080
- 🐛 __FIXED__ `Table` <kbd>Shift+Click</kbd> no longer expands the selection when `allowMultipleSelection=false`. #1323
- 🐛 __FIXED__ `Table` disjoint-selection behavior (no longer results in janky updates). #1249
- __CHANGED__ `Table` `menuElement` now selects-all `onMouseDown`, not `onClick` (for consistency with `Header`s).
- The `returnEndOnly` flag feels unclean, but...it gets the job done.
- I put the expand-region logic in `FocusedCellUtils` to make it slightly easier to unit-test.
- Do the interactions feel correct?
_SINGLE SELECTION:_
_DISJOINT SELECTIONS:_

[Table] Improve shift-select behavior

---

packages/table/src/cell/cell.tsx
packages/table/src/cell/formats/truncatedFormat.tsx

Pass cell height and width to child, for use in shouldComponentUpdate
~The props aren't used by the element, but its presence means faster redraw for cells with truncated formats.~ The props are used by the element to avoid re-measuring if the parent size didn't change across updates.
This is on top of another in-progress PR -- ignore the first two commits.
I'm cloning all the cell children -- does this make sense?

[Table] Pass parent width/height props to TruncatedFormat

---

packages/core/src/components/menu/menuItem.tsx
packages/core/test/menu/menuTests.tsx

Pass `popoverProps` object to `menuItem`, like in `Labs/Select`.
I'm not sure if there are any test needed. If yes, tell me

[MenuItem] Pass popoverProps to menuItem

---

packages/table/src/headers/_headers.scss

- 🐛 __FIXED__ `Table` no longer shows misleading cursor over interaction bar when selection disabled.
Toggling between selection disabled and selection enabled:

[Table] Fix interaction-bar cursor when selection disabled

---

packages/table/src/interactions/selectable.tsx
packages/table/test/harness.ts
packages/table/test/tableBodyTests.tsx

- 🐛 __FIXED__ `DragSelectable` now responds to <kbd>Ctrl + Click</kbd> the same way it does to right-click (vis-a-vis triggering context menus).
- Should we try to handle <kbd>Ctrl + Click</kbd> events from `ContextMenuTarget` directly? That way no one ever has to worry about them behaving differently (in theory).

[Table] Fix DragSelectable context-menu behavior on Ctrl + Click

---

packages/table/src/tableBody.tsx
packages/table/test/tableTests.tsx

- 🐛 __FIXED__ `Table` now fires `onCompleteRender` as expected when using `RenderMode.BATCH`.
Not sure how this broke originally. :/ I tried and failed to add a test for a multi-frame batch render, so I added/updated a couple simple tests for now.

[Table] Fix onCompleteRender for RenderMode.BATCH

---

packages/table/src/interactions/selectable.tsx
packages/table/test/selectableTests.tsx

- 🐛 __FIXED__ `Table` no longer invokes `onSelection` excessively on `mousemove` when `selectedRegions` is controlled.
- Before, I was comparing the next `selectedRegions` candidate to `this.props.selectedRegions` under the assumption that the prop would contain the last emitted value. That obviously doesn't hold up when `selectedRegions` is controlled. 
- Now, I'm keeping a `lastEmittedSelectedRegions` instance variable in `DragSelectable`. I compare the current `selectedRegions` candidate to this old value to determine whether I should invoke `onSelection` again. If the values are deeply equal, I don't invoke.
- Does that sound good?

[Table] Fix onSelection being called too much in controlled mode

---

packages/table/src/headers/header.tsx

- 🐛 __FIXED__ Double-clicking a `Table` row header's resize handle, no longer throws an error.

[Table] Double-clicking row resize handle no longer throws error

---

packages/core/src/components/forms/_input-group.scss

Is the `.pt-input-action > .pt-spinner` selector acceptable?
Before:
After:

[Input group] More precise selector for spinners in input groups

---

packages/core/src/components/editable-text/_editable-text.scss

When a long string without any spaces is entered into multiline EditableText, the component's height will increase to fit the text. Previously, a vertical scrollbar will appear on the right side of the component.
Before fixing the bug (vertical scrollbar on the right will show when the component is in edit mode) :
After fixing the bug (the component's height is increased to fit the text) :

[EditableText] Fix multiline height for long strings with no spaces

---

packages/table/src/quadrants/_quadrants.scss

- 🐛  __FIXED__ `Table` now displays a left border on selections that are flush with the left side of the grid.
- You'll notice a visual regression with the left border when the row header is hidden. This is fixed in #1621, which hides the `LEFT` and `TOP_LEFT` quadrants when they're not needed. :)

[Table] Fix missing selection border on left edge of grid

---

packages/labs/src/common/errors.ts
packages/labs/src/components/popover/popover2.tsx
packages/labs/src/components/popover/popoverMigrationUtils.ts
packages/labs/src/components/popover/popoverMigrations.ts
packages/labs/test/popover2Tests.tsx

[Labs/Popover2] Ease Popover2 migration with prop shims

---

packages/site-docs/package.json
packages/table/package.json

- `@blueprintjs/table` now depends on `@blueprintjs/core` 1.25.0, which contains the new `Icon` component used throughout the table

Prepare release table-1.26.1

---

packages/table/src/quadrants/_quadrants.scss
packages/table/src/quadrants/tableQuadrant.tsx
packages/table/src/quadrants/tableQuadrantStack.tsx
packages/table/src/quadrants/tableQuadrantStackCache.ts
packages/table/test/quadrants/tableQuadrantStackTests.tsx

- If `isRowHeaderShown=false` and `numFrozenColumns=0`, don't render the `LEFT` or `TOP_LEFT` quadrants at all. 
- **Edge case:**
1. Set `isRowHeaderShown=false`.
2. Scroll downward and rightward a bit.
3. Set `isRowHeaderShown=true`.
4. *Expected:*
- The row header should appear pre-scrolled to the current scroll offset (as shown in the GIF below).
- The menu element should appear sync'd to the proper row-header width.

[Table] Don't render LEFT and TOP_LEFT quadrants if they're not needed

---

packages/core/src/components/popover/popover.tsx

if no targetElement is set, dont try to setState depending on its properties.

[Popover] Prevent accessing the targetElement if it doesn't exist

---

packages/table/src/quadrants/tableQuadrantStack.tsx
packages/table/src/quadrants/tableQuadrantStackCache.ts

- #1444 `Table` no longer allows inertial scroll beyond the last row or column.
- #1573 `Table` now doesn't stick _as much_ when you try to scroll slowly leftward/upward from the last column/row.
- Not really sure what the problem is here.
- `Table` now caches the scroll container's `clientWidth`/`clientHeight` upon the first `wheel` event in a gesture, reducing DOM reads during the gesture.  
- The cached value is cleared in the debounced view-sync method after the gesture has ended.
- This eliminates DOM reads during the wheel gesture.
- ⚠️  This assumes the `clientWidth` and `clientHeight` won't change during the wheel gesture.
- **Does scrolling actually feel better, or at least not worse?** 
- Is the ⚠️  assumption above okay for now? I guess this assumption may break if we …

[Table] Prevent overscroll, refactor scrolling logic in TableQuadrantStack

---

packages/core/src/components/popover/popover.tsx

nit: In `popover.tsx`, change `!targetElement` to `targetElement == null` instead.

[Popover] Change !targetElement to targetElement == null instead

---

packages/table/src/quadrants/tableQuadrantStack.tsx

Fixes a bug introduced in #1637 when the grid is smaller than the container. (`Utils.clamp` would complain that `max` can't be less than `min`.)

[Table/TableQuadrantStack] Fix 'clamp' error when grid smaller than container

---

packages/table/src/cell/formats/truncatedFormat.tsx

`@default WHEN_TRUNCATED`
And yet we say in the unstructured description that `ALWAYS` is the default. This PR fixes that inconsistency.

TruncatedFormat: Fix default TruncatedPopoverMode in docs

---

packages/core/package.json

Allow React 16 to be installed alongside Blueprint. 
This *does not guarantee full support* for React 16, but I've manually tested locally and all components render without errors. There may still be issues with deeper interaction logic (though I'm optimistic they'll be very rare), so at least this way folks can encounter those bugs and report them!
Note that until we begin work on 2.0, we are not doing any automated testing against React 16 (see #1659). We are also still using (very old) React typings (see #1031).

allow React 16 in core peerDependencies

---

packages/table/src/cell/formats/jsonFormat.tsx
packages/table/src/cell/formats/truncatedFormat.tsx
packages/table/test/formatsTests.tsx

- Benefits: No more detecting truncation, which is expensive. Performance benefits
- Drawbacks: A mix of little … and big …s, but I think this will be uncommon and the big … can change meaning from “contents don’t fit cell” to “contents are really big”, also an icon change will help
- Drawbacks: Wrapped text no longer gets … of any sort (unless real big). I’m fine with this, it’s pretty common. Apps that wrap should also resizeByTallest
-How we do it: 
— Change the default from detectTruncation to fixedTruncation
— Choose sane default
— Write good release notes
I may have missed spots

[Table] Turn off text truncation by default and raise fixed truncation limit

---

packages/table/src/cell/editableCell.tsx
packages/table/test/editableCellTests.tsx

We were updating saved and dirty value to match the value whenever _any_ prop changed, no matter what. Even if `shouldComponentUpdate` would have returned false, because `componentWillReceiveProps` is always true. So if there were any changes made before rendering got there (because batched rendering), it'd reset those changes. Now this no longer happens. 
Is `componentWillReceiveProps` even the right place for this? It apparently can't live in `componentWillUpdate` because that won't take a `setState`, but... is there a better lifecycle spot for this? 
Or more generally: is there a better way to do what I'm doing?

[Table/EditableCell] Only update saved and dirty values if value changed

---

packages/core/src/components/menu/_submenu.scss

Change the `position` of submenu popovers to be `absolute` instead of `relative`
Any particular reason why it was `relative` in the first place?

[Submenus] Switch popover from relative to absolute positioning

---

packages/core/test/overlay/overlayTests.tsx
packages/core/test/toast/toasterTests.ts

- __FIXED__ `Toaster` flaky test has been disabled until we can fix it.
- Follow up issue: https://github.com/palantir/blueprint/issues/1680

[Core] Skip flaky test, add comments mentioning FLUP issue

---

packages/table/src/headers/header.tsx

- 🔄 __CHANGED__ `Table` now always disables batch rendering for header cells.
- __Why?__ Because we kept seeing race conditions where we tried to sync quadrant row-header sizes before the final header cells finished rendering, leading to mismeasurements. The cost here is likely minimal, since header cells are less numerous than body cells and generally won't have tons of content in them (e.g. they won't have huge JSON blobs or `detectTruncation` logic).

[Table] Always disable batch-rendering in headers

---

packages/table/src/docs.md
packages/table/src/regions.ts

- 🌟 __NEW__ `Table` documentation now includes a section about _Regions_ and the `IRegion` interface.
- How's the language? Anything stick out as confusing, incorrect, or awkwardly worded?

[Table] Add Regions/IRegion docs

---

packages/table/src/cell/_cell.scss
packages/table/src/cell/editableCell.tsx
packages/table/src/common/classes.ts
packages/table/src/headers/_headers.scss
packages/table/src/headers/editableName.tsx

Make some style modifications to the surrounding div of the editable text, with a new class, to make it always horizontally fill the cell. Double-clicking anywhere in the cell will open the input now, and it takes up the whole space. 
Is position: absolute really the best way of doing this? I'm not happy with it, but I couldn't come up with anything better.

[Table] Make editable cells fill cells vertically

---

packages/docs/src/styles/_props.scss
packages/table/src/headers/columnHeaderCell.tsx

- #1675 `ColumnHeaderCell`'s `useInteractionBar` deprecation label is no longer truncated.
I changed some SCSS styles to add better handling for long tags in our prop descriptions.

[ColumnHeaderCell] Fix deprecated label on `useInteractionBar` prop

---

packages/datetime/src/dateInput.tsx
packages/datetime/src/datePicker.tsx
packages/datetime/src/dateRangeInput.tsx
packages/datetime/src/dateRangePicker.tsx
packages/datetime/test/common/dateTestUtils.ts
packages/datetime/test/datePickerTests.tsx
packages/datetime/test/dateRangePickerTests.tsx

Reverts palantir/blueprint#1693
Undoing the revert to get the #1647 changes back into `master` now that we've cut the 1.31.0 release.

Revert "Revert "[DateTime] Add dayPickerProps to datetime components""

---

packages/table/src/headers/rowHeader.tsx

Extremely simple fix to make defaultProps for RowHeader static so that React 16 doesn't complain.

[Table] Add missing `static` keyword on RowHeader defaultProps to fix React 16 warning

---

packages/core/src/components/forms/form-group.md
packages/core/src/components/forms/formGroup.tsx
packages/core/src/components/index.ts
packages/core/test/forms/formGroupTests.tsx
packages/core/test/index.ts

add `FormGroup` component + tests + docs
this component _does not support_ HTML props spread because it renders so many elements and we'd have several prop types conflicts (label, required, disabled).
took some creative liberties with the `required` implementation.

[Core] FormGroup component!

---

packages/table/src/cell/_borders.scss
packages/table/src/cell/_common.scss
packages/table/src/table.tsx

Add 2px inset box-shadow to frozen columns and rows.
- Colors? I picked blue4 for light theme and blue1 for dark theme
- I refactored the border styles to be more readable (would be nice if everything could just be inset styles in a future PR)

[Table] Add emphasized borders for frozen columns and rows

---

packages/core/src/components/alert/alert.md

- Fix grammar in docs
Reference
- https://jakubmarian.com/information-is-vs-informations-are-is-information-plural-or-singular-in-english/
- https://english.stackexchange.com/questions/117552/why-does-information-not-have-a-plural-form

[Core/Alert] Fix grammar in docs ("informations" => "information")

---

packages/core/src/components/overlay/overlay.tsx
packages/core/test/overlay/overlayTests.tsx

When overlays are unmounted, we currently only re-enable scrolling if there are no other overlays in the stack. However, if the none of the remaining overlays would prevent scrolling, we should also re-enable scrolling on unmount.
This has been causing the following issue:
1. A modal dialog is opened (which uses an overlay that prevents scrolling)
2. A user action triggers a toast (which also uses an overlay, but shouldn't prevent scrolling)
3. The dialog closes, but the toast remains visible. At this stage, scrolling should be re-enabled, but isn't.
The new tests, and the logic for determining whether an overlay in the stack would prevent scrolling.

[Core/Overlay] Fix overlay unmount issue that prevented scrolling

---

packages/core/src/common/utils.ts
packages/core/test/common/utilsTests.ts
packages/table/src/common/internal/platformUtils.ts
packages/table/src/headers/header.tsx
packages/table/src/interactions/reorderable.tsx
packages/table/src/interactions/selectable.tsx
packages/table/src/tableBody.tsx
packages/table/test/columnHeaderCellTests.tsx
packages/table/test/common/internal/index.ts
packages/table/test/common/internal/platformUtilsTests.ts
packages/table/test/selectableTests.tsx
packages/table/test/selectionTests.tsx
packages/table/test/tableTests.tsx

A morning surprise for @llorca.
- 🔄 __CHANGED__ `Table` no longer toggles selection on click; now, you must `cmd` + click to deselect cells, columns, or rows.
- 🐛 __FIXED__ `Table` `ctrl` + click now works on Windows again.
- There was an edge case for rows due to the fact that selected rows become reorderable, meaning the `DragReorderable` component would swallow all clicks (even `cmd` + clicks meant for deselecting). The fix required a refactor of the `disabled?` prop to optionally be a function that accepts the current `MouseEvent`, so it can check if the `metaKey` is pressed.
- This isn't an issue for columns, because the reorder handle is the only trigger for reordering; the rest of the column header cell is managed by the `DragSelectable` layer.
- This isn't an issue for body cells …

[Table] Deselect cells on cmd+click only

---

packages/table/src/common/direction.ts
packages/table/src/common/internal/directionUtils.ts
packages/table/src/common/internal/focusedCellUtils.ts
packages/table/src/common/internal/selectionUtils.ts
packages/table/src/common/movementDelta.ts
packages/table/src/interactions/selectable.tsx
packages/table/src/regions.ts
packages/table/src/table.tsx
packages/table/test/common/internal/directionUtilsTests.ts
packages/table/test/common/internal/focusedCellUtilsTests.ts
packages/table/test/common/internal/index.ts
packages/table/test/common/internal/selectionUtilsTests.ts
packages/table/test/regionsTests.ts
packages/table/test/tableTests.tsx

- __NEW__ `Table` <kbd>Shift + ⬆️ / ⬇️ / ⬅️ / ➡️ </kbd> hotkeys to resize selection (using focused cell as anchor if present).
- See function comments in the diff for details (in particular: [this comment](https://github.com/palantir/blueprint/pull/1707/files#diff-3c6700ce4c8768ee12a26d3b6b187392R14)).
- Really would like to decompose `<Table>`, but not in this PR. 
- I discovered a bug with somewhat-related behavior: #1706 
When `allowMultipleSelection=true`:

[Table] Shift + arrow keys to resize selection

---

packages/core/examples/buttonsExample.tsx

Happy to change the button text or the href but currently the button opens http://blueprintjs.com/docs/ which isn't a duplicate of the page the button is on

[Core/Button] Fix "Duplicate this page" button in docs

---

packages/core/src/components/button/button.md

For consistency with other notes like [here](http://blueprintjs.com/docs/#core/components/callout.css-api)

[Core/Button] Remove outdated note about minimal buttons in button groups

---

packages/core/src/common/props.ts

addresses the following error:
```
Warning: Unknown prop `popoverProps` on <a> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
in a (created by Blueprint.AnchorButton)
...
```

[Core] Add popoverProps to INVALID_PROPS

---

packages/table/src/table.tsx

added nulls since that actually the correct typing on ref. doest have an effect since strictNullChecks arent enabled
for reference: here is the correct type of Ref. your react typings are a bit outdated
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L77

[Table] Add null-checks when accessing rowHeaderElement

---

packages/site-docs/package.json
packages/table/package.json
packages/table/src/table.tsx

- `Table` Fix NPE error that was sometimes thrown when scrolling with `isRowHeaderShown=false`. (🎩  @mscolnick)

Prepare Release table-1.29.1

---

packages/core/src/components/dialog/_dialog.scss

Change `user-select` from `initial` to `text` for `.pt-dialog`. Chrome 62 regression.
Can someone check that it works as expected with Chrome <= 61?

[Dialog] Fix `user-select` value

---

packages/table/src/cell/_cell.scss
packages/table/src/cell/cell.tsx
packages/table/src/cell/editableCell.tsx
packages/table/src/table.tsx
packages/table/src/tableBody.tsx
packages/table/src/tableBodyCells.tsx

Editable cells can be edited when focused by pressing `f2` -- so one can edit editable tables merely with `f2`, `enter`, and the arrow keys -- no mouse required!
This is done by making cells able to be browser-focused, and having them focus themselves whenever, well, they become focused. This also lets the focus stay on the table when you're done editing a cell. 
There's... a bit of a horrible hack to allow the hotkeys to... pass through to the div beneath. I'm not sure if we should keep this or if there's a better way, or what? We could make some sort of slightly better version of cells having these endpoints, and make it less of a hack, maybe? Or fix hotkeys to find the DOM element underneath using `ReactDOM.findDOMNode`?
This doesn't work as well with the cell render batching if you're …

[Table] Edit focused cells on f2

---

packages/core/src/components/context-menu/context-menu.md
packages/core/src/components/context-menu/contextMenuTarget.tsx

ContextMenuTarget already handles the case where renderContextMenu returns undefined or null. This changes the type of renderContextMenu in IContextMenuTarget to reflect that this is allowed.

[Core] Improve types: IContextMenuTarget.renderContextMenu can return undefined

---

packages/core/src/docs/icons.md

Close the span `className` since it is missing a `"`.

Close the className of the span in Icon documentation.

---

packages/core/src/components/button/abstractButton.tsx
packages/core/test/buttons/buttonTests.tsx

- 🐛  __FIXED__ `Button` (and `AnchorButton`) with `iconName` no longer include erroneous right padding when `text=""`.
- I'm coercing `""` children to `undefined` so that this rule is applied:
```scss
// ensure icon button with no text is a perfect square
&[class*="pt-icon-"]:empty {
padding: 0;
&::before {
margin-right: 0;
}
}
```
___BEFORE:___
`text=""`
`iconName="edit"`
`rightIconName="edit"`
___AFTER:___
`text=""`
`iconName="edit"`
`rightIconName="edit"` _(unchanged)_

[Core/Button] Fix erroneous padding when text=""

---

packages/core/src/components/forms/numericInput.tsx

Rename `char` identifier to `character` in a couple of places, since `char` is a ClosureScript reserved word.

Avoid using a reserved word as an identifier

---

packages/datetime/src/_datepicker.scss

`@mixin calendar-day()`.
_Note:_ seems like `showWeekNumbers` and `onWeekClick` are meant to be set together and omitting the callback is actually undefined behavior. this means the whole `pointer-events` thing is moot and we should allow clicking on the element.
see https://github.com/gpbl/react-day-picker/pull/338/files#diff-94429edb7ff780d5a0f9baebb8277e02R70 for the unsafe (required) prop invocation.

[DatePicker] calendar-day() mixin

---

packages/table/src/docs.md

- `Table` Added documentation for `resizeRowsByApproximateHeight` instance method
- Language, clarity, and formatting.

[Table] Added documentation for resizeRowsByApproximateHeight

---

packages/datetime/src/dateInput.tsx
packages/datetime/test/dateInputTests.tsx

BEFORE:
1. Make a `DateInput` with `canClearSelection=false` and `timePrecision` enabled.
1. Select a date.
1. Click the selected date again.
1. `onChange` is erroneously emitted with `null`, suggesting that the date has just been deselected, which shouldn't be possible.
AFTER:
`DateInput` no longer emits `onChange` with `null` when clicking selected date with `canClearSelection=false` with `timePrecision` enabled.
Nothing in particular. Easy fix.
Here's a working example with the following props:
```tsx
<DateInput
canClearSelection={false}
value={new Date(2017, Months.NOVEMBER, 6)}
onChange={console.log}
timePrecision={TimePickerPrecision.SECOND}
/>
```

[DateInput] Selected value stays selected when canClearSelection=false with timePrecision enabled

---

packages/datetime/src/dateInput.tsx
packages/datetime/test/dateInputTests.tsx

- `DateInput` now accepts custom `timePickerProps`
- Are all the component `timePickerProps` being overridden correctly by top-level props?

[DateInput] Make timePickerProps configurable

---

packages/labs/src/components/select/multiSelect.tsx
packages/labs/test/multiSelectTests.tsx

- `MultiSelect` no longer throws an error when `selectedItems` is not controlled.

[MultiSelect] Uncontrolled selectedItems no longer throws error

---

packages/datetime/src/common/monthAndYear.ts
packages/datetime/src/dateRangePicker.tsx
packages/datetime/src/index.md
packages/datetime/test/dateRangePickerTests.tsx

- `DateRangePicker` with `contiguousCalendarMonths=false` now shows selected end date in right view on init. 
- (Before, the right view always showed the month immediately after the left view, which wasn't always helpful.) 
Demonstrated in `DateRangeInput`:

[DateRangePicker] Show selected date's end month on init if contiguousCalendarMonths=false

---

packages/table/src/cell/cell.tsx
packages/table/src/cell/editableCell.tsx

Typing any character now replaces the cell content with that character and puts it in edit mode, essentially letting you arrow around and type in the correct cell.

[Table/EditableCell] Type in a cell to edit it now

---

packages/core/src/components/editable-text/editableText.tsx

Set scrollLeft as well as selection position to guarentee that the scroll is correct.
I tried, repeatedly, to figure out why setSelectionRange doesn't seem to work properly, for us, in chrome. I... had a lot of trouble playing with it to get it to do it programmatically in _any_ browser. Even using existing examples. 
This method of doing it works in chrome, and other browsers, and will make sure we're scrolled to the end when we need to be.

[EditableText] Add extra code to make sure we move scroll position to the end

---

packages/core/src/components/menu/_submenu.scss

Extend .pt-popover-content to fill the gap between the menu item and its submenu.
Tested in Chrome 61.0.3163.100, and IE 11.0.9600.17420.

[Core/Menu] Update styles to fix submenu hover semantics

---

packages/core/src/components/slider/rangeSlider.tsx
packages/core/test/slider/rangeSliderTests.tsx

- 🐛 __FIXED__ `RangeSlider` always moves the nearest handle, even when handle values are equal.
- This will have minor merge conflicts with PR #1762.

[Core/RangeSlider] When values equal, always move the nearest handle on track click

---

packages/core/examples/collapseExample.tsx
packages/core/src/components/collapse/_collapse.scss
packages/core/src/components/collapse/collapse.md
packages/core/src/components/collapse/collapse.tsx
packages/core/test/collapse/collapseTests.tsx

Allow the `Collapse` component to take in a prop `keepChildrenMounted` which allows its children to remain rendered. Helps with React performance, especially if the children are complex.

Add prop to keep Collapse children mounted

---

packages/table/src/headers/columnHeaderCell.tsx
packages/table/src/headers/editableName.tsx
packages/table/test/columnHeaderCellTests.tsx

Clone the header name so it gets the index as props when created, so it can use it to pass it in the callbacks. Also improve the header so that it actually is controlled mode, more or less.

[Table] Better editable names

---

packages/docs-app/src/examples/labs-examples/tagInputExample.tsx
packages/labs/src/components/tag-input/_tag-input.scss
packages/labs/src/components/tag-input/tag-input.md
packages/labs/src/components/tag-input/tagInput.tsx
packages/labs/test/tagInputTests.tsx

Added an extra property to the `TagInput` component. Setting the property to true makes it non-interactive in the UI. Updated the docs and tests.

Add a disabled state to <TagInput>

---

packages/core/src/components/forms/_common.scss
packages/labs/src/components/tag-input/_tag-input.scss

Updated the `TagInput`'s placeholder color for consistency with other `input` elements.

Fix TagInput dark placeholder color

---

packages/core/src/components/forms/inputGroup.tsx
packages/core/test/controls/inputGroupTests.tsx
packages/datetime/test/dateInputTests.tsx
packages/datetime/test/dateRangeInputTests.tsx

- `InputGroup` now supports custom styles passed via the `style` prop.
- `DateInput` now supports custom input styles passed via the `inputProps` prop.
- `DateRangeInput` now supports custom input styles passed via the `(start,end)InputProps` props.
Do we need to support a top-level style prop on `DateInput` and `DateRangeInput` too? See https://github.com/palantir/blueprint/issues/1554#issuecomment-330186724.

[Core,DateTime] Support custom `style` on InputGroup and datetime inputs

---

packages/core/src/components/popover/popover.tsx
packages/labs/src/components/popover/popover2.tsx

Prevent DOM reflow on popover mount by only checking for dark ancestors when popover is open.
Seeing some really bad perf in tables where every cell / header has a popover (right click menus, column menus), and each componentDidMount is causing a reflow when the popover does the element.closest("pt-dark") check. We don't need to check this unless the popover is actually open (or about to become open) as the class is only applied to the non-inline portal anyway, which is only visible when the popover is open.

[Table] Prevent DOM reflow by optimizing popover dark-ancestor checks

---

packages/datetime/src/_datepicker.scss
packages/datetime/src/dateInput.tsx
packages/datetime/src/datePicker.tsx
packages/datetime/src/datePickerCaption.tsx
packages/datetime/src/datePickerCore.tsx
packages/datetime/src/dateRangePicker.tsx
packages/docs-app/src/examples/datetime-examples/dateInputExample.tsx
packages/docs-app/src/examples/datetime-examples/datePickerExample.tsx
packages/docs-app/src/examples/datetime-examples/dateRangeInputExample.tsx
packages/docs-app/src/examples/datetime-examples/dateRangePickerExample.tsx

- 🎉 __NEW__ `DateTime` components now support `reverseMonthAndYearMenus` prop to show year menu on the left.
- `DatePicker`
- `DateRangePicker`
- `DateTimePicker`
- `DateInput`
- `DateRangeInput`
- 🔄 __CHANGED__ `DatePicker` menu styles:
- Caret now shows persistently.
- Caret is `$pt-text-muted-color`.
- Caret is `$pt-text-color` on `select:hover`.
_`DatePicker`_
_`DateRangePicker`_
_`DateInput`_
_`DateRangeInput`_

[DateTime] Add `reverseMonthAndYearMenus` prop to all relevant components

---

packages/datetime/src/dateInput.tsx
packages/datetime/src/dateRangeInput.tsx
packages/datetime/test/dateInputTests.tsx
packages/datetime/test/dateRangeInputTests.tsx

- `DateInput` and `DateRangeInput` now applies custom `className` to its `pt-popover-target` (along with `popoverProps.className)

[DateTime/___Input] Pass both className and popoverProps.className to popover targets

---

packages/labs/src/components/popover/popover2.tsx

Make sure targetElement exists before trying to call `closest` on it

[Popover2] Make sure targetElement exists before trying to call its function

---

packages/core/src/components/hotkeys/keyCombo.tsx

Per offline discussion with @giladgray, return span instead of div such that the keycombo can be used inline, e.g. to prompt users to use keyboard combinations to do things.

[KeyCombo] Render span element instead of div

---

packages/core/src/components/progress/_progress-bar.scss

- __FIXED__ Change `pt-progress-meter` to `display: block` so it stops erroneously responding to `text-align` rules applied to parents.
Suggested by @llorca in https://github.com/palantir/blueprint/issues/1859#issuecomment-349058985.
See dev preview.

[Core/ProgressBar] Change pt-progress-meter to display: block

---

packages/karma-build-scripts/createKarmaConfig.js
packages/table-dev-app/src/mutableTable.tsx
packages/table/src/cell/cell.tsx
packages/table/src/cell/formats/truncatedFormat.tsx
packages/table/src/common/utils.ts
packages/table/src/table.tsx
packages/table/test/formatsTests.tsx

Create a faster, less-accurate "truncate by approx" that is synchronous rather than async and doesn't require measuring the DOM, for extra speeds. 
It's definitely somewhat faster in batch-on-update mode, and _much_ faster (visibly takes much less time) on "none" render mode. Pick "json" for the cell contents to make this more obvious. 
This isn't... quite done yet -- there are a couple open questions. Namely:
- currently the defaults are hardcoded into the class, the same way table is -- we should probably be pulling this out somewhere common, yes? Where should they go?
- additionally -- the defaults for "buffer lines" are slightly different -- having a buffer line if you're not wrapping the text means the cell needs to be twice as long, which is silly. Should we be passing the "wrap …

[Table] Added option to truncated format for truncated by approx

---

packages/datetime/src/dateInput.tsx
packages/datetime/src/dateRangeInput.tsx
packages/datetime/test/dateInputTests.tsx
packages/datetime/test/dateRangeInputTests.tsx

- `DateInput` and `DateRangeInput` now save the typed value(s) on <kbd>Enter</kbd>.
- They also move/transfer the focus state appropriately.
- The tests don't corroborate my understanding of what should be happening. Maybe I just need to sleep on it. I've commented or omitted some checks in the meantime.
- Idea for followup: Revert to the old value on <kbd>Esc</kbd>? Thoughts?
- Does controlled mode look good?
_`DateInput`_
_`DateRangeInput`_

[DateInput/DateRangeInput] Commit typed value on 'Enter' key press

---

packages/core/src/components/forms/control-group.md
packages/core/src/components/forms/controlGroup.tsx
packages/core/src/components/forms/file-upload.md
packages/core/src/components/forms/fileUpload.tsx
packages/core/src/components/forms/label.md
packages/core/src/components/forms/label.tsx
packages/core/src/components/forms/text-area.md
packages/core/src/components/forms/textArea.tsx
packages/core/src/components/index.ts
packages/core/test/forms/fileUploadTests.tsx
packages/core/test/index.ts
packages/docs-app/src/examples/core-examples/controlGroupExample.tsx
packages/docs-app/src/examples/core-examples/index.ts

- Add JS APIs for `ControlGroup`, `FileUpload`, `Label`, `TextArea`.
- Add example for `ControlGroup`.
- Add tests for `FileUpload`.
- There are some subtleties to the `FileUpload` component, so I added tests.
- I really think we should have at least a simple test for every component. Exact quotes from my experience trying to use the `FileUpload` component in a test:
- "Damn, I accidentally specified a prop as required instead of optional"
- "Damn, I accidentally forgot to export the component from `index.ts`"
I'd so much rather rely on a test for those things than on fallible human cognition in a code review.

[Core] Add JS APIs for ControlGroup, FileUpload, Label, TextArea

---

packages/docs-app/src/examples/labs-examples/index.ts
packages/docs-app/src/examples/labs-examples/omnibarExample.tsx
packages/labs/src/common/classes.ts
packages/labs/src/components/_index.scss
packages/labs/src/components/index.ts
packages/labs/src/components/omnibar/_omnibar.scss
packages/labs/src/components/omnibar/omnibar.md
packages/labs/src/components/omnibar/omnibar.tsx
packages/labs/src/components/omnibox/omnibox.md
packages/labs/src/index.md

think I got everything, would be good to doublecheck

rename Omnibox -> Omnibar

---

packages/labs/src/components/timezone-picker/timezonePicker.tsx
packages/labs/test/timezonePickerTests.tsx

This changes the type of `popoverProps` in the `TimezonePicker` component from `IPopoverProps` to `IPopover2Props`.  It seems like it used `IPopoverProps` in error because the underlying implementation uses `Popover2` (through `<Select />`).  I discovered this when I tried to pass in a `position` prop, but it had no effect; the correct prop to use was `placement`.
Is this change safe?  Since it was using the incorrect props before, this catches usages of Popover(1) and will force consumers to use the new props.
This is now possible:

[Labs/TimezonePicker] Use correct popover props for TimezonePicker

---

packages/table/package.json
packages/table/src/table.tsx
packages/table/test/editableCellTests.tsx
packages/table/test/editableNameTests.tsx
packages/table/test/tableTests.tsx

- Call super methods of AbstractComponent instead of validateProps directly
- Use new enzyme state method
- Use full mount instead of shallow mount
- Remove update tests due to awkward error boundary prop setting with new enzyme API (also already tested on mount)

Fix table tests
