palantir/blueprint

packages/core/src/components/overlay/overlay.tsx
packages/core/src/components/portal/portal.tsx
packages/core/test/portal/portalTests.tsx
packages/select/src/components/select/select.tsx

```js
componentDidMount() {
// The portal element is inserted in the DOM tree after
// the Modal's children are mounted, meaning that children
// will be mounted on a detached DOM node. If a child
// component requires to be attached to the DOM tree
// immediately when mounted, for example to measure a
// DOM node, or uses 'autoFocus' in a descendant, add
// state to Modal and only render the children when Modal
// is inserted in the DOM tree.
modalRoot.appendChild(this.el);
}
```
(https://reactjs.org/docs/portals.html#event-bubbling-through-portals)

Portal only renders children after mounted

---

packages/core/src/components/forms/_common.scss

Wrong font since normalize upgrade.
Following up on https://github.com/palantir/blueprint/pull/1886

[Input] Inherit font size

---

packages/core/src/common/errors.ts
packages/core/src/components/popover2/popover2.tsx
packages/core/src/components/popover2/popoverMigrationUtils.ts
packages/core/src/components/tooltip2/tooltip2.tsx
packages/core/test/popover2/popover2Tests.tsx
packages/docs-app/src/components/navbarActions.tsx
packages/docs-app/src/examples/core-examples/tooltip2Example.tsx
packages/labs/test/timezonePickerTests.tsx
packages/select/src/components/select/select.tsx

`PopperJS.Placement` and `Position` are redundant. Prefer `Position` as it has been in our public API since the beginning.

Remove PoppperJS.Placement prop. Use Position in public API instead

---

packages/core/src/common/constructor.ts
packages/core/src/common/errors.ts
packages/core/src/common/index.ts
packages/core/src/common/utils.ts
packages/core/src/components/context-menu/contextMenuTarget.tsx
packages/core/src/components/hotkeys/hotkeys.tsx
packages/core/src/components/hotkeys/hotkeysEvents.ts
packages/core/src/components/hotkeys/hotkeysTarget.tsx
packages/core/test/context-menu/contextMenuTests.tsx
packages/core/test/hotkeys/hotkeysTests.tsx

Implement `HotkeysTarget` and `ContextMenuTarget` by returning a new HOC rather than monkeypatching.
Behavior is maintained from before.

rewrite HotkeysTarget and ContextMenuTarget as HOCs

---

packages/labs/src/components/tag-input/tagInput.tsx
packages/labs/test/tagInputTests.tsx

- Fix errant `TagInput` behavior that was introduced in #1801 work.

Fix TagInput onKeyDown/onKeyUp handlers that broke in @blueprintjs/labs@0.14.1

---

packages/core/src/components/button/_button-group.scss
packages/core/src/components/button/button-group.md
packages/core/src/components/popover/popover.md
packages/core/src/components/popover/popover.tsx
packages/docs-app/src/examples/core-examples/buttonGroupPopoverExample.tsx
packages/docs-app/src/examples/core-examples/common/fileMenu.tsx
packages/docs-app/src/examples/core-examples/index.ts
packages/docs-app/src/examples/core-examples/popoverButtonGroupExample.tsx
packages/docs-app/src/examples/core-examples/popoverInlineExample.tsx
packages/docs-app/src/examples/core-examples/popoverInteractionKindExample.tsx
packages/docs-app/src/examples/core-examples/popoverMinimalExample.tsx
packages/docs-app/src/examples/core-examples/popoverPositionExample.tsx
packages/docs-app/src/examples/core-examples/popoverSizingExample.tsx
packages/docs-app/src/styles/_examples.scss
packages/docs-app/src/styles/_sections.scss

Lots of popover docs changes.
Best part IMO is the new `Position` docs, which feature (\*gasp\*) _color_:
But we also have several, more granular _examples_:
_Maybe_:

Graduate Labs Components - Part 3: Popover docs

---

packages/core/src/common/errors.ts
packages/core/src/components/popover/popover.tsx
packages/core/test/popover/popoverTests.tsx

- Handle all the validation errors that old `Popover` used to handle.
- Fix interaction between `Popover`'s `disabled` prop and `isOpen` prop.
- `disabled=true` overrides `isOpen=true`, keeping the popover closed.
- Invoke `onInteraction` whenever the `this.state.isOpen` changes as a result of changing the `disabled` prop.
- Write tests.

Graduate Labs Components - Part 4: Popover validation

---

packages/core/src/common/errors.ts
packages/core/src/components/popover/popover.tsx
packages/core/test/popover/popoverTests.tsx
packages/docs-app/src/examples/core-examples/popoverExample.tsx
packages/docs-app/src/examples/core-examples/popoverInlineExample.tsx
packages/docs-app/src/examples/core-examples/popoverInteractionKindExample.tsx

- Fix docs-app scroll-jumping issue on the `PopoverInlineExample` by setting `enforceFocus={false}`
- Fix issue where `PopoverInlineExample` scroll containers weren't being centered on mount.
- Fix issue where `PopoverInlineExample` non-inline popover wasn't tracking the target.
- Set `enforceFocus={false}` on the `CLICK_TARGET_ONLY` example, so user can still click on things in the rest of the docs app. 
- Remove mentions of old props in Popover error-message constants.

Graduate Labs Components: Fix/Improve Popover Examples

---

packages/select/src/components/query-list/queryList.tsx

s/`item: T | undefined`/`item: T`
documentation already says `(item: T, event?: any) => void` http://blueprintjs.com/docs/#labs/omnibox

Require value in `IListItemsProps.onItemSelect`

---

packages/labs/src/components/tag-input/tag-input.md
packages/labs/src/components/tag-input/tagInput.tsx
packages/labs/test/tagInputTests.tsx

inputValue, onInputChange props to listen/control input without resorting to inputProps

Adding input-level props to tagInput

---

packages/docs-app/src/examples/core-examples/popoverInlineExample.tsx

- Stop using `requestAnimationFrame` in `PopoverInlineExample.componentDidMount`.
- Assume prod mode will fix the flashes of unstyled content that led to my using these in the first place.
- (From a commit I failed to push before) Change:
- `scrollSync{1,2}` to `scrollSync{Left,Right}`
- `scrollContainer{1,2}Ref` to `scrollContainer{Left,Right}Ref`

Graduate Labs to Core: Stop using rAF in componentDidMount; change 1,2 => Left,Right

---

packages/datetime/src/dateRangePicker.tsx
packages/datetime/test/dateRangePickerTests.tsx

Adding a "Today" and "Yesterday" shortcut to the date range selector. These only show up when allowSingleDayRange is enabled (since it wouldn't really work otherwise).

Add Yesterday and Today shortcuts when allowSingleDayRange enabled

---

packages/core/src/common/props.ts
packages/core/src/components/tag-input/tagInput.tsx
packages/datetime/src/dateInput.tsx
packages/datetime/src/dateRangeInput.tsx
packages/select/src/components/omnibar/omnibar.tsx
packages/select/src/components/select/multiSelect.tsx
packages/select/src/components/select/select.tsx
packages/select/src/components/select/suggest.tsx

- `HTMLInputProps` alias uses `InputHTMLAttributes` instead of `HTMLProps` (does not include `ref` or `key`)
- remove `const { ref, ...htmlInputProps } = inputProps` workaround!!
- add `TagInput` `inputRef` prop because `inputProps` does not expose it anymore.

HTMLInputProps without ref or key

---

packages/table/src/common/utils.ts
packages/table/src/locator.ts

We'd like to add some text to our column headers (column descriptions) which should be shown in the header cell (as an affordance to users that they can click and view more details about the column) but not taken into account for double-click-to-resize interactions on the column.

[release/1.x] [table] measureTextContentWithExclusions

---

packages/core/test/callout/calloutTests.tsx
packages/core/test/controls/numericInputTests.tsx
packages/core/test/controls/radioGroupTests.tsx
packages/core/test/menu/menuTests.tsx
packages/core/test/popover/popoverTests.tsx
packages/core/test/slider/rangeSliderTests.tsx
packages/core/test/slider/sliderTests.tsx
packages/core/test/tag-input/tagInputTests.tsx
packages/core/test/tooltip/tooltipTests.tsx
packages/core/test/tree/treeTests.tsx
packages/select/test/queryListTests.tsx
packages/select/test/selectTests.tsx
packages/select/test/suggestTests.tsx
packages/table/test/quadrants/tableQuadrantStackTests.tsx
packages/table/test/quadrants/tableQuadrantTests.tsx
packages/table/test/resizableTests.tsx
packages/table/test/selectableTests.tsx
packages/table/test/selectionTests.tsx
packages/table/test/tableBodyTests.tsx
packages/table/test/tableTests.tsx

see commits for individual strategies to address warnings.
a few warning messages remain, namely that `NaN ... left` one in PopoverArrow, which I suspect is coming from Popper due to Phantom being a weird environment.
also includes (what I think is the) fix for Popover flakes, from https://github.com/palantir/blueprint/pull/2028/commits/1089e6e0c42329926067157b164451e6e7ad92f1 in #2028

fix warnings in tests

---

packages/core/src/components/overlay/overlay.tsx
packages/core/src/components/toast/toast.md
packages/core/src/components/toast/toaster.tsx
packages/core/test/overlay/overlayTests.tsx

- `Toaster` renders `children` after state toasts
- 🐛  `Overlay` now passes through non-JSX `children`
- `string | number` children will not be animated. to be fair, this is an improvement over the previous behavior where it would simply die if given non-JSX children.
- major refactors to Toasts documentation to clarify expected usage (see #1224)

Toast docs + children support

---

packages/core/src/components/menu/_submenu.scss
packages/docs-app/src/components/navbarActions.tsx
packages/docs-app/src/index.scss

- move infrastructure packages into submenu in releases dropdown
- 🐛  fix CSS issue with submenu in popover on button in button group (yuck)

[docs] move infra packages into submenu in releases dropdown

---

packages/core/src/components/overlay/overlay.tsx
packages/core/test/overlay/overlayTests.tsx

Uses `Overlay.openStack` to test if a document click is in a descendant overlay. Children overlays _should_ always be after the parent's index, so I think this should work for most cases.
This PR does not handle the case of having a non-`Overlay` `Blueprint.Portal` or `ReactDOM.createPortal`.

[Overlay] Support nested overlays

---

.circleci/config.yml
packages/core/src/components/hotkeys/hotkeyParser.ts
packages/core/test/controls/numericInputTests.tsx
packages/core/test/editable-text/editableTextTests.tsx
packages/core/test/overlay/overlayTests.tsx
packages/core/test/popover/popoverTests.tsx
packages/core/test/portal/portalTests.tsx
packages/core/test/tag-input/tagInputTests.tsx
packages/datetime/test/dateRangeInputTests.tsx
packages/karma-build-scripts/createKarmaConfig.js
packages/karma-build-scripts/package.json
packages/table/src/common/utils.ts
packages/table/test/clipboardTests.ts
packages/table/test/common/internal/scrollUtilsTests.tsx
packages/table/test/quadrants/tableQuadrantStackTests.tsx
packages/table/test/tableTests.tsx
packages/table/test/utilsTests.ts
yarn.lock

- switch from PhantomJS to ChromeHeadless (that was easy)
- tired of faffing about with focus failures on a browser that isn't even real!
- #2033 introduced some test failures (author's Circle setup did not support our test parallelism 😢 ), so here I fixed them.
- also took a stab at fixing test flakes (not entirely successful) and i was able to un-skip all the skipped tests!

switch to chrome headless, deflake tests

---

packages/core/test/overlay/overlayTests.tsx

Don't know of a way to assert that enzyme wrappers are unmounted before tests.
https://github.com/airbnb/enzyme/issues/911 captures the heart of this discussion: it's up to the consumer to ensure their tests clean up after themselves. enzyme does not automatically unmount, or provide a `cleanup()` method. There's actually a [**Note** to this effect](https://github.com/airbnb/enzyme/blob/master/docs/api/mount.md#full-rendering-api-mount) on the `.mount()` docs.

always unmount Overlay in tests -- fixes flakes!

---

packages/datetime/package.json
packages/datetime/src/_daterangepicker.scss
packages/datetime/src/dateInput.tsx
packages/datetime/src/datePicker.tsx
packages/datetime/src/datePickerCaption.tsx
packages/datetime/src/datePickerCore.tsx
packages/datetime/src/dateRangeInput.tsx
packages/datetime/src/dateRangePicker.tsx
packages/datetime/src/index.ts
packages/datetime/test/datePickerCaptionTests.tsx
packages/datetime/test/datePickerTests.tsx
packages/datetime/test/dateRangePickerTests.tsx
packages/tslint-config/index.js
yarn.lock

Upgrade the `react-day-picker` dependency from version `^5.3.0` to `^7.0.7` and update to accomadate breaking changes in the `react-day-picker` package highlighted in their [CHANGELOG](https://github.com/gpbl/react-day-picker/blob/master/CHANGELOG.md).
Type accuracy and breaking changes highlighted in the `react-day-picker` [CHANGELOG](https://github.com/gpbl/react-day-picker/blob/master/CHANGELOG.md).

Upgrade react-day-picker to v7

---

packages/core/src/common/classes.ts
packages/core/src/components/callout/_callout.scss
packages/core/src/components/callout/callout.md
packages/core/src/components/callout/callout.tsx
packages/core/test/callout/calloutTests.tsx
packages/docs-app/src/examples/core-examples/calloutExample.tsx
packages/docs-app/src/examples/core-examples/index.ts
packages/table/test/columnHeaderCellTests.tsx

- added `.pt-callout-icon` class to adjust padding & layout when icon is present
- existing CSS API is unchanged
- add Callout Example in docs

Callout renders SVG Icon component

---

packages/core/src/components/icon/icon.tsx
packages/core/test/icon/iconTests.tsx
packages/icons/src/iconName.ts
packages/icons/src/index.ts
packages/node-build-scripts/generate-icons-source

- 🔥 remove `LegacyIconName` type and support
- add generated `IconNames` module: `export const ARROW_DOWN = "arrow-down"; ...`
- generate-icons-source produces files that export many consts instead of one object. upside is they're all string literals without the `as` cast.
- use `import * as` to glob generated consts into objects.
- ⚠️  `IconName` becomes derived type from shape of `IconNames`. comes out the same and works identically in VS Code 👍

short icon names only

---

package.json
packages/core/src/common/utils.ts
packages/datetime/src/common/errors.ts
packages/datetime/src/dateInput.tsx
packages/docs-app/src/components/blueprintDocs.tsx
packages/docs-theme/src/components/documentation.tsx
packages/docs-theme/src/styles/_navbar.scss
packages/table/package.json
packages/table/src/common/context.ts
packages/table/src/common/errors.ts
packages/table/src/common/utils.ts
packages/table/src/headers/columnHeaderCell.tsx
packages/table/src/headers/headerCell.tsx
packages/table/src/headers/rowHeaderCell.tsx
packages/table/src/table.tsx
packages/table/src/tableBodyCells.tsx
packages/table/test/columnHeaderCellTests.tsx
yarn.lock

- see commits
- needs a regression pass

Remove remaining deprecated props

---

packages/core/src/common/_flex.scss
packages/core/src/common/_mixins.scss

sweet `pt-flex-container($dir, $margin, $inline, $fill)` mixin does it all!
@adidahiya this is the base branch for other flex PRs, but currently it contains just the code for the flex mixin so we can review that separately from the PRs that use it.

flex box mixin

---

packages/core/src/common/props.ts
packages/core/src/components/forms/fileInput.tsx
packages/core/src/components/menu/menuItem.tsx
packages/core/test/collapsible-list/collapsibleListTests.tsx
packages/docs-app/src/examples/core-examples/toastExample.tsx

- `IActionProps` `text` accepts `React.ReactNode` (instead of only strings)
- affects `Breadcrumb`, `Button`, `MenuItem`, `Toast`
- `FileInput` also accepts `React.ReactNode` text

IActionProps text accepts ReactNode

---

packages/core/src/common/alignment.ts
packages/core/src/common/classes.ts
packages/core/src/common/index.ts
packages/core/src/components/button/abstractButton.tsx
packages/core/src/components/button/buttonGroup.tsx
packages/core/src/components/navbar/navbarGroup.tsx
packages/docs-app/src/examples/core-examples/buttonGroupExample.tsx
packages/docs-app/src/examples/core-examples/buttonGroupPopoverExample.tsx
packages/docs-app/src/examples/core-examples/common/alignmentSelect.tsx

- add `Alignment` enum and `Classes.alignmentClass()`

Alignment enum

---

packages/core/src/components/icon/icon.md
packages/core/test/icon/iconTests.tsx
packages/docs-app/src/examples/core-examples/common/iconSelect.tsx
packages/icons/src/index.ts
packages/node-build-scripts/generate-icons-source
scripts/upgrade-blueprint-2.0.0-rename

- delete `IconClasses` constants file as it's simply `Classes.iconClass(IconNames.*)`

remove IconClasses

---

packages/core/src/common/classes.ts
packages/core/src/components/button/_button.scss
packages/core/src/components/button/_common.scss
packages/core/src/components/tag-input/_tag-input.scss
packages/core/src/components/tag-input/tagInput.tsx
packages/docs-app/src/examples/core-examples/tagInputExample.tsx

- actually three-column layout, with tags (and children) in center container
- `rightElement` supports buttons and spinners out of the box, but other elements will likely need custom CSS
- ⚠️  aligning the `rightElement` is basically impossible to generalize 😢 . any thoughts about how to handle this?
- the left icon and values are easy to center because they're owned by TagInput: we know size, position, etc about those.
- check out the margins on the left icon — they’re very specific to center it properly
and they change when large
- but `rightElement?: React.ReactNode` we know _nothing_ about!
in the docs example it’s a small button but it could be _anything_, from a large button to an entire app-in-a-box
- the `align-items: flex-start` fucks it all up cuz i don’t know what kind of …

flex tag input

---

packages/core/src/components/button/_button-group.scss

huge deletions
> `    [     default ]  [ active ] [ hover ]`:

remove dividers from minimal button groups

---

packages/core/src/common/utils.ts
packages/core/src/components/collapsible-list/collapsibleList.tsx
packages/core/src/components/forms/radioGroup.tsx
packages/core/src/components/hotkeys/hotkey.tsx
packages/core/src/components/hotkeys/hotkeys.tsx
packages/core/src/components/hotkeys/hotkeysEvents.ts
packages/core/src/components/popover/popover.tsx
packages/core/src/components/tabs/tabs.tsx

Since components end up proxied when using `react-hot-loader`, comparing to `React.createElement(Component).type` rather than `Component` should be a better solution to check if a component is of the right type (e.g. a `Hotkey`) 🙂 
Whether the components changed still behave as normal: Collapsible List, Radio Group, Hotkeys, Popover and Tabs.

Fix #2095: Ensure elements are compared to proxied component type

---

packages/core/src/components/dialog/_dialog.scss

- the cross on the right doesn't need padding, it's already properly sized
- there's a margin applied to all icons in the dialog header, should be disabled for the cross (it's only useful for the icon near the dialog title)

[Dialog] Fix icon positioning in dialog header

---

packages/webpack-build-scripts/webpack.config.base.js

`localhost` reopens in the browser after every `dev` command. especially annoying when your default browser isn't your dev browser.
what do you think about going back to pre-2.0 behavior with this PR?

Don't open server in browser when running dev

---

packages/core/src/common/errors.ts
packages/core/src/components/alert/alert.tsx
packages/core/test/alert/alertTests.tsx
packages/docs-app/src/examples/core-examples/alertExample.tsx

- `Alert`: add `canEscapeKeyCancel`, `canOutsideClickCancel`, `onClose`, `transitionDuration` props
- `onClose` is single alternative to separate `onCancel`/`onConfirm` props
- event handlers are all optional now, and handler-less usage is supported
- tweaked warnings, added warnings for new `can*Cancel` props
- __did not add `canEnterKeyConfirm`__ (see #517) because it's not easy to implement (key events require focus, blah blah), and is already supported by simply `tab`-ing onto a button and pressing `enter` or `space`

[core] add support for more Alert props

---

packages/core/src/common/classes.ts

Added a number of classes to constants that were not previously there:
- pt-running-text
- pt-running-text-small
- pt-monospace-text
- pt-list
- pt-list-unstyled
The need to replace used class strings with new constants.
I stumbled upon #2047 and thought i could contribute here. Seemed easy enough for a good first PR so i can start diggin the project.
Let me know if i am missing anything.

Add missing text class constants

---

packages/core/src/_typography.scss

use exact pixels for heading line-height and ensure descenders are always visible.

headings use pixel values for line-height

---

packages/datetime/src/dateInput.tsx
packages/datetime/test/dateInputTests.tsx

This PR enables the dateinput popover to be closed:
* after tabbing out of the last tabbable element inside the date popover
* clicking ESC key
Currently, shift tabbing out of the dateinput will close the date popover, however, tabbing through the popover elements do not close the popover after tabbing out of the last tabbable element. ESC also does not have any effect.
Is there a better way to implement this feature?

Close dateinput popover

---

packages/datetime/src/dateRangePicker.tsx
packages/datetime/test/dateRangePickerTests.tsx

This PR should fix couple small bugs in `DateRangePicker`:
1) When `minDate` === `startDate` === `endDate` month, both left and right calendar shows that month, but right calendar month selector shows the next month (see screenshot 1). 
**Cause:** `fromMonth` which is passed to right `ReactDayPicker` is after `rightView` date which is passed as `month`.
**Fix:** Now right calendar shows month immediately after left calendar month if `startDate` === `endDate` month. (I'm assuming that a desirable behaviour was calendars to never show the same month since right and left calendar `fromMonth` and `toMonth` are different).
2) When calculating `initialMonth`, `endDate` isn't taken in account. This could result in left calendar month being after right calendar month, if only `endDate` defined …

Date range calendars order

---

packages/core/src/components/icon/icon.tsx
packages/core/test/icon/iconTests.tsx

Adds a `title` prop to `Icon`, allowing consumers to override or disable the hover text.

[core] Add Icon `title` prop

---

packages/core/src/components/forms/label.tsx
packages/core/test/forms/labelTests.tsx
packages/core/test/index.ts

Adds a space in between `text` and `helperText` for the Label component
The updated `Label` component and new tests
`Before`
`After`

[core] Add space in between Label 'text' and 'helperText'.

---

packages/core/src/components/tree/_tree.scss
packages/docs-theme/src/components/block.tsx
packages/docs-theme/src/components/modifierTable.tsx
packages/docs-theme/src/components/page.tsx
packages/docs-theme/src/styles/_api.scss
packages/docs-theme/src/styles/_content.scss

Fix #2163: give ModifierTable its own class. stop reusing `.docs-modifiers`, which was the cause of this issue.
Fix #2194: tree caret icon rotation
Fix #2177: move pt-running-text back to docs-section. oof, preempts so many other tiny regressions!

[docs] fix regressions

---

packages/docs-app/src/components/docsIcon.tsx
packages/docs-app/src/components/icons.tsx
packages/docs-app/src/styles/_icons.scss

_(transition slowed for video, actual is 100ms)_
use 20px icon for 20px download link:

[docs] refactor docs icons styles

---

packages/core/src/components/tree/tree.tsx
packages/core/src/components/tree/treeNode.tsx

This feature add a new generics type prop for ITreeNode called 'nodeData'.
The user can use this property to store custom user data, object reference, etc.

Add ITreeNode.nodeData property

---

packages/datetime/src/_datepicker.scss
packages/datetime/src/datePickerCaption.tsx
packages/docs-app/src/examples/datetime-examples/common/momentDate.tsx
packages/docs-app/src/examples/datetime-examples/dateInputExample.tsx
packages/docs-app/src/examples/datetime-examples/datePickerExample.tsx
packages/docs-app/src/examples/datetime-examples/dateRangeInputExample.tsx
packages/docs-app/src/examples/datetime-examples/dateRangePickerExample.tsx
packages/docs-app/src/examples/datetime-examples/dateTimePickerExample.tsx
packages/docs-app/src/styles/_examples.scss

- stop measuring year select width in DatePickerCaption cuz it never really changes
- fix alignment of `<` `>` icons in DPC
- add `MomentDate` and `MomentDateRange` in examples to standardize display

[datetime] caption & examples alignment

---

packages/select/src/components/select/multiSelect.tsx

Pressing the escape key will now close the MultiSelect Popover when it is open and the input field is focused.  An escape keypress will also now blur the input field.

[Select] fixes #2135 - Adds a blur explicitly when escape key is pressed

---

packages/core/src/components/tree/tree.tsx
packages/core/src/components/tree/treeNode.tsx
packages/datetime/src/common/utils.ts
packages/datetime/test/dateRangePickerTests.tsx
packages/select/src/components/omnibar/omnibar.tsx
packages/select/src/components/select/multiSelect.tsx
packages/select/src/components/select/select.tsx
packages/select/src/components/select/suggest.tsx

https://github.com/palantir/blueprint/pull/2132#discussion_r172109621 pointed out a bug in how we were defining our `ofType` methods for generic components. This PR fixes all usages.
cc @izikorgad

fix ofType syntax

---

packages/select/src/components/query-list/queryList.tsx

- There is a regression in 2.x where the classname passed to a Select, which is then passed into a QueryList is not passed back to the Select.renderer to be attached on the popover
- Accidentally closed  https://github.com/palantir/blueprint/pull/2211

Fix querylist classname regression

---

packages/datetime/src/dateInput.tsx
packages/datetime/test/dateInputTests.tsx

Fixed issue caused by bumping react-day-select.
The update in react-day-select caused a slight change in behavior. Tabbing inside the date select popover will tab through the month, year selectors, then prev/next month arrow, then the first day of the current month. Prior version focused on the prev and next month's dates ie. days with `DayPicker-Day--outside` class. Now, after tabbing out of the first day of the current month, the popover will close.
Additionally, once the first day is focused, users can move the focused day by using the arrow keys. This PR adds changes which will allow the user to move the focused day and still close the popover by pressing tab anytime.

Fixed broken DateInput close feature due to bumping react-day-select

---

packages/select/src/components/select/multiSelect.tsx
packages/select/src/components/select/suggest.tsx

Updated #2079 PR for latest 2.0 branch

Pass inputRef to <Suggest> & <MultiSelect>

---

packages/core/src/components/button/abstractButton.tsx
packages/core/src/components/forms/controls.tsx
packages/core/src/components/forms/inputGroup.tsx
packages/core/src/components/menu/menu.tsx
packages/core/src/components/popover/popover.tsx
packages/core/src/components/portal/portal.tsx
packages/core/src/components/tag-input/tagInput.tsx
packages/docs-app/src/examples/core-examples/popoverExample.tsx
packages/select/src/common/predicate.ts
packages/select/src/components/omnibar/omnibar.tsx
packages/select/src/components/query-list/queryList.tsx
packages/select/src/components/select/multiSelect.tsx
packages/select/src/components/select/select.tsx
packages/select/src/components/select/suggest.tsx
packages/select/src/tsconfig.json
packages/select/test/tsconfig.json
packages/table/src/cell/cell.tsx
packages/table/src/headers/columnHeader.tsx
packages/table/src/quadrants/tableQuadrant.tsx
packages/table/src/quadrants/tableQuadrantStack.tsx

also add `| null` type to all ref props in all packages (for compatibility)
and fix a React warning in Popover example

enable strict mode in select package

---

packages/landing-app/src/index.scss
packages/landing-app/src/logo.ts

- 🙌 pause logo animation when offscreen to avoid scrolling performance impact.
- refactor `Animator`: add `stop()` & `isRunning()` & `add()`
- enable TSLint for logo

[landing] fix alignment, pause animation when offscreen

---

packages/core/src/components/icon/icon.tsx
packages/core/test/icon/iconTests.tsx

`color` is not handled in `<Icon>` because:
https://github.com/palantir/blueprint/blob/6cc104e5c8b4711d3aa314768ee505ba9bf71a23/packages/core/src/components/icon/icon.tsx#L19-L24
https://github.com/palantir/blueprint/blob/6cc104e5c8b4711d3aa314768ee505ba9bf71a23/packages/core/src/components/icon/icon.tsx#L64-L68
This PR fixed a issue that `color` property doesn't work on `<Icon>`:
```js
<Icon icon="add" color="red"/> // icon is now "red".
```
If user also pass a `style` to the component, final `style` should includes user defined properties:
```js
<Icon icon="add" color="red" style={{ color: "blue", border: "1px solid green" }}/> // icon is "red" with a green border.
```

Fix "color" property of <Icon>

---

package.json

- 🌟  #2200 Publish correct ES module files
- Upgrade to TypeScript 2.7 for development and enable `esModuleInterop` and `allowSyntheticDefaultImports` compiler flags to emit valid ES import statements for modules such as `classnames` and `moment`.
- ⚠️ bumped `tslib` dependency in all packages to support these new flags
- #2173 basic support for Windows development (🎩 @reiv)
- 🌟 #2205 `Portal` supports SSR now - it renders nothing on the server
- 🔥 the DOM element created by `Portal` is now treated as its root, so `className` is applied to this element. this also means that no dummy element is created inside the portal, making it one level shallower.
- 🔥 Removed `containerRef` prop as it no longer makes sense given note above. Users can simply apply refs to the elements they render in the …

Prepare Release v2.0.0-rc.3

---

packages/core/src/components/tag/_common.scss
packages/core/src/components/tag/tag.md
packages/core/src/components/tag/tag.tsx
packages/docs-app/src/examples/core-examples/tagExample.tsx

- `Tag` remove button renders `Icon` (and preserves CSS support)
- add options to `TagExample` and move to top of docs page

[tag] use Icon in remove button

---

packages/table/src/cell/editableCell.tsx
packages/table/test/editableCellTests.tsx

(reboot of #2192, cc @maclockard)
> Currently, if I don't change the controlled `value` as the result of a `onConfirm`, this check prevents the original value from overriding the `savedValue`. This is useful in a case where input to the `EditableCell` is being validated, and if it doesn't pass validation, the value of the cell shouldn't change.
In this PR, if `EditableCell` is controlled, then `value` prop will always update state fields on re-render.

Allow edits to be rejected for EditableCell

---

packages/core/src/components/toast/_toast.scss

[core] Fix Toaster regression

---

packages/datetime/src/_timepicker.scss
packages/datetime/src/common/classes.ts
packages/datetime/src/common/dateUtils.ts
packages/datetime/src/common/timeUnit.ts
packages/datetime/src/index.ts
packages/datetime/src/timePicker.tsx
packages/datetime/test/common/dateUtilsTests.tsx
packages/docs-app/src/examples/datetime-examples/timePickerExample.tsx

Adding an additional prop ~~`hourFormat`~~ `useAmPm` to the TimePicker component to support a 12-hour clock and AM/PM switcher. ~~`hourFormat` can be set to either of the two strings `"12hour"` or `"24hour"` to toggle the AM/PM switcher and type of hour unit being used.~~ `useAmPm` is a boolean which defaults to `false` (using the 24-hour clock by default to maintain backwards compatibility) and can be set to `true` to set the hour range to 12-hours and display an AM/PM dropdown.
I also added a switch to the TimePicker documentation page to set the example component's `hourFormat`.
https://media.giphy.com/media/39m89EvdXoQFbCPKYk/giphy.gif

Support for 12-hour clock (AM/PM) for TimePicker component

---

packages/docs-app/src/examples/select-examples/films.tsx
packages/select/src/common/itemRenderer.ts
packages/select/src/components/query-list/queryList.tsx

This PR adds `query` to the props passed to `itemRenderer`, making it possible to implement text highlighting. The `Select` docs example now makes use of this.

[select] Add query to itemRenderer props

---

packages/core/package.json
packages/core/src/components/menu/menuItem.tsx
packages/core/src/components/popover/arrow.tsx
packages/core/src/components/popover/popover.tsx
packages/core/src/components/popover/popoverMigrationUtils.ts
packages/core/src/components/tooltip/tooltip.tsx
packages/select/src/common/menuRenderer.ts
yarn.lock

upgrade popper & react-popper for latest typings

---

packages/core/src/components/portal/portal.tsx
packages/core/test/portal/portalTests.tsx
packages/docs-app/package.json
yarn.lock

blueprintPortalClassName supports multiple classes

---

packages/core/src/components/hotkeys/keyCombo.tsx

-  add minimal prop for icon-only version (pulled out of #2243)

refactor KeyCombo component

---

packages/table/src/table.tsx

From: https://github.com/palantir/blueprint/issues/1974
The issues lies in updateViewportRect method in table.tsx.
Code below:
```
this.setState({ viewportRect: nextViewportRect });
const { viewportRect } = this.state;
const didViewportChange =
(viewportRect != null && !viewportRect.equals(nextViewportRect)) ||
(viewportRect == null && nextViewportRect != null);
```
is incorrect because viewportRect is destructured after the setState. React recent updates have changed the way setState is executed and state may be set immediately, thus causing didViewportChange to be false and the onVisibleCellsChange to not be invoked. Simply swapping the first two lines fixes the issue.
`didViewportChange` working properly. The table performance perhaps improving via: …

[Table] Call onVisibleCellsChange on scroll (in React 16.x)

---

packages/core/src/components/forms/_numeric-input.scss
packages/docs-app/src/examples/core-examples/alertExample.tsx
packages/docs-app/src/examples/core-examples/buttonGroupExample.tsx
packages/docs-app/src/examples/datetime-examples/dateInputExample.tsx
packages/docs-app/src/examples/datetime-examples/dateRangeInputExample.tsx
packages/docs-app/src/styles/_examples.scss
packages/docs-theme/src/components/modifierTable.tsx
packages/docs-theme/src/components/typescript/enumTable.tsx
packages/docs-theme/src/components/typescript/interfaceTable.tsx
packages/docs-theme/src/styles/_content.scss
packages/docs-theme/src/tags/css.tsx
packages/labs/src/index.ts
packages/node-build-scripts/sass-compile
packages/table/src/interactions/_interactions.scss

handful of docs regressions

---

packages/core/src/common/props.ts
packages/core/src/components/button/abstractButton.tsx
packages/core/src/components/button/buttonGroup.tsx
packages/core/src/components/button/buttons.tsx
packages/core/src/components/callout/callout.tsx
packages/core/src/components/card/card.tsx
packages/core/src/components/forms/controlGroup.tsx
packages/core/src/components/forms/fileInput.tsx
packages/core/src/components/forms/inputGroup.tsx
packages/core/src/components/forms/label.tsx
packages/core/src/components/forms/textArea.tsx
packages/core/src/components/navbar/navbar.tsx
packages/core/src/components/navbar/navbarDivider.tsx
packages/core/src/components/navbar/navbarGroup.tsx
packages/core/src/components/navbar/navbarHeading.tsx
packages/core/src/components/popover/popover.tsx
packages/core/src/components/portal/portal.tsx
packages/core/test/card/cardTests.tsx
packages/datetime/test/dateRangeInputTests.tsx
packages/docs-app/src/components/clickToCopy.tsx

part of #2266. fixes #2181.
ensure `HTMLAttributes` appears last in extends list (otherwise it breaks the interface tables)

use HTMLAttributes instead of HTMLProps

---

packages/core/src/components/button/_common.scss
packages/core/src/components/forms/_file-input.scss

That shadow actually works fine locally without this change, but not on the docs website (the `::after` has no `box-shadow` rule). This PR explicitly adds a `box-shadow` rule to the `::after` without relying on the mixin

Fix file input button shadow

---

packages/core/src/components/popover/popover.tsx
packages/core/src/components/tooltip/tooltip.tsx

With the `targetElementTag` prop passed to `Popover` or `Tooltip` you can change the component from a `<div>` to a `<g>` (or anything). This makes Tooltips work inside `<svg>`. The `targetComponent` prop is passed to react-popper <Target> as the component prop.
`Popover` `targetElementTag`. This should be able to be a `string` or an `JSX.Element` see https://github.com/souporserious/react-popper/issues/107 but I was not sure how to get typescript to allow both.
NEED HELP: adding tests and fixing prop types to allow JSX.Element. As is solves issue #2250

Add Popover targetElementTag prop

---

packages/core/src/components/forms/input-group.md

Matches some other components, and generally makes the page better looking

[Docs] Move input group example near description

---

packages/core/src/components/overlay/overlay.tsx

[Overlay] add backdrop key

---

packages/core/src/components/forms/label.tsx

The current implementation of helperText on Label only allows for text, this fixes the regression and allows for React nodes again.
Adding React nodes as helperText

fixes: helperText no longer accepting React nodes

---

packages/select/src/common/index.ts
packages/select/src/common/itemListRenderer.ts
packages/select/src/common/listItemsProps.ts
packages/select/src/common/menuRenderer.ts
packages/select/src/components/omnibar/omnibar.tsx
packages/select/src/components/query-list/queryList.tsx
packages/select/src/components/select/multiSelect.tsx
packages/select/src/components/select/select-component.md
packages/select/src/components/select/select.tsx
packages/select/src/components/select/suggest.tsx
packages/select/src/index.ts
packages/select/test/index.ts
packages/select/test/queryListTests.tsx
packages/select/test/renderFilteredItemsTests.tsx
packages/select/test/selectTests.tsx

following up from @reiv's excellent work in #2080, this PR moves `menuRenderer` prop to `QueryList` and makes its behavior available to all `select` components. it also separate the `renderer` props from `itemListRenderer` props, such that `iLR` is the only one who knows about `renderItem` and the ref handler. `renderer` now receives the rendered `itemList` element, which simplifies its logic greatly.
- 🔥 `menuRenderer` &rArr; `itemListRenderer` to match other prop names (tho this prop hasn't shipped yet, so not breaking)
- 🌟 `renderFilteredItems` static function is generally useful for ...rendering filtered items.
- pull `initialContent`, `noResults`, `itemListRenderer` up to `QueryList` props.
- `QueryList` `renderer` receives rendered `itemList` ReactNode.
- add `filteredItems` to …

[select] itemListRenderer

---

packages/core/src/components/skeleton/_skeleton.scss

Make all descendants of `.pt-skeleton` invisible, including `::before` and `::after`. This will hide icons when the skeleton animation shows.
🎩 Thanks @univerio!! (#2178)

Hide nested content for .pt-skeleton

---

packages/core/src/components/context-menu/context-menu.md
packages/datetime/src/dateinput.md
packages/docs-app/src/examples/core-examples/popoverInlineExample.tsx
packages/docs-app/src/examples/datetime-examples/common/momentDate.tsx
packages/docs-app/src/examples/datetime-examples/dateInputExample.tsx
packages/docs-app/src/examples/datetime-examples/dateRangeInputExample.tsx
packages/docs-app/src/styles/_examples.scss

for #2266 
- fix alignment of date tags in datetime examples (and make them normal size)
- docs language updates to dateinput
- rename context-menu sections so they don't wrap lines
- PopoverInlineExample now has an "Open" switch as auto-opening causes auto-scroll and breaks the portal'ed popover

docs edits

---

packages/core/src/components/popover/_popover.scss
packages/core/src/components/popover/popover.md

Part of #2266 
refactor popover styles a bit. remove `.pt-popover-target` _styles_ (the element still exists) to fix input shadow clipping -- all the popper logic still works great, in all examples.

remove pt-popover-target styles to fix input shadow clipping

---

packages/core/src/components/menu/_common.scss
packages/core/src/components/menu/_menu.scss

- menu items align all children to flex-start
- fix top margin for SVG icons in large menu item
cc @reiv

[menu] fix large menu items

---

packages/docs-app/src/examples/table-examples/tableEditableExample.tsx
packages/docs-app/src/examples/table-examples/tableFormatsExample.tsx
packages/docs-app/src/examples/table-examples/tableFreezingExample.tsx
packages/docs-app/src/examples/table-examples/tableReorderableExample.tsx
packages/docs-app/src/examples/table-examples/tableSortableExample.tsx
packages/docs-app/src/styles/_sections.scss
packages/docs-theme/src/components/baseExample.tsx

- **`HACKHACK`**: `BaseExample` now defers initial render with a `requestAnimationFrame`. See the code comments for explanations (hopefully they're clear).
- This was motivated by [this](https://github.com/palantir/blueprint/issues/2266#issuecomment-375030766) rendering bug with table examples.
- 🤔 **Need to figure out why the docs site suffers from a Flash of Unstyled Content.**
- Removed the interaction bar in the table-editing example. Wasn't necessary, and fixes the incorrect-header-sizing issue that seems to only appear on the docs site:
- Fixed padding beneath table examples by using `renderExample` instead of `render`:

[Docs] Fix table bugs

---

package.json

**Release notes for changes from 2.0.0-rc.3:**
- 🌟 #2241 Run published CSS files through postcss to remove comments and run Autoprefixer.
- #2268 Copyright comments in files use `/*` comments only.
- #2269 Use `React.HTMLAttributes` instead of `React.HTMLProps` in components that support arbitrary HTML props.
- #2230 Publish the 2.0.0 upgrade script which renames most symbols.
```sh
./upgrade-blueprint-2.0.0-rename
```
- #2174 `NumericInput` supports continuous value change by holding down the button (:tophat: @reiv)
- #2231 `Tag` uses SVG `Icon` for remove button
- #2233 Fix `Toaster` layout regression (:tophat: @reiv)
- #2247 Upgrade Popper.js and react-popper for latest typings
- #2255 `blueprintPortalClassName` context key supports multiple classes
- #2256 Add `KeyCombo` `minimal` …

Prepare Release v2.0.0-rc.4

---

packages/docs-theme/src/styles/_layout.scss

[docs] add spacing around site for narrow widths

---

package.json
packages/core/package.json
packages/docs-app/src/whats-new.md
packages/test-commons/package.json

- add note about new icons package in "What's new in 2.0" section
- Prepare release v2.0.1

[2.0.1] React peer dependency 16.2 for fragments

---

packages/core/src/components/forms/_controls.scss
packages/core/src/components/forms/controls.tsx
packages/core/test/controls/controlsTests.tsx

- `Checkbox` now renders `Icon`s instead of using CSS icons for checked and indeterminate
- refactor controls.tsx to support this, and to use composition instead of inheritance

Checkbox renders SVG icons

---

packages/select/src/common/itemListRenderer.ts
packages/select/test/isotest.js

Does not f𝗂x #2336 ([whoops](https://github.com/palantir/blueprint/pull/2337#issuecomment-377514514)).
The addition of `items` to the Omnibar SSR test case might still prevent other build errors down the line.

[select] Add items prop to Omnibar isotest

---

packages/docs-theme/src/components/documentation.tsx

the `Documentation` component assumes that the scroll parent is `document.documentElement` - this is not necessarily always the case, so I added a `scrollParent` prop that lets consumers override this. By default `scrollParent` is just `document.documentElement`

Add scrollParent prop to Documentation component

---

packages/core/src/components/slider/coreSlider.tsx
packages/core/src/components/slider/handle.tsx
packages/core/src/components/slider/rangeSlider.tsx
packages/core/src/components/slider/slider.tsx
packages/core/test/slider/sliderTests.tsx

This PR changes the slider styles to use percentages instead of absolute pixel values. This should allow the slider to be freely resized without requiring a forced re-render.
This recording shows the slider being resized (`width` is being set in the inspector).

[Slider] Use percentage values in slider styles

---

config/tsconfig.base.json

This PR fixes a bug that affects `at-loader` on Windows: typings from `node_modules` aren't loaded automatically as they are in other environments, resulting in many errors during compilation, primarily when running unit tests. For example, running `yarn test` in the `core` package produces 836 errors, because the namespace for Mocha isn't loaded:
```
ERROR in [at-loader] ./test/alert/alertTests.tsx:15:1
TS2304: Cannot find name 'describe'.
ERROR in [at-loader] ./test/alert/alertTests.tsx:16:5
TS2304: Cannot find name 'it'.
...
```
(Note that `tsc` still emits correct code, but the type-checking process fails).
The fix is to explicitly instruct `tsc` to look in `node_modules/@types` for type declarations, which is something it [should already be doing by …

[dev] Fix missing types from node_modules with at-loader on Windows

---

packages/core/package.json
packages/core/src/components/button/_common.scss
packages/core/src/components/forms/_common.scss
packages/core/src/components/menu/_menu.scss
packages/docs-app/package.json
packages/table-dev-app/package.json
yarn.lock

Split off from #2357.
[Changelog](https://github.com/necolas/normalize.css/blob/master/CHANGELOG.md#800-february-2-2018):
> Remove support for older browsers Android 4, lte IE 9, lte Safari 7.
> Don't remove search input cancel button in Chrome/Safari.
> Form inputs inherit font-family.
> Fix text decoration in Safari 8+.
This PR also removes some redundant `font-family: inherit` rules that are already handled by normalize.css.

Upgrade to normalize.css 8.0.0

---

packages/docs-theme/src/components/scrollbar.ts

Always provide `index` argument:
https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule

fix docs site on Firefox ESR

---

packages/core/src/components/popover/popover.tsx

This PR makes two changes to the way `Popover` handles focus events.
1. Use [`FocusEvent.relatedTarget`](https://developer.mozilla.org/en-US/docs/Web/API/FocusEvent)¹ instead of wrapping `document.activeElement` in a timeout to accomplish the same.
2. Check if the target gained focus when it was already previously focused but the *page itself* lost focus (e.g. due to tabbing out) -- in this case the popover won't open again.
___________
<sup>[1] MDN says this is "experimental technology", but it seems to be available in all browsers save for IE < 9.</sup>

[Popover] Improved focus event handling

---

packages/core/src/components/portal/portal.tsx
packages/core/test/portal/portalTests.tsx

invoke `Portal` `onChildrenMount` _after_ children mount.
this was super easy to verify fixed with the added unit test! failed hard at first, now it'll be green.

invoke Portal onChildrenMount _after_ children mount

---

packages/core/src/components/context-menu/contextMenu.tsx
packages/core/src/components/context-menu/contextMenuTarget.tsx
packages/core/src/components/overlay/overlay.tsx
packages/core/src/components/popover/popover.tsx
packages/core/test/context-menu/contextMenuTests.tsx
packages/core/test/overlay/overlayTests.tsx
packages/core/test/popover/popoverTests.tsx

several intertwined changes here with some very tricky associated logic. i added unit tests!
- change `ContextMenu` modifiers such that it won't leave the viewport (instead of window; fixes #803)
- `Overlay` `didClose` and `Popover` `popoverDidClose` lifecycle methods!
- now possible with `react-transition-group` `onExited` method (did not exist in 1.0)
- remove `ContextMenu` element when the menu closes (using lifecycle method above; fixes #2131)
- fix `Overlay` outside click logic #1188

ContextMenu fixes & Overlay didClose

---

package.json
packages/core/src/components/card/card.md
packages/core/src/components/card/card.tsx

🎆 **Highlights:** customize CSS namespace, percentage-based `Slider`, Blueprint TSLint rules!
- ⭐️ #2325 Support for customizing the CSS class namespace `pt-`
- in the upcoming 3.0 release, we will change this namespace to `bp3-` to avoid style conflicts with previous versions of Blueprint on the same page
- added a new docs page about [Classes]() to encourage use of the forward-compatible `Classes` constants
- #2328 Fix Webpack externals so `*.bundle.js` files are as light as possible
- #2367 Fix TypeScript bundling with `at-loader` on Windows (🎩 @reiv 
- ⭐️ #2341 `Slider` now uses percentages instead of pixels for layout, resulting in effortless resizes! (🎩 @reiv)
- 📦 #2362 Upgrade to Normalize.css 8.0.0 to fix `font-family` issues on some components (🎩 @reiv)
- #2399 Added `Overlay` …

Prepare release v2.2.0

---

packages/core/src/components/editable-text/_editable-text.scss
packages/core/src/components/editable-text/editableText.tsx
packages/docs-app/src/examples/core-examples/editableTextExample.tsx

Changed the `Classes` constants in #2325 but didn't update CSS

fix editable text classes

---

packages/core/src/components/forms/select-forms.md
packages/core/src/components/tag-input/tag-input.md
packages/core/src/components/text/text.md
packages/core/src/components/tree/tree.md
packages/docs-app/src/components/colorPalettes.tsx
packages/docs-app/src/examples/core-examples/buttonGroupExample.tsx
packages/docs-app/src/examples/core-examples/buttonGroupPopoverExample.tsx
packages/docs-app/src/examples/datetime-examples/dateTimePickerExample.tsx
packages/docs-app/src/examples/select-examples/multiSelectExample.tsx
packages/docs-app/src/styles/_colors.scss
packages/select/src/components/select/multiSelect.tsx

- 🌟  docs Color Palettes replace variable name with 'click to copy' text 
- move Text and Tree examples to top
- HTML Selects and Tag Inputs link to select package
- fix some missing keys
- `DateTimePicker` example is controlled so it shows initial date
- fix `MultiSelectExample` initial content

docs regressions

---

packages/core/test/tag-input/tagInputTests.tsx
packages/docs-app/src/examples/core-examples/popoverExample.tsx
packages/docs-app/src/examples/core-examples/tagInputExample.tsx
packages/table/test/tableTests.tsx
packages/tslint-config/index.js
packages/tslint-config/package.json
tslint.json
yarn.lock

- tslint becomes peer dependency
- reasonable defaults in shared config, move TODOs to repo config
- add missing keys (due to enabling `jsx-key` rule)

tslint config updates

---

packages/core/src/components/editable-text/editableText.tsx
packages/core/test/editable-text/editableTextTests.tsx

Make the `onEdit` event pass the initial value of Editable text component before it gets modified.
I've made the changes that I see they will implement the needed feature in #2422, so I'm not sure if there're other changes that need to be made.

#2422 Add value parameter to onEdit callback

---

packages/core/src/common/classes.ts
packages/core/src/common/utils.ts
packages/core/src/components/non-ideal-state/_non-ideal-state.scss
packages/core/src/components/non-ideal-state/nonIdealState.tsx
packages/core/src/components/popover/popover.tsx
packages/core/test/non-ideal-state/nonIdealStateTests.tsx
packages/docs-app/src/components/icons.tsx
packages/docs-app/src/examples/core-examples/nonIdealStateExample.tsx

- :fire: `visual` &rArr; `icon` to match other components
- :fire: replace most of the `NIS` classes constants with flex layout and rhythm
- use `Classes.HEADING` on the `<h4>`.
- use `pt-flex-container()` to ensure margin between all children and centering.
- move `ensureElement()` from `Popover` to `common/utils`

refactor NonIdealState: fewer classes, simple styles

---

packages/select/src/components/select/multiSelect.tsx

This fixes the docs for `MultiSelect`'s `resetOnSelect` prop.  The default is documented as being `true`, but it is actually `false`.  Whether the default is intended to be true, changing the actual default value would be a potential functionality break.

Fix default value doc for resetOnSelect

---

packages/docs-theme/src/styles/_layout.scss
packages/docs-theme/src/styles/_variables.scss

not entirely sure why this fixes it (or why the former styles broke it) but seems like code blocks are now always as wide as possible.

fix docs width due to code blocks

---

packages/core/src/_reset.scss
packages/core/src/_typography.scss
packages/core/src/blueprint.scss
packages/core/src/common/_variables.scss
packages/core/src/common/classes.ts
packages/icons/src/_icons.scss

changing the CSS namespace prevents conflicts between Blueprint 1.x and 3.x elements.
add `_reset.scss` file for limited global resets: `body`, `p`, `strong`, `small`
TODO

change CSS namespace to `bp3`

---

scripts/revert-lerna-publish

sometimes (often) you botch the `lerna publish`. this script makes short work of resetting the repo state so you can try again.

revert-lerna-publish script to delete tags and commit

---

.circleci/config.yml

inspiration: https://circleci.com/blog/circleci-hacks-reuse-yaml-in-your-circleci-config-with-yaml/
also now `deploy-npm` job requires successful lint and tests.

use YAML anchors to clean up circle config

---

packages/core/scripts/upgrade-blueprint-2.0.0-rename

Previously, our checks for removed props, such as `warn submenuViewportMargins REMOVED`, worked incorrectly because they didn't provide a third argument to warn. This PR fixes that in two ways: `warn` now works as expected if it only has two arguments, and removed props now use the `warnProp` function which respects the `$PREFIX` variable.
This PR also slightly tweaks the error message shown for these warnings.

Fix upgrade script's treatment of removed props

---

packages/core/src/components/spinner/_common.scss

Current is too large compared to large, and too small compared to small
Before:
After:

[Spinner] Slightly thinner stroke

---

packages/core/src/components/button/_button.scss

ensure no padding on empty buttons (CSS icons only support)

[button] fix large CSS-icon-only button width

---

packages/docs-app/src/examples/core-examples/alertExample.tsx
packages/docs-app/src/examples/core-examples/buttonGroupExample.tsx
packages/docs-app/src/examples/core-examples/buttonGroupPopoverExample.tsx
packages/docs-app/src/examples/core-examples/buttonsExample.tsx
packages/docs-app/src/examples/core-examples/calloutExample.tsx
packages/docs-app/src/examples/table-examples/cellLoadingExample.tsx
packages/docs-app/src/examples/table-examples/columnLoadingExample.tsx
packages/docs-app/src/examples/table-examples/tableFormatsExample.tsx
packages/docs-app/src/tags/reactExamples.ts
packages/docs-theme/src/components/example.tsx
packages/docs-theme/src/index.ts
packages/docs-theme/src/tags/css.tsx
packages/docs-theme/src/tags/reactExample.tsx

- new `Example` component will eventually replace `BaseExample` as _the way_ to author docs examples.
- composition instead of inheritance is just so much more legible and less magical! 
- examples using `Example` simply implement `render()` like any other React component and can define their options as a single fragment. this is much friendlier to newcomers than the previous situation where we extended some inscrutable `BaseExample<S>` class and implemented `renderExample()` and `renderOptions()`.
- `BaseExample` still exists -- this PR is purely additive. we'll remove it once all examples are converted.
- refactor a handful of examples to demonstrate the new API.
- i don't want to do _all of them_ in this PR as it'll be overwhelming and its very rote--we can easily parallelize after …

[docs] new Example component makes more legible examples

---

packages/docs-app/src/examples/datetime-examples/dateRangePickerExample.tsx
packages/docs-app/src/examples/table-examples/cellLoadingExample.tsx
packages/docs-app/src/examples/table-examples/columnLoadingExample.tsx
packages/docs-app/src/examples/table-examples/tableDollarExample.tsx
packages/docs-app/src/examples/table-examples/tableEditableExample.tsx
packages/docs-app/src/examples/table-examples/tableFormatsExample.tsx
packages/docs-app/src/examples/table-examples/tableFreezingExample.tsx
packages/docs-app/src/examples/table-examples/tableLoadingExample.tsx
packages/docs-app/src/examples/table-examples/tableReorderableExample.tsx
packages/docs-app/src/examples/table-examples/tableSortableExample.tsx
packages/docs-app/src/styles/_examples.scss
packages/docs-theme/src/components/example.tsx
packages/docs-theme/src/styles/_examples.scss

`Example` `showOptionsBelowExample` changes layout so options are in a row below the example.
Refactor `DRP` example (see screenshot) and all Table examples to use new API.

[docs] Example prop to show options below example

---

packages/core/package.json
packages/datetime/package.json
packages/docs-app/src/getting-started.md
packages/docs-theme/package.json
packages/icons/package.json
packages/labs/package.json
packages/landing-app/package.json
packages/select/package.json
packages/table-dev-app/package.json
packages/table/package.json
packages/timezone/package.json

- it's been a peer dependency forever but I don't think this is correct, and is often a source of upgrade pain to users
- most libraries declare react and react-dom as peer deps (r-t-g does this too) so it seems reasonable for that to be the minimal set of peer deps
- r-t-g is not exposed in our APIs so it can be a normal dependency
- maaaybe `transitionName/Duration` but those use basic types so not really "exposing"
- also the official recommendation: https://github.com/reactjs/react-transition-group/issues/32

📦 move react-transition-group to regular dependency

---

packages/docs-data/package.json
packages/docs-theme/package.json
packages/docs-theme/src/components/documentation.tsx
yarn.lock

- upgrade to latest documentalist 1.3.2 for `const/type` support and `index` param in `linkify()` util.
- this will unblock #2484
- include `index` in `renderType` to avoid duplicate keys

📦 upgrade documentalist

---

packages/core/scripts/upgrade-blueprint-2.0.0-rename
packages/core/scripts/upgrade-blueprint-3.0.0-rename

**Changes to 2.0 script**:
* rename `IconClasses` when used in a NIS `visual`
* only warn about remaining uses of `IconClasses`, trying to replace it with invalid TS just ends badly
**New 3.0 script**:
* Same functions and help docs as 2.0. (Sidenote: I think we should've just done these in node.js instead of bash for more cross-platform compat, but too late now)
* Handles NIS `visual` -> `icon`
* Renames classes to `Classes.HEADING`

Add 3.0 upgrade script; improve 2.0 script

---

packages/core/src/common/errors.ts
packages/core/src/components/toast/toast.md
packages/core/src/components/toast/toaster.tsx
packages/core/test/toast/toasterTests.ts

to avoid breaking change in React 16.
https://reactjs.org/blog/2017/09/26/react-v16.0.html#breaking-changes

Toaster.create throws error if used within lifecycle method

---

packages/core/src/common/errors.ts
packages/core/src/components/toast/toast.md
packages/core/src/components/toast/toaster.tsx

to avoid breaking change in React 16.
https://reactjs.org/blog/2017/09/26/react-v16.0.html#breaking-changes

[1.x] Toaster.create errors if ReactDOM.render returns null

---

packages/core/src/components/table/_table.scss

- nicer hover/active effects with `.pt-interactive`
- move some colors to the Sass placeholder so they work in dark theme
before:
after:

[HTML Table] Nicer interactive styles (hover + active)

---

package.json
packages/core/package.json
packages/docs-theme/package.json
packages/docs-theme/src/components/baseExample.tsx

already published from `next` branch so it'll appear as the `@next` npm dist-tag.
`@blueprintjs/core@3.0.0-beta.1`
`@blueprintjs/docs-theme@3.0.0-beta.1`

3.0.0-beta.1

---

packages/core/src/common/props.ts
packages/core/test/common/propsTests.ts

Add `"round"` to the list of invalid html props, this will prevent the `round` prop being passed through to the the HTML Input element [here](https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/forms/inputGroup.tsx#L92).
I've incorporated this prop into the existing tests for this utility function, but not for the InputGroup component itself.
Round does not appear to be a valid html attribute so adding it to this list should be fine
* https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes

[Common] Adding 'round' to the INVALID_PROPS list

---

packages/core/src/components/button/_button.scss

[Core] Buttons are directly children of align-(left|right) parents

---

packages/docs-app/src/components/blueprintDocs.tsx
packages/docs-data/compile-docs-data

follow up from #2545
versions selector on 1.x site now only links to latest, as the other versions do not matter here.

[1.x] docs version selector links to latest

---

packages/docs-app/src/components/navHeader.tsx
packages/docs-data/compile-docs-data

follow up from #2545
versions selector on 2.x site now only links to latest, as the other versions do not matter here.

[2.x] docs version selector links to latest

---

packages/core/src/components/icon/_icon.scss
packages/docs-app/src/examples/core-examples/iconExample.tsx

also added a intent select in the icon example, so it's easy to test out

[Core] support dark intent colors on icons

---

packages/core/src/components/portal/portal.md

[Docs] Portal typo

---

packages/core/src/components/button/_common.scss

could argue this is a regression. we used to have this property in 1.x: https://github.com/palantir/blueprint/blob/release/1.x/packages/core/src/components/button/_common.scss#L102
makes sense to set it for buttons that are not in flex containers.

vertical-align on buttons

---

packages/core/src/components/context-menu/contextMenuTarget.tsx
packages/core/src/components/hotkeys/hotkeys.tsx
packages/core/src/components/hotkeys/hotkeysTarget.tsx

```
lerna ERR! ERROR in [at-loader] ../../node_modules/@blueprintjs/core/dist/esm/components/hotkeys/hotkeysTarget.d.ts:4:18
lerna ERR!     TS2320: Interface 'IHotkeysTarget' cannot simultaneously extend types 'Component<any, any, any>' and 'ComponentLifecycle<any, any, never>'.
```

use default type params for HotkeysTarget & CMTarget

---

packages/table/src/common/grid.ts
packages/table/src/table.tsx
packages/table/test/tableTests.tsx

Tables are now horizontally scrollable when there are no rows of data but real columns extend beyond the container width.

Horizontal scrolling is no longer disabled when columns filling width with no rows of data

---

packages/core/src/components/forms/_common.scss
packages/core/src/components/forms/_controls.scss
packages/core/src/components/forms/_form-group.scss
packages/core/src/components/forms/form-group.md
packages/core/src/components/forms/formGroup.tsx
packages/core/test/forms/formGroupTests.tsx
packages/docs-app/src/examples/core-examples/formGroupExample.tsx
packages/docs-app/src/examples/core-examples/index.ts
packages/docs-app/src/styles/_examples.scss

- 🔥 `requiredLabel` &rArr; `labelInfo`, remove "required" feature
- refactor docs and add React example

[core] better FormGroup

---

packages/core/src/components/menu/menu.md
packages/core/src/components/menu/menu.tsx

Not related to an issue.
Added static properties to the `Menu` component to allow easier importing of it's child components `MenuDivider` and `MenuItem`. Extending an **existing pattern** found on the `NavBar` component.
Allow imports such as: 
```
import { ..., Menu, MenuDivider, MenuItem, ... } from '@blueprintjs/core';
```
to be reduced to:
```
import { ..., Menu, ... } from '@blueprintjs/core';
``` 
Where usage of `MenuDivider` would be changed to `Menu.Divider` etc...
I've also aligned the reference to this pattern on the `Menu` component's documentation page to match the `NavBar` documentation.

[Menu] Add Menu child components as static properties of the Menu component

---

packages/datetime/src/dateInput.tsx
packages/datetime/src/datePicker.tsx
packages/datetime/test/dateInputTests.tsx
packages/datetime/test/datePickerTests.tsx

* Add `isUserChange` support for DateInput to be able to distinguish month/year changes from real date selections.
* Change the name of the second parameter of the onChange handler in `IDatePickerProps` to `isUserChange`, so all supported components use the same argument name.

[DateTime] Add `isUserChange` support for DateInput

---

packages/core/src/components/menu/menuItem.tsx
packages/datetime/src/dateInput.tsx
packages/datetime/src/dateRangeInput.tsx
packages/datetime/test/dateInputTests.tsx
packages/datetime/test/dateRangeInputTests.tsx

- removed default `usePortal={false}` in `MenuItem`, `DateInput`, `DateRangeInput`

[Core/Datetime] remove usePortal={false} where not documented

---

packages/core/src/components/tag-input/tagInput.tsx
packages/core/test/tag-input/tagInputTests.tsx

Added a default empty string value for the `inputValue` property, in order to correct the warning mentioned in the issue.

defined a default empty value for tagInput's inputValue

---

packages/docs-app/src/examples/select-examples/films.tsx
packages/docs-app/src/examples/select-examples/selectExample.tsx
packages/select/src/common/itemListRenderer.ts
packages/select/src/common/listItemsProps.ts
packages/select/src/components/query-list/queryList.tsx

- new `itemDisabled: keyof T | (T => boolean)` prop allows disabling items in the list!
- provide callback or prop name shorthand (a la lodash)
- no tests yet as the QueryList suite just has placeholders for relevant tests

[Select] new itemDisabled prop

---

packages/core/src/components/slider/handle.tsx
packages/core/src/components/slider/handleProps.tsx
packages/core/src/components/slider/multiSlider.tsx
packages/core/src/components/slider/slider.tsx
packages/core/src/components/slider/sliders.md
packages/docs-app/src/examples/core-examples/multiSliderExample.tsx

Several fixes to MultiSlider before final merge

MultiSlider fixes

---

packages/tslint-config/src/rules/blueprintClassesConstantsRule.ts
packages/tslint-config/test/rules/blueprint-classes-constants/true/test.tsx.lint

- update the regex to only detect `pt-` as a prefix: not preceded by letter or dash
cc @styu

blueprint-classes-constants rule only detects leading pt- *prefix*

---

packages/core/src/components/alert/alert.tsx
packages/core/src/components/context-menu/contextMenu.tsx
packages/core/src/components/overlay/overlay.tsx
packages/core/src/components/popover/popover.tsx
packages/core/src/components/tooltip/tooltip.tsx
packages/core/test/alert/alertTests.tsx
packages/core/test/dialog/dialogTests.tsx
packages/core/test/overlay/overlayTests.tsx
packages/core/test/popover/popoverTests.tsx
packages/core/test/tooltip/tooltipTests.tsx
packages/datetime/test/dateInputTests.tsx
packages/datetime/test/dateRangeInputTests.tsx
packages/docs-app/src/examples/core-examples/popoverExample.tsx
packages/docs-app/src/examples/datetime-examples/dateRangeInputExample.tsx
packages/select/src/components/omnibar/omnibar.tsx
packages/select/src/components/select/multiSelect.tsx
packages/select/src/components/select/select.tsx
packages/select/src/components/select/suggest.tsx
packages/select/test/selectTests.tsx
packages/select/test/suggestTests.tsx
packages/table/src/headers/columnHeaderCell.tsx

- `IOverlayLifecycleProps` defines `onOpening`, `onOpened`, `onClosing`, `onClosed`
- 4 methods passed directly to CSSTransition to leverage their reliable code
- 🔥this results in slightly different semantics, mainly that the popover content is always mounted in the DOM during any of these lifecycles.
- previously, in `onOpening` and `onClosed` the content was not in the DOM (before entering or after exiting, respectively)
- 🔥 replace `Overlay` `didOpen`, `didClose` props with those above
- 🔥 replace `Popover` `popoverDid/Will*` props with those above
> slightly different semantics, mainly that the popover content is always mounted in the DOM during any of these lifecycles.
could this be an issue? @invliD thoughts?

[Overlay] better lifecycle props for all overlay components

---

packages/core/src/components/tag-input/tagInput.tsx
packages/core/test/tag-input/tagInputTests.tsx
packages/docs-app/src/examples/core-examples/tagInputExample.tsx

- fix: `TagInput` `addOnBlur` fires when leaving container, not just blurring text input
- new: `TagInput` `addOnPaste` (default true) invokes `onAdd` with clipboard contents
cc @acrigler

[TagInput] paste support + addOnPaste prop

---

packages/core/src/_typography.scss

so it'll adapt to container instead of always being 12px

use smaller (relative) font-size for `code`

---

packages/docs-app/src/components/blueprintDocs.tsx
packages/docs-theme/src/components/documentation.tsx
packages/docs-theme/src/components/navigator.tsx

- new `Documentation` `navigatorExclude` and `Navigator` `itemExclude` props to support excluding items from the navigator results.
can no longer navigate to "Components" page or "Overlays" section.

[docs] Navigator supports excluding items

---

packages/core/src/components/button/_button-group.scss
packages/core/src/components/button/_button.scss
packages/core/src/components/button/button-group.md
packages/core/src/components/button/button.md
packages/docs-app/src/examples/core-examples/buttonGroupExample.tsx
packages/docs-app/src/examples/core-examples/buttonGroupPopoverExample.tsx

(separate PR targeting `docs-rewrite` branch because this one's kinda big)
- fix button group alignment support (#2358 introduced regression)
- fix vertical fill: expands vertically!
- merge CSS examples into one
- move CSS sub-sections up and make them about React usage

[docs] improve button-group docs

---

packages/datetime/src/dateinput.md
packages/datetime/src/datepicker.md
packages/datetime/src/daterangeinput.md
packages/datetime/src/daterangepicker.md
packages/datetime/src/datetimepicker.md
packages/datetime/src/index.md
packages/datetime/src/timepicker.md
packages/timezone/src/components/timezone-picker/timezone-picker.md
packages/timezone/src/components/timezone-picker/timezonePicker.tsx

fixes #2542 
refactor all datetime component docs a la #2574 (which this PR is targeting).

[docs] refactor datetime docs to focus on React usage

---

config/tsconfig.base.json
packages/core/src/accessibility/focusStyleManager.ts
packages/docs-app/src/tsconfig.json
packages/karma-build-scripts/createKarmaConfig.js
packages/karma-build-scripts/package.json
packages/landing-app/src/tsconfig.json
yarn.lock

- enable typescript sourcemaps in tsconfig, so each package will now include `*.{d.ts,js,js.map}` for each original TS file.
👍 👍 👍

TS sourcemaps & fix code coverage reports

---

packages/docs-app/src/components/blueprintDocs.tsx
packages/docs-app/src/components/navHeader.tsx
packages/docs-app/src/index.tsx
packages/docs-data/compile-docs-data.js
packages/docs-data/package.json
packages/docs-data/src/index.d.ts
packages/docs-data/src/index.js
packages/docs-theme/package.json
packages/docs-theme/src/common/context.ts
packages/docs-theme/src/components/documentation.tsx
packages/docs-theme/src/components/page.tsx
packages/docs-theme/src/styles/_layout.scss
packages/docs-theme/src/tags/defaults.ts
yarn.lock

- upgrade to documentalist 1.4.0 and use new `NpmPlugin` so there's only one docs data file (versions and releases now live inside docs.json)
- add `Documentation` `renderPageActions` prop to customize upper-right actions
- because docs-theme doesn't know about our github URL
- add "Edit this page" link in these actions

upgrade documentalist, add "edit this page" links

---

packages/core/scripts/upgrade-blueprint-3.0.0-rename.sh
packages/core/src/components/context-menu/contextMenu.tsx
packages/core/src/components/index.ts
packages/core/src/components/popover/popover.tsx
packages/core/src/components/popover/popoverProps.tsx
packages/core/src/components/popover/popoverSharedProps.tsx
packages/core/src/components/tooltip/tooltip.tsx
packages/core/test/popover/popoverTests.tsx
packages/core/test/tooltip/tooltipTests.tsx

pulling out the renames from #2609 and unifying the props interfaces between Popover and Tooltip.
- `IPopoverSharedProps` for the common Popover/Tooltip bits
- 🔥 `rootElementTag` => `wrapperTagName`
- 🔥 `targetElementTag` => `targetTagName`

IPopoverSharedProps used by Popover and Tooltip, some prop renames

---

packages/core/src/components/non-ideal-state/_non-ideal-state.scss

`auto` horizontal margins on `NonIdealState`s [were removed](https://github.com/palantir/blueprint/pull/2489/files#diff-27d14069409a15d17d8c55b7c834997dL26) between the `3.0.0-beta.0` and `3.0.0-beta.1` releases, causing visual breaks for users which were relying on that to do centering. This PR brings that margin back.

[Core] Add margin back to NonIdealState component

---

packages/core/src/components/overflow-list/overflowList.tsx

Previously, changing the `collapseFrom` prop of the `OverflowList` would not recalculate what's visible, leading to weird behavior where the overflow just moves from one side to the other, which reorders the items instead of keeping the order and overflowing the now correct items.

[OverflowList] Recalculate visible items when modifying collapseFrom

---

packages/docs-app/package.json
packages/docs-app/src/components/docsIcon.tsx
yarn.lock

- Add dependency `downloadjs@^1.4.7` for easy plug-and-play downloads.
- Add ability to one-click download Blueprint icons from the right-click context menu in the docs.
- Functionality: I've tested across multiple browsers and versions, but if you want to be extra safe you can test yourself.

Add one-click download for icons

---

packages/core/package.json

merging `next` into `develop`
```
- @blueprintjs/core@3.0.0-rc.1
```

Publish 3.0.0-rc.1

---

packages/core/src/components/forms/textArea.tsx

I often times find it necessary to interact with the raw DOM element of text areas in particular for imperative operations such as selection, cursor position and focus management. core/InputGroup accomplishes this with an "inputRef" prop that effectively exposes the "ref" prop of the underlying ReactElement. I decided to maintain consistency with core/InputGroup etc. by using the prop name "inputRef", although this is a slight misnomer.

core/TextArea: Accept inputRef prop

---

packages/core/src/components/forms/numericInput.tsx

Fixes #1490: Expose inputRef prop on NumericInput component
Implement similar behavior/interface that exists in InputGroup, TextArea, Checkbox, etc.

Fix #1490: core/NumericInput inputRef

---

README.md
package.json

[**3.0 Changelog and migration guide ▸**](https://github.com/palantir/blueprint/wiki/3.0-Changelog)
Blueprint 3.0 supports multiple major versions of Blueprint on the same page through removing global styles and deconflicting selectors by changing the namespace. It also restores support for React 15 in most packages.

update readme for 3.0, yarn dev:all -> dev

---

packages/docs-app/src/examples/select-examples/omnibarExample.tsx
packages/select/src/components/omnibar/omnibar.tsx

- remove errant `inputProps.onBlur` from example which broke selection as it would close popover whenever focus leaves input (like mousing down on an item)
- `Omnibar` now always invokes `onItemSelect` (remove empty query check)

[Omnibar] fix example

---

packages/core/src/_typography.scss
packages/core/src/components/popover/popoverArrow.tsx
packages/docs-theme/src/components/documentation.tsx

- `a > code` looks like a link
- fix `PopoverArrow` NaN warnings (mostly in tests)
- `Documentation` navigates to default page when hash is empty

three little fixes

---

packages/docs-app/src/components/navHeader.tsx
packages/docs-app/src/index.tsx

- `useNextVersion={false}` now that 3.0.0 is published `@latest`
- exclude v0 release from version dropdown

[docs] fixes for version selection

---

package.json
packages/core/package.json
packages/core/src/components/html-select/htmlSelect.tsx
packages/datetime/package.json
packages/docs-theme/package.json
packages/icons/package.json
packages/labs/package.json
packages/node-build-scripts/package.json
packages/select/package.json
packages/table/package.json
packages/test-commons/package.json
packages/timezone/package.json
yarn.lock

- restores editing support in VSCode (I was having problems with TS2.7.2 not re-compiling on changes).
- no changes to .d.ts files so this is not breaking (verified locally by diffing .d.ts files agains those in 3.0.0 packages)

upgrade to TypeScript 2.8

---

packages/core/scripts/upgrade-blueprint-3.0.0-rename.sh
packages/core/src/common/errors.ts
packages/core/src/components/spinner/spinner.md
packages/core/src/components/spinner/spinner.tsx
packages/core/test/spinner/spinnerTests.tsx

- 👍  this actually un-breaks a 3.0 API break: `<Spinner className={Classes.SMALL} />` now works as it used to!
- remove the replacer from the upgrade script as it's no longer breaking

[Spinner] Classes.LARGE/SMALL determine default size

---

packages/core/src/components/icon/icon.tsx
packages/core/test/icon/iconTests.tsx

try hovering an icon, especially one in a button. no browser tooltip!

[Icon] use desc element for title (no browser tootltip, still a11y)

---

packages/core/src/components/tree/tree.tsx
packages/core/src/components/tree/treeNode.tsx

- Fix support for generic types in Tree component
addresses https://github.com/palantir/blueprint/issues/2627

Fix support for generic types in Tree component

---

packages/core/src/components/button/_button-group.scss
packages/core/src/components/context-menu/contextMenu.tsx
packages/core/src/components/html-select/htmlSelect.tsx
packages/core/src/components/menu/menuItem.tsx
packages/docs-app/src/examples/core-examples/toastExample.tsx

- fix vertical button groups
- `ContextMenu` fix double-right-click behavior so it moves the menu
- `MenuItem` bring back `usePortal={false}` (removed unsafely in #2539)

fix small regressions

---

packages/core/src/common/classes.ts

Not related to an open issue (that I could find). Noticed in use that the `bp3-text-small` class wasn't available as an export of the `Classes` module. Checked the [typography documentation page](http://blueprintjs.com/docs/#core/typography) and noticed that a couple more weren't available so I've added those too.
Added exports to the `Classes` module for the following text CSS classes:
- `bp3-text-small`
- `bp3-text-disabled`
- `bp3-rtl`

[Core] Added missing text css classnames to Classes module

---

packages/tslint-config/src/rules/blueprintClassesConstantsRule.ts
packages/tslint-config/test/rules/blueprint-classes-constants/true/test.tsx.lint

- ignore angular directives `<pt-popover>`
- support template strings

[tslint] classes-constants rule fixes

---

packages/docs-app/src/getting-started.md

I copy pasted the unpkg css lines for blueprintjs while working with the 3.x release then finally noticed that the referenced css was the 2.x line. Not sure if the code snippet below this needs it.

Bump unpkg example to 3.0.0

---

packages/docs-app/README.md

Fix the broken localhost link to the docs app in the docs app readme

Fix path to docs app

---

packages/core/src/components/forms/controls.tsx

- add `tagName` prop so you can have a checkbox not wrapped in a `<label>`, which causes event problems when you listen for `click` on a parent element. 
- obnoxious DOM side effect: pretty sure this is because clicking a label around an input also clicks the input and ends up triggering a whole bunch of events. 
- set `tagName="div"` to render a beautiful checkbox that can be clicked directly (but not the text)

[Checkbox] add tagName prop

---

packages/core/src/common/props.ts
packages/core/src/components/forms/radioGroup.tsx
packages/core/src/components/html-select/htmlSelect.tsx
packages/core/test/controls/radioGroupTests.tsx
packages/docs-app/src/examples/core-examples/numericInputBasicExample.tsx

- I added `IHTMLOptionProps` in #2605 without realizing we already had `IOptionProps` used in RadioGroup. oops!
- this PR removes `IHTMLOptionProps` in favor of `IOptionProps` which is maybe a tiny API break but i doubt anyone actually uses the type
- `RadioGroup` `options` prop supports optional `label`

[core] use IOptionProps instead of IHTMLOptionProps

---

packages/docs-theme/src/components/example.tsx

allow disabling `forceUpdate` behavior in `Example` frame as it interferes with non-React libraries.

[docs-theme] add Example forceUpdate prop to disable that behavior

---

packages/core/package.json
packages/core/scripts/sass-inline-svg.js
packages/core/src/components/forms/_controls.scss
packages/core/src/components/forms/controls.tsx
packages/core/test/controls/controlsTests.tsx
yarn.lock

- Checkbox suffered greatly in the switch to SVG icons because its implementation no longer relied purely on CSS: React state was necessary to ensure the correct icon was rendered at the correct time.
- This introduced a bunch of subtle bugs where the DOM and the state could get out of sync (due to an incorrect implementation of un/controlled state).
- This PR brings us back to the CSS-only world by _embedding the SVG images_ for `small-tick` and `small-minus` in the checkbox CSS directly.
- This is functionally identical to the oild font usage `content: $pt-icon-small-tick` (in fact, that's the line that was replaced) so we no longer even need to support the font fallback!
- As a result, I was able to remove from the React component the `indicator` logic _and_ the `checked` state (which …

[Checkbox] inline SVG background-image for icon

---

packages/node-build-scripts/css-dist.sh

enable `--map` flag to postcss to externalize sourcemap. 
Sass compilation already generates  a `.css.map` file but without this flag, postcss would encode and inline the sourcemap, ballooning blueprint.css from 293K to 396K during a supposed production step!

🔧 external source maps in css-dist

---

packages/core/src/components/forms/_controls.scss
packages/docs-app/src/examples/core-examples/checkboxExample.tsx

- Checkbox alignment has always been a few pixels off from normal text, because the indicator relied heavily on line-height for centering (classic 2014).
- In this PR, control indicator is now an inline element and does not rely on line-height for positioning.
- Also refactor away from a bad `@extend` that generated very bloated CSS.
height: 16px. padding/position.
height: 18px (standard line-height). centered: perfect.

[Checkbox] indicator is inline element

---

packages/core/src/components/forms/_controls.scss

- **before** #2716 removed the padding-left on checkbox which caused checkboxes with lots of content to use default flow layout: 
- **after** this PR brings back the padding/margin combo _as a mixin_ so it's much less repetitive:

[Checkbox] revert to padding/margin

---

packages/core/src/components/forms/_controls.scss

- as much shared indicator style as possible
- indicator uses `1em` for size so all we have to do for large is bump the `font-size`
- switch uses other values to achieve its oblong appearance
- Radio indicator uses radial-gradient for the white dot
- Switch `indicator-colors()` mixin for legibility & remove unused variables

[Checkbox] refactor indicators style

---

packages/datetime/src/dateFormat.tsx

As per https://github.com/palantir/blueprint/issues/2612 - Remove null from the signature of the `formatDate` function.
~~This is a non-backward compatible API change.~~
N/A

Remove null from signature of formatDate

---

packages/webpack-build-scripts/webpack.config.base.js

- put assets in `assets/` directory so they don't pollute the root directory
- preserve original filename (much shorter than hash) but include hash as query param for cache busting

[webpack-build-scripts] put assets in assets/ dir, preserve filenames

---

packages/core/src/components/panel-stack/panelProps.ts
packages/core/src/components/panel-stack/panelStack.tsx
packages/core/src/components/panel-stack/panelView.tsx
packages/core/test/panel-stack/panelStackTests.tsx
packages/docs-app/src/examples/core-examples/panelStackExample.tsx

- `openPanel` accepts IPanel instead of three args.
-this is more future-proof as we can update the one interface in non-breaking ways and see benefits everywhere, whereas changing the signature of the function would be breaking.
- `PanelView` `onClose/Open` props cleans up the `PanelStack` logic
cc @kadhirvelm

[PanelStack] use IPanel in openPanel() public API

---

packages/core/src/components/forms/_control-group.scss

Currently when a ControlGroup only has a single child component the :last-child border rules are applied.
```
<ControlGroup>
<Button icon="filter">Filter</Button>
</ControlGroup>
```
__Before:__
__After:__

[ControlGroup] Give border radius to :only-child

---

packages/core/src/components/forms/_control-group.scss

Adding `border-radius: inherit` to the popover-target and popover-wrapper will pass it on to whatever component is wrapped (eg. button)
__Before:__
__After:__

[ControlGroup] Add border-radius inheritance support to popovers

---

packages/core/scripts/sass-inline-svg.js
packages/core/src/components/breadcrumbs/_breadcrumbs.scss
packages/core/src/components/forms/_controls.scss

- inline SVG icons in breadcrumbs css, like we did for checkboxes in #2709

[Breadcrumbs] inline SVG icons

---

packages/table/src/cell/editableCell.tsx
packages/table/test/editableCellTests.tsx

Fixes bug where wrapText={true} has doesn't work for 
fix and tests

[table] fix wrapText on EditableCell component

---

packages/docs-theme/src/components/navigator.tsx
packages/docs-theme/src/styles/_navigator.scss

- fix navigator path alignment
- limit search results to 10
- better placeholder `"Fuzzy search headings..."`

[docs] Navigator results limit

---

packages/datetime/src/dateInput.tsx

- this worked in JS due to the props spread, but had to expose it in the TS props to be usable there.

[DateInput] add showActionsBar prop definition

---

packages/core/src/components/forms/_control-group.scss
packages/core/src/components/html-select/_common.scss
packages/docs-app/src/examples/core-examples/controlGroupExample.tsx

- add new selector added in 3.0 to control-group scss
- add more control types to ControlGroupExample
- HTMLSelect `<select>` tag grows to fill parent (fixes `fill` bug I found in example)

[ControlGroup] fix HTMLSelect support

---

packages/core/src/components/components.md
packages/core/src/components/index.ts
packages/core/src/components/overflow-list/overflowList.tsx
packages/core/src/components/popover/popover.tsx
packages/core/src/components/resize-sensor/resize-sensor.md
packages/core/src/components/resize-sensor/resizeSensor.tsx
packages/core/test/index.ts
packages/core/test/isotest.js
packages/core/test/resize-sensor/resizeSensorTests.tsx
packages/core/test/tsconfig.json

- `<ResizeSensor>` provides a React interface to `ResizeObserver` with a required `onResize` callback.
- refactor `OverflowList` and `Popover` to use this new guy.

[new] ResizeSensor component

---

packages/docs-app/src/examples/select-examples/suggestExample.tsx
packages/select/src/components/select/suggest.tsx
packages/select/test/suggestTests.tsx

- refactor `Suggest` to support new `QueryList` state and un/controlled features.
- ⭐️  `Suggest` now shows the selected item as the placeholder text when editing.
- this provides a much nicer experience as it doesn't mess with your typing, and the code is oh so much simpler!
- I was able to remove an entire state field `isTyping`, which was responsible for inconsistent behavior in the common test suites.
- revert disabled tests and fix esc/tab tests.
- add `resetOnSelect` switch to example

[Suggest] refactor to support new QueryList state

---

packages/docs-app/src/examples/select-examples/suggestExample.tsx
packages/select/src/common/itemListRenderer.ts
packages/select/src/common/listItemsProps.ts
packages/select/src/components/omnibar/omnibar.tsx
packages/select/src/components/query-list/queryList.tsx
packages/select/src/components/select/multiSelect.tsx
packages/select/src/components/select/select.tsx
packages/select/src/components/select/suggest.tsx
packages/select/test/multiSelectTests.tsx
packages/select/test/omnibarTests.tsx
packages/select/test/queryListTests.tsx
packages/select/test/renderFilteredItemsTests.tsx
packages/select/test/selectComponentSuite.tsx
packages/select/test/selectTests.tsx
packages/select/test/suggestTests.tsx
packages/timezone/test/timezonePickerTests.tsx

- ⭐️ optional `query`/`onQueryChange`, `activeItem`/`onActiveItemChange` props supported in all 4 components, implemented in `QueryList`
- `resetOnSelect` has also been made a "common" prop, supported natively in `QueryList`
- each component's state now reflects the features it adds on top of `QueryList` (like a few track `isOpen` for their popover)
- I recognize that this PR is very large and I'd be happy to break it up into smaller chunks if you suggest lines along which to cut. I already pulled several features out of my original attempt (see #2646 and #2723).
- Ok, I reverted `Suggest` in here because it requires more work than the others. See #2748
- The commits do a fairly good job of telling the story, so that may be a good way to review.

[select] un/controlled activeItem & query!

---

packages/core/src/components/dialog/_dialog.scss
packages/core/src/components/dialog/dialog.tsx
packages/core/test/dialog/dialogTests.tsx

- replace the broken `canOutsideClickClose` re-implementation in `Dialog` with pointer-events logic so we can simply reuse the correct logic in `Overlay` itself.
- we already had this `none/all` pair for `user-select`, so it makes sense to add the `pointer-events` combo too.

[Dialog] fix eager closing

---

packages/core/src/components/menu/menuItem.tsx
packages/core/src/components/popover/popover.md
packages/core/src/components/popover/popover.tsx
packages/core/src/components/popover/popoverSharedProps.ts
packages/core/test/popover/popoverTests.tsx
packages/docs-app/src/examples/core-examples/index.ts
packages/docs-app/src/examples/core-examples/popoverDismissExample.tsx
packages/docs-app/src/styles/_examples.scss

- improve `Classes.POPOVER_DISMISS` behavior:
- walk up DOM tree, looking for first DISMISS or DISMISS_OVERRIDE. only dismiss if DISMISS found. this makes for very easy dismiss overriding (and I think fixes some deep issues with the old impl).
- ignore DISMISS clicks if they come from inside a disabled element.
- new `Popover` `captureDismiss` prop (default `true`) invokes `preventDefault()` on `Classes.POPOVER_DISMISS` clicks. `Popover` now ignores dismiss clicks if default is prevented, so Popovers around a `Popover captureDismiss` will not close when an inner popover is dismissed.
- `MenuItem` disables `captureDismiss` to preserve existing (desired) behavior where clicking a nested submenu closes the entire hierarchy.
- add nice tests for all this new behavior

[Popover] new captureDismiss=true prop for better uncontrolled click-to-close

---

packages/core/src/components/menu/menu.tsx

[Menu] supports arbitrary HTML attributes

---

packages/core/src/components/tabs/tabs.tsx

blueprint's `tabs` rendering fail on jsdom. It may  happen on browser.
`document.querySelector` returns `null` if document.body has no matched selector.
We have to consider this.
```
> document.querySelector('missing-selector')
null
```
My test case screenshot

Fix tabs querySelector on jsdom

---

packages/core/src/components/resize-sensor/resize-sensor.md

Corrected example of ResizeSensor API to use `onResize` vs. `onChange` so it matches the surrounding instructions and the imported class def.
The example code's usage of `onResize` compared with expectations in `resizeSensor.tsx`.

match event handler prop name with code and docs

---

packages/core/src/components/popover/popover.md
packages/core/src/components/popover/popover.tsx
packages/core/src/components/popover/popoverSharedProps.ts
packages/core/test/popover/popoverTests.tsx

- disable `captureDismiss` by default as the `preventDefault()` call breaks `<a href>` behavior 😢

[Popover] captureDismiss=false by default 

---

site/docs/v1/index.html
site/docs/v2/index.html
site/docs/versions/index.html

Add redirects between the following URLs:
- `docs/versions/` => `docs/` - invalid route, nothing to show there
- `docs/v1/` => `docs/versions/1/` - legacy route pre #2545 
- `docs/v2/` => `docs/versions/2/` - legacy route pre #2545

[docs] redirect old docs/v{1,2}/ URLs to new URLs

---

packages/core/src/components/collapse/collapse.tsx

BP requires `"@types/react": "^16.0.34"` and it is pinned by `yarn.lock`.
For this version of typings, it is provided an overload, then the `HACKHACK` does not persist.
```ts
function createElement<P>(
type: SFC<P> | ComponentClass<P> | string,
props?: Attributes & P,
...children: ReactNode[]): ReactElement<P>;
```

Remove `HACKHACK`

---

packages/core/src/components/forms/radioGroup.tsx
packages/core/src/components/html-select/htmlSelect.tsx
packages/core/test/controls/radioGroupTests.tsx
packages/core/test/html-select/htmlSelectTests.tsx
packages/core/test/index.ts

- 🐛 Fix regression: `<RadioGroup>` passes custom `className` to its options
- 🐛 Fix regression: `<HtmlSelect>` passes custom `className` to its options
Nothing in particular. Should be simple.
N/A

[RadioGroup] [HtmlSelect] options support className and disabled

---

packages/core/src/components/popover/popover.md
packages/core/src/components/popover/popoverMigrationUtils.ts
packages/core/src/components/popover/popoverSharedProps.ts
packages/docs-app/src/examples/core-examples/popoverExample.tsx

- #2770 Popover now supports `"auto-start"` and `"auto-end"`.
- Updated example
- Updated docs
- Docs language

Add Popover support for "auto-start" and "auto-end"

---

packages/core/src/common/utils.ts
packages/core/src/components/button/abstractButton.tsx
packages/core/test/buttons/buttonTests.tsx
packages/core/test/common/utilsTests.tsx

- `Utils.isEmptyReactNode` to ensure correct detection of empty nodes.
- this fixes a regression in #2727 where `children` is easily non-null

[Button] Utils.isEmptyReactNode solves icon regression

---

packages/core/src/components/tag-input/tagInput.tsx
packages/core/test/tag-input/tagInputTests.tsx

- __[TagInput]__ Slightly modified behavior for `addOnPaste`:
If true, `onAdd` will be invoked when the user pastes text ___containing the separator___ into the input. Otherwise, pasted text will remain in the input.
__Note:__ For example, if addOnPaste=true and separator="\n" (new line), then:
- Pasting `"hello"` will _not_ invoke `onAdd`
- Pasting `"hello\n"` will invoke `onAdd` with `["hello"]`
- Pasting `"hello\nworld"` will invoke `onAdd` with `["hello", "world"]`
In the pre-`addOnPaste` world of Blueprint 1.X, we implemented this behavior via a custom `onPaste` callback, but that callback appears to no longer be supported. This was a specific request for our use case that we need to support somehow: reasoning is that users may want to refine a single line of pasted text before …

[TagInput] On paste, don't tag-ify text if no separator included

---

packages/core/src/components/html-select/_html-select.scss
packages/core/src/components/html-select/htmlSelect.tsx
packages/datetime/src/_common.scss
packages/datetime/src/_datepicker.scss
packages/datetime/src/_daterangepicker.scss
packages/datetime/src/common/classes.ts
packages/datetime/src/datePicker.tsx
packages/datetime/src/datePickerCaption.tsx
packages/datetime/src/datePickerNavbar.tsx
packages/datetime/src/dateRangePicker.tsx
packages/datetime/test/dateInputTests.tsx
packages/datetime/test/datePickerCaptionTests.tsx
packages/datetime/test/datePickerTests.tsx
packages/datetime/test/dateRangePickerTests.tsx

- use minimal `HTMLSelect` for month/year dropdowns.
- use minimal `Button` for next/previous buttons.
- use `navbarElement` prop to render custom next/prev buttons instead of restyling the existing classes.
- caption is responsible for month/year selects
- navbar is responsible for prev/next buttons.
- `DatePicker` uses single `handleMonthChange` for all DayPicker events
- caption (month/year select) and navbar (prev/next buttons) now all use the same logic for changes!
- use `Divider` for all the internal separators
- add `HTMLSelect` `iconProps` prop so we can position the icon
`DatePicker`
`DateRangePicker`
`DateRangePicker contiguousCalendarMonths`

[DatePicker] reuse existing components in caption

---

packages/datetime/src/_timepicker.scss
packages/datetime/src/dateInput.tsx
packages/datetime/src/datePicker.tsx
packages/datetime/src/datePickerCaption.tsx
packages/datetime/src/datePickerCore.tsx
packages/datetime/src/dateTimePicker.tsx
packages/datetime/src/datetimepicker.md
packages/datetime/src/timePicker.tsx
packages/datetime/test/dateInputTests.tsx
packages/datetime/test/datePickerTests.tsx
packages/docs-app/src/examples/datetime-examples/common/momentDate.tsx
packages/docs-app/src/examples/datetime-examples/common/precisionSelect.tsx
packages/docs-app/src/examples/datetime-examples/dateInputExample.tsx
packages/docs-app/src/examples/datetime-examples/datePickerExample.tsx
packages/docs-app/src/examples/datetime-examples/dateRangePickerExample.tsx

- add `timePrecision` and `timePickerProps` to shared date picker props
- and remove them from `DateInputProps`
- `DatePicker` now includes time selection if one of the above props is defined
- ❌ **Deprecate** `DateTimePicker` since `DatePicker` can do it all now

[DatePicker] time support: timePrecision & timePickerProps

---

packages/datetime/src/common/monthAndYear.ts
packages/datetime/src/dateRangePicker.tsx

- gentle refactors to `DRP` a la #2789

[DateRangePicker] refactors to reduce some complexity

---

packages/table/src/headers/_headers.scss

* [table] Fixes stacking context of `.bp3-table-th-menu`: menu icon was covered by `.bp3-table-th-menu-container-background` before
* Menu Icon in `<ColumnHeaderCell>` with `menuRenderer`

[table] fix invisible table menu icon

---

packages/core/src/components/button/_button.scss
packages/core/src/components/spinner/_spinner.scss
packages/core/src/components/spinner/spinner.tsx
packages/core/test/spinner/spinnerTests.tsx

- add HTML wrapper tag around `<svg>` and move animation to this element, because SVG tags do not support animations or transforms in IE 11 ([source](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/supportcsstransformsonsvg/?q=svg))

[Spinner] restore IE support

---

packages/core/src/components/icon/_icon.scss
packages/core/src/components/icon/icon.md
packages/core/src/components/icon/icon.tsx
packages/core/test/icon/iconTests.tsx

- `<Icon>` now renders an HTML element that _contains_ the `<svg>` image so CSS properties work as expected (especially `padding`)
- add `<Icon tagName>` prop to customize this element (default "span")
- `color` prop is now directly set as `<svg fill>` attribute and overrides other CSS colors (including intent)
- set CSS class for icon like we used to: `.bp3-icon.bp3-icon-{name}`
- this greatly simplifies migration as folks tend to select the icon-name class (wish they didn't but oh well)
- refactor icon styles to separate SVG from legacy font
- only apply legacy font styles if icon element is `:empty`
- this has the neat side effect of acting as a kind of "fallback" if you remove the `<svg>` image.
- fix docs version selector accordingly

[Icon] render HTML element & tagName prop

---

packages/core/src/components/skeleton/_common.scss
packages/core/src/components/skeleton/_skeleton.scss

this took some digging! turns out the `!important` on background was preventing the animation from ever appearing, _only on Firefox_.
then I took the liberty of refactoring the animation styles.

[Skeleton] fix FF support!

---

packages/core/src/common/classes.ts
packages/core/src/components/spinner/_spinner.scss
packages/core/src/components/spinner/spinner.tsx

- add `spinner-animation` element to isolate spinner from parent display styles
- this is basically what we had [back in 1.x](https://blueprintjs.com/docs/versions/1/#core/components/progress/spinner.css-api) with `.pt-spinner > .pt-spinner-svg-container > svg`

[Spinner] add additional child element to isolate spinner from parent

---

packages/core/src/components/icon/_icon.scss

- go back to using `inline-block` because hey it's not an API break and it worked reliably
- take no chances with double-icons: `!important` on content clearing
- fixes tag removable and timepicker arrows

[Icon] revert to inline-block

---

packages/core/src/components/overlay/overlay.tsx

I checked the 2.x/3.x branches and aligned this code to those, which fixed my issues. This appears to just have been a typo in 1.x.

Fixed containerElement query to not throw errors, align with 2.x/3.x

---

packages/select/src/components/select/select-component.md

Copied this over and realized that the argument should not be item but rather film.
Change the typo

[Select Documentation] Fix incorrect argument name

---

packages/select/src/components/select/suggest.tsx
packages/select/test/suggestTests.tsx

Fixes #2784.
The `Suggest` component now takes an optional selectedItem prop. If defined the selectedItem state will be initialised with the given selectedItem.

[Suggest] Added selectedItem prop

---

packages/core/src/components/tag-input/_tag-input.scss
packages/core/src/components/tag-input/tagInput.tsx
packages/docs-app/src/examples/core-examples/tagInputExample.tsx

- `<TagInput>` now uses `$input-padding-horizontal` when empty.
- Same as `<InputGroup>`.
Minor as this fix may be, there were a few ways to do it, none of which felt great:
- Inline style on the component
- Felt dirty given our current scheme driven by CSS classes.
- Add an `-empty` CSS class to `.bp3-tag-input`, change its padding-left to 10px.
- __(This is what I did.)__
- Modifies the element that sets the existing padding.
- Minor con: it introduces a new (non-exported) CSS class into the vocabulary.
- Add an `-empty` CSS class to `.bp3-tag-input-values` to scope this clunky special class strictly _within_ the outer `<TagInput>` element.
- Feels a little cleaner philosophically.
- But then we have padding split between `bp3-tag-input` and `bp3-tag-input-values`.
- Use some CSS …

[TagInput] Use $input-padding-horizontal when empty for consistency with <InputGroup>

---

packages/datetime/src/timePicker.tsx
packages/datetime/test/timePickerTests.tsx

Fixed #2794 
`NumericInput` has prop called `clampValueOnBlur`, which indicates whenever or not input automatically clamp to boundaries. Should We introduce similar functionality for `Timepicker`?

[timepicker] Fix allowing to type time that exceeds time bounds

---

packages/core/src/common/classes.ts
packages/core/src/components/html-table/_html-table.scss
packages/core/src/components/html-table/htmlTable.tsx

Add a condensed property to HTML tables that just modifies sizing for tables and tabular elements without affecting the sizing of, e.g., nested buttons.
Whether the distinction between condensed and small for tables is clear.

Add condensed property to HTML tables

---

packages/core/package.json
yarn.lock

for https://github.com/haithembelhaj/sass-inline-svg/pull/10
reviewers: ensure that checkboxes and breadcrumbs still look good.

🔧 bump sass-inline-svg

---

packages/select/src/components/select/multiSelect.tsx
packages/select/test/multiSelectTests.tsx

- Add `placeholder` prop at the top of Multiselect component.
- Multiselect `placeholder` prop.
Note that you can still change the placeholder as before by doing:
```
<MultiSelect tagInputProps={{ placeholder: 'Search anything...' }} />
```
as well as:
```
<MultiSelect placeholder="Search anything..." />
```

[Select] Add placeholder prop to multiselect component

---

packages/docs-app/src/examples/select-examples/omnibarExample.tsx
packages/select/src/components/query-list/queryList.tsx
packages/select/test/queryListTests.tsx
packages/select/test/selectComponentSuite.tsx

- always reset active item if it's now filtered or disabled (even if `resetOnQuery=false`).
- this behavior existed before but didn't work very well. i refactored the state manipulation logic and now it works very well.
- better handling of `shouldCheckActiveItemInViewport` so the active item is always visible in the viewport.
- this behavior regressed at some point. no longer!
- adjust omnibar example hotkey props for better experience.
CC @switz - followups from your recent PR.

[select] QueryList reset followups

---

packages/docs-app/README.md
packages/webpack-build-scripts/webpack.config.base.js

Allows configuring the webpack dev server port
Running the dev server with and without the `PORT` env set

enable port configuration in webpack dev server. Closes #2921

---

packages/core/src/components/icon/_icon.scss

- seems as though IE does not properly support CSS `unset` keyword.

[Icon] fix font icons on IE11

---

packages/core/src/components/icon/icon.tsx
packages/core/test/icon/iconTests.tsx

- unknown icon name renders markup but no path elements, resulting in blank icon.

[Icon] unknown string icon name renders blank icon

---

packages/core/src/components/forms/_controls.scss

- a little `position` change makes all the difference -- ensure the indicator stays inside the switch body at all times.

[Switch] Fix indicator when line-height != 1

---

packages/select/src/components/select/suggest.tsx
packages/select/test/suggestTests.tsx

Fixes #2784.
The `Suggest` now accepts a defaultSelectedItem prop to set the initial value of the component in uncontrolled mode ( default uncontrolled state ).

Added support for defaultSelectedItem.

---

packages/docs-app/src/examples/core-examples/collapseExample.tsx

Stops collapse button from moving left/right in collapse demo, shown here:
Minor in-line css changes in:
https://github.com/palantir/blueprint/compare/develop...mattfwood:mw/fix-collapse-demo?expand=1#diff-e8d90268ddca67b0ed4f7f87ec7e791f

Fix collapse button jumping in demo

---

packages/core/src/components/hotkeys/hotkeys.tsx
packages/core/test/hotkeys/hotkeysTests.tsx

Hotkey groups with labels that are have the global={true} prop should
now also be alphabetically sorted.
Fixes #2439 
The change will prioritize global hotkeys, but still sort them with other global hotkey groups. If a hotkey group is both global but also has a group name, it will still sort it alphabetically.
Sorting and order of global hotkey groups with a group name set.

[hotkeys] Fix sorting for global hotkey groups with labels

---

packages/core/src/components/forms/formGroup.tsx
packages/core/test/forms/formGroupTests.tsx
packages/docs-app/src/examples/core-examples/formGroupExample.tsx

I'd like to hide the `<label>` tag when no label is passed so it doesn't take any space (margin) in the layout.

Form group: hide label when falsy

---

packages/core/src/components/spinner/_spinner.scss
packages/core/src/components/spinner/spinner.tsx
packages/core/test/spinner/spinnerTests.tsx

- 🌟 compute spinner SVG `viewBox` based on computed `strokeWidth` so the track always exactly fills the frame to the edge and never exceeds it.
- 👍 also, `tagName` now affects both DOM wrappers so it can actually be used in an SVG.
20px:
50px:
100px:
175px:

[Spinner] prevent track overflow

---

packages/core/test/overflow-list/overflowListTests.tsx

just a total refactor of the `OverflowList` test suite to use a friendly harness.
extracted from #2975

[OverflowLists] refactor tests to use a sweet harness

---

packages/table-dev-app/src/mutableTable.tsx
packages/table/src/interactions/selectable.tsx
packages/table/src/table.tsx

This pull request implements a change to the `Table` component that passes the newly focused cell through the `selectedRegionTransform` function of the table if it is present. This is to ensure that invariants enforced in the `selectedRegionTransform` function (e.g., "only whole rows should be selected") are not violated after the user navigates to another cell with the keyboard.
Please check my changes made to the `handleFocusMove()` method of the `Table` component. I have updated the table dev app as well to make this change easier to test.

[Table] Newly focused cell after keyboard navigation is now transformed

---

packages/core/src/common/utils.ts
packages/core/src/components/slider/multiSlider.tsx
packages/core/src/components/tabs/tabs.tsx
packages/table/src/cell/cell.tsx
packages/table/src/cell/editableCell.tsx
packages/table/src/cell/formats/jsonFormat.tsx
packages/table/src/cell/formats/truncatedFormat.tsx
packages/table/src/column.tsx
packages/table/src/table.tsx

- ⚠️ `Utils.isElementOfType` now checks `displayName` equality to support multiple minor versions.
- Utils are not part of the public API (though they are exported) so this will not be considered an API break
- previously it created an element which is potentially expensive (for react-hot-loader support)
- refactor `Tabs` and `MultiSlider` a little bit to support this new usage.
- does this still support react-hot-loader?

less brittle element type checks

---

packages/tslint-config/src/rules/blueprintClassesConstantsRule.ts
packages/tslint-config/src/rules/utils/addImportToFile.ts
packages/tslint-config/src/tsconfig.json
packages/tslint-config/test/rules/blueprint-classes-constants/true/test-icons.tsx.fix
packages/tslint-config/test/rules/blueprint-classes-constants/true/test-icons.tsx.lint
packages/tslint-config/test/rules/blueprint-classes-constants/true/test.tsx.fix
packages/tslint-config/test/rules/blueprint-classes-constants/true/test.tsx.lint

Create a fixer for classes-constants lint rule
1. The lint rule will now fail the entire node, instead of just the pt-* string
2. The lint rule now has a fixer that will replace the pt-* string with the blueprint import
This does not create a fixer for icons, since that rule is slightly more complex, and should handle the options for creating an `<Icon {...} />` element, or using `IconNames`
Lint rule semantics/test cases.

Create a fixer for classes-constants lint rule

---

packages/core/src/components/tag/tag.tsx
packages/core/test/tag/tagTests.tsx

- only render `Text` child if children is not empty.
- this is analogous to what we did in #2775 for `Button`

[Tag] don't render text if no children

---

packages/core/src/common/_variables.scss
packages/core/src/components/forms/_common.scss
packages/core/src/components/forms/_input-group.scss
packages/core/src/components/forms/_input.scss
packages/core/src/components/forms/textArea.tsx

- adjust newly added variables a bit so small inputs sit better.
- smaller buttons are a little bigger so there's more space around icon
- adjust input small padding so icon remains centered
- fix font icon size in input-group CSS example
- fix padding on small+round inputs
- refactor `<textarea>` styles to better support small/large sizes
- add `TextArea` `small` prop
before (#2953) | after (this PR)
---|--
cc @tnrich. thank you for getting this started!

[Input/InputGroup/TextArea] small modifier follow-ups

---

packages/core/test/panel-stack/panelStackTests.tsx
packages/tslint-config/src/rules/blueprintClassesConstantsRule.ts
packages/tslint-config/test/rules/blueprint-classes-constants/true/test-icons.tsx.fix
packages/tslint-config/test/rules/blueprint-classes-constants/true/test-icons.tsx.lint
packages/tslint-config/test/rules/blueprint-classes-constants/true/test.tsx.fix
packages/tslint-config/test/rules/blueprint-classes-constants/true/test.tsx.lint

- reject `bp3-` prefix (and tests)
- merge multiple spaces in remaining template string

[tslint] reject bp3- prefix too

---

packages/datetime/src/dateInput.tsx
packages/datetime/test/dateInputTests.tsx

Add `todayButtonText` and `clearButtonText` props to `DateInput` so these properties can be passed down to the underlaying `DatePicker` that is used by it when the props are spread into that component.
The adding of both props to the `DateInput` component.

[DateInput] Add support for datepicker clearButtonText and todayButtonText props.

---

yarn.lock

Running more recent `yarn` (v1.10.1) will generate these hashes. I love having a clean branch to work from so I'm making this as a standalone PR. This will reduce the noise for anyone on recent `yarn`.

include integrity hashes in yarn lock

---

packages/select/src/components/query-list/queryList.tsx
packages/select/test/queryListTests.tsx

Fixed an issue where query lists with controlled queries and `resetOnQuery={false}` would reset the active item when receiving new props despite the query itself not changing.

Fix reset of active item when query hasn't changed

---

packages/datetime/src/dateInput.tsx

This ensures that when pressing `tab` the focus of the datepicker is blurred and disabled.
The comment included is no longer valid, as the popover is by default handled in a portal, which means the tab index is incorrect anyway.
Whether this breaks anything in terms of UI.

DateInput tab fix

---

packages/core/src/components/html/html.md

Also correct link to html-table page.
No code changes.

Docs Only: Correct Table reference to HTMLTable

---

README.md
package.json
packages/core/package.json
packages/datetime/package.json
packages/docs-app/package.json
packages/docs-theme/package.json
packages/icons/package.json
packages/karma-build-scripts/package.json
packages/labs/package.json
packages/landing-app/package.json
packages/select/package.json
packages/table-dev-app/package.json
packages/table/package.json
packages/timezone/package.json
scripts/preview.js
yarn.lock

- resolution for node-gyp to support XCode 10+
- `*` dep for -build-scripts packages so we can release them without having to change all package.json files
- preview script without `GH_AUTH_TOKEN` will not fail the build
- update min version of yarn in readme

🔧 fix dependencies

---

packages/core/src/components/icon/_icon.scss

`vertical-align: text-bottom` makes icons sit much better with inline text.
-|-|-

fix icons alignment

---

packages/core/src/components/alert/alert.tsx
packages/core/src/components/dialog/dialog.tsx
packages/core/src/components/overlay/overlay.tsx
packages/core/src/components/popover/popover.tsx
packages/core/src/components/popover/popoverSharedProps.ts
packages/core/src/components/portal/portal.tsx
packages/core/src/components/tooltip/tooltip.tsx
packages/core/test/alert/alertTests.tsx
packages/core/test/dialog/dialogTests.tsx
packages/core/test/overlay/overlayTests.tsx
packages/core/test/popover/popoverTests.tsx
packages/core/test/portal/portalTests.tsx

Add `container` prop to `<Portal>` `<Overlay>` `<Popover>` `<Tooltip>` `<Dialog>` `<Alert>` component to mount children into specified node.

[Portal] add container prop

---

packages/core/test/isotest.js
packages/datetime/test/isotest.js
packages/icons/test/isotest.js
packages/select/test/isotest.js
packages/table/test/isotest.js
packages/test-commons/src/generateIsomorphicTests.ts
packages/timezone/test/isotest.js

- refactor `generateIsomorphicTests(Components, config)` to use config object in mapped type. four args become two.
- refactor isotest suites to use new config object
- add `className` isotest to assert that `className` prop appears in rendered output.
- 👍 this sets us up well for adding a `style` prop across the board.
```
@blueprintjs/core:     ✓ <MultiSlider>
@blueprintjs/core:     ✓ <MultiSlider className>
@blueprintjs/core:     ✓ <Navbar>
@blueprintjs/core:     ✓ <Navbar className>
@blueprintjs/core:     ✓ <NavbarDivider>
@blueprintjs/core:     ✓ <NavbarDivider className>
@blueprintjs/core:     ✓ <NavbarGroup>
@blueprintjs/core:     ✓ <NavbarGroup className>
@blueprintjs/core:     ✓ <NavbarHeading>
@blueprintjs/core:     ✓ <NavbarHeading className>
@blueprintjs/core:     ✓ …
```

add isotest for className prop

---

packages/core/src/components/navbar/_navbar.scss

- remove unused `logo` styles (this component no longer exists)

remove unused logo styles from navbar

---

packages/core/src/components/forms/_control-group.scss

Caret-specific z-index on focus was set for `.bp3-select`, but not for `.bp3-html-select`.
Caret icon when you focus a `HTMLSelect` in a `ControlGroup`.

[ControlGroup] fix disappearing caret on focus of HTMLSelect in ControlGroup

---

packages/datetime/src/dateRangeInput.tsx
packages/datetime/src/dateRangePicker.tsx
packages/datetime/test/dateRangeInputTests.tsx
packages/datetime/test/dateRangePickerTests.tsx
packages/docs-app/src/examples/datetime-examples/dateRangeInputExample.tsx
packages/docs-app/src/examples/datetime-examples/dateRangePickerExample.tsx

Added a `singleMonthOnly` prop to show only a single month in the DateRangePicker and DateRangeInput. Have set the prop to default to false, to avoid visual breaking changes to anyone using this already and not passing the prop.
By default,
When `singleMonthOnly` prop is set to true

Single Month Only Prop in DateRangePicker

---

packages/core/src/components/menu/menuItem.tsx

the MenuItem now supports the property tagName which defaults to "a"
./src/components/menu/menuItem.tsx
I'm on windows so I'm unable to build any of the testing stuff because your `yarn verify` setup is requiring access to `bash`... so someone is going to have to test this as I'm unable to.
```cmd
PS C:\*obsured*\blueprint> yarn verify
yarn run v1.10.1
$ npm-run-all -s compile dist:libs dist:apps -p test lint
$ lerna run compile
lerna info version 2.7.1
lerna info versioning independent
$ tsc -p ./src
$ tsc -p ./src
lerna ERR! compile Errored while running script in '@blueprintjs/icons'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run compile
lerna ERR! 'bash' is not recognized as an internal or external command,
lerna ERR! operable program or batch file. …
```

Using tagName JSX variable for MenuItem

---

packages/core/src/components/overlay/overlay.tsx
packages/core/src/components/popover/popoverSharedProps.ts
packages/core/test/dialog/dialogTests.tsx
packages/core/test/overlay/overlayTests.tsx

- `portalClassName` prop on all Overlay components, to add a class directly on the root portal element!

[Overlay] add portalClassName to IOverlayableProps

---

packages/core/src/common/classes.ts
packages/core/src/components/html-table/_html-table.scss
packages/core/src/components/html-table/htmlTable.tsx

- replace `Classes.CONDENSED` (added in #2904 with the wrong name) with `Classes.HTML_TABLE_CONDENSED`. 
- this is actually a revert to pre-3.x usage.

fix HTML_TABLE_CONDENSED name (reverts 3.x break)

---

packages/core/src/components/tag-input/tagInput.tsx
packages/core/test/tag-input/tagInputTests.tsx

This change modifies `TagInput` to not clear the value displayed in the `input` field when adding tags if the consumer passes in their own `inputValue` prop. Previously, adding tags would clear this field, which resulted in confusing behavior in `MultiSelect`, as described in the issue. This seems philosophically correct: If the consumer specifies an explicit value for `inputValue`, it should never be overridden in `TagInput`'s state.

Don't clear TagInput inputValue state if controlled

---

packages/core/src/components/callout/_callout.scss

- remove bottom margin when a Callout contains only a title (no body text)

[Callout] support title only

---

packages/core/src/components/popover/popoverMigrationUtils.ts
packages/core/src/components/popover/popoverSharedProps.ts
packages/docs-app/src/examples/core-examples/popoverExample.tsx

`PopoverPosition` extends `Position` enum with `auto`, `auto-end`, `auto-start`

[Popover] add PopoverPosition enum = Position + auto values

---

packages/select/src/common/listItemsProps.ts
packages/select/src/components/query-list/queryList.tsx

Adds a flag `scrollToActiveItem` which defaults to `true` for select list components.
Prevents this undesirable scrolling behavior when updating active item based on mouse hover:
Note this is just by hovering, no scroll wheel was used in the creation of this gif.

[Select] Flag to optionally scroll to active item for select components

---

packages/tslint-config/src/rules/blueprintClassesConstantsRule.ts
packages/tslint-config/src/rules/blueprintHtmlComponentsRule.ts
packages/tslint-config/src/rules/blueprintIconComponentsRule.ts
packages/tslint-config/src/rules/utils/addImportToFile.ts
packages/tslint-config/src/rules/utils/replaceTagName.ts
packages/tslint-config/src/tsconfig.json
packages/tslint-config/test/rules/blueprint-html-components/true/all.tsx.fix
packages/tslint-config/test/rules/blueprint-html-components/true/all.tsx.lint
packages/tslint-config/test/rules/blueprint-html-components/true/test.tsx.fix
packages/tslint-config/test/rules/blueprint-html-components/true/test.tsx.lint

- add fixer for `blueprint-html-components` tslint rule
- also enable `strict` mode in tslint-config package

[tslint] blueprint-html-components fixer!

---

packages/core/src/common/props.ts
packages/core/src/components/alert/alert.tsx
packages/core/src/components/button/abstractButton.tsx
packages/core/src/components/callout/callout.tsx
packages/core/src/components/dialog/dialog.tsx
packages/core/src/components/forms/inputGroup.tsx
packages/core/src/components/forms/numericInput.tsx
packages/core/src/components/icon/icon.tsx
packages/core/src/components/non-ideal-state/nonIdealState.tsx
packages/core/src/components/tag-input/tagInput.tsx
packages/core/src/components/tag/tag.tsx
packages/core/src/components/toast/toast.tsx
packages/core/src/components/tree/treeNode.tsx
packages/docs-app/src/components/icons.tsx

```ts
/**
* Alias for a `JSX.Element` or a value that renders nothing.
*
* In React, `boolean`, `null`, and `undefined` do not produce any output.
*/
export type OptionalElement = JSX.Element | boolean | null | undefined;
```
```
icon?: IconName | OptionalElement;
```
this new interface allows for more falsy uses consistent with other React APIs.

relaxed typings for optional JSX.Elements

---

packages/core/src/components/popover/popover.tsx
packages/core/src/components/popover/popoverSharedProps.ts
packages/docs-app/src/examples/core-examples/popoverExample.tsx
packages/docs-app/src/examples/core-examples/popoverPortalExample.tsx

- `Popover` `boundariesElement` prop to quickly set both `flip` & `preventOverflow` Popper modifier behavior

[Popover] add boundary prop for easier modifiers

---

packages/core/src/components/toast/toast.tsx

When using keys to update a toast you should also be able to pass in a new timeout prop. This lets you show a toast while something is loading for example and then hide it once it finishes.
connects https://github.com/palantir/blueprint/issues/3107

Fixed bug where new timeout prop passed to toastr update was ignored

---

packages/select/src/components/omnibar/omnibar.tsx
packages/select/src/components/select/select.tsx
packages/select/src/components/select/suggest.tsx

- standardize `inputProps` docs in `select` package.

[select] fix inputprops docs

---

packages/core/src/components/html-table/htmlTable.tsx

[HTMLTable] fix html props type

---

packages/core/src/components/popover/popover.tsx
packages/core/test/controls/inputGroupTests.tsx
packages/datetime/src/dateInput.tsx
packages/datetime/test/dateInputTests.tsx

- fix Popover's injection of `tabIndex` into target element
- previously it would remove any `tabIndex` unless a condition was met. 
- now the condition ensures that _some_ tabIndex is set, and uses prop otherwise.
cc @kittle31

[Popover/DateInput] fix tabIndex & inputRef support

---

README.md
packages/docs-app/src/components/welcome.tsx

new sandbox uses the latest libs (3.9.0, etc) and imports CSS files from JS so they're always the latest. this makes updating really easy with the little "refresh dependency" button.
| before | after |
|-|-|
| ![image](https://user-images.githubusercontent.com/464822/49322220-8232cc00-f4c2-11e8-88c2-88c9eeca5dd7.png) | ![image](https://user-images.githubusercontent.com/464822/49322225-8ced6100-f4c2-11e8-9e83-ab17640147ac.png) |

Update codesandbox URL

---

packages/core/src/components/tree/tree.tsx
packages/core/src/components/tree/treeNode.tsx
packages/core/test/tree/treeTests.tsx

Adds `onNodeMouseEnter` and `onNodeMouseLeave` event handlers to a `Tree`.
Naming of new props

add mouseenter and mouseleave events to treenode

---

packages/core/src/common/utils.ts
packages/core/src/common/utils/safeInvokeMember.ts
packages/core/src/components/popover/popover.tsx
packages/core/src/components/popover/popoverSharedProps.ts
packages/core/test/popover/popoverTests.tsx

1. add new util `safeInvokeMember` that is useful for nested prop callbacks. I put this in its own file in `common/utils/` because the overloads are quite verbose.
```js
safeInvokeMember(this.props.inputProps, "onChange", evt);
```
2. add `Popover targetProps` to set props on `Classes.POPOVER_TARGET` element (alongside `targetTagName` and `targetClassName`).
- this provides much improved support for an advanced use case of positioning the target manually using `style` attributes: simply set `targetProps={{ style: { left, top } }}`

[Popover] add targetProps

---

package.json
scripts/preview.js
yarn.lock

This should improve the OSS contribution experience. The preview bot will now log artifact URLs directly to Circle console if `GH_AUTH_TOKEN` is missing. This means no more digging through Artifacts tab or pestering users to add this auth token.

Circle bot logs artifact URLs if auth token is missing

---

packages/core/src/components/icon/icon.tsx

Add an `htmlTitle` prop to `<Icon>` which gets applied as the HTML `title` attribute, and appears as the built in browser tooltip on hover
Helps address/provide workaround for #3214

Add htmlTitle prop to Icon

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

ran through a flow with @gabeboning and turns out the build works best when folks __DO NOT__ enable it on their forks. we've had issues with build parallelism and with the preview comments that are all resolved if contributors just leverage our build configuration instead of enabling their own.

update contributing notes: DO NOT enable Circle for forks.

---

packages/core/src/components/popover/popover.tsx
packages/core/src/components/tooltip/tooltip.tsx

`popover.reposition()` & `tooltip.reposition()` (grab a `ref` first) schedules popper update.

[Popover/Tooltip] add public reposition() method to schedule popper update

---

packages/datetime/src/_datepicker.scss
packages/datetime/src/_daterangepicker.scss
packages/datetime/src/datePickerNavbar.tsx
packages/datetime/src/dateRangePicker.tsx
packages/datetime/test/dateRangePickerTests.tsx

- ~Update documentation~
The linked bug happens in contiguous month mode, because the `DatePickerCaption` component on both months control `leftView`. With this fix, we now render two `DayPicker`s whose captions have different behaviors.
- Display two `DayPicker`s whose `DatePickerCaption` has different behaviors in contiguous month mode
- Allow hiding individual nav buttons in `DatePickerNavbar` to keep rendering consistent in contiguous mode

[DateRangePicker] Fix caption behavior in contiguous month mode

---

packages/core/src/components/hotkeys/hotkeys.md

[Documentation] Missing s from documentation hotkeys.md doc

---

packages/core/src/components/editable-text/editableText.tsx

Added type prop to EditableText
`editableText.tsx`

Added EditableText input type field

---

packages/docs-app/src/examples/core-examples/panelStackExample.tsx

React does not guarantee that the state changes are applied immediately. It is best practice to use an updater function if the new state relies on the current state.
Replacing simple `setState` merges with updater functions `state => newState` since state updates may be asynchronous and/or delayed.

Fix setState calls using updater functions

---

packages/core/src/components/menu/menuItem.tsx

Add two new props to menu item to allow you to apply a classname to the text and label wrapper elements

Add menu item classnames

---

packages/core/src/components/dialog/_dialog.scss

Fixes the dialog css docs for the dialog close button:
- Leave the noop `{ns}-dialog-close-button` class
- Add `{ns}-button}` and `{ns}-minimal}` classes
- Change icon from small cross to cross
Previously on dialog css docs:
Next week on dialog css docs:

Fix dialog css docs

---

packages/core/src/components/context-menu/context-menu.md

Instead of falling back to the imperative API, suggest using `ContextMenuTarget`, where decorators are not an option. 
I couldn't find this suggestion in the docs. If the PR gets merged I can send one for the [hotkey decorator](https://blueprintjs.com/docs/#core/components/hotkeys.decorator) too.
I tested this locally already and I couldn't find any issues with this approach.

Suggest using `ContextMenuTarget` as a HOC

---

packages/core/src/components/context-menu/context-menu.md

To make it more obvious that you can manually create a dark context menu, as raised in https://github.com/palantir/blueprint/issues/3229

[docs] show optional isDarkTheme parameter in ContextMenu API docs

---

packages/core/src/components/popover/popover.md

I _think_ `inline` is outdated b/c I don't see docs on that prop above. I'm pretty sure this section means to reference `usePortal={false}` instead.

Popover docs: inline -> usePortal={false}

---

packages/docs-app/src/getting-started.md
packages/webpack-build-scripts/externals.js

- update webpack externals list to latest dependencies
- update CDN usage example to list correct required deps.
- push CDN usage section to bottom of Getting Started page to keep the focus on most common usage scenario (NPM)
- small edits to getting started language

[docs] fix CDN usage & bundle externals

---

packages/core/src/components/overflow-list/overflowList.tsx
packages/core/test/overflow-list/overflowListTests.tsx

The `OverflowList` is a `PureComponent`, which means it only re-renders when props don’t shallow equal previous props. The way I’m using it allows all props to remain the same, but the renderer methods’ behavior can still change (some additional data is loaded which changes how an item is rendered). This doesn’t trigger a re-render in the overflow list, so the renderers are never called again, which means the change never gets rendered.
This PR changes the `OverflowList` to be a regular `Component`, so that it always re-renders, even when props shallow-equal previous props.

[OverflowList] Always re-render items

---

packages/docs-app/src/examples/timezone-examples/components/customTimezoneTarget.tsx
packages/docs-app/src/examples/timezone-examples/components/index.ts
packages/docs-app/src/examples/timezone-examples/timezonePickerExample.tsx
packages/timezone/src/common/errors.ts
packages/timezone/src/components/index.ts
packages/timezone/src/components/timezone-picker/timezone-picker.md
packages/timezone/src/components/timezone-picker/timezoneMetadata.ts
packages/timezone/src/components/timezone-picker/timezonePicker.tsx
packages/timezone/test/timezonePickerTests.tsx

- 🌈 __Enhancement__: In `<TimezonePicker>`, support a custom target instead of the default button by passing a custom child.
- Only one child is supported; providing more than one will print a console warning in dev mode.
- If a custom child is provided, all button-specific props will be ignored (i.e., `buttonProps`, `disabled`, `placeholder`, `valueDisplayFormat`).
- 🌈 __Enhancement__: Export `getTimezoneMetadata()` from `packages/timezone` to enable easy, arbitrary timezone formatting in custom targets.
- Necessary for some internal work.
- Other:
- _Update example_: Add "Custom target" toggle that shows the globe icon GIF'd below.
- _Update tests_.
- _Update docs_.
- __Q:__ Can you help me organize the documentation for `<TimezonePicker>`? Feels busy right now.
- I added a non-exported …

[TimezonePicker] Support a custom target via <children>

---

packages/select/src/components/select/suggest.tsx

- keep showing query inside `Suggest` input when popover is closed and _no item is selected_.

[Suggest] query remains when closed if nothing is selected.

---

packages/datetime/src/dateRangePicker.tsx
packages/datetime/src/shortcuts.tsx
packages/datetime/test/dateRangePickerTests.tsx

To avoid breaking backcompat (i.e. clicking on shortcut only changes the date by default), I added an optional parameter to `IDateRangeShortcut` to let users specify that a certain shortcut should be allowed to change the time as well as date.

Allow shortcuts to change time in Date Range Picker

---

packages/docs-app/src/examples/select-examples/suggestExample.tsx
packages/select/src/components/select/suggest.md
packages/select/src/components/select/suggest.tsx

- new `disabled` prop to quickly disable the entire thing.
- new `resetOnClose` prop resets active item & query when the popover closes, a la corresponding prop on `Select`.

[Suggest] add `disabled` and `resetOnClose` props

---

packages/select/src/components/query-list/queryList.tsx
packages/select/test/queryListTests.tsx

Fix a bug in QueryList where `activeItem` state is always initialized to first filtered enabled item, completely ignoring the potentially controlled `activeItem` prop.
Is there any related controlled vs uncontrolled behavior of `activeItem` that may also be incorrect?
N/A

[QueryList] Initialize activeItem state correctly based on prop.

---

packages/core/src/components/tooltip/tooltip.tsx

- Add `Tooltip` `interactionKind` prop that supports `HOVER | HOVER_TARGET_ONLY` (defaults to the latter, as always).

[Tooltip] allow HOVER interactions

---

packages/core/src/components/tag-input/tagInput.tsx
packages/core/src/components/tag/_tag.scss
packages/core/src/components/tag/tag.tsx
packages/docs-app/src/examples/core-examples/tagExample.tsx
packages/docs-app/src/examples/core-examples/tagInputExample.tsx

- add `<Tag fill>` prop to make it a block element.
- add `<TagInput intent>` prop to support colors.

[Tag] fill & [TagInput] intent props

---

packages/select/src/components/select/select-component.md

docs: Fix link to Popover

---

packages/core/package.json
packages/datetime/package.json
packages/docs-app/package.json
packages/docs-data/package.json
packages/docs-theme/package.json
packages/icons/package.json
packages/karma-build-scripts/package.json
packages/labs/package.json
packages/landing-app/package.json
packages/node-build-scripts/package.json
packages/select/package.json
packages/table-dev-app/package.json
packages/table/package.json
packages/test-commons/package.json
packages/test-react15/package.json
packages/timezone/package.json
packages/tslint-config/package.json
packages/webpack-build-scripts/package.json

Specifying the directory as part of the `repository` field in a `package.json`
allows third party tools to provide better support when working with monorepos.
For example, it allows them to correctly construct a commit diff for a specific
package.
This format was accepted by npm in
[npm/rfcs#19](https://github.com/npm/rfcs/pull/19).
Specifically, we'd like to use this field to construct better commit diff links on Dependabot [update PRs](https://github.com/NCI-Agency/anet/pull/1172), taking you straight to [these commits](https://github.com/palantir/blueprint/commits/develop/packages/core).

Add directory details to packages/*/package.json

---

packages/datetime/package.json
packages/icons/package.json
packages/labs/package.json
packages/node-build-scripts/package.json
packages/select/package.json
packages/table/package.json
packages/test-commons/package.json
packages/timezone/package.json
packages/tslint-config/package.json
packages/webpack-build-scripts/package.json

Specifying the directory as part of the `repository` field in a `package.json` allows third party tools to provide better support when working with monorepos. For example, it allows them to correctly construct a commit diff for a specific package.
This format was accepted by npm in https://github.com/npm/rfcs/pull/19.

Add directory to repository details in package.json files

---

packages/datetime/src/dateRangePicker.tsx
packages/datetime/src/daterangepicker.md
packages/datetime/test/dateRangePickerTests.tsx

- more obvious naming: `shouldChangeTime` &rArr; `includeTime`.
- this is **NOT AN API BREAK** as the original PR that added this prop was _merged today 1/17_ and this PR _will merge before_ the next release.
- 📖 add `Shortcuts` section to DRP docs
- revert unnecessary test changes.
(cc @yixunx)

[DRP] Shortcuts support changing time & docs

---

packages/datetime/src/dateRangePicker.tsx
packages/datetime/src/shortcuts.tsx

- turns out `IDateRangeShortcut` was defined _differently (after #3293)_ in two separate files!
- thankfully, this PR is __not__ an API BREAK because the offending type (in shortcuts.tsx) was not exported from the package root (or used at all outside its home file).

[DRP] dedupe shortcuts prop types

---

packages/core/src/components/forms/numericInput.tsx
packages/core/test/controls/numericInputTests.tsx

- add `NumericInput` `rightElement` prop

[NumericInput] new rightElement prop

---

packages/core/src/common/classes.ts
packages/core/src/components/forms/_controls.scss
packages/core/src/components/forms/controls.tsx
packages/core/test/controls/controlsTests.tsx
packages/docs-app/src/examples/core-examples/switchExample.tsx

This adds the ability to put text inside a switch when both active and inactive. 
Is structuring these text elements as children of the control indicator appropriate? 
Whats the best way to ensure appropriate font size/vertical spacing in both regular and large switch mode?

Add internal text to switch component

---

packages/core/src/components/spinner/spinner.tsx
packages/core/test/isotest.js

- change `Spinner.SIZE_SMALL` from 24 to 20 so it fits with other sizes used in blueprint. 24 was unique...

[Spinner] SIZE_SMALL = 20

---

packages/core/src/common/utils.ts
packages/core/test/common/utilsTests.tsx

countDecimalPlaces returns decimal places for all number notations and do not covert the number to string (faster):
```
console.log(Utils.countDecimalPlaces(1e-10));
// expected output 10
console.log(Utils.countDecimalPlaces(NaN));
// expected output 0
```
countDecimalPlaces from packages/core/src/common/utils.ts

countDecimalPlaces for number type

---

packages/core/src/components/popover/popoverSharedProps.ts

In pr [#2617](https://github.com/palantir/blueprint/pull/2617) the type of the `onInteraction` prop was [changed](https://github.com/palantir/blueprint/commit/f111cdccd166053cded030fbcbab60239d6e5d17#diff-526f9b7061d074b106ee2b67a5dafc14L122) to no longer include the event as the second argument (added as part of [#2340](https://github.com/palantir/blueprint/issues/2430)). However the the code still [conforms to the previous interface](https://github.com/palantir/blueprint/blob/9728e61b420eda381cedce06166a4caf6b958bc4/packages/core/src/components/popover/popover.tsx#L501). All I've done is change it back to what it was so I've not included tests, docs changes etc. 🙂

Corrected the type of Popover's onInteraction prop

---

packages/core/src/components/button/_button-group.scss
packages/docs-app/src/examples/core-examples/buttonGroupPopoverExample.tsx
packages/docs-app/src/styles/_examples.scss

Update <ButtonGroup /> styling to allow Popover Buttons nested in ButtonGroups to fill up all available space.
**Before:**
**After:**

Fill Popover Buttons in <ButtonGroup />

---

packages/core/src/components/popover/popover.tsx
packages/core/src/components/slider/handle.tsx
packages/core/src/components/slider/multiSlider.tsx
packages/core/src/components/spinner/spinner.tsx
packages/core/test/popover/popoverTests.tsx
packages/datetime/src/datePicker.tsx
packages/datetime/src/dateRangePicker.tsx
packages/datetime/test/dateInputTests.tsx
packages/datetime/test/datePickerTests.tsx
packages/datetime/test/dateRangePickerTests.tsx
packages/datetime/test/dateTimePickerTests.tsx
packages/docs-app/src/components/colorPalettes.tsx
packages/docs-app/src/components/navIcons.tsx
packages/docs-app/src/examples/core-examples/collapseExample.tsx
packages/docs-app/src/examples/core-examples/nonIdealStateExample.tsx
packages/docs-app/src/examples/core-examples/panelStackExample.tsx
packages/docs-app/src/examples/core-examples/popoverExample.tsx
packages/docs-app/src/examples/datetime-examples/common/formatSelect.tsx
packages/docs-app/src/examples/datetime-examples/dateRangePickerExample.tsx
packages/docs-theme/src/components/navButton.tsx
packages/docs-theme/src/components/navMenuItem.tsx
packages/docs-theme/src/components/typescript/enumTable.tsx
packages/docs-theme/src/components/typescript/interfaceTable.tsx
packages/node-build-scripts/package.json
packages/select/test/omnibarTests.tsx
packages/table-dev-app/src/features.tsx
packages/table-dev-app/src/mutableTable.tsx
packages/table/test/locatorTests.tsx
packages/tslint-config/package.json
yarn.lock

- upgrade `tslint` and related packages
- fix all the fails (all of them were `--fix`able)
- does this count as a major version rev of `@blueprintjs/tslint-config`? I don't think so.

🔧 upgrade tslint

---

packages/core/src/components/tabs/tab.tsx
packages/core/src/components/tabs/tabs.md
packages/core/src/components/tabs/tabs.tsx
packages/core/test/tabs/tabsTests.tsx
packages/docs-app/src/examples/core-examples/tabsExample.tsx

Related to #3317, but doesn't really fix it. 
This PR adds a `panelClassName` prop to Tab component to let users add a class name to tab panel container. An existing `className` prop affects _both_ tab and tab panel, which is not always desirable.  
I think I have updated prop description in tabs/tab.tsx correctly but I couldn't figure out how to get it displayed in docs. I need help to check if panelClassName prop description is correctly displayed.

[Tabs] add panelClassName prop

---

packages/core/src/common/_mixins.scss
packages/core/src/components/tree/_tree.scss
packages/docs-app/src/examples/core-examples/treeExample.tsx

Fixed not applying intent color for icons inside tree component
Is there a better solution to fix this?
https://68-144397854-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html#core/components/tree

[Core] Fixed incorrect intent color for <Icon /> inside <Tree />

---

packages/core/src/components/tree/_tree.scss
packages/core/src/components/tree/treeNode.tsx
packages/core/test/tree/treeTests.tsx
packages/docs-app/src/examples/core-examples/treeExample.tsx

Add option to disabale tree node
Should I organize scss rules changes in different way? Is more tests needed?
https://61-144397854-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html#core/components/tree

[Core] Add option to make tree node disabled

---

packages/core/src/components/drawer/drawer.tsx

Updated 'isCloseButtonShown' prop at 'Drawer' not to be defaulted regularly (through defaultProps) because of prop validation would throw error for default props (title == null && isCloseButtonShown == true).
Simply updated the way of defaulting `isCloseButtonShown` prop, to avoid unnecessary warnings.
Nothing specific, small PR

Drawer default prop warning fix

---

packages/core/src/components/overlay/overlay.tsx

The default is actually 300: https://github.com/gabeboning/blueprint/blob/develop/packages/core/src/components/overlay/overlay.tsx#L176
This updates the comment/documentation to match.

Update `<Overlay>` transitionDuration comment

---

packages/core/src/components/forms/controls.tsx

Fixes #3408
I don't think `input.indeterminate` should ever be null, but we can avoid the snapshot testing bug raised in #3408 by simply checking if `this.input` is a valid ref.

[Core] Checkbox: fix indeterminate state update

---

packages/core/src/components/forms/text-inputs.md

[Core] Docs: fix small typo

---

packages/docs-app/src/examples/core-examples/overlayExample.tsx
packages/docs-app/src/styles/_examples.scss

Add button to the Overlay content in the docs example that makes the Overlay container need to scroll

[Docs] Overlay Example: add button to toggle scrolling behavior

---

packages/datetime/src/dateInput.tsx
packages/datetime/src/datePicker.tsx
packages/datetime/src/datePickerCore.tsx
packages/datetime/src/dateRangeInput.tsx
packages/datetime/src/dateRangePicker.tsx

The origin link to `http://react-day-picker.js.org/Modifiers.html` is 404, and it can not be redirected to a correct page.

fix: fix react-day-picker api link broken

---

packages/docs-app/src/examples/select-examples/multiSelectExample.tsx

Change secondary return on ternary operator to be undefined rather than null. The rightElement property of tagInputProps takes either an Element or undefined, but not null. The current example has it being passed null if the length of films is 0.

set clearButton ternary to return undefined

---

packages/select/src/components/query-list/queryList.tsx

Links https://github.com/palantir/blueprint/issues/3425

[Select] hide QueryList item list when menuContent and createItemView are both null

---

packages/core/src/components/tag-input/tagInput.tsx
packages/core/test/tag-input/tagInputTests.tsx
packages/docs-app/src/examples/select-examples/films.tsx
packages/docs-app/src/examples/select-examples/multiSelectExample.tsx
packages/select/src/common/listItemsProps.ts
packages/select/src/common/predicate.ts
packages/select/src/components/query-list/queryList.tsx
packages/select/src/components/select/multiSelect.tsx
packages/select/test/queryListTests.tsx

Allow pasting of multiple values in `MultiSelect`.
The clipboard contains separated values (where the separator is configurable via `tagInputProps.separator`):
* Select multiple _existing_ items on paste:
* _(If the "Create item" option is enabled)_
Select a combination of _existing_ and _newly created_ items on paste:
* _(If the "Create item" option is enabled)_
Select all _newly created_ items on paste:
* _(UX nicety)_
If a pasted value is already selected, set that item as the active item on paste:
_In general, the code moves the active item to the final existing item amongst the pasted values._
I originally tried to implement this outside of `MultiSelect` in a wrapping component (by listening to `tagInputProps.onAdd`, which is invoked when values are added via paste), but that didn't …

[MultiSelect] Enable pasting of multiple values (same as TagInput)

---

packages/core/src/components/panel-stack/_panel-stack.scss

Add a z-index property to the panel-stack-header class to not allow later DOM elements to overlay
Potential other solutions

Add z-index to panel stack header

---

packages/core/src/components/forms/text-inputs.md
packages/core/src/components/forms/textArea.tsx
packages/core/test/forms/textAreaTests.tsx
packages/core/test/index.ts

Add a default-false prop to `TextArea`: `growVertically`. When set to `true`, the text area will expand vertically to accomodate all the user's input without scrolling.
Does this break any existing behavior?

Add option to grow text area with input

---

packages/core/src/components/forms/textArea.tsx
packages/core/test/forms/textAreaTests.tsx

Fixes https://github.com/palantir/blueprint/pull/3398#discussion_r268290146

[Core] TextArea: fix style object regression

---

packages/table/src/headers/header.tsx
packages/table/src/table.tsx

Prop documentation updates for `ITableProps.enableRowResizing` and `IHeaderProps.isResizeble` to show that they both default to true instead of false.
The underlying [Resizable Component](https://github.com/zelein/blueprint/blob/develop/packages/table/src/interactions/resizable.tsx#L19) defaults to true and can be seen on [L77](https://github.com/zelein/blueprint/blob/develop/packages/table/src/interactions/resizable.tsx#L77) defaulting to true

Table props documentation updates

---

CHANGELOG.md
README.md
package.json
packages/docs-app/src/whats-new-3.0.md
packages/landing-app/src/index.html

- Switch to standard Apache-2.0 license (#3457)
- Checkbox: fix indeterminate state update (#3409)
- TagInput: use undefined instead of null to hide clearButton (#3436)
- PanelStack: Add z-index to panel stack header to fix layout issue (#3414)
- TextArea: Add `growVertically` prop to allow component to grow height with input text (#3398)
- Drawer: Add `position` prop, deprecate `vertical` prop (#3386)
- Switch to standard Apache-2.0 license (#3457)
- Fix react-day-picker API hyperlink in documentation (#3435)
- Switch to standard Apache-2.0 license (#3457)
- Switch to standard Apache-2.0 license (#3457)
- Select: hide QueryList item list when menuContent and createItemView are both null (#3426)
- MultiSelect: Enable pasting of multiple values (same as TagInput) (#3428) 
- Switch to …

Prepare release v3.15.0

---

packages/datetime/src/dateInput.tsx

Add support for IE11 by using this check: https://stackoverflow.com/a/49325196
Tested under IE11, Firefox (60 ESR) and Chrome (73).
Note: testing under IE11 was slightly hindered by the fact that `yarn dev` (or `yarn dev:datetime`) gives an error: 
so I had to test it using our own application. And while testing the fix under Chrome, it turned out that `this.popoverContentEl` was sometimes `null` (hence the comment and the extra check).
Also, `yarn.lock` in `develop` appears out of date.

[datetime] Fix DateInput under Internet Explorer 11

---

packages/core/package.json
packages/core/test/overflow-list/overflowListTests.tsx
packages/core/test/popover/popoverTests.tsx
packages/core/test/text/textTests.tsx
packages/datetime/package.json
packages/datetime/src/datePickerCaption.tsx
packages/datetime/test/datePickerCaptionTests.tsx
packages/docs-data/package.json
packages/icons/package.json
packages/labs/package.json
packages/landing-app/package.json
packages/select/package.json
packages/table/package.json
packages/test-commons/package.json
packages/test-react15/package.json
packages/timezone/package.json
yarn.lock

Fixes #3265
- Fix dependency ranges for packages within this repo after the latest minor version releases
- Upgrade react-day-picker to 7.3.0
- Regenerate lockfile (some minor / patch bumps in dev dependencies)
- Minor bumps of enzyme-related dependencies
- Fix some test suites to better use `ReactWrapper#update()` and clean up after themselves
Ported some changes from https://github.com/palantir/blueprint/pull/3279 (thanks @sokmeann!)

Upgrade react-day-picker, fix caption months support, regen lockfile

---

packages/core/src/components/forms/numeric-input.md

- Updated documentation
Made initial state of NumericInput value as NumericInput.VALUE_EMPTY instead of null
NumericInput documentation update

Fix for NumericInput throws type error when value=null #3479

---

packages/core/src/components/popover/popover.md

- Incorrectly showed up as strikethrough text on https://blueprintjs.com/docs/#core/components/popover

Fix accidental markdown strikethrough

---

packages/datetime/src/dateRangePicker.tsx
packages/datetime/test/dateRangePickerTests.tsx

Add a check to prevent hacking the initial month if singleMonthOnly is true. This was causing it to render the previous month if initialMonth was the same month as maxDate.
I think line 197 only considered for when two months are shown. (See the comment on line 191)
Any details about DateRangePicker that I may be unaware of. I recreated the issue locally and tested the fix with a yarn link. Here is a code snippet that will recreate the issue: 
```
<DateRangePicker singleMonthOnly initialMonth={new Date(2019, Months.MAY, 6)} minDate={new Date(2019, Months.MARCH, 3)} maxDate={new Date(2019, Months.MAY, 6)}/>
```

do not hack date if showing singleMonthOnly

---

packages/select/src/components/query-list/queryList.tsx
packages/select/test/queryListTests.tsx

Seems https://github.com/palantir/blueprint/pull/3072 broke the activeItem changing when items change. This is a better fix for the original issue.
- [ X ] Includes tests
- setQuery runs when when query changes
- remove the guard in part of setQuery to see if the query changed

Change activeItem when items change

---

packages/core/src/components/forms/_control-group.scss

Removed `position: relative;` which was there to create a new stacking context.
Not sure why this caused the issue but there is already `z-index` to create a stacking context, `position: relative` may not be needed.

[core] Fix number of clicks required to use HTMLSelect inside ControlGroup in Firefox

---

packages/core/src/components/tag-input/_tag-input.scss

Flexboxes default values for `min-width` is always `auto`. This means that that the size for that element will be at least its contents size.
This problem shows in the TagInput component where if the tag is too large it's going to overflow the container ignoring the parent width. The fix for that is just setting min-width to be 0 in the container (tag-input-values).
Before: 
After:

Fix TagInput's Tags overflowing the container

---

packages/core/src/components/panel-stack/panelStack.tsx
packages/core/src/components/panel-stack/panelView.tsx
packages/core/test/panel-stack/panelStackTests.tsx
packages/docs-app/src/examples/core-examples/panelStackExample.tsx

In some use cases the header (back button + panel title) isn't actually needed. This PR adds a prop allowing the consumer to hide the header entirely. It is then their responsibility to allow closing panels.

[core] Allow hiding panel stack header

---

packages/core/src/components/button/abstractButton.tsx

React recently updated the typings for HTML button's `type` field from `string` to a more limited union. See: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L1848 for the current types. 
This is currently an issue for folks on newer versions of react typings since `IButtonProps` is no longer assignable to the props for `Button`.

Update abstract button props to match react's.

---

packages/core/src/components/collapse/collapse.md

Blueprint contains a lint rule that fails when you use non-Blueprint versions of certain HTML components, including `pre`. This PR modifies the documentation for the `Collapse` component to use the Blueprint `Pre` component instead of HTML `pre` to avoid the lint rule failure.

Use Blueprint Pre component in Collapse example

---

packages/core/src/common/errors.ts
packages/core/src/components/panel-stack/panelStack.tsx
packages/core/test/panel-stack/panelStackTests.tsx

Allows working around #3173. I personally need this to start with multiple panels.
Allow controlling the panel stack from the outside to have greater control over the exact panels rendered.

[core] Add controlled mode to PanelStack

---

packages/datetime/src/dateRangeInput.tsx
packages/datetime/test/dateRangeInputTests.tsx

The `disabled` prop will first read from `getInputProps` before `this.props.disabled`.
Ensuring tests cover all use cases.

Consumers of DateRangeInput can now disable specific date inputs.

---

packages/table/src/headers/rowHeaderCell.tsx
packages/table/test/index.ts
packages/table/test/rowHeaderTests.tsx

This adds a `nameRenderer` property to `RowHeaderCell` so you can do custom JSX in the row header. This is virtually identical to the `nameRenderer` functionality in the `ColumnHeaderCell`
There were no specific tests for `RowHeaderCell`, so I added them - copying `columnHeaderCell.tsx` directly, and then adapting or removing the tests as appropriate (the row header doesn't have a menu, for example)
If this will break anything in existing consumers (it shouldn't)
No visual impact without the nameRenderer in use, I will try to come up with an example or something

Add support for nameRenderer in RowHeaderCell

---

packages/tslint-config/src/rules/blueprintHtmlComponentsRule.ts
packages/tslint-config/test/rules/blueprint-html-components/true/all.tsx.fix
packages/tslint-config/test/rules/blueprint-html-components/true/all.tsx.lint

Added condition in `packages/tslint-config/src/rules/blueprintHtmlComponentsRule.ts` to check if its a table tag then proceed according.
Added some test to verify the changes in the rules.

fix tslint table error and add test

---

packages/datetime/src/timePicker.tsx

I couldn't find any way to write a test case for this. Changing input via `TestUtils.Simulate.change()` does not solve the problem since it enters a whole value. I've also tried with `TestUtils.Simulate.keyDown()` but no luck. I didn't have enough time to think about it, so I'll decide to open a PR. Maybe someone else has an idea how to test this?

[Datetime] Fix typing values into TimePicker's fields

---

packages/core/src/components/tooltip/tooltip.md

- Tooltips fails when using any of the target props if the target is a string, since there is nowhere to give the props to - eg. `targetClassName`

Update tooltip docs

---

packages/select/src/components/query-list/queryList.tsx
packages/select/test/selectComponentSuite.tsx

Fix crashing Select component, when trying to naivagte using keyboard, but all items are disabled
[`Docs preview`](https://25903-71939872-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html#select/select-component)

Fix crashing Select component

---

packages/select/src/components/query-list/queryList.tsx
packages/select/src/components/select/select.tsx
packages/select/test/selectTests.tsx

Added `disabled?: boolean` props to `QueryList` explicitly and handled `itemRenderer` invocation accordingly.

[select] fix: do not call itemRenderer when Select is disabled

---

packages/core/src/components/toast/_toast.scss

add word-break for long toast strings

[core] fix(Toast): long words in toast messages no longer break container layout

---

packages/core/src/_typography.scss
packages/core/src/components/callout/_callout.scss
packages/core/src/components/hotkeys/hotkeys.md
packages/core/src/components/popover/popover.md
packages/core/src/components/tooltip/tooltip.md
packages/datetime/src/dateFormat.tsx
packages/datetime/src/dateinput.md
packages/datetime/src/datepicker.md
packages/datetime/src/daterangeinput.md
packages/datetime/src/daterangepicker.md
packages/datetime/src/timepicker.md

Fixes #139
Fixes #1725 
Fixes #3621
Fixes #2931

Various documentation fixes

---

packages/core/src/components/forms/_controls.scss

[core] fix(Switch): tweak dark theme hover/active colors

---

packages/datetime/src/_datepicker.scss
packages/datetime/src/common/classes.ts
packages/datetime/src/datePicker.tsx
packages/datetime/test/datePickerTests.tsx
packages/docs-app/src/examples/datetime-examples/datePickerExample.tsx

Added `highlightCurrentDay` prop to toggle whether the current day should be highlighted in the calendar.
default prop value => `false`

[datetime] feat(DatePicker): add option to highlight current day

---

packages/core/src/components/hotkeys/hotkeysTarget.tsx
packages/core/test/hotkeys/hotkeysTests.tsx

Fixed typo of `keyDown` & `keyUp` props in `@HotkeysTarget` to `onKeyDown` & `onKeyUp`.

[core] fix(HotkeysTarget): typo with keyUp & keyDown in HotkeysTarget

---

packages/core/src/components/forms/textArea.tsx
packages/core/test/forms/textAreaTests.tsx

<TextArea  growVertically={true} /> should work like the second example in the link below
https://codesandbox.io/s/blueprint-sandbox-dfjbv
- componentDidMount implementation
- internal <textarea> ref
- naming and English expression 
N/A

Make <TextArea growVertically={true}/> size appropriately to the initial contents

---

packages/table-dev-app/src/features.tsx
packages/table/src/headers/editableName.tsx
packages/table/test/editableNameTests.tsx

The re-rendering was due to the passing of an anonymous function thereby removing it.

remove anonymous function, fix docs in <EditableName component and add test

---

package.json
packages/core/package.json
packages/core/src/common/utils/compareUtils.ts
packages/core/test/common/utils/compareUtilsTests.ts
packages/datetime/package.json
packages/docs-theme/package.json
packages/icons/package.json
packages/labs/package.json
packages/node-build-scripts/package.json
packages/select/package.json
packages/table/package.json
packages/test-commons/package.json
packages/timezone/package.json
yarn.lock

⚠️ Breaking changes ⚠️ 
- [core] Removed `getShallowUnequalKeyValues` utility function. This function was not used in any blueprint packages or palantir internal repos, so it feels safe enough to remove.

chore: upgrade to typescript 3.5.3

---

packages/datetime/src/dateRangeInput.tsx
packages/datetime/test/dateRangeInputTests.tsx

Selected date in the state and the changed date are checked using the `areSameTime` date-util to 
determine if the user has changed any `<TimePicker />` values. If timepicker values are updated then the popover is kept open.

[datetime]fix (dateRangeInput): DateRangeInput should not close on selection when time inputs receive key presses

---

packages/core/src/components/editable-text/editableText.tsx

HTMLInputElement supports `selectAllOnFocus` method only on inputs
with type text, search, url, tel and password.
Check type of `HTMLInputElement` in `EditableText` component before calling `selectAllOnFocus` method because it throws on inputs with certain types.
Should `inputSupportsSelection` function be left in `editableText.tsx` or placed somewhere in `common/utils` or extracted and published as a standalone npm module?

Fix crashing on inputs with type number.

---

.vscode/settings.json
packages/core/src/components/popover/popover.tsx
packages/core/test/popover/popoverTests.tsx

[core] fix(Popover): only apply active class to target in uncontrolled mode

---

packages/docs-app/src/blueprint.md
packages/docs-app/src/principles.md

[docs-app] create "Design Principles" section, mention CSS API contract

---

packages/core/src/components/drawer/_drawer.scss

Correcting use of $dialog-padding to $drawer-padding
Can't isolate drawer.scss because it incorrectly uses $dialog-padding variable instead of $drawer-padding
I guess build of individual components? Specifically, the Drawer component styles
N/A

Use variable $drawer-padding

---

packages/core/src/common/classes.ts

Since create-react-app passes only variables starts with REACT_APP_, this PR catchs this variable too.

create-react-app environment variable

---

packages/table/src/cell/editableCell.tsx
packages/table/test/editableCellTests.tsx

Pass `tabIndex` prop from `<EditableCell` to `<Hotkeys`

[table] fix(EditableCell): support tabIndex prop correctly

---

packages/datetime/src/common/dateUtils.ts
packages/datetime/src/dateRangeInput.tsx
packages/datetime/src/dateRangePicker.tsx
packages/datetime/src/shortcuts.tsx
packages/datetime/test/dateRangeInputTests.tsx
packages/datetime/test/dateRangePickerTests.tsx
packages/docs-app/src/examples/datetime-examples/dateRangePickerExample.tsx

add `selectedShortcutIndex` and `onShortcutChange` props to `<DateRangePicker`

[datetime] feat(DateRangePicker): add active menu styles to shortcuts

---

packages/core/src/components/menu/menuItem.tsx

Error in console:
```
react-dom.development.js?4646:545 Warning: React does not recognize the `labelClassName` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `labelclassname` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
in a (created by Blueprint3.MenuItem)
in li (created by Blueprint3.MenuItem)
in Blueprint3.MenuItem (created by HomePage)
in ul (created by Blueprint3.Menu)
in Blueprint3.Menu (created by HomePage)
...
```

Do not pass labelClassName to HTML element.

---

packages/core/src/components/toast/toaster.tsx

According to https://github.com/palantir/blueprint/blob/06a186c90758bbdca604ed6d7bf639c3d05b1fa0/packages/core/src/components/toast/toaster.tsx#L91 only top and bottom are supported.

[core] docs(Toaster): fix position prop comment

---

packages/core/src/components/slider/multiSlider.tsx
packages/core/test/slider/multiSliderTests.tsx

- [ x ] Includes tests
- [  ] Update documentation
Fixes a bug in the rendering of a multislider's track. As the values were sorted with a vanilla alphabetical .sort() rounding errors such as 1.2e-7 were sorted as higher than the value 1. This resulted in a track style of {left: "20.00%", right: "100.00%"}, which would not render on chrome (other browsers not tested)
Fairly simple change, would appreciate comments on the test as i'm new to frontend

Fix render bug with multislider track fill

---

packages/datetime/src/_timepicker.scss
packages/datetime/src/timePicker.tsx
packages/datetime/test/dateRangePickerTests.tsx
packages/datetime/test/timePickerTests.tsx

Text input is no longer immediately validated and rejected inside TimePicker. Instead, a "danger" intent is applied to the input if it is invalid, and the update is rejected upon blur.

[datetime] fix(TimePicker): allow more natural text entry

---

packages/select/src/components/select/suggest.tsx

No issue yet
Please advise if these items are needed.  inputProps are already documented and this commit just sets a default.
Set the default autocomplete HTML attribute to "off" so that browser drop downs don't render in front of the component menu options.
The default value set by this commit

[select] Default autoComplete for text input in <Suggest> to "off"

---

packages/core/src/common/props.ts
packages/core/src/components/tabs/tab.tsx
packages/core/src/components/tabs/tabTitle.tsx
packages/core/test/tabs/tabsTests.tsx

Spread extra props sent to the `<Tab>` onto the rendered `<div>` in the implementation of `<TabTitle>`.

[core] feat(Tab): spread HTML props to rendered div

---

packages/core/src/common/abstractComponent2.ts
packages/core/src/common/abstractPureComponent2.ts
packages/core/src/components/slider/multiSlider.tsx
packages/table/src/headers/header.tsx
packages/table/src/interactions/resizable.tsx
packages/table/src/table.tsx
packages/table/src/tableBody.tsx
packages/table/src/tableBodyCells.tsx
packages/table/test/selectionTests.tsx
packages/table/test/tableTests.tsx

Fixes some bugs from #3702 around the use of new lifecycle methods in `MultiSlider`, `Resizable` (table package), `Table`, and `TableBodyCells`.
Using the example from the bug report:

fix: lifecycle methods in MultiSlider, Resizable, and TableBodyCell

---

packages/core/src/components/breadcrumbs/_breadcrumbs.scss
packages/core/src/components/breadcrumbs/breadcrumb.tsx
packages/core/test/breadcrumbs/breadcrumbTests.tsx

Display `<Breadcrumb />`'s `icon` prop.

[core] feat(Breadcrumb): render icon if provided through props

---

packages/core/src/components/panel-stack/panelStack.tsx

Fix an issue where `<PanelStack />` could animate in the wrong direction.
`<PanelStack />` should only update its internal state via `componentDidUpdate()` when the `stack` length changes. Currently, pushing an item onto `stack` sets `direction: push`. As the `<PanelStack />` begins to animate, updating the `stack` without changing its length (i.e. updating a property in one of its `<IPanel />`s) will set `direction: pop`, leading to an unintended animation change.

[core] fix(PanelStack): do not trigger unintended animations

---

packages/docs-data/package.json
yarn.lock

chore: use latest tree-sitter-typescript from github

---

packages/core/src/components/tag-input/tagInput.tsx

[core] fix(TagInput): prevent infinite setState in componentDidUpdate

---

packages/datetime/src/index.ts

Export `IDateRangeInputProps` in the same fashion as other component proptypes.
Probably the single line of the diff.

Export IDateRangeInputProps from @blueprintjs/datetime.

---

packages/datetime/src/dateInput.tsx
packages/datetime/test/dateInputTests.tsx
packages/docs-app/src/examples/datetime-examples/dateInputExample.tsx
packages/docs-app/src/styles/_examples.scss

Add `fill` prop to DateInput which is forwarded to the contained Popover.

[datetime] feat(DateInput): add fill prop

---

packages/table/src/common/clipboard.ts

Use 'text' instead of 'text/html' or 'text/plain' in DataTransfer.setData so that table cell copy can work in IE11

[table] fix: cell copy to clipboard works in IE11

---

packages/select/src/common/classes.ts
packages/select/src/components/select/multiSelect.tsx
packages/select/test/multiSelectTests.tsx
packages/test-commons/src/utils.ts

[select] fix(MultiSelect): better handling of key events in TagInput remove buttons

---

packages/core/src/components/forms/_controls.scss

Added the use of variables `$switch-indicator-background-color-disabled` and `$dark-switch-indicator-background-color-disabled` in the mixin `indicator-colors`
Switch component

[core] fix(Switch): indicator background colors

---

packages/datetime/src/shortcuts.tsx

This ensures event.relatedTarget is properly populated when the date input box is blurred by clicking on the date picker popover shortcuts.

Include tabIndex for date picker shortcuts

---

packages/core/src/components/editable-text/editableText.tsx
packages/docs-app/src/examples/core-examples/editableTextExample.tsx

Same as https://github.com/palantir/blueprint/pull/3841 but on a 3.17.x release branch

[3.17.x] [core] feat(EditableText): add alwaysRenderInput experimental feature

---

packages/core/src/components/editable-text/editableText.tsx
packages/docs-app/src/examples/core-examples/editableTextExample.tsx

Add new prop `alwaysRenderInput` to make the component render an input which can, in theory, retain focus across `isEditing={true|false}` interactions.
Does this work in practice to solve the linked bug
Note that, at least right now, it doesn't work well with Blueprint's ContextMenu.

[core] feat(EditableText): add alwaysRenderInput experimental feature

---

packages/core/src/components/drawer/_drawer.scss

I added the variables `$drawer-background-color` and `$dark-drawer-background-color`. So colors can be set in variables, not overridden in CSS
Drawer component
N/A

[core] feat(Drawer): add Sass variables for background color

---

packages/core/src/components/tag-input/_tag-input.scss

Add `intent` to `active` class

[core] fix(TagInput): add intent styling when component is active

---

packages/core/package.json

This change explicitly declares the [dom4 side effect](https://github.com/palantir/blueprint/blob/3eef70e0b8b1bcce9de0836dbe2e28deff3ee8d9/packages/core/src/components/index.ts#L21) that is necessary for Blueprint to work in IE11 so that Webpack doesn't tree-shake it away.
Without this change, Webpack was stripping dom4 out of my build, which resulted in my app working fine in modern browsers but throwing errors such as this one in IE11:
```
Object doesn't support property or method 'closest'
```
I've tested this change locally by editing the `package.json` file in my `node_modules/@blueprintjs/core` directory and it works! IE11 no longer throws errors when the build includes this.

[core] fix: Explicitly declare dom4 side effects

---

packages/core/src/components/panel-stack/panelStack.tsx

Fix an issue where the PanelStack would not update when its props were changed.
In #3787 a change was made to only update the PanelStack if its stack length changed. Before that, a change to the stack would update the internal state of the animation and stack. This caused issues when 1) there were changes to the stack (but not its length) and 2) the component was animating, since it could trigger an animation in the opposite direction.
Unfortunately, it did not take into account that the stack could change without changing its length. This PR uses two different conditions to check if the stack has changed and if the animation direction needs to be updated.
This fixes an issue introduced in #3787.

Fix PanelStack

---

packages/datetime/test/datePickerTests.tsx

DatePicker unit tests started failing in December because
it relied on being able to press "next month". This change
sets the initial month to January.
DatePicker unit tests started failing in December because
it relied on being able to press "next month". This change
sets the initial month to January
Green unit tests

Fix DatePicker unit test

---

packages/core/package.json
yarn.lock

Upgrade `react-popper` to 1.3.7, which contains this fix for a page-crashing issue: https://github.com/popperjs/react-popper/pull/320

Update react-popper to include important bugfix

---

packages/core/package.json

Unfortunately, breaking the dom4 inclusion out to `configureDom4.js` in https://github.com/palantir/blueprint/pull/3868 allowed it to get tree-shaken away, again. We need to include the `index.js` files that include it in our side effects list so that webpack evaluates them.
My understanding of what was happening, following the model laid out [in the Webpack docs](https://webpack.js.org/guides/tree-shaking/#clarifying-tree-shaking-and-sideeffects), is:
* We import directly from the root `index.js` file, so it was included
* We don't import directly from the `components/index.js`, so it was skipped
* Since `components/index.js` was skipped, `configureDom4.js` was also skipped (even though it has side effects)
Previously, https://github.com/palantir/blueprint/pull/3867 included …

Include index.js files in sideEffects list

---

packages/core/src/components/toast/_toast.scss

When a toaster is positioned bottom, if any of the toasts are exited that aren't the first toast, the exit animation renders in the correct direction (down)

[core] fix(Toast): bottom toasts exit in the correct direction

---

packages/docs-app/src/examples/core-examples/formGroupExample.tsx

Previous version used duplicate id attributes, which is invalid.
It also had the label for the group of switches have a target,
where it probably makes sense for it not to.
No visual changes.

[examples] fix label id in formGroupExample

---

packages/core/src/components/forms/numericInput.tsx
packages/core/test/controls/numericInputTests.tsx

Fixes #3889 
Fixed situation when pass to `NumericInput` value as float number and it rounds incorrectly

[core] fix(NumericInput): correct rounding of default value

---

packages/docs-theme/src/styles/_layout.scss

remove `flex-wrap` cuz this shouldn't wrap?
seen in Chrome 79:

[docs] fix wrapping docs title

---

packages/core/src/components/toast/_toast.scss

removed a ```bottom: auto; ``` css line as it was cutting off the shadow of a toast and doesn't seem to add any other functionality.

[core] fix(Toast): bottom shadow is no longer clipped

---

packages/core/src/components/popover/popover.md

[core] docs(Popover): fix text referencing "dismiss" buttons in example

---

packages/core/src/components/editable-text/editableText.tsx
packages/core/test/editable-text/editableTextTests.tsx

[core] fix(EditableText): allow setting value to null in controlled mode

---

packages/core/src/components/overlay/overlay.tsx

Fixes #3928 by adding a type check when the event's target is not an HTML Element.
I'd appreciate it if a maintainer would write a test for this case. I only reproduced this in our environment when debugging it, and honestly I'm currently not very strong in JavaScript circa 2020 (especially testing in it).
None, this was done in order to remove an error that showed up in the console, and caused the app to crash in development mode via create-react-app.
(also, queue joke for ex-Palantirian still making a code contribution to Blueprint)

Add type check for Overlay focus element.

---

packages/table/src/common/utils.ts
packages/table/src/headers/columnHeaderCell.tsx
packages/table/src/headers/header.tsx

- fixes `ColumnHeader.handleResizeDoubleClick` with enabled ColumnReordering and menuRenderer
- added `bp-table-text-no-measure` class to header's maybeRenderReorderHandle
- added `bp-table-text-no-measure` class to columnHeaderCell's maybeRenderDropdownMenu
- modified **packages/table/src/common/utils.ts** `measureTextContentWithExclusions` logic
- I searched through the code, `measureTextContentWithExclusions` is used only at `handleResizeDoubleClick`, so I assumed that it would be ok to modify it
- I modified `measureTextContentWithExclusions` as it is possible to have both ColumnReordering and menuRenderer icons inside header
- I removed dom manipulations at `measureTextContentWithExclusions`, and replaced it with metrics computation
- added `EXCLUDED_ICON_PLACEHOLDER_WIDTH` constant …

[table] fix: column resize calculation on header double click

---

.eslintignore
packages/core/src/common/constructor.ts
packages/core/src/common/errors.ts
packages/core/src/common/position.ts
packages/core/src/common/utils.ts
packages/core/test/common/utils/compareUtilsTests.ts
packages/core/test/overlay/overlayTests.tsx
packages/core/test/popover/popperUtilTests.ts
packages/core/test/toast/toasterTests.ts
packages/icons/src/iconName.ts
packages/landing-app/src/logo.ts
packages/node-build-scripts/es-lint.js
packages/select/test/listItemsPropsTests.ts
packages/table/src/common/utils.ts
packages/table/src/interactions/resizeSensor.ts
packages/table/test/clipboardTests.ts
packages/table/test/regionsTests.ts

Including some FLUPs and cleanup from recent PRs
changelog here https://github.com/palantir/blueprint/wiki/3.x-Changelog#january-23-2020

Prepare release

---

.eslintignore
.eslintrc.json
packages/eslint-config/index.js
packages/eslint-config/package.json
packages/eslint-config/tslint.json
packages/node-build-scripts/es-lint.js

eslint-config:
- 🔧 fix package reference to `@blueprintjs/tslint-config`, allowing this package to be used outside the Blueprint monorepo
node-build-scripts:
- 🔧 fix(es-lint): use default ESLint resolution to find config file
- feat(es-lint): support resolution of `.eslintignore` file at the root of a git repo (useful for monorepos like Blueprint's)
- feat(es-lint): support arbitrary additional arguments to `eslint` CLI

fix: eslint-config package reference, improve es-lint build script

---

packages/core/src/components/panel-stack/_panel-stack.scss
packages/core/src/components/panel-stack/panelStack.tsx
packages/core/test/panel-stack/panelStackTests.tsx
packages/docs-app/src/examples/core-examples/panelStackExample.tsx

A new `renderCurrentPanelOnly` prop, which is `true` by default to preserve the backward compatibility, which allows the panels to preserve their state while being hidden.
My current implementation does not work _yet_ though - do read the code comments.
Nothing specific.

[core] feat(PanelStack): add renderCurrentPanelOnly prop

---

packages/core/src/components/panel-stack/panel-stack.md
packages/core/src/components/panel-stack/panelStack.tsx
packages/core/test/panel-stack/panelStackTests.tsx
packages/docs-app/src/examples/core-examples/panelStackExample.tsx
packages/docs-app/src/styles/_examples.scss

- rename renderCurrentPanelOnly -> renderActivePanelOnly
- add to docs example to demonstrate the effect of the new prop

[core] fix(PanelStack): rename prop and other fixes

---

packages/core/src/components/html-select/_html-select.scss

In Firefox when using dark mode all option elements are styled the same regardless of if they are disabled or not. Reproduced with Firefox for Mac OS and Windows.
Set the color for option:disabled to $pt-dark-text-color-disabled
In the select "bar" is disabled. Edit: Updated to show correct screenshots.
Before:
After:

Fix disabled option color in dark mode for Firefox

---

packages/core/src/components/forms/inputGroup.tsx

Reverted a change that stopped updating input field padding when right element changed. Infinite update is fixed by a check to see if the rightElement prop changed.
Before
After

fix right element padding adjusting on update

---

packages/select/src/components/query-list/queryList.tsx
packages/select/src/components/select/suggest.tsx
packages/select/test/suggestTests.tsx

Make setActiveItem public so the parent components can reset the activeItem
when necessary.
When the Suggest Popover is closed and there is a selectedItem the activeItem
should always be set to selectedItem.  When the Popover is opened again the
value of the component is reflected correctly.
Make setActiveItem in the QueryList component a public function so that parent components can call it.  I saw similar behavior in setQuery already and I believe this is a decent compromise so that parent components (Select, Suggest, any other components that are added to this library in the future) do not have to add the boilerplate of keeping track of the active item since QueryList already does this.  It is only in the case of closing a Popover that this "reset" needs to happen.
The public / private …

[select] feat(Suggest): sync activeItem with selectedItem on popover close

---

packages/datetime/src/common/dateUtils.ts
packages/datetime/src/dateRangePicker.tsx

fixes #3970
fixes #3838
For quite some time (since the beginning of this open source repo), the behavior for this component has been to use `null` to represent unbounded ranges. The type definition has been wrong about this, while the documentation was correct. I think the simplest and safest thing to do here is to fix the typedef to correctly declare `null` instead of `undefined`.

[datetime] fix(DateRange): values are possibly null, not undefined

---

packages/core/src/components/forms/numericInput.tsx
packages/core/test/controls/numericInputTests.tsx

[core] feat(NumericInput): supply input element to onValueChange

---

packages/docs-app/src/examples/core-examples/breadcrumbsExample.tsx

[docs-app] feat(BreadcrumbsExample): render current as input

---

packages/core/src/components/tag-input/tag-input.md
packages/core/src/components/tag-input/tagInput.tsx
packages/core/test/tag-input/tagInputTests.tsx

Allows users to press `DELETE` on their keyboards to delete an item from `<TagInput />`, which in turn is used by the `Select` family of components.
Handling `DELETE` to remove item mimics the way `DELETE` works in a text editor, where an user can delete from the beginning of the line forward. Reaching the end of the line, in our case passing the last selected item in `<TagInput />` will stop deleting. Moving the selection to the first item and deleting from that point onwards repeatedly will delete all the selected items.
- Maybe `DELETE` was not implemented on purpose, if that's the case then ignore this PR.
- Ensure new behavior is in the spirit of Blueprint
- Ensure this change is compatible with other components, since I know other components depend on `<TagInput />`

[core] feat(TagInput): handle delete to remove items

---

packages/datetime/src/datepicker.md

Improved the documentation for the localization of Datetime components.
The current example doesnt work, as it is using the default LocaleUtil implementation which just implements english language ( https://github.com/gpbl/react-day-picker/blob/v7.3.0/src/LocaleUtils.js )
I've added an example following the example in the documentation of react-day-picker to implement localization using moment  ( http://react-day-picker.js.org/docs/localization ), and added a link pointing towards this page, for people needing more detailed example on how to actually override the LocaleUtil functions on the default implementation.

Improved documentation for localization of Datetime components

---

packages/core/src/docs/colors.md

I was a little puzzled that I could not import colors into my less file, until I realized that the example given in the documentation was only for Sass, so I added an example for Less.
Whether this adheres to your documentation style.

Add example to import variables into Less file

---

packages/select/src/components/select/multiSelect.tsx

Changed code in MultiSelect to stop corrupting existing `inputProps`.
Not related to this PR, but BP should consider taking a similar approach for other components to avoid corrupting props.  It is an anti-pattern for components to mutate its own props.

Fix repeated classname in MultiSelect inputProps

---

README.md

Adds some necessary steps in the one-time setup portion for those running on Windows.  The build tooling in BlueprintJS requires these steps.

Added windows documentation

---

packages/core/src/components/forms/numericInput.tsx
packages/core/test/controls/numericInputTests.tsx

When the value of a NumericInput is at max disable the increment button and when the value is at min disable the decrement button.

[core] feat(NumericInput): disable buttons when value at min/max

---

.eslintignore
.eslintrc.json
.vscode/extensions.json
.vscode/settings.json
packages/core/package.json
packages/eslint-config/README.md
packages/eslint-config/package.json
packages/eslint-plugin-blueprint/package.json
yarn.lock

eslint now works properly inline as a linter and formatter in vscode

chore: upgrade (typescript-)eslint, adjust VSCode settings

---

packages/core/src/common/classes.ts
packages/core/src/common/errors.ts
packages/core/src/common/props.ts
packages/core/src/components/forms/_input-group.scss
packages/core/src/components/forms/inputGroup.tsx
packages/core/test/controls/inputGroupTests.tsx
packages/docs-app/src/examples/core-examples/inputGroupExample.tsx

Related discussion: https://github.com/palantir/blueprint/issues/4039#issuecomment-612308331
This PR adds a new `leftElement` to the `InputGroup`, which should allow users a better option for injecting left-aligned content than the current `leftIcon` prop.  The current `leftIcon` prop allows content, but is not styled in a good enough way to align things correctly.
This PR uses the same approach as `rightElement` currently does for calculating necessary padding.  
It also adds the styling for the icon (color, margins, etc) that is currently being applied to leftIcon.  I chose to do this because I feel it may be common to add `<Icon>` in `leftElement`, for example when a custom icon is specified.
I modified the example in the docs to have one usage.  I felt it was good to illustrate how it …

[core] feat(InputGroup): add leftElement prop

---

package.json
packages/node-build-scripts/package.json
packages/tslint-config/index.js
packages/tslint-config/package.json
scripts/verifyCleanLockfile.sh
yarn.lock

- upgrades to tslint 6.0 and tslint-react 5.0
- it turns out 6.1 has an unintentional breaking change where it requires ts 3.8 (see https://github.com/palantir/tslint/issues/4929). ts should be upgraded in a separate PR
- removes tslint-config-prettier since formatting rules were disabled in TSLint 6.0, making the config obsolete.
- adds some rule configuration to `@blueprintjs/tslint-config` to retain some of the stricter rules which were disabled in TSLint 6.0
- we should replace these with ESLint rules soon, but I wanted to keep this PR simple by avoiding changing of rule implementations

chore: upgrade to TSLint 6.0

---

packages/datetime/src/common/dateRange.ts
packages/datetime/src/common/dateUtils.ts
packages/datetime/src/dateRangeInput.tsx
packages/datetime/src/dateRangePicker.tsx
packages/datetime/src/dateRangeSelectionStrategy.ts
packages/datetime/src/index.ts
packages/datetime/src/shortcuts.tsx

When I develop a custom wrapper component for DateInput, I find utility functions in `./dateTime/src/common/dateUtils` pretty useful. I would like them to be exported, same as `Utils` from `packages/core`

Export DateUtils

---

packages/core/src/components/tag/_common.scss

Add vertical padding to "Tag" component for large style
Ratio between horizontal and vertical padding value should be decided. For default style, the ratio  between horizontal and vertical padding is 3 to 2. However, I followed 2 to 1 ratio for large style which is the current ratio for single line large tags.
There is no visual change for single line content.
For multiline content, the old version is:
The updated version for multiline content is:

Add vertical padding to "Tag" component for large style

---

packages/datetime/src/_datepicker.scss
packages/datetime/src/_timepicker.scss
packages/datetime/src/common/classes.ts
packages/datetime/src/datePicker.tsx

In order to fix the alignment of the time picker's buttons, a wrapper is added for the time picker component of date picker.
Before:
After

Fix date picker's time buttons alignment

---

packages/core/src/common/utils/index.ts
packages/core/src/common/utils/refUtils.ts
packages/core/src/components/button/abstractButton.tsx
packages/core/src/components/forms/inputGroup.tsx
packages/core/test/buttons/buttonTests.tsx
packages/datetime/src/dateInput.tsx
packages/datetime/src/dateRangeInput.tsx
packages/select/src/components/select/select.tsx
packages/select/src/components/select/suggest.tsx

Add support for `callback ref` and `ref hook` for `Button`, `Anchor Button` and `InputGroup`
Typing for the props(`elementRef`, `inputRef`)

Add support for callback ref and ref hook

---

packages/select/src/components/query-list/queryList.tsx
packages/select/test/selectComponentSuite.tsx

thanks to @AaronJRubin for the proposal in #4134... this is a slightly different implementation which avoids using `this.state` since this boolean flag shouldn't cause a re-render of the component
- N/A ~Update documentation~

 [select] fix(MultiSelect): create new item with IME 

---

packages/core/src/common/index.ts
packages/core/src/common/refs.ts
packages/core/src/common/utils/index.ts
packages/core/src/common/utils/refUtils.ts
packages/core/src/components/button/abstractButton.tsx
packages/core/src/components/button/buttons.tsx
packages/core/src/components/forms/inputGroup.tsx
packages/datetime/src/dateInput.tsx
packages/datetime/src/dateRangeInput.tsx
packages/select/src/components/select/select.tsx
packages/select/src/components/select/suggest.tsx

Follow-up from #4093 (heads up @tanmoyopenroot) to be less verbose and move the ref utils & types to be exported from the top-level of the core package.
remaining to do in this PR:

chore: refactor ref handler changes from #4093

---

packages/datetime/src/index.ts
packages/datetime/src/timePicker.tsx

Add more control over inputs in TimePicker. In some cases (e.g. navigation with hotkeys) it requires to control keydown, keyup, blur, focus events

Add focus and keyboard events control to TimePicker

---

packages/core/src/components/slider/handleProps.tsx
packages/core/src/components/slider/multiSlider.tsx
packages/core/test/slider/multiSliderTests.tsx

Add the following props to `MultiSlider.Handle`:
- `trackStyleBefore?: React.CSSProperties` 
- `trackStyleAfter?: React.CSSProperties` (takes prescedence over trackStyleBefore)

Add trackStyleBefore and trackStyleAfter to MultiSlider.Handle (#4116)

---

packages/datetime/src/timePicker.tsx
packages/docs-app/src/examples/datetime-examples/timePickerExample.tsx

If `autoFocus: true` is passed to TimePicker, set `autoFocus: true` for hour unit input.  
It will help to improve forms accessibility

Add autoFocus prop to TimePicker

---

packages/docs-data/compile-docs-data.js
packages/docs-theme/src/components/modifierTable.tsx
packages/docs-theme/src/components/typescript/methodTable.tsx
packages/docs-theme/src/tags/defaults.ts
packages/docs-theme/src/tags/index.ts
packages/docs-theme/src/tags/method.tsx
packages/table/src/docs/table-api.md

Add a table to docs-theme render methods
Use a @method tag to render methods
Similar functionality to the interface table but for methods
Before:
After:

Add a docs-theme table for rendering methods

---

packages/core/src/components/alert/_alert.scss

add a word-break in for alert-contents
Ensuring content inside Alert breaks the large word in order to prevent content from going off
the Alert container.

fix: ensured that Alert text does not overflow

---

packages/select/src/components/select/suggest.tsx

check for `refObject` or `callback` on popup interaction
Visual Test
Code used to test

fix(suggest): check for refObject or callback on popup interaction

---

packages/core/src/components/forms/numericInput.tsx
packages/core/src/components/forms/numericInputUtils.ts

Close loophole where IMEs could be used to inject invalid characters, and handle Japanese full-width number input.
Whether I should be using preventDefault or any other HTML event API things in my handler (doesn't seem necessary, but maybe there are edge cases?).
Before:
After:

[core] fix(NumericInput): enforce numeric chars only with IME

---

packages/select/src/common/itemListRenderer.ts

ItemListRenderer is expected to return `null` because [it's default implementation](https://github.com/palantir/blueprint/blob/c96f8d2f0f0d4684574bc90a989691df404e35a8/packages/select/src/components/query-list/queryList.tsx#L333-L351) can return null

Fix ItemListRenderer return type
