README.md
package.json
packages/core/package.json
packages/datetime/package.json
packages/docs/package.json
packages/landing/package.json
packages/table/package.json
scripts/prepRelease.sh

- Add description field to each `package.json` for better display on npmjs.org

Prepare Release 1.0.1

---

packages/core/src/components/context-menu/contextMenu.tsx

Fix small typo in context menu

---

docs/index.html
packages/landing/src/index.html

fixes #106 
editing the `docs/` dir directly cuz we need fix ASAP without an NPM release (only private package has changed).

fix package name on landing

---

docs/docs/index.html
packages/docs/src/index.html

Add initial-scale meta property to docs HTML

---

packages/docs/src/index.html
packages/landing/src/index.html
packages/landing/src/landing.tsx

Addressing Tony's feedback:
- sentence casing for features headings
- smart quotes to replace dumb quotes

Typographic fixes in landing

---

packages/landing/src/index.html

Pending: rebuild landing site, will batch it with this + #114 + #113

Condense copy to fix landing's pt-feature layout

---

docs/blueprint-landing.css
docs/blueprint-landing.js
docs/index.html
packages/landing/src/index.html

Rebuild landing site

---

packages/docs/src/components/styleguide.tsx
packages/docs/src/index.html
packages/landing/src/index.html

Fix hostname for GA

---

README.md

Also, remove a line about the location of compiled assets -- reading of this page already requires knowledge of NPM, and the next section explains how to download packages.

Clarify Blueprint's purpose in README

---

packages/landing/src/index.html

More accurate NPM install command on landing page

---

packages/core/src/_dark-theme.scss

Fix wording about dark theme switch location

---

packages/core/examples/collapsibleListExample.tsx
packages/docs/src/styles/_colors.scss

- adjust colors z-index (fixes #169)
- fix CollapsibleList example missing import

little docs fixes

---

packages/docs/src/components/navbar.tsx
packages/docs/src/styles/_navbar.scss

Turn docs logo into link to landing

---

packages/docs/src/styles/_layout.scss
packages/docs/src/styles/_navbar.scss
packages/docs/src/styles/_variables.scss

Fix dark docs header background color

---

packages/core/src/components/toast/_toast.scss

fix toast timeout docs

---

docs/blueprint-landing.css
docs/docs/docs.css
docs/index.html

Rebuild docs site with latest changes.

update docs site

---

packages/landing/src/index.html

Landing page copy tweaks.
I feel strongly that this is an improvement in wording.

Landing main copy wording tweaks

---

packages/core/examples/toastExample.tsx
packages/core/src/components/toast/_toast.scss

- Set link color to white for intent toasts
- Added a link inside the primary toast for demo

White links for intent toasts

---

packages/core/examples/menuExample.tsx

Update menu example

---

packages/table/src/index.ts

A non-conflicting merge between two branches caused
a duplicate identifier error. This commit de-dupes
the identifier.

Fix merged code

---

scripts/preview.sh

- Add another `\n` to preview comment message
- Replace `<b>` with `<strong>`

Bring back new line in PR preview

---

.github/ISSUE_TEMPLATE.md

Swap description for steps to reproduce

Add "steps to repro" to issue template

---

.github/PULL_REQUEST_TEMPLATE.md

We need the keyword "fixes" to actually close issues automatically when closing PRs

Update PR template to close issues when closing PRs

---

packages/core/src/components/_index.scss

Update React docs URL

---

packages/datetime/src/dateInput.tsx

- Properly check for null/undefined dates

Fix DateInput throws error on null dates.

---

packages/datetime/src/dateInput.tsx
packages/datetime/test/dateInputTests.tsx

- [N/A] Update documentation
Check for nulls and strings in `fromMomentToDate` and `fromDateToMoment`

Better handling of edge cases in DateInput data

---

gulp/sass.js
package.json
packages/core/package.json
packages/docs/package.json

- __Fixed__ removed `!default` statements from `variables.less` and `variables.scss`

Prepare Release v1.3.1

---

circle.yml

- capture dist/ directories as circle artifacts so we can see the compiled output of each package in every build. this will be helpful for reviewing build changes.
- allow preview comment from all branch owners, not just this repository. this should permit previews from forks, per https://github.com/palantir/blueprint/pull/349#issuecomment-266558309. (cc @adidahiya)

capture dist/ directories as circle artifacts

---

packages/core/package.json

Add @types/tether dependency to core package

---

packages/datetime/src/dateInput.tsx

- on input blur if field is empty, no errors appear

Fix DateInput component deleted value should not produce error

---

packages/core/src/components/dialog/dialog.tsx

remove comment about version 3.0

---

packages/core/src/components/spinner/_spinner.scss

Tweak colors used in dark spinner

---

.github/PULL_REQUEST_TEMPLATE.md

Addresses some of https://github.com/palantir/blueprint/issues/372
h/t @adidahiya

Add “Enable CI” in PR template

---

packages/core/src/_typography.scss
packages/docs/src/components/section.tsx

Set a font-size for `<pre />` elements.

Set a font-size for pre elements

---

packages/core/src/components/tooltip/tooltip.tsx

add backticks to HTML tag in tooltip props

---

packages/core/examples/dialogExample.tsx
packages/core/examples/nonIdealStateExample.tsx
packages/core/src/components/dialog/_dialog.scss
packages/core/src/components/non-ideal-state/_non-ideal-state.scss
packages/core/test/dialog/dialogTests.tsx

Proper sentence casing

---

packages/core/src/components/tabs/_tabs.scss

... solution for React applications.
There are other options, and I don't recommend it for our internal projects.
#509 brought this to my attention. This is a small wording change.

Don't endorse react-router as the standard

---

packages/core/src/common/classes.ts

* Added complementary classes for IntelliSense completion.

Added complementary classes

---

packages/core/src/components/button/buttons.tsx

Fix AnchorButton to expect HTMLAnchorElement props

---

packages/core/src/components/forms/_common.scss
packages/core/src/components/forms/_select.scss
packages/docs/src/styles/_sections.scss

- Add support for minimal `<select>`

Support for minimal-style select element

---

packages/datetime/src/index.ts

Export IDateInputProps from datetime

---

packages/docs/src/components/styleguide.tsx
tslint.json

Per https://github.com/palantir/blueprint/pull/542/files#r97858419

Ban Object.assign with TSLint

---

gulp/typescript.js
packages/table/preview/index.tsx
packages/table/preview/nav.tsx
packages/table/preview/perf.tsx
packages/table/preview/store.ts
packages/table/tsconfig.json

- new lint glob captures all source dirs
- fix lint failures in table/preview
- auto-fix is the best!
- disable rules in a few cases:
- many classes per file
- lots of multiline jsx + inline lambdas (easier to disable than refactor)

TSLint missing files (like table/preview)

---

CONTRIBUTING.md
scripts/artifactVariables.sh

**Fixes #372**
@giladgray Could you check if preview comments still work when PRing from a branch of this repo instead of a fork?

Fix preview comments for forks

---

packages/core/src/components/forms/controls.tsx

resolve Checkbox indeterminate warning

---

packages/core/src/components/button/abstractButton.tsx
packages/core/src/components/button/buttons.tsx

- **move most of the logic to `abstractButton.tsx`**
- `renderChildren()` and `getProps()` reduce duplicated render logic
- replace key handle switches with simple `if`
- rename key handlers to `handle*`

DRY Buttons components 

---

packages/landing/src/landing.scss

Fix will be obvious in preview.

Fix landing page tagline centering

---

CONTRIBUTING.md

Significant edits to CONTRIBUTING.md provide enough detail to get started and refer to wiki pages for canonical coding conventions.

edit CONTRIBUTING.md

---

packages/core/test/tree/treeTests.tsx

Hm... this worked when i tried uncommenting it locally?

Fix tree contextmenu test

---

packages/docs/src/components/propsTable.tsx
packages/docs/src/styles/_props.scss

[docs] enlarge code font size in props tables

---

packages/core/src/common/utils.ts

Does this solve usage in a `strictNullChecks` environment?

add undefined and null to safeInvoke signature

---

packages/core/src/components/tree/_tree.scss

`$blue3` -> `$pt-intent-primary`

Use primary intent color for selected tree node

---

packages/core/examples/editableTextExample.tsx
packages/core/examples/toastExample.tsx
packages/core/src/components/forms/_numeric-input.scss
packages/core/src/components/navbar/_navbar.scss
packages/core/src/components/popover/_popover.scss

Clean up some docs casing

---

packages/core/src/common/_mixins.scss

Will add needed contrast to tags
cc @pkwi

Increase colored text contrast in dark theme

---

packages/core/src/components/editable-text/editableText.tsx
packages/core/test/editable-text/editableTextTests.tsx

EditableText fires onChange on escape

---

gulp/util/webpack-config.js
packages/core/package.json
packages/core/src/components/_index.scss
packages/datetime/package.json
packages/table/package.json

- include `tslib` in `*.bundle.js` for simplicity
- namespace bundles inside `Blueprint` var: `Blueprint.Core`, `Blueprint.Datetime`, `Blueprint.Table`
- add "browser" (for unpkg) and "webpack" (to override "browser" in webpack) entries to package.json
- documentation

real unpkg support

---

packages/core/src/components/tree/tree.tsx
packages/core/test/tree/treeTests.tsx

Fix null reference bug in Tree code

---

packages/table/src/table.tsx

Changed error to warning for validate props

Don't throw Errors for non-Column children of Table

---

packages/core/src/common/_color-aliases.scss

Follow up from https://github.com/palantir/blueprint/pull/697

Update dark link color

---

packages/datetime/src/_common.scss
packages/datetime/src/_datepicker.scss
packages/datetime/src/_daterangepicker.scss

- Move common vars to common file
- Collapse BEM selectors
- Fix display of outside days (hidden in date range picker by default)

Refactor date picker styles

---

packages/core/package.json
packages/datetime/package.json
packages/table/package.json

- use "unpkg" field in package.json instead of "browser"

Fix package manifest files

---

docs/blueprint-landing.js
docs/docs/docs.css
docs/docs/docs.js
packages/core/package.json
packages/datetime/package.json
packages/docs/package.json
packages/landing/package.json
packages/table/package.json

- Fixed package manifests to work correctly with webpack (#777)
- Renamed Tabs2 module files to match component names
- `tab.tsx` &rarr; `tab2.tsx`
- `tabs.tsx` &rarr; `tabs2.tsx`

Prepare release v1.11.1

---

packages/core/src/components/popover/popover.tsx
packages/core/src/components/tooltip/tooltip.tsx

- add tetherOptions to Tooltip too
- clean up docs for Popover tetherOptions prop
follow-up from #750, cc @Binck360

Tooltip tetherOptions

---

docs/blueprint-landing.js

not exactly sure why it broke in the first place, but `npm run build:landing` fixed it handily.
merging this PR will instantly fix https://blueprintjs.com.

rebuild landing site so it works

---

docs/docs/docs.js
packages/datetime/src/dateRangePicker.tsx

Fix check for ordering of left and right views in DateRangePicker

---

packages/core/src/common/errors.ts
packages/core/src/components/slider/coreSlider.tsx
packages/core/test/slider/sliderTests.tsx

Slider throws error if given 0 for stepSize or labelStepSize

---

packages/table/src/headers/columnHeaderCell.tsx
packages/table/src/headers/rowHeaderCell.tsx

- Fix columnHeaderCell dropping user specified classnames

[Table] Include user specified classname in columnHeaderCell

---

packages/core/src/components/button/_common.scss

[Button] Fix disabled minimal button style

---

packages/table/preview/index.tsx
packages/table/src/cell/formats/truncatedFormat.tsx

Swap the default preformatted property for TruncatedFormat from true to false

[Table] Change the default for preformatted for formats

---

packages/datetime/examples/common/formatSelect.tsx
packages/datetime/examples/common/precisionSelect.tsx
packages/datetime/examples/dateInputExample.tsx
packages/datetime/examples/timePickerExample.tsx
packages/datetime/src/dateInput.tsx
packages/datetime/src/dateTimePicker.tsx

Add the ability to specify a timePrecision with the DateInput
Is this the right approach? Or do you want a separate component entirely. There's probably a lot of duplication if we make separate components.

Add the ability to use dateInput with a DateTimePicker

---

packages/datetime/src/dateInput.tsx
packages/datetime/test/dateInputTests.tsx

cc @mfedderly 
this will fix the build.

[DateInput] add unit test for timePrecision

---

packages/table/preview/index.tsx
packages/table/src/common/cell.ts
packages/table/src/common/classes.ts
packages/table/src/headers/columnHeader.tsx
packages/table/src/headers/rowHeader.tsx
packages/table/src/interactions/selectable.tsx
packages/table/src/layers/_layers.scss
packages/table/src/layers/focusCell.ts
packages/table/src/regions.ts
packages/table/src/table.tsx
packages/table/src/tableBody.tsx
packages/table/test/regionsTests.ts
packages/table/test/selectableTests.tsx
packages/table/test/selectionTests.tsx

Adds focus cell to table, allow focus cell to be moved around with arrow keys
This is the framework for the rest of everything we need to do with focus cell -- make sure the behavior and setup makes sense.

[Table] Add focus cell to blueprint table

---

packages/core/src/common/classes.ts

pt-ui-text-large
pt-text-muted

Add some class names

---

packages/core/src/common/abstractComponent.ts
packages/core/src/components/dialog/dialog.tsx
packages/core/src/components/overlay/overlay.tsx
packages/core/src/components/popover/popover.tsx
packages/core/src/components/portal/portal.tsx
packages/core/src/components/slider/handle.tsx
packages/core/src/components/slider/rangeSlider.tsx
packages/core/src/components/slider/slider.tsx
packages/core/src/components/tabs/tab.tsx
packages/core/src/components/tabs/tabList.tsx
packages/core/src/components/tabs/tabPanel.tsx
packages/core/src/components/tabs/tabs.tsx
packages/core/src/components/tabs2/tab2.tsx
packages/core/src/components/tabs2/tabs2.tsx
packages/core/src/components/tag/tag.tsx
packages/core/src/components/toast/toast.tsx
packages/core/src/components/tooltip/tooltip.tsx
packages/datetime/src/dateInput.tsx
packages/datetime/src/datePicker.tsx
packages/datetime/src/dateRangeInput.tsx
packages/datetime/src/dateRangePicker.tsx
packages/datetime/src/dateTimePicker.tsx
packages/datetime/src/timePicker.tsx

- ensure `public static displayName` is used everywhere (not just `public displayName`)
- 🏅 add `displayName: never` definition to AbstractComponent to prevent this in the future!

public static displayName

---

packages/core/src/docs/typography.md

add a little note about component i18n

---

packages/core/src/_icons.scss

- support `.pt-intent-*` on the icon classes (alternative to #1021)

support .pt-intent-* on the icon classes

---

packages/core/src/common/_mixins.scss
packages/core/src/components/forms/_control-group.scss

- use the mixin added in #854 to force a new stacking context on `.pt-control-group` 🎉

.pt-control-group creates a new stacking context

---

docs/docs/site-docs.css
packages/datetime/package.json
packages/docs/src/styles/_examples.scss
packages/site-docs/package.json

:fireworks: **Highlights**: So many fixes for `DateRangeInput`!
**This patch release contains a series of significant fixes to the behavior of `DateRangeInput`** including much improved support for controlled mode and better handling of hovered dates. All notes apply only to `DateRangeInput`:
- __Fixed__ Clicking a start date in controlled mode moves the focus to the end date #971 
- __Fixed__ Controlled mode now has the same UX as uncontrolled mode #1040 
- __Fixed__ Editing date with the keyboard overrides display of hovered date #1041 
- __Fixed__ After typing an invalid date into a field, hovering over a valid date will hide the error state for the duration of the hover #1041 
- __Changed__ Throw a descriptive …

Prepare Release Datetime v1.14.1

---

packages/table/preview/index.tsx
packages/table/src/cell/_borders.scss

NOTE: Left the example with no rows temporarily, before merging I will put it back! 
Pretty much making this up, so please tell me if I'm doing it wrong

[Table] Fix row border for ghost cells

---

gulp/util/karma-config.js

Major oops. Bump coverage back up to 80%.

---

packages/core/examples/popoverExample.tsx
packages/core/src/components/popover/popover.md
packages/core/src/components/popover/popover.tsx
packages/core/test/popover/popoverTests.tsx

- fix `PopoverExample` content
- expose public `popoverElement` and `targetElement` refs for testing
- add docs section about "Testing popovers"

[Popover] happier testing

---

packages/core/src/components/forms/controls.tsx
packages/core/src/components/forms/radioGroup.tsx

fix RadioGroup onChange event type + Checkbox indeterminate docs

---

packages/table/src/cell/editableCell.tsx

Fix lint error in `EditableCell.tsx`

[Table] Fix lint error in EditableCell

---

packages/core/src/components/portal/portal.tsx
packages/core/test/portal/portalTests.tsx

Change portal context property name

---

packages/core/resources/icons/icons.json

Nits from https://github.com/palantir/blueprint/pull/1221
Id -> ID
Ip -> IP

Update names in icons.json

---

packages/table/src/table.tsx

Quick PR to clean up the ordering of props and state keys in `table.tsx`.

[Table] Alphabetize props and state in table.tsx

---

packages/datetime/examples/timePickerExample.tsx
packages/datetime/src/common/dateUtils.ts
packages/datetime/src/timePicker.tsx
packages/datetime/test/common/dateTestUtils.ts
packages/datetime/test/common/dateUtilsTests.tsx
packages/datetime/test/timePickerTests.tsx

Added minTime and maxTime options
Please make sure feature works as it's expected
Please read my questions in #1220
Check if API is designed correctly(usage of Date object)
Code quality
Check if tests names make sense to you

[Datetime] Added minTime and maxTime options to TimePicker component

---

packages/core/src/components/navbar/navbar.md
packages/site-docs/src/blueprint.md

[docs] navbar component, dom4 script

---

packages/core/src/components/tag/tag.tsx

[Tag] fix HTMLAttributes type

---

.editorconfig
.gitignore

Useful for tools editor side like prettier

Add max_line_length for editor configs

---

docs/blueprint-landing.css
docs/docs/site-docs.css
package.json
packages/core/package.json
packages/labs/package.json
packages/site-docs/package.json
packages/table/package.json

- __Fixed__ Apply `baseline` to `.pt-form-group.pt-inline` only (#1360)

Prepare release v1.23.1

---

packages/core/src/components/dialog/dialog.tsx

[Dialog] Add transitionName prop

---

packages/core/src/components/overlay/overlay.tsx
packages/core/test/overlay/overlayTests.tsx

[Overlay] Only remove body.pt-overlay-open when the stack is empty

---

packages/table/src/common/classes.ts
packages/table/src/headers/_headers.scss
packages/table/src/headers/columnHeaderCell.tsx

[Table] Show menu icon when menu is open in column header

---

packages/labs/src/components/query-list/queryList.tsx

[Labs] Fixes QueryList onKeyDown only fires for up and down keys (#1403)

---

packages/table/src/quadrants/tableQuadrantStack.tsx
packages/table/src/table.tsx

- __Changed__ `Table` quadrant-sync logic now lives in a new component, `TableQuadrantStack`. 
How does this refactor look? Are any of the constructs or patterns weird? Any typos etc?

[Table] Frozen Rows/Cols - Part 6: Refactor quadrant logic

---

packages/core/resources/icons/icons.json

I was having trouble finding this icon, so added a few more tags that came to my mind when searching for it

Add tags for pt-icon-dashboard

---

packages/datetime/src/dateInput.tsx
packages/datetime/test/dateInputTests.tsx

Pass locale to moment for formatting. Fixes #1428

---

packages/labs/src/components/select/multiSelect.tsx
packages/labs/test/index.ts
packages/labs/test/multiSelectTests.tsx

~~- [ ] Update documentation~~ N/A
None
The tests could probably be improved
None

Fixes MultiSelect placeholder and adds tests

---

.gitignore
packages/core/src/blueprint.scss
packages/core/src/common/_variables.scss
packages/labs/test/multiSelectTests.tsx

- add package-lock.json to gitignore
- fix a lint warning
- move `$output-bourbon-deprecation-warnings` to _variables file so it'll… …… turn off warnings in all packages

fix some warnings

---

packages/labs/src/components/popover/popover2.tsx

Follow up from https://github.com/palantir/blueprint/pull/1438#discussion_r133064664

[Tooltip2] Fix disabled tooltip

---

packages/labs/src/components/select/multiSelect.tsx
packages/labs/test/multiSelectTests.tsx

Changes the typings and adds a unit test
If there are any other similar changes that should be made

[Labs / MultiSelect] Allow tags to be arbitrary elements

---

packages/labs/test/multiSelectTests.tsx

[MultiSelect] Fix tests line length lint

---

packages/table/preview/index.html
packages/table/preview/index.tsx

In the `Table` dev preview page:
- Add a switch to toggle custom column headers
- Disable frozen columns/rows by default
- Increase default row count to 100
- Set default cell content to "long text" (instead of "cell name")
- Enable column resizing by default
- This PR contains no consumer-facing changes.

[Table] Improve the dev preview

---

packages/table/preview/index.tsx

Enable copy/paste on table example

[docs] Add copy/paste to sortable table example

---

packages/core/src/components/forms/_file-upload.scss

Wasn't able to edit the commit on the PR: #1586 
@cmslewis, @llorca , now the CSS selector is changed, as you said guys.
Hope, this second PR won't mess up your git workflow.

[File Upload] add css height property, when using .pt-large class

---

docs/blueprint-landing.css
docs/blueprint-landing.js
docs/docs/site-docs.css
packages/core/package.json
packages/labs/package.json
packages/site-docs/package.json
packages/table/package.json

:fireworks: **Highlights**: `TimezonePicker` component
- https://github.com/palantir/blueprint/pull/1566 Add [prettier](https://github.com/prettier/prettier) formatting using `tslint-plugin-prettier` to automagically format the codebase
- https://github.com/palantir/blueprint/pull/1569 `MenuItem` now accepts `popoverProps`, allowing for greater control over submenu popovers (🎩 @AlexMarvelo)
- https://github.com/palantir/blueprint/pull/1600 File upload input with `.pt-large` modifier now has correct height (`40px` instead of `30px` previously) (🎩 @Landish)
- https://github.com/palantir/blueprint/pull/1580 `Table` interaction-bar cursor is now styled correctly when selection is disabled.
- …

Prepare release v1.29.0

---

packages/labs/src/components/select/select.tsx

To be merged into https://github.com/palantir/blueprint/pull/1579 (bb/1512)

[Labs/Select] Fix undesired page scroll when focusing input in popover

---

packages/table/preview/mutableTable.tsx

Adds switches to enabled "fixed truncation" which will truncate a string based on how many characters it has.

[Table] Add more switches for text layout to dev preview

---

packages/table/src/cell/formats/jsonFormat.tsx
packages/table/src/cell/formats/truncatedFormat.tsx
packages/table/test/formatsTests.tsx

Follow ups to https://github.com/palantir/blueprint/pull/1656 
Warning: untested

[Table/TruncatedFormat] Follow up to #1656

---

packages/core/test/tabs/tabs2Tests.tsx

- `Tabs2` Write tests verifying the the fix in #1492.

[Core/Tabs2] Write tests for Tabs2 fix in #1492

---

packages/table/src/quadrants/tableQuadrantStack.tsx

- 🐛 __FIXED__ `Table` no longer swallows wheel events that would otherwise scroll the surrounding page.
- Turns out that explicitly setting the `scrollLeft`/`scrollTop` of the target quadrant is sufficient to keep it in sync with its dependent quadrant in each animation frame.
- This means we don't need to `preventDefault` on the wheel event anymore (we were doing that before to prevent the target quadrant from scrolling faster than dependent quadrants).

[Table] Stop preventDefault'ing on wheel

---

packages/table/preview/mutableTable.tsx

Add toggle for custom headers, which was missing

[Table] Add toggle for custom column headers to preview

---

packages/datetime/src/dateInput.tsx
packages/datetime/src/datePicker.tsx
packages/datetime/src/dateRangeInput.tsx
packages/datetime/src/dateRangePicker.tsx
packages/datetime/test/common/dateTestUtils.ts
packages/datetime/test/datePickerTests.tsx
packages/datetime/test/dateRangePickerTests.tsx

Reverts palantir/blueprint#1647
Will re-merge after 1.31.0 is cut in a moment and include this in 1.32.0, just so we can polish some final things.

Revert "[DateTime] Add dayPickerProps to datetime components"

---

packages/core/src/common/classes.ts
packages/core/src/components/callout/callout.md
packages/core/src/components/callout/callout.tsx
packages/core/src/components/index.ts
packages/core/test/callout/calloutTests.tsx
packages/core/test/index.ts

add `Callout` component with props for all the modifiers.
anything missing?
should we add an example component? (I don't think it's necessary)

[Core] Callout component!

---

packages/table/src/cell/cell.tsx

Check what the children are, to make sure I'm only passing if it's the right kind of thing
There's a bit of a complicated if struture here -- can we do it more cleanly?

Only pass parent size props if child is truncatedFormat

---

packages/docs/src/components/interfaceTable.tsx
packages/table/examples/cellLoadingExample.tsx
packages/table/examples/tableEditableExample.tsx
packages/table/examples/tableReorderableExample.tsx
packages/table/examples/tableSortableExample.tsx
packages/table/preview/features.tsx
packages/table/test/columnHeaderCellTests.tsx

Remove usage of deprecated props in examples/docs

Remove deprecated props from examples

---

packages/core/src/common/utils/isDarkTheme.ts
packages/core/src/components/context-menu/contextMenu.tsx
packages/core/src/components/context-menu/contextMenuTarget.tsx
packages/core/src/components/popover/popover.tsx

Context menu respects dark theme.
Is there a better way of doing this??
but still

[Core/ContextMenu] ContextMenu respects dark theme

---

packages/datetime/src/_datepicker.scss

[DateTime] Add style for week numbers

---

.vscode/settings.json

exclude files from watch and search, not from the sidebar

smarter vscode settings

---

packages/core/src/components/button/_common.scss

Follow up from https://github.com/palantir/blueprint/pull/1738
cc @franciscofabian

[Button] Proper styles for disabled active minimal buttons

---

packages/core/examples/cardExample.tsx
packages/core/examples/index.ts
packages/core/src/components/card/card.md
packages/core/src/components/card/card.tsx
packages/core/src/components/index.ts
packages/core/test/card/cardTests.tsx
packages/core/test/index.ts

Hey, after @giladgray introduced `Callout` and `FormGroup` components, I think it's time to add one more little thing, the `Card` component.
Added `Card` component with extra loading feature, tests, and docs
* Should interactive mode be disabled, while loading? [For now, both state can be used simultaneously]
* Should onClick only be called, when card is in interactive mode? [For now, it's always called; it doesn't depends on interactive mode]
* ~While loading, should `tabindex="-1"` be added for every child of the card component? [For now, it's added for every single node under card component]~
Live preview:
https://23-95210685-gh.circle-artifacts.com/0/home/ubuntu/blueprint/packages/site-docs/dist/index.html#core/components/card.javascript-api

[Core] Card component

---

packages/labs/src/components/popover/popover2.tsx

Fix lint error on master

---

packages/datetime/src/common/dateUtils.ts
packages/datetime/src/dateFormatter.ts
packages/datetime/src/dateInput.tsx
packages/datetime/src/dateRangeInput.tsx
packages/datetime/src/dateinput.md
packages/datetime/src/daterangeinput.md
packages/datetime/src/index.ts
packages/docs-app/src/examples/datetime-examples/common/formatSelect.tsx
packages/docs-app/src/examples/datetime-examples/dateInputExample.tsx
packages/docs-app/src/examples/datetime-examples/dateRangeInputExample.tsx

[DateInput, DateRangeInput] Add a `format` prop for custom display formatting

---

packages/core/src/components/tooltip/tooltip.md

Fix typo in tooltip documentation

---

packages/node-build-scripts/generate-css-variables

Fix generated variables.less file

---

packages/docs/src/components/documentation.tsx
packages/docs/src/tags/heading.tsx

fix docs scrolling

---

package.json
packages/core/package.json
packages/core/src/components/tabs/tabs.tsx
packages/datetime/package.json
packages/datetime/src/dateInput.tsx
packages/docs/package.json
packages/docs/src/components/documentation.tsx
packages/labs/package.json
packages/table-dev-app/src/mutableTable.tsx
packages/table/package.json
packages/table/test/quadrants/tableQuadrantStackTests.tsx
yarn.lock

compiler now detects variables that are assigned but never read!

upgrade to typescript 2.6.2

---

packages/table/src/cell/formats/truncatedFormat.tsx

Missed the docs for it in the props options, adding it now

Add docs for truncated-by-approx

---

packages/core/src/common/classes.ts
packages/core/src/components/collapsible-list/collapsible-list.md
packages/core/src/components/collapsible-list/collapsibleList.tsx
packages/core/src/components/forms/_file-input.scss
packages/core/src/components/forms/_index.scss
packages/core/src/components/forms/file-input.md
packages/core/src/components/forms/fileInput.tsx
packages/core/src/components/forms/forms.md
packages/core/src/components/index.ts
packages/core/src/components/slider/coreSlider.tsx
packages/core/src/components/table/_table.scss
packages/core/test/collapsible-list/collapsibleListTests.tsx
packages/core/test/forms/fileInputTests.tsx
packages/core/test/index.ts
packages/core/test/slider/sliderTests.tsx
packages/docs-app/src/examples/core-examples/collapsibleListExample.tsx
packages/docs-app/src/examples/core-examples/progressExample.tsx
packages/docs-app/src/examples/core-examples/sliderExample.tsx

Partially #293 
Removes `pt-condensed` and `Classes.TABLE_CONDENSED` in favor of `pt-small`

Rename  FileUpload, renderVisibleItem, renderLabel, replace pt-condensed with pt-small

---

.github/ISSUE_TEMPLATE.md

warning in issue template about internal content

---

.circleci/config.yml

@cmslewis 
see https://circleci.com/docs/2.0/configuration-reference/#filters-1

Run deploy-npm job on master or release branches

---

packages/datetime/src/common/errors.ts
packages/datetime/src/dateInput.tsx
packages/datetime/test/dateInputTests.tsx
packages/docs-app/src/examples/datetime-examples/dateInputExample.tsx

delete deprecated openOnFocus prop

---

packages/docs-app/src/blueprint.md
packages/table/package.json

Remove es6-shim explicit dependency, add docs

---

packages/webpack-build-scripts/package.json

webpack-build-scripts dependencies

---

README.md

Extra ? in Readme

---

packages/core/karma.conf.js
packages/core/test/index.ts
packages/core/test/tag-input/tagInputTests.tsx

Turned out the be easier than I expected. :)

Fix TagInput test coverage

---

scripts/get-publishable-paths-from-semver-tags
scripts/publish-npm-semver-tagged

- Remove unnecessary CLI flags
- Remove support for SLS artifacts

Simplify get-publishable-paths-from-semver-tags

---

packages/core/src/components/forms/form-group.md

Fix FormGroup example

---

package.json

- #1999 Added new UI icons: `inner-join`, `left-join`, `right-join. Updated `people` icon.
- #1893 Fixed anchor navigation links in sidebar
- 41ee60e815f854f5d8d10f6741b20c224d93dd8c Fixed documentation links to point to new default branch on GitHub (`develop` instead of `master`)

Prepare release core@1.35.1

---

package.json
packages/core/package.json
packages/docs-app/package.json
packages/docs-app/src/components/blueprintDocs.tsx
packages/docs-app/src/components/navbarActions.tsx
packages/docs-app/src/index.tsx
packages/docs-data/compile-docs-data
packages/docs-data/src/index.d.ts
packages/landing-app/package.json

Merge release/1.x into develop

---

packages/core/src/components/forms/fileUpload.tsx

Remove onInputChange from htmlProps spread.

---

.circleci/config.yml
package.json

Attempting to fix publishing issues due to the way we persist assets in the CI workflow.
Fixes #2024

Prepare release 2.0.0-beta.3

---

packages/datetime/src/_timepicker.scss
packages/datetime/src/common/timeUnit.ts
packages/datetime/src/timePicker.tsx
packages/docs-app/src/examples/datetime-examples/timePickerExample.tsx

- new `common/timeUnit` module
- refactor `maybeRenderArrowButton` args for conciseness

use Icon in TimePicker arrows

---

packages/core/package.json
packages/datetime/package.json
packages/docs-theme/package.json
packages/icons/package.json
packages/labs/package.json
packages/select/package.json
packages/table/package.json
packages/timezone/package.json

add sideEffects:false to package manifests

---

packages/core/package.json
packages/datetime/package.json
packages/docs/package.json
packages/labs/package.json
packages/table/package.json

[release/1.x] add sideEffects:false to package manifests

---

packages/core/src/components/card/card.md
packages/core/src/components/forms/numericInput.tsx

- Card Elevation usage fixes #1976
- document `NumericInput` null for major/minorStepSize fixes #1978

small docs issues

---

packages/core/src/components/button/abstractButton.tsx
packages/core/src/components/button/button-group.md
packages/core/src/components/button/buttonGroup.tsx
packages/core/src/components/navbar/navbar.md
packages/docs-app/src/examples/core-examples/navbarExample.tsx
packages/table-dev-app/src/nav.tsx

see 3a230f38e9103c6805d7b94f11cd478d84a216f9, accidentally pushed it to `develop` already

Alignment enum

---

packages/core/src/components/navbar/navbar.md

so that it matches the actual docs example

[Navbar] Update JS code example

---

packages/docs-app/src/blueprint.md
packages/docs-theme/src/styles/_syntax.scss
scripts/upgrade-blueprint-2.0.0-rename

- update DOM4 and TypeScript sections in blueprint.md (main docs page)
- italicize types in syntax theme (clever hack for JS users)
- add more renames to upgrade script

update upgrade script & blueprint.md

---

packages/docs-theme/src/components/documentation.tsx

the 🥇  goes to `requestAnimationFrame`

fix docs scrollToReference 

---

packages/core/src/common/props.ts
packages/core/src/components/forms/radioGroup.tsx

per https://github.com/palantir/blueprint/pull/2117#discussion_r167119112

RadioGroup accepts number values

---

packages/core/src/components/tabs/_tabs.scss

support links in tab titles

---

packages/core/src/components/forms/controls.tsx
packages/core/src/components/menu/menuDivider.tsx
packages/core/src/components/non-ideal-state/nonIdealState.tsx
packages/core/src/components/tabs/tab.tsx

MenuDivider, NIS, Tab, Controls

more ReactNode support, document children where helpful

---

packages/core/src/components/card/_card.scss
packages/docs-app/src/examples/core-examples/cardExample.tsx
packages/docs-app/src/examples/core-examples/dialogExample.tsx
packages/docs-app/src/examples/core-examples/popoverExample.tsx

have no idea what to do with the dialog example

Remove lorem text from card and popover examples

---

.circleci/config.yml

let's see what the tests look like in only 4 containers instead of 7.

reduce build parallelism

---

packages/docs-app/src/examples/core-examples/calloutExample.tsx
packages/docs-app/src/styles/_examples.scss
packages/docs-theme/src/components/block.tsx
packages/docs-theme/src/components/modifierTable.tsx
packages/docs-theme/src/components/page.tsx
packages/docs-theme/src/components/typescript/enumTable.tsx
packages/docs-theme/src/components/typescript/interfaceTable.tsx
packages/docs-theme/src/components/typescript/typeAliasTable.tsx
packages/docs-theme/src/styles/_navbar.scss

check it out @llorca!
see commits.

[docs] fix visual regressions

---

packages/core/src/components/forms/_file-input.scss

fix file input button

---

packages/core/src/common/classes.ts
packages/core/src/components/callout/_callout.scss
packages/core/src/components/callout/callout.tsx
packages/core/src/components/dialog/_dialog.scss
packages/core/src/components/dialog/dialog.tsx

See https://github.com/palantir/blueprint/pull/2138#discussion_r168585887

[release/1.x] more graceful h5 CSS selectors

---

.vscode/extensions.json

well this is neat. thanks VS Code for being the best.
also shameless plug for my VS Code editor/syntax theme.

add list of recommended VS Code extensions

---

packages/docs-data/package.json
packages/docs-theme/package.json
yarn.lock

no API breaks, just stabilizing things

Upgrade to documentalist 1.0.0

---

.circleci/config.yml
README.md
package.json
packages/docs-app/src/components/blueprintDocs.tsx
packages/docs-app/src/components/docsIcon.tsx

And standardize NPM scripts so you don't have to change them when you switch branches.
Fixes #2168

 [release/1.x] Fix minor docs issues

---

packages/core/src/components/icon/icon.md

Fixed a documentation import bug.

[docs] Minor fix: Import statement for IconNames

---

package.json
packages/docs-app/src/tags/reactExamples.ts
packages/docs-theme/src/components/documentation.tsx

[1.x] fix docs examples & nav jumping

---

README.md

fixes a typo on readme, (ladning to landing)

fixing typo, (ladning to landing)

---

.browserslistrc
package.json
packages/core/src/components/forms/_controls.scss
yarn.lock

this does a nice number on yarn.lock, lots of deletions.
also fixes any yarn.lock issues currently on develop as a result of recent PRs.

upgrade to stylelint-config-palantir v3

---

.circleci/config.yml

Root cause of CI failure seems to be https://github.com/nodejs/docker-node/issues/649

[release/1.x] Bump docker-node in CI

---

.circleci/config.yml

Bump docker-node in CI

---

packages/core/src/components/tooltip/tooltip.md

inspired by https://github.com/palantir/blueprint/issues/1007#issuecomment-370001503

bring back some tooltip docs lost in 2.0 transition

---

packages/datetime/src/_datetimepicker.scss
packages/datetime/src/_timepicker.scss

for #2266 
this is a minor breaking style change

[TimePicker] remove padding

---

packages/docs-app/package.json
packages/docs-data/package.json
packages/docs-data/src/index.js
packages/docs-theme/package.json
packages/docs-theme/src/components/documentation.tsx
packages/landing-app/package.json
packages/table-dev-app/package.json
packages/table/package.json
packages/webpack-build-scripts/package.json
yarn.lock

a bunch of updates to ensure that the docs-app does not contain any ES6 syntax. 
see commits for individual strategies.

IE11 support on docs site

---

packages/docs-app/src/examples/core-examples/popoverInlineExample.tsx
packages/docs-app/src/styles/_examples.scss
packages/docs-app/src/styles/_sections.scss

- better color for positioning buttons
- same style for inset elements

Tweak popover docs colors

---

packages/docs-app/src/styles/_colors.scss

[Docs] Tick message in monospace

---

packages/datetime/src/_datepicker.scss

Dark theme now looks good on hover

[datetime] Proper colors for caret in datepicker

---

packages/docs-app/src/examples/select-examples/films.tsx

[docs] Add missing key in <strong> element

---

packages/landing-app/src/logo.ts

previously we were rendering the background every frame, but it's just a big static pattern so that was wholly unnecessary. now background is rendered on start, and re-rendered only on document resize.
**huge perf gains!**

[landing] only render background when needed (huge gainz)

---

packages/docs-app/src/components/blueprintDocs.tsx
packages/docs-app/src/styles/_nav.scss
packages/docs-theme/src/components/documentation.tsx
packages/docs-theme/src/styles/_layout.scss

[docs] fix nav item centering, add copyright

---

README.md
package.json
packages/docs-app/src/components/blueprintDocs.tsx
packages/docs-app/src/whats-new.md

- remove docs banner
- update docs notes about 2.0
full release notes on the wiki: https://github.com/palantir/blueprint/wiki/What's-new-in-Blueprint-2.0

🌟 Prepare release v2.0.0 🌟 

---

packages/docs-app/src/examples/select-examples/multiSelectExample.tsx

Add clear button on multiselect example

---

packages/docs-app/src/resources.md

that has been broken this whole time 🤔

[Docs] Update resources link

---

packages/docs-app/src/styles/_resources.scss
packages/docs-theme/src/styles/_variables.scss

Pre https://github.com/palantir/blueprint/pull/2305:
Post https://github.com/palantir/blueprint/pull/2305 (lost 60px width to padding):
This PR:

[Docs] Increase site width

---

packages/core/src/components/forms/controls.tsx

[core] Add missing invoke in checkbox component

---

packages/core/src/common/abstractComponent.ts
packages/core/src/common/abstractPureComponent.ts
packages/core/src/common/index.ts
packages/core/src/common/utils.ts
packages/core/src/compatibility/browser.ts
packages/core/src/components/forms/controls.tsx
packages/core/src/components/forms/inputGroup.tsx
packages/core/src/components/forms/text-area.md
packages/core/src/components/menu/_submenu.scss
packages/core/src/components/tag-input/tagInput.tsx
packages/docs-theme/src/components/documentation.tsx

Fixes #2365 (large tag X)
~~Fixes #2370 (checkbox onChange)~~ already fixed
Fixes #2347 (validateProps docs)
Fixes #1861 (InputGroup right padding)
docs nav now ensures that active menu item is visible after page change.

fix a bunch of little bugs

---

packages/core/src/components/forms/_input-group.scss
packages/core/src/components/forms/_input.scss

* Support pt-fill on InputGroups
* Does this change have any effects on other Blueprint components?

Add pt-fill support for InputGroups

---

packages/core/src/components/non-ideal-state/_non-ideal-state.scss

remove unused import in _non-ideal-state.scss

---

packages/core/src/components/forms/_file-input.scss

!default for file-input variables

---

packages/core/src/components/card/card.md
packages/core/src/components/card/card.tsx

"increases to the maximum level"

fix cards interactive docs

---

packages/core/src/common/classes.ts
packages/core/src/components/card/card.tsx
packages/datetime/src/common/classes.ts
packages/table/src/common/classes.ts

Adds missing class constants to the 1.x release branch to ease upgrading and compliance with new lint rules

[release/1.x] Add missing class constants

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md
.github/ISSUE_TEMPLATE/Support_question.md
README.md

https://blog.github.com/2018-05-02-issue-template-improvements/
- add issue templates for bug reports, feature requests and questions
- remove link to SO; official support is done here
- nice README subsection for migration and issue templates

Add issue templates

---

packages/core/package.json
packages/datetime/package.json
packages/docs-theme/package.json
packages/icons/package.json
packages/labs/package.json
packages/select/package.json
packages/table/package.json
packages/timezone/package.json

sideEffects: *.css

---

.circleci/config.yml
packages/core/src/_typography.scss
packages/core/src/common/classes.ts
packages/core/src/components/dialog/dialog.tsx
packages/core/src/components/forms/_form-group.scss
packages/core/src/components/html/html.md
packages/core/src/components/icon/icon.tsx
packages/core/src/components/table/_table.scss
packages/docs-app/src/components/blueprintDocs.tsx
packages/docs-app/src/index.scss
packages/docs-app/src/styles/_colors.scss
packages/docs-app/src/styles/_sections.scss
packages/docs-theme/src/styles/_overrides.scss
packages/landing-app/src/index.html
packages/node-build-scripts/generate-icons-source.js

(replacing #2473 so we can use Lerna on `next` branch for this release.)

Prep 3.0.0-beta.0 release

---

packages/core/src/components/tabs/_tabs.scss

Extracted from https://github.com/palantir/blueprint/pull/2489/files#diff-aa7de1342926c31ce8684788445249a9
Before:
After:

[Tabs] fix vertical static tab styling

---

packages/core/src/components/forms/_controls.scss

Extracted from https://github.com/palantir/blueprint/pull/2489/files#diff-29fb8cc692012fb6e0f4008160fb2b2c

[Controls] fix align-right for switches

---

packages/core/src/components/table/table-html.tsx

- Fix typings generated from `table-html.tsx` when trying to use `@blueprintjs/core@3.0.0-beta.0`

Fix generated typings for table-html

---

packages/core/src/components/popover/popover.md

Fix popover docs links

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md
.github/ISSUE_TEMPLATE/Support_question.md

fixes https://github.com/palantir/blueprint/issues/2526#issuecomment-390731843

Add "Environment" to all issue templates

---

packages/core/test/overflow-list/overflowListTests.tsx
packages/table/test/tableTests.tsx

hopefully this will resolve test flakes.

allow retrying OverflowList & Table tests

---

packages/webpack-build-scripts/externals.js

add tslib to webpack externals

---

packages/core/src/components/slider/slider.tsx
packages/core/src/components/slider/sliderHandle.tsx
packages/core/src/components/slider/sliders.md
packages/docs-app/src/examples/core-examples/multiSliderExample.tsx

- add docs for MultiSlider
- refactor example

MultiSlider docs

---

packages/table/src/headers/columnHeaderCell.tsx

(re-opening of https://github.com/palantir/blueprint/pull/2534 -- sorry for the slow response on that one)

Fix 'unknown prop `index` on <div> tag' errors

---

packages/core/src/components/toast/_toast.scss

[Toaster] override inline overlay styles

---

packages/docs-app/src/components/welcome.tsx

omg finally, a permanent home for a link to a sandbox.
👏 special thanks to @jrshust for setting up the sandbox!

[docs] replace changelog link with sandbox link

---

packages/core/src/components/forms/form-group.md
packages/core/src/components/forms/numeric-input.md
packages/core/src/components/forms/text-inputs.md
packages/datetime/src/dateInput.tsx
packages/datetime/src/dateRangeInput.tsx
packages/datetime/src/dateinput.md
packages/datetime/src/daterangeinput.md

Fixes several broken links in docs which were not updated to reflect changes made to the URL path structure in v3

fix broken links in docs

---

packages/core/src/components/button/abstractButton.tsx
packages/core/src/components/button/button.md
packages/core/src/components/button/buttons.tsx

[Button] set tabIndex=-1 when disabled

---

packages/core/src/components/button/_button.scss

- move minimal selector. regression from #2574

[Button] fix dark & minimal

---

packages/core/src/components/menu/_submenu.scss

- fix submenu menu item style
- fix dark portal menu shadows

[MenuItem] fix submenu style

---

packages/docs-app/src/components/blueprintDocs.tsx

- remove docs banner from 1.x site

[1.x] remove banner

---

package.json
packages/core/package.json
packages/datetime/package.json
packages/docs-theme/package.json
packages/icons/package.json
packages/karma-build-scripts/package.json
packages/labs/package.json
packages/node-build-scripts/package.json
packages/select/package.json
packages/table/package.json
packages/test-commons/package.json
packages/timezone/package.json
packages/tslint-config/package.json
packages/webpack-build-scripts/package.json

fixes this issue when running tasks in package directories (not in root or via lerna):
per https://softwareengineering.stackexchange.com/a/285986

valid SPDX license identifiers

---

packages/docs-app/src/examples/core-examples/buttonGroupPopoverExample.tsx
packages/docs-app/src/examples/core-examples/checkboxExample.tsx
packages/docs-app/src/examples/core-examples/common/alignmentSelect.tsx
packages/docs-app/src/examples/core-examples/radioExample.tsx
packages/docs-app/src/examples/core-examples/switchExample.tsx

- switches for large, inline, alignIndicator
- all examples inherit from `CheckboxExample` for state mgmt

[Checkbox] better examples

---

packages/datetime/src/dateFormat.tsx

cc @ntrinquier in #2724 
fixes #2612

merge 4.x into develop

---

packages/core/src/components/panel-stack/panel-stack.md
packages/core/src/components/panel-stack/panelProps.ts
packages/docs-theme/src/styles/_props.scss

- major edits to `PanelStack` docs
cc @kadhirvelm

[PanelStack] documentation

---

packages/table/test/editableCellTests.tsx

edit tests per https://github.com/palantir/blueprint/pull/2701#discussion_r202966386

[EditableCell] tests flup from #2701

---

packages/core/src/components/tree/_tree.scss
packages/core/src/components/tree/treeNode.tsx

Matched the expand icon with original designs
**Design**

[Tree] Updated animated expand icon

---

packages/datetime/package.json
packages/datetime/src/common/dateUtils.ts
packages/datetime/src/datePicker.tsx
packages/datetime/test/common/dateUtilsTests.tsx
packages/datetime/test/datePickerTests.tsx
yarn.lock

- just a big tender massage to basically all of the `DatePicker` internals without affecting the appearance or usability
- major focus on using `const` over `let`
- the biggest code change is the introduction of `updateValue()` to manipulate `this.state.value` and standardize the handler impls
- see the individual commits, I've been careful

[DatePicker] ❤️ 

---

packages/docs-app/src/resources.md

Added new components and updated visual styles. Symbols coming in the next few weeks.
**Typography**
* updated Headings sizes (font + line height)
* updated Dialog heading sizes (h5 => h4)
* added Small text styling
**Buttons**
* fixed gradient styling for Default buttons
* added small buttons with icon
* added small icon buttons - primary
**Callouts**
* updated icons
* updated Callout heading sizes (h5 => h4)
**Dropdown menus**
* fixed “Circular” icon
* fixed section headers' spacing
* fixed hover state color
**Navigation bar**
* updated header
**Lists & trees**
* fixed Empty state positioning
**Tags & badges**
* added Rounded tags example
* added Removable tags example
**Forms**
* updated button styling in File upload
* updated secondary text
* added Control group
* added Numeric input …

[Resources] Sketch file update

---

packages/datetime/test/dateRangePickerTests.tsx

- refactor all the DRP tests to use enzyme with a cool harness.
- i think this shaves a handful of seconds off the total test time!

[DateRangePicker] all tests use enzyme

---

packages/core/src/common/classes.ts
packages/core/src/components/_index.scss
packages/core/src/components/components.md
packages/core/src/components/divider/_divider.scss
packages/core/src/components/divider/divider.md
packages/core/src/components/divider/divider.tsx
packages/core/src/components/index.ts
packages/docs-app/src/examples/core-examples/dividerExample.tsx
packages/docs-app/src/examples/core-examples/index.ts

- new `Divider` component replaces the old `<hr>` styles

[new] Divider component

---

packages/core/src/components/text/text.tsx

- saw some compile errors in test code so I fixed this. no noticeable change.

[Text] fix ref usage

---

packages/core/src/components/overflow-list/overflowList.tsx

- adjust the threshold to be slightly more permissive.

[OverflowList] fix browser zoom behavior

---

packages/core/src/components/hotkeys/_hotkeys.scss
packages/core/src/components/tag/_common.scss
packages/docs-app/src/components/navHeader.tsx
packages/docs-app/src/styles/_nav.scss
packages/docs-theme/src/styles/_navbar.scss

- use new icon props on tag. better alignment.

[docs] better version tag styles

---

packages/core/src/components/skeleton/_common.scss

Increasing contrast to make the skeletons animation a bit more prominent.

[Skeleton] Increase animation contrast

---

packages/core/src/components/collapse/collapse.tsx

- move `Collapse` `AnimationState` docs onto the enum values
- `CLOSING_END` &rArr; `CLOSING`

[Collapse] refactor docs

---

packages/core/src/docs/classes.md
packages/datetime/src/datetimepicker.md

[docs] Modifiers & update DTP deprecation

---

packages/select/src/common/listItemsProps.ts
packages/select/src/components/select/select.tsx

follow up from https://github.com/palantir/blueprint/pull/2894#discussion_r215706918

[select] update docs for other resetOnX props

---

CONTRIBUTING.md

Minor text fix in `CONTRIBUTING.md`

Update contributing guide port to 9000

---

packages/core/src/components/tag/_common.scss

[Tag] fix remove button centering

---

packages/core/test/hotkeys/hotkeysTests.tsx

fix semantic merge conflict in hotkeys tests

---

packages/tslint-config/src/rules/blueprintClassesConstantsRule.ts

[tslint] refactor fixer code

---

packages/docs-theme/package.json
packages/docs-theme/src/components/navigator.tsx
yarn.lock

- bump the dep and massage options for better results

📘 upgrade fuzzaldrin-plus and improve navigator results

---

packages/docs-app/src/components/icons.tsx
packages/icons/resources/icons/icons.json
packages/icons/src/index.md

📘 update icons docs & add example to package

---

packages/core/src/components/breadcrumbs/breadcrumb.tsx

This introduces the same behavior buttons have.

Render breadcrumb children

---

packages/core/src/components/forms/_controls.scss

- fixes an occasional bug where checkbox indicator can become misaligned

[Checkbox] fix indicator display

---

packages/core/src/_reset.scss
packages/core/src/common/_mixins.scss

Only set default font-family on body selector

---

packages/core/src/components/forms/formGroup.tsx

- two new props on `FormGroup` to handle _even more use cases!_

[FormGroup] add contentClassName and style props

---

packages/core/src/common/_flex.scss
packages/core/src/components/tag/_common.scss

- fixes issue where text can appear vertically misaligned in other fonts.

[Tag] fix line-height for centering

---

packages/core/src/components/forms/label.md

Minor changes to docs demonstrating proper usage of Label component

fix label documentation example

---

packages/node-build-scripts/ts-lint.js

🔧 ts-lint --fix

---

packages/select/src/components/query-list/queryList.tsx
packages/select/test/queryListTests.tsx

pass through next props to `setQuery` during `componentWillRecieveProps` in `QueryList`

Fix change activeItem when query changes on props for QueryList

---

.github/PULL_REQUEST_TEMPLATE.md

Gilad had to ask me to do this, and now he doesn't need to anymore!

Include "enable preview comments" in PR templates

---

packages/core/src/docs/variables.md

Add elevation variables in docs

---

packages/core/src/components/hotkeys/hotkeys.md

Simple typo in Hotkeys documentation page.

FIXED: @HotkeyTarget -> @HotkeysTarget typo

---

packages/core/src/components/panel-stack/panelStack.tsx

[PanelStack] Allow any prop type for initial panels

---

packages/core/src/docs/index.md

Fixing typo

---

packages/datetime/src/datePicker.tsx
packages/datetime/test/datePickerTests.tsx

[DatePicker] fix onChange on month change after initial day selection

---

packages/datetime/src/shortcuts.tsx

- Fix shortcuts.tsx react import typings

Fix shortcuts.tsx react import typings

---

packages/datetime/src/timePicker.tsx
packages/datetime/test/dateRangePickerTests.tsx

- Includes tests
updates the time when time inputs change event fired if the time is valid

Hover over date clears time filter fix #3420

---

packages/core/src/common/_color-aliases.scss

To increase the contrast between dark default and dark muted text.

Fix dark muted and disabled text contrast

---

packages/core/src/components/tree/_tree.scss

[Core] Fixed not applying intent color for Icons inside Tree with dark mode

---

.circleci/config.yml
package.json
packages/core/package.json
packages/datetime/package.json
packages/karma-build-scripts/package.json
packages/labs/package.json
packages/node-build-scripts/package.json
packages/select/package.json
packages/table/package.json
packages/timezone/package.json
yarn.lock

Attempting to fix the testing timeouts

Upgrade testing infra

---

packages/docs-app/src/examples/core-examples/toastExample.tsx

[docs-app] Fix minor bug in upload toast example

---

config/tsconfig.base.json
package.json
packages/core/package.json
packages/core/src/common/utils/compareUtils.ts
packages/core/src/components/divider/divider.tsx
packages/core/src/components/forms/controls.tsx
packages/core/src/components/icon/icon.tsx
packages/core/src/components/menu/menuItem.tsx
packages/core/src/components/overflow-list/overflowList.tsx
packages/core/src/components/popover/popover.tsx
packages/core/src/components/spinner/spinner.tsx
packages/core/src/components/text/text.tsx
packages/datetime/package.json
packages/docs-theme/package.json
packages/icons/package.json
packages/labs/package.json
packages/node-build-scripts/package.json
packages/select/package.json
packages/select/src/components/omnibar/omnibar.tsx
packages/select/test/multiSelectTests.tsx
packages/select/test/selectTests.tsx
packages/select/test/suggestTests.tsx
packages/table/package.json
packages/table/src/table.tsx
packages/test-commons/package.json
packages/timezone/package.json
yarn.lock

will upgrade to 3.5 in a different PR

chore: upgrade to typescript 3.2

---

package.json
packages/docs-data/package.json
packages/docs-theme/package.json
packages/table/package.json
yarn.lock

fixes #3574
gets everything using TS 3.5

chore: upgrade documentalist

---

packages/datetime/package.json
packages/select/package.json
packages/table/package.json
packages/timezone/package.json

fix: correctly declare react peer deps in package.json

---

packages/core/src/components/popover/popover.md

Just a simple doc fix
See above

Fix Popover.md imports

---

packages/core/src/components/button/_button.scss
packages/docs-app/src/examples/core-examples/buttonsExample.tsx

[core] fix(AnchorButton) left text alignment

---

packages/datetime/package.json
packages/datetime/src/dateInput.tsx
packages/datetime/src/datePickerCaption.tsx
packages/datetime/src/datePickerCore.tsx
packages/datetime/src/datePickerNavbar.tsx
packages/datetime/src/dateRangeInput.tsx
packages/datetime/src/dateRangePicker.tsx
packages/datetime/src/datepicker.md
packages/datetime/src/index.ts
packages/datetime/test/datePickerCaptionTests.tsx
packages/tslint-config/index.js
yarn.lock

[datetime] fix: upgrade react-day-picker, clean up type imports

---

packages/core/src/common/utils/compareUtils.ts
packages/select/src/components/query-list/queryList.tsx
packages/select/test/queryListTests.tsx

Revert a buggy line change in #3702

[select] fix(QueryList): re-render when controlled items change

---

packages/core/src/components/toast/_toast.scss

fix[Toast]: change style for first bottom toast

---

packages/core/src/components/forms/_label.scss

Fix NumericInput when placed inside a label
I don't think either are needed

Fix NumericInput button

---

packages/core/src/components/tag-input/tag-input.md

Basic spelling change.
Adding the change to the documentation.

Fix dropdown spelling.

---

packages/core/src/components/forms/inputGroup.tsx

[core] fix(InputGroup): prevent infinite setState in componentDidUpdate

---

packages/core/src/components/collapse/collapse.tsx

[core] fix(Collapse): simplify lifecycle, fix animation bugs

---

packages/core/src/components/popover/popoverSharedProps.ts

[core] docs: update link to popper.js modifiers reference

---

packages/core/src/common/props.ts
packages/core/src/components/breadcrumbs/breadcrumbs.tsx
packages/docs-app/src/examples/core-examples/breadcrumbsExample.tsx

[core] remove non-HTML attributes in overflow menu items

---

packages/core/src/common/props.ts

update INVALID_PROPS list used by `removeNonHTMLProps()` utility fn

[core] fix(Button): remove invalid HTML attr

---

package.json
yarn.lock

- [#3982](https://github.com/palantir/blueprint/pull/3982) feat(`NumericInput`): supply input element in `onValueChange` callback
- [#3993](https://github.com/palantir/blueprint/pull/3993) feat(`TagInput`): handle delete to remove items
- [#3998](https://github.com/palantir/blueprint/pull/3998) fix(`Button`): remove invalid HTML attr `"outlined"`
- [#4033](https://github.com/palantir/blueprint/pull/4033) docs: Add example to import variables into Less file
- [#4012](https://github.com/palantir/blueprint/pull/4012) feat(`DatePicker`): add support for `dayPickerProps.renderDay`
- [#3983](https://github.com/palantir/blueprint/pull/3983) fix(`DateRange`): values are possibly null, not undefined
- 🔥 note that this may cause a minor break if you are compiling TypeScript with `strictNullChecks` …

Prepare release 3.25.0

---

packages/core/src/components/panel-stack/_panel-stack.scss

[PanelStack] Fix header z-index

---

packages/core/src/components/popover/popover.md

[core] docs: fix popper v1 documentation links

---

package.json
packages/eslint-config/package.json
packages/eslint-plugin/package.json
packages/eslint-plugin/src/rules/classes-constants.ts
packages/eslint-plugin/src/tsconfig.json
packages/node-build-scripts/package.json
yarn.lock

[ESLint 7.0 migration guide](https://eslint.org/docs/user-guide/migrating-to-7.0.0)
[typescript-eslint 3.0 release notes](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0)

feat: upgrade eslint, typescript-eslint
